graph TB
  subgraph Controllers
    WechatController
  end
  subgraph Infrastructure
    ArrayQueueDemo
    Config
    ConfigA
    ConfigB
    ConfigC
    ConfigD
    RedisConfig
    RestTemplateConfig
  end