graph TB
  subgraph Controllers
    AcResourceDetails
    CaptchaController
    GlobalControllerAdvise
    IndexController
    LoginController
    NotificationController
    OpenIdResourceDetails
    SessionController
    SessionInvalidController
    SignUpController
    SmsCredentialController
    SmsResourceDetails
    SocialConnectController
    SocialConnectStatusController
    SocialSignUpController
    UserController
  end
  subgraph Services
    AlipayServiceProvider
    CredentialService
    CredentialServiceImpl
    NotificationService
    QQServiceProvider
    ServiceAssert
    SmsUserDetailsService
    SmsUserDetailsServiceImpl
    SocialUserDetailsServiceImpl
    UserDetailsServiceImpl
    UserService
    UserServiceImpl
    WechatMpServiceProvider
    WechatServiceProvider
  end
  subgraph Data_Access
    JpaConnectionRepository
    JpaUsersConnectRepository
    UserConnectionRepository
    UserRepository
  end
  subgraph Security
    AbstractChannelSecurityConfigurer
    AcAccessTokenProvider
    AcAuthenticationConfiguration
    AcAuthenticationFilter
    AcAuthenticationProvider
    AcAuthenticationToken
    AcChannelSecurityConfigurer
    AcOAuth2Configuration
    AcTokenGranter
    AlipayOAuth2AuthenticationService
    AlipayOAuth2Template
    AuthController
    AuthenticatedUser
    AuthenticationFailureEventListener
    AuthenticationSuccessEventListener
    AuthorizationCodeJwtConfiguration
    AuthorizationServerConfiguration
    BaseSecurityConfiguration
    CaptchaAuthenticationFilter
    ChannelSecurityConfigurer
    DefaultJwtTokenStore
    DefaultPasswordStrategy
    JwtAuthController
    JwtAuthenticationEntryPoint
    JwtAuthenticationFailureHandler
    JwtAuthenticationFilter
    JwtAuthenticationSuccessEventListener
    JwtAuthenticationSuccessHandler
    JwtLogoutSuccessHandler
    JwtProperties
    JwtSecurityConfiguration
    JwtTokenProvider
    JwtTokenStore
    OAuth2Controller
    OpenIdAccessTokenProvider
    OpenIdAuthenticationConfiguration
    OpenIdAuthenticationFilter
    OpenIdAuthenticationProvider
    OpenIdAuthenticationToken
    OpenIdChannelSecurityConfigurer
    OpenIdJwtConfiguration
    OpenIdOAuth2Configuration
    OpenIdTokenGranter
    PasswordChangedEvent
    PasswordProperties
    PasswordStrategy
    PasswordStrength
    QQOAuth2Template
    SecurityCenterAutoConfiguration
    SecurityConfiguration
    SecurityErrorEnum
    SmsAccessTokenProvider
    SmsAuthenticationConfiguration
    SmsAuthenticationFilter
    SmsAuthenticationProvider
    SmsAuthenticationToken
    SmsChannelSecurityConfigurer
    SmsJwtConfiguration
    SmsOAuth2Configuration
    SmsTokenGranter
    SocialAuthenticatedUser
    SocialChannelSecurityConfigurer
    SocialSecurityConfigurer
    SsoAuthClient
    WebAuthenticationFailureHandler
    WebAuthenticationSuccessHandler
    WebSecurityConfiguration
    WechatAccessGrant
    WechatMpAccessGrant
    WechatMpOAuth2Template
    WechatOAuth2Template
  end
  subgraph Infrastructure
    AcLoginConfigurer
    AcProperties
    AlipayConnectConfiguration
    AlipayProperties
    AliyunSmsProperties
    AliyunSmsSenderConfiguration
    CredentialConfig
    CredentialProperties
    OpenIdLoginConfigurer
    OpenIdProperties
    QQConnectConfiguration
    QQProperties
    ResourceServerConfiguration
    SmsCredentialProperties
    SmsLoginConfigurer
    SmsNotificationAutoConfiguration
    SocialAutoConfiguration
    SocialProperties
    SocialWebAutoConfiguration
    SsoClientAutoConfiguration
    SsoClientProperties
    WebConfiguration
    WebSessionConfiguration
    WechatConnectionConfiguration
    WechatMpConnectionConfiguration
    WechatMpProperties
    WechatProperties
  end
  Controllers --> Services
  Infrastructure --> Services
  Security --> Controllers
  Services --> Data_Access