graph TB
  subgraph Controllers
    ArticleController
    EntryController
    UserController
  end
  subgraph Services
    EntryService
    EntryServiceImpl
    UserService
    UserServiceImpl
  end
  subgraph Data_Access
    ArticleRepository
    BrowseLogRepository
    CollectionRepository
    EntryRepository
    RoleRepository
    UserRepository
  end
  subgraph Security
    AuthController
    AuthService
    AuthServiceImpl
    JwtAuthenticationEntryPoint
    JwtAuthenticationTokenFilter
    JwtUser
    JwtUserDetailsServiceImpl
    JwtUserFactory
    WebSecurityConfig
  end
  subgraph Infrastructure
    RedisCacheConfiguration
    Swagger2
  end
  Controllers --> Services
  Infrastructure --> Services
  Security --> Controllers
  Services --> Data_Access