graph TB
  subgraph Controllers
    AuthenticationController
    ChatController
    ChatRoomController
  end
  subgraph Services
    CassandraInstantMessageService
    ChatRoomService
    DefaultUserService
    InstantMessageService
    RedisChatRoomService
    UserDetailsServiceImpl
    UserService
  end
  subgraph Data_Access
    ChatRoomRepository
    InstantMessageRepository
    Role
    RoleRepository
    User
    UserRepository
  end
  subgraph Security
    WebSecurityConfig
  end
  subgraph Infrastructure
    CassandraConfig
    WebConfig
    WebSocketConfigSpringSession
  end
  Controllers --> Data_Access
  Controllers --> Services
  Services --> Data_Access