graph TB
  subgraph Controllers
    InventoryController
    OrderController
    ShipmentController
  end
  subgraph Services
    InventoryService
    OrderService
    ShipmentService
  end
  subgraph Data_Access
    InventoryRepository
    OrderRepository
    OrderShipmentRepository
  end
  subgraph Infrastructure
    CreateShipmentConsumerPact
    GetProductConsumerPact
    KafkaConsumerConfig
    KafkaProducerConfig
    KafkaTopicConfig
    MessageListenerShipment
    MessageProducer
    SwaggerConfig
  end
  Controllers --> Services
  Infrastructure --> Services
  Services --> Data_Access