graph TB
  subgraph Infrastructure
    AbstractNotifyUserListener
    ConfigType
    EnableEtcdConfig
    EtcdConfig
    EtcdConfigAutoConfiguration
    EtcdConfigBasic
    EtcdConfigBeanDefinitionRegistrar
    EtcdConfigListener
    EtcdConfigListenerMethodProcessor
    EtcdConfigLoader
    EtcdConfigProperties
    EtcdConfigPropertySource
    EtcdConfigService
    EtcdConfigServiceImpl
    EtcdConfigurationProperties
    EtcdConfigurationPropertiesBindingPostProcessor
    EtcdListener
    Listener
    UpdateCacheListener
    UpdateReferenceListener
  end