graph TB
  subgraph Controllers
    DemoServiceController
    FeignSampleController
    HttpClientSampleController
    OkHttpSampleController
    ReactorNettySampleController
    RestTemplateSampleController
    ServiceSampleController
    WebClientSampleController
  end
  subgraph Services
    DemoService
    DemoServiceImpl
    ServiceSampleClient
  end
  subgraph Security
    TracerDubboFilter
    TracerScgGlobalFilter
    TracerWebfluxFilter
  end
  subgraph Infrastructure
    ProxyMinimalHttpClient
    ReactorNettyAutoConfiguration
    TracerAutoConfiguration
    TracerContextServletListener
    TracerFeignAutoConfiguration
    TracerHttpClientAuoConfiguration
    TracerOkHttpAuoConfiguration
    TracerProperties
    TracerRestTemplateAuoConfiguration
    TracerScgAutoConfiguration
    TracerServletAutoConfiguration
    TracerWebClientAuoConfiguration
    TracerWebfluxAutoConfiguration
  end
  Controllers --> Services
  Infrastructure --> Services
  Security --> Controllers