graph TB
  subgraph Controllers
    AccountController
    AccountResource
    AliasController
    AliasResource
    BccController
    BccResource
    DomainController
    DomainResource
    UserController
  end
  subgraph Services
    AbstractBccServiceImpl
    AccountService
    AccountServiceImpl
    AliasService
    AliasServiceImpl
    BccService
    BccServiceImpl
    CustomUserDetailsService
    DomainService
    DomainServiceImpl
    UserService
    UserServiceImpl
  end
  subgraph Data_Access
    AccountRepository
    AliasRepository
    BccRepository
    DomainRepository
    IncomingBccRepository
    OutgoingBccRepository
    RoleRepository
    UserRepository
  end
  subgraph Security
    AuthController
    AuthService
    AuthServiceImpl
    CorsConfiguration
    CustomUserDetailsPasswordService
    JwtAuthenticationConverter
    JwtAuthenticationFilter
    JwtAuthenticationProvider
    JwtAuthenticationToken
    JwtTokenProvider
    PasswordConfirmable
    PasswordEqualsValidator
    PasswordsMatches
    RefreshTokenProvider
    RequestLoggingFilterConfig
    SecurityConfiguration
  end
  subgraph Infrastructure
    MailServerConfiguration
    PersistenceConfiguration
  end
  Controllers --> Services
  Infrastructure --> Services
  Security --> Controllers
  Services --> Data_Access