graph TB
  subgraph Controllers
    RegController
  end
  subgraph Services
    SessionManager
    UserManager
  end
  subgraph Security
    AuthFilter
    Filter
    FilterResult
  end
  subgraph Infrastructure
    ApplicationProperties
    ApplicationReadyEventListener
    CacheConfiguration
    ClientConfiguration
    ClientProperties
    KafkaConfiguration
    KafkaConsumer
    ServerConfiguration
  end
  Controllers --> Services
  Infrastructure --> Services
  Security --> Controllers