graph TB
  subgraph Controllers
    ChangeUserEndpointAdapter
    ChangeUserEndpointPort
    FindUserEndpointAdapter
    FindUserEndpointPort
    UserController
  end
  subgraph Services
    ChangeExistingUserService
    DeleteUsersByIdService
    FindUserService
    SubmitNewUserService
  end
  subgraph Data_Access
    UserRepository
  end
  Controllers --> Services
  Services --> Data_Access