graph TB
  subgraph Controllers
    CallerController
    CallmeController
    GreetingController
    MainController
    SecureCallerBundleController
    SecureCallerController
    SecureCallmeBundleController
    SecureCallmeController
  end
  subgraph Security
    SecurityConfig
  end
  subgraph Infrastructure
    ClientSSLProperties
  end
  Security --> Controllers