graph TB
  subgraph Controllers
    TransactionController
  end
  subgraph Services
    OrderService
    StockService
  end
  subgraph Data_Access
    OrderRepository
  end
  Controllers --> Services
  Services --> Data_Access