graph TB
  subgraph Controllers
    OrderServiceImpl
    ProductServiceImpl
    ScoreServiceImpl
    TCCScoreServiceImpl
    UserController
    UserServiceImpl
  end
  subgraph Services
    OrderService
    ProductService
    ScoreService
    TCCScoreService
    UserService
  end
  subgraph Data_Access
    Order
    OrderReposity
    Product
    ProductReposity
    Score
    ScoreReposity
    User
    UserReposity
  end
  subgraph Security
    WebSecurityConfig
  end
  subgraph Infrastructure
    H2ServerConfiguration
  end
  Controllers --> Data_Access
  Controllers --> Services