graph TB
  subgraph Security
    JWTAuthorizationListener
  end
  subgraph Infrastructure
    RedissonConfig
    SocketioHazelcastProperties
    SocketioRedisTemplateConfiguration
    SocketioRedisTemplateProperties
    SocketioRedissonConfiguration
    SocketioRedissonProperties
    SocketioServerAutoConfiguration
    SocketioServerProperties
  end