graph TB
  subgraph Controllers
    BookController
    HealthController
    LoginController
    LoginControllerAdvice
    RegistrationController
    RegistrationControllerAdvice
  end
  subgraph Services
    BookService
    BookServiceImpl
    UserDetailsServiceImpl
    UserService
    UserServiceImpl
    UserValidationService
  end
  subgraph Data_Access
    BookRepository
    UserRepository
  end
  subgraph Security
    ExceptionMessageAccessor
    GeneralMessageAccessor
    JwtAuthenticationEntryPoint
    JwtAuthenticationFilter
    JwtProperties
    JwtTokenManager
    JwtTokenService
    PasswordEncoderConfiguration
    SecurityConfiguration
  end
  subgraph Infrastructure
    MessageConfiguration
    SwaggerConfiguration
  end
  Controllers --> Services
  Infrastructure --> Services
  Security --> Controllers
  Services --> Data_Access