graph TB
  subgraph Controllers
    UserController
  end
  subgraph Services
    CustomUserService
    HibernateSearchService
    MailService
    MailServiceImpl
    UserSearchService
    UserService
    UserServiceImpl
  end
  subgraph Data_Access
    RoleRepository
    UserRepository
    UserRoleRepository
  end
  subgraph Security
    AuthController
    InvalidPasswordResetToken
    JwtAuthenticationEntryPoint
    JwtAuthorizationTokenFilter
    JwtUserDetailsService
    MethodSecurityConfig
    PasswordResetToken
    PasswordResetTokenController
    PasswordResetTokenRepository
    PasswordResetTokenService
    PasswordResetTokenServiceImpl
    WebSecurityConfig
  end
  subgraph Infrastructure
    HibernateSearchConfig
    MailConfig
    ModelMapperConfig
    ObjectMapperConfig
    SwaggerConfig
    WebMvcConfig
  end
  Controllers --> Services
  Infrastructure --> Services
  Security --> Controllers
  Services --> Data_Access