graph TB
  subgraph Controllers
    AddressController
    UserController
  end
  subgraph Services
    AddressService
    AddressServiceImpl
    UserService
    UserServiceImpl
  end
  subgraph Data_Access
    AddressRepository
    UserCustomRepository
    UserCustomRepositoryImpl
    UserRepository
  end
  subgraph Infrastructure
    CacheCustomizer
    CachingConfigurationProperties
  end
  Controllers --> Services
  Infrastructure --> Services
  Services --> Data_Access