graph TB
  subgraph Controllers
    InventoryController
  end
  subgraph Services
    TenantServiceAspect
  end
  subgraph Data_Access
    InventoryRepository
    MultiTenancyRepository
    VendorRepository
  end
  subgraph Security
    SecurityConfig
  end
  subgraph Infrastructure
    FlywayConfig
    HibernateInterceptorConfiguration
  end
  Controllers --> Services
  Infrastructure --> Services
  Security --> Controllers
  Services --> Data_Access