graph TB
  subgraph Controllers
    LoginController
  end
  subgraph Services
    LoginService
    LoginServiceImpl
    UserDetailsServiceImpl
  end
  subgraph Security
    AuthenticationTokenFilter
    EntryPointUnauthorizedHandler
    MyAccessDeniedHandler
    SecurityModelFactory
    TokenDetail
    TokenDetailImpl
    WebSecurityConfig
  end
  Controllers --> Security
  Controllers --> Services
  Services --> Security