graph TB
  subgraph Controllers
    UserController
  end
  subgraph Services
    CustomOidcUserService
    LocalUserDetailService
    UserService
    UserServiceImpl
  end
  subgraph Data_Access
    RoleRepository
    UserRepository
  end
  subgraph Security
    AuthController
    CustomOAuth2UserService
    FacebookOAuth2UserInfo
    GithubOAuth2UserInfo
    GoogleOAuth2UserInfo
    HttpCookieOAuth2AuthorizationRequestRepository
    LinkedinOAuth2UserInfo
    OAuth2AccessTokenResponseConverterWithDefaults
    OAuth2AuthenticationFailureHandler
    OAuth2AuthenticationSuccessHandler
    OAuth2UserInfo
    OAuth2UserInfoFactory
    PasswordMatches
    PasswordMatchesValidator
    RestAuthenticationEntryPoint
    TokenAuthenticationFilter
    TokenProvider
    WebSecurityConfig
  end
  subgraph Infrastructure
    AppProperties
    WebConfig
  end
  Controllers --> Services
  Infrastructure --> Services
  Security --> Controllers
  Services --> Data_Access