graph TB
  subgraph Controllers
    InventoryController
    OrderController
    ProductController
  end
  subgraph Services
    InventoryServiceClient
    InventoryServiceFeignClient
    ProductService
  end
  subgraph Data_Access
    InventoryItem
    InventoryItemRepository
    Order
    OrderItem
    OrderRepository
    Product
    ProductRepository
  end
  subgraph Security
    AuthHeaderFilter
    OAuth2Config
    WebSecurityConfigurer
  end
  subgraph Infrastructure
    WebMvcConfig
  end
  Controllers --> Data_Access
  Controllers --> Services
  Security --> Data_Access
  Services --> Data_Access