graph TB
  subgraph Security
    SwaggerAuthorizationConfiguration
    SwaggerAuthorizationProperties
  end
  subgraph Infrastructure
    DocketConfiguration
    SwaggerAutoConfiguration
    SwaggerProperties
    SwaggerUiConfiguration
    SwaggerUiProperties
  end