graph TB
  subgraph Controllers
    UserRestController
  end
  subgraph Services
    IUserService
    UserServiceImpl
  end
  subgraph Data_Access
    UserRepository
  end
  subgraph Security
    InvaildUserAuthenticationEntryPoint
    SecurityConfig
    SecurityFilter
  end
  subgraph Infrastructure
    AppConfig
  end
  Controllers --> Services
  Infrastructure --> Services
  Security --> Controllers
  Services --> Data_Access