graph TB
  subgraph Controllers
    BooksController
    ErrorController
    LogoutController
    SurveyController
    SurveyControllerIT
    TodoController
    WelcomeController
  end
  subgraph Services
    DataService
    SurveyService
    TodoService
    UserDaoServiceCommandLineRunner
    WelcomeService
  end
  subgraph Data_Access
    User
    UserDAOService
    UserRepository
    UserRepositoryCommandLineRunner
    UserRestRepository
  end
  subgraph Security
    SecurityConfig
    SecurityConfiguration
  end
  subgraph Infrastructure
    BasicConfiguration
  end
  Controllers --> Infrastructure
  Controllers --> Services
  Services --> Data_Access