graph TB
  subgraph Controllers
    AdviceController
    AuthController
    AuthorizationController
    HelloController
    InterceptorController
    RdbmsController
    UserController
  end
  subgraph Services
    AuthServiceImpl
    InfoService
    InfoServiceImpl
    ServiceUnavailable
    UserService
    UserServiceImpl
  end
  subgraph Data_Access
    CassandraInfoPersistentRepository
    CassandraUserPersistentRepository
    InfoPersistentRepository
    LocalInfoPersistentRepository
    LocalUserPersistentRepository
    MongoInfoPersistentRepository
    MongoUserPersistentRepository
    RdbmsInfoPersistentRepository
    RdbmsUserPersistentRepository
    UserPersistentRepository
  end
  subgraph Security
    AuthComponent
    AuthService
    BCryptPasswordEncryptionComponent
    UnAuthorized
  end
  subgraph Infrastructure
    CacheRepository
    LocalCacheRepository
    RedisCacheRepository
  end
  Controllers --> Security
  Controllers --> Services
  Services --> Data_Access
  Services --> Security