graph TB
  subgraph Controllers
    ApiController
    UserController
    WebController
  end
  subgraph Services
    ApiServiceImpl
    IApiService
    PersonServiceImpl
    ServiceAop
  end
  subgraph Infrastructure
    AnnotationBeanConfiguration
    ApplicationConfiguration
    DruidConfiguration
    DruidDataSourceProperties
    DubboComsumerConfiguration
    DubboProperties
    DubboProviderConfiguration
    MProxyTransactionManagementConfiguration
  end
  Controllers --> Services
  Infrastructure --> Services