graph TB
  subgraph Controllers
    CatalogController
    CatalogControllerIT
    CirculationDeskController
    CirculationDeskControllerIT
  end
  subgraph Services
    CatalogManagement
    CirculationDesk
  end
  subgraph Data_Access
    Book
    BookRepository
    CatalogBook
    CatalogRepository
    Hold
    HoldRepository
  end
  subgraph Security
    Authenticated
    AuthenticatedUserArgumentResolver
    KeycloakJwtAuthenticationConverter
    LibraryWebSecurityConfiguration
  end
  Controllers --> Data_Access
  Controllers --> Security
  Controllers --> Services
  Services --> Data_Access