graph TB
  subgraph Infrastructure
    AbstractTuCacheService
    LocalCacheService
    LocalCacheServiceConfigure
    RedisCacheService
    RedisCacheServiceConfigure
    RedissonCacheService
    RedissonCacheServiceConfigure
    TuCache
    TuCacheAspect
    TuCacheAutoConfigure
    TuCacheClear
    TuCacheCondition
    TuCacheProfiles
    TuCacheProfilesConfigure
    TuCacheService
    TuTreeCache
    TucacheDefaultThreadPool
  end