graph TB
  subgraph Controllers
    ApplicationErrorController
    ControllerExceptionHandler
    FaultyRestController
    HashtagController
    PostController
    UserController
  end
  subgraph Services
    HashtagService
    HashtagServiceImpl
    PostService
    PostServiceImpl
    UserDetailsServiceImpl
    UserService
    UserServiceImpl
  end
  subgraph Data_Access
    FollowRepository
    HashtagPostsRepository
    HashtagsRepository
    LikesRepository
    PostsRepository
    UsersRepository
  end
  subgraph Security
    AuthenticationController
    JwtRequestFilter
    RefreshToken
    RefreshTokenRepository
    RefreshTokenService
    RefreshTokenServiceImpl
    SecurityConfig
  end
  subgraph Infrastructure
    JpaConfig
    MicrometerConfig
  end
  Controllers --> Services
  Infrastructure --> Services
  Security --> Controllers
  Services --> Data_Access