graph TB
  subgraph Controllers
    GenericControllerAdvice
    UserController
  end
  subgraph Services
    CustomUserDetailsService
    UserService
    UserServiceImpl
  end
  subgraph Data_Access
    UserRepository
  end
  subgraph Security
    SecurityConfiguration
  end
  subgraph Infrastructure
    WebMvcConfiguration
  end
  Controllers --> Services
  Infrastructure --> Services
  Security --> Controllers
  Services --> Data_Access