graph TB
  subgraph Controllers
    AdController
    AdSiteController
    AuthAdminController
    AuthPermissionRuleController
    AuthRoleController
    HelloController
    LoginController
    UploadController
  end
  subgraph Services
    AdService
    AdServiceImpl
    AdSiteService
    AdSiteServiceImpl
    AuthAdminServiceImpl
    AuthLoginServiceImpl
    AuthPermissionRuleServiceImpl
    AuthPermissionServiceImpl
    AuthRoleAdminServiceImpl
    AuthRoleServiceImpl
  end
  subgraph Security
    AuthAdmin
    AuthAdminDao
    AuthAdminService
    AuthLoginService
    AuthPermission
    AuthPermissionDao
    AuthPermissionRule
    AuthPermissionRuleDao
    AuthPermissionRuleService
    AuthPermissionService
    AuthRole
    AuthRoleAdmin
    AuthRoleAdminDao
    AuthRoleAdminService
    AuthRoleDao
    AuthRoleService
    AuthRuleAnnotation
    AuthorizeAspect
    CorsConfig
    CorsFilter
    DruidStatFilter
  end
  subgraph Infrastructure
    PageHelperConfig
    PublicFileUrlConfig
  end
  Controllers --> Security
  Controllers --> Services
  Services --> Security