apiVersion: v1
kind: Secret
metadata:
  name: shopsphere-secrets
  namespace: shopsphere
type: Opaque
data:
  MONGODB_USERNAME: cm9vdA==
  MONGODB_PASSWORD: cm9vdA==
  JWT_SECRET: bXlTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb25UaGF0SXNMb25nRW5vdWdoRm9ySFMyNTZBbGdvcml0aG0yMDI0
  STRIPE_SECRET_KEY: eW91cl9zdHJpcGVfc2VjcmV0X2tleV9oZXJl
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""
