@startuml

  class MavenWrapperDownloader {
    -WRAPPER_VERSION : String
    -DEFAULT_DOWNLOAD_URL : String
    -MAVEN_WRAPPER_PROPERTIES_PATH : String
    -MAVEN_WRAPPER_JAR_PATH : String
    -PROPERTY_NAME_WRAPPER_URL : String
    +main() : void
    +getPasswordAuthentication() : PasswordAuthentication
  }

package com.tomo.mcauthentication {
  class McAuthenticationApplication {
    +main() : void
  }
}

package com.tomo.mcauthentication.application {
  class McAuthenticationEventHandler {
    -eventStore : EventStore
    +listen() : void
    +handleEvent() : void
    +subscribedToEventType() : Class<DomainEvent>
  }
  class BaseMapper {
    -modelMapper : ModelMapper
  }
}

package com.tomo.mcauthentication.application.authentication {
  class BaseLoginCommandHandler {
    -sessionRepository : SessionRepository
    -tokenProvider : TokenProvider
    +toDto() : SessionDto
  }
  class EmailLoginCommandHandler {
    +handle() : SessionDto
  }
  class FacebookLoginCommandHandler {
    +handle() : BaseUserDto
  }
  class LogoutCommandHandler <<Service>> {
    +abstractHandle() : void
  }
  class SessionAuthenticationCommandHandler <<Service>> {
    +handle() : SessionDto
  }
  class GoogleLoginCommandHandler {
    +handle() : BaseUserDto
  }
}

package com.tomo.mcauthentication.application.authentication.command {
  class BaseLoginCommand {
    -rememberMe : Boolean
    -userAgent : String
    -ipAddress : String
  }
  class FacebookLoginCommand {
    -accessCode : String
  }
  class EmailLoginCommand {
    -email : String
    -password : String
    -rememberMe : Boolean
    -userAgent : String
    -ipAddress : String
  }
  class LogoutCommand {
  }
  class GoogleLoginCommand {
    -accessCode : String
  }
  class SessionAuthenticationCommand {
  }
}

package com.tomo.mcauthentication.application.authentication.dto {
  class SessionDto {
    -sessionId : String
    -accessToken : String
    -expirationDate : LocalDateTime
    -tokenType : String
    -refreshToken : String
    -userAgent : String
    -ipAddress : String
    -lastActivity : LocalDateTime
    -userId : String
    +create() : SessionDto
    +setSessionId() : void
    +setTokenType() : void
    +setUserId() : void
  }
  class RecoveryPasswordDto {
  }
}

package com.tomo.mcauthentication.application.configuration {
  class AbstractVoidyCommandHandler {
    +handle() : Voidy
    +abstractHandle() : void
  }
  interface RequestHandler {
  }
  interface QueryHandler {
  }
  interface CommandHandler {
  }
}

package com.tomo.mcauthentication.application.contracts {
  interface Identifiable {
  }
  interface Response {
  }
  class BaseQuery {
  }
  interface Command {
  }
  class BaseCommand {
  }
  interface Query {
  }
  interface McAuthenticationModule {
  }
  class Voidy {
  }
  class BaseRequest {
    -id : UUID
    +id() : UUID
    +setId() : void
  }
  interface Request {
  }
}

package com.tomo.mcauthentication.application.contracts.security {
  class AbstractAuthenticateRequest {
    +authToken() : String
    +setAuthToken() : void
  }
  class AbstractAuthenticateQuery {
  }
  class AbstractAuthorizeQuery {
  }
  class AbstractAuthorizeCommand {
  }
  class AbstractAuthenticateCommand {
  }
  class AbstractAuthorizeRequest {
  }
  interface Authorize {
  }
  interface Authenticate {
  }
}

package com.tomo.mcauthentication.application.recovery {
  class UpdatePasswordWithRecoveryCodeCommandHandler <<Service>> {
    +abstractHandle() : void
  }
  class CreatePasswordRecoveryCodeCommandHandler <<Service>> {
    +handle() : RecoveryPasswordDto
  }
  class GetUserRegistrationWithRecoveryCodeQueryHandler {
    -userRegistrationRepository : UserRegistrationRepository
    -encryptionService : EncryptionService
    +handle() : UserRegistrationDto
  }
  class PasswordRecoveryCodeCreatedEventHandler {
    -module : McAuthenticationModule
    -recoveryLink : String
    +listen() : void
    +handleEvent() : void
    +subscribedToEventType() : Class<PasswordRecoveryCodeCreated>
  }
  class SendPasswordRecoveryEmailCommandHandler {
    +abstractHandle() : void
  }
}

package com.tomo.mcauthentication.application.recovery.command {
  class CreatePasswordRecoveryCodeCommand {
    -email : String
  }
  class UpdatePasswordWithRecoveryCodeCommand {
    -newPassword : String
    -newPasswordRepeated : String
    -recoveryCode : String
  }
  class SendPasswordRecoveryEmailCommand {
  }
}

package com.tomo.mcauthentication.application.recovery.dto {
  class GetUserRegistrationWithRecoveryCodeQuery {
  }
}

package com.tomo.mcauthentication.application.registration {
  class ConfirmUserRegistrationCommandHandler {
    +handle() : BaseUserDto
  }
  class GetUserRegistrationQueryHandler {
    +handle() : UserRegistrationDto
  }
  class NewUserRegisteredEventHandler {
    -authenticationModule : McAuthenticationModule
    -confirmationLink : String
    +listen() : void
    +handleEvent() : void
    +subscribedToEventType() : Class<UserRegistrationRequested>
  }
  class RegisterNewUserCommandHandler {
    +abstractHandle() : void
  }
  class SendRegistrationConfirmationEmailCommandHandler {
    +abstractHandle() : void
  }
  class ChangePasswordCommandHandler <<Service>> {
    +abstractHandle() : void
  }
}

package com.tomo.mcauthentication.application.registration.command {
  class RegisterNewUserCommand {
    +getPassword() : String
    +setPassword() : void
    +getEmail() : String
    +setEmail() : void
    +getFirstName() : String
    +setFirstName() : void
    +getLastName() : String
    +setLastName() : void
  }
  class ConfirmUserRegistrationCommand {
    -confirmationLink : String
  }
  class ChangePasswordCommand {
    -oldPassword : String
    -newPassword : String
    -newPasswordRepeated : String
  }
  class SendRegistrationConfirmationEmailCommand {
  }
}

package com.tomo.mcauthentication.application.registration.dto {
  class UserRegistrationDto {
    -email : String
    -firstName : String
    -lastName : String
    -registerDate : LocalDateTime
    -status : UserRegistrationStatus
  }
}

package com.tomo.mcauthentication.application.registration.query {
  class GetUserRegistrationQuery {
  }
}

package com.tomo.mcauthentication.application.users {
  class GetUserQueryHandler {
    -userRepository : UserRepository
    +handle() : BaseUserDto
  }
  class ChangeUserDetailsCommandHandler <<Service>> {
    +abstractHandle() : void
  }
}

package com.tomo.mcauthentication.application.users.command {
  class ChangeUserDetailsCommand {
    -userId : UUID
    -firstName : String
    -lastName : String
    +getAuthorities() : List<String>
  }
}

package com.tomo.mcauthentication.application.users.dto {
  class BaseUserDto {
    -userId : String
    +setUserId() : void
  }
}

package com.tomo.mcauthentication.application.users.query {
  class GetUserQuery {
    +getUserId() : UserId
  }
}

package com.tomo.mcauthentication.domain {
  interface EncryptionService {
  }
  class DomainRegistry {
    -applicationContext : ApplicationContext
    +encryptionService() : EncryptionService
    +passwordService() : PasswordService
    +tokenProvider() : TokenProvider
    +modelMapper() : ModelMapper
    +userRepository() : UserRepository
    +userRegistrationRepository() : UserRegistrationRepository
    +userEmailMustBeUnique() : UserEmailMustBeUnique
    +userRegistrationMustBeUnique() : UserRegistrationMustBeUnique
  }
}

package com.tomo.mcauthentication.domain.oauth2 {
  class OAuth2Principal {
    -id : String
    -email : String
    -firstName : String
    -lastName : String
    -imageUrl : String
    -provider : String
  }
  class OAuth2Service {
    -oAuth2Authentication : OAuth2Authentication
    -userRespository : UserRepository
    +registerAuthenticate() : User
    +authenticateAndRegister() : User
  }
  interface OAuth2Authentication {
  }
}

package com.tomo.mcauthentication.domain.registration {
  interface UserRegistrationRepository {
  }
  class EmailAuthenticationService <<Service>> {
    +authenticate() : User
    +createPasswordRecoveryCode() : String
    +recoverPasswordWithRecoveryCode() : void
  }
  enum UserRegistrationStatus {
  }
  class UserRegistrationId {
    +hashPrimeValue() : int
    +hashOddValue() : int
  }
  class PasswordService {
    -DIGITS : String
    -LETTERS : String
    -STRONG_THRESHOLD : int
    -SYMBOLS : String
    -VERY_STRONG_THRESHOLD : int
    +generateStrongPassword() : String
    +isStrong() : boolean
    +isVeryStrong() : boolean
    +isWeak() : boolean
  }
  interface UsersCounter {
  }
  class UserRegistration <<Entity>> {
    -RECOVERY_CODE_EXPIREATION_MSEC : Long
    -id : long
    -password : String
    -email : String
    -firstName : String
    -lastName : String
    -confirmationCode : String
    -registerDate : LocalDateTime
    -status : UserRegistrationStatus
    -recoveryCode : String
    +registerNewUser() : UserRegistration
    +createUser() : User
    +createRecoveryCode() : String
    +isRecoveryCodeUnexpired() : boolean
    +isRecoveryCodeExpired() : boolean
    +changePassword() : void
    +changePasswordWithRecoveryCode() : void
    +assertNewPassword() : void
  }
}

package com.tomo.mcauthentication.domain.registration.events {
  class PasswordChanged {
    -userRegistrationId : long
    -password : String
  }
  class PasswordRecovered {
    -userRegistrationId : long
    -password : String
    -recoveryCode : String
  }
  class UserRegistrationRequested {
    -userRegistrationId : long
    -email : String
    -confirmationCode : String
    -firstName : String
    -lastName : String
    -registerDate : LocalDateTime
    -status : UserRegistrationStatus
  }
  class UserRegistrationConfirmed {
    -userRegistrationId : long
    -status : UserRegistrationStatus
    -userId : UserId
  }
  class PasswordRecoveryCodeCreated {
    -email : String
    -recoveryCode : String
    -recoveryCodeExpirationDate : LocalDateTime
  }
}

package com.tomo.mcauthentication.domain.registration.rules {
  class UserRegistrationMustBeUnique {
    -repository : UserRegistrationRepository
    -email : String
    +isRuleComplied() : Boolean
    +message() : String
  }
  class PasswordRecoveryCodeShouldBeExpiredOrNull {
    -userRegistration : UserRegistration
    +isRuleComplied() : Boolean
    +message() : String
  }
  class PasswordRecoveryCodeShouldNotExpired {
    -userRegistration : UserRegistration
    +isRuleComplied() : Boolean
    +message() : String
  }
  class PasswordsMustMatch {
    -providedPassoword : String
    -storedPassword : String
    +isRuleComplied() : Boolean
    +message() : String
  }
  class UserRegistrationMustBeConfirmed {
    -userRegistrationStatus : UserRegistrationStatus
    +isRuleComplied() : Boolean
    +message() : String
  }
  class UserRegistrationCannotBeConfirmedMoreThanOnce {
    +isRuleComplied() : Boolean
    +message() : String
  }
  class RecoveryCodeMustMatch {
    -providedCode : String
    -storedCode : String
    +isRuleComplied() : Boolean
    +message() : String
  }
  class UserRegistrationCannotBeConfirmedAfterExpiration {
    -CONFIRMATION_LINK_DURATION : int
    +isRuleComplied() : Boolean
    +message() : String
  }
}

package com.tomo.mcauthentication.domain.session {
  class SessionAuthenticationService <<Service>> {
    +authenticate() : Session
    +logout() : Session
  }
  class SessionId {
    +hashOddValue() : int
    +hashPrimeValue() : int
  }
  interface TokenProvider {
  }
  interface SessionRepository {
  }
  class Session <<Entity>> {
    -EXPIRATION_MSEC : Long
    -sessionId : SessionId
    -accessToken : String
    -expirationDate : LocalDateTime
    -tokenType : TokenType
    -refreshToken : String
    -userAgent : String
    -ipAddress : String
    -lastActivity : LocalDateTime
    -userId : UserId
    +isExpired() : boolean
  }
  class JwtTokenProvider <<Service>> {
    -logger : Logger
    -appProperties : AppProperties
    +createToken() : String
    +getUserIdFromToken() : UserId
    +validateToken() : boolean
    +getTokenType() : TokenType
    +createRefreshToken() : String
  }
}

package com.tomo.mcauthentication.domain.session.events {
  class SessionCreated {
    -sessionId : SessionId
    -userId : UserId
  }
}

package com.tomo.mcauthentication.domain.session.rule {
  class SessionCannotBeExpiredWhenRefreshTokenIsMissing {
    +isRuleComplied() : Boolean
    +message() : String
  }
}

package com.tomo.mcauthentication.domain.users {
  class EmailLogin {
  }
  class User <<Entity>> {
    +updateDetails() : void
    +setLastName() : void
    +setFirstName() : void
  }
  class UserId {
    +hashOddValue() : int
    +hashPrimeValue() : int
  }
  interface UserRepository {
  }
}

package com.tomo.mcauthentication.domain.users.events {
  class UserNameChanged {
  }
  class UserCreated {
  }
}

package com.tomo.mcauthentication.domain.users.rules {
  class UserEmailMustBeUnique {
    +isRuleComplied() : Boolean
    +message() : String
  }
}

package com.tomo.mcauthentication.infrastructure {
  class McAuthenticationModuleExecutor {
    +executeCommand() : Response
    +executeQuery() : Response
  }
}

package com.tomo.mcauthentication.infrastructure.http.oauth2 {
  class FacebookOAuth2Authentication <<Service>> {
    +authenticate() : OAuth2Principal
  }
  class GoogleOAuth2Authentication <<Service>> {
    +authenticate() : OAuth2Principal
  }
  class AbstractOAuth2Authentication {
    +authenticateUser() : OAuth2Principal
  }
  class CustomOAuth2UserService <<Service>> {
    +loadUser() : OAuth2User
  }
}

package com.tomo.mcauthentication.infrastructure.http.oauth2.user {
  class OAuth2UserInfoFactory {
    +getOAuth2UserInfo() : OAuth2UserInfo
  }
  class FacebookOAuth2UserInfo {
    +getId() : String
    +getName() : String
    +getEmail() : String
    +getImageUrl() : String
  }
  class GoogleOAuth2UserInfo {
    +getId() : String
    +getName() : String
    +getEmail() : String
    +getImageUrl() : String
  }
  class OAuth2UserInfo {
    +getId() : String
    +getName() : String
    +getEmail() : String
    +getImageUrl() : String
  }
}

package com.tomo.mcauthentication.infrastructure.persistence {
  class SessionRepositoryJpaAdapter <<Repository>> {
    +nextIdentity() : SessionId
    +findByUserId() : List<Session>
    +findByAccessToken() : Session
  }
  class UserRegistrationJpaRepositoryAdapter {
    +countByEmailAndStatus() : long
    +findAllByEmail() : List<UserRegistration>
    +findByEmail() : UserRegistration
    +findByConfirmationCode() : UserRegistration
    +findByRecoveryCode() : UserRegistration
    +findByUserId() : UserRegistration
  }
  interface SessionJpaRepository <<Repository>> {
  }
  class BaseJpaAdapter {
    -jpaRepository : E
    +save() : T
    +findById() : T
    +findAll() : List<T>
    +saveAll() : void
  }
  class UserRepositoryJpaAdapter {
    +nextIdentity() : UserId
    +findByEmail() : User
  }
  interface UserRegistrationJpaRepository <<Repository>> {
  }
  interface UserJpaRepository <<Repository>> {
  }
}

package com.tomo.mcauthentication.infrastructure.processing {
  class LoggingQueryHandlerDecorator {
    +handle() : Response
  }
  interface PipelineBuilder {
  }
  class LoggingCommandHandlerDecorator {
    +handle() : Response
  }
  class ErrorCommandHandlerDecorator {
    +abstractHandle() : void
  }
}

package com.tomo.mcauthentication.infrastructure.processing.builder {
  class CommandHandlerPipelineBuilder {
    +with() : CommandHandlerPipelineBuilder
    +build() : CommandHandler
  }
  class QueryHandlerPipelineBuilder {
    +with() : QueryHandlerPipelineBuilder
    +build() : QueryHandler
  }
  class AbstractPipelineBuilder {
    -request : E
    -handler : S
    -applicationContext : ApplicationContext
    +with() : PipelineBuilder
    +setApplicationContext() : void
    +getHandler() : S
    +getHandlerName() : String
  }
}

package com.tomo.mcauthentication.infrastructure.service {
  class MD5EncryptionService <<Service>> {
    +encryptedValue() : String
  }
}

package com.tomo.mcauthentication.infrastructure.springboot.configuration {
  class SecurityConfig {
    -oAuth2AuthenticationSuccessHandler : OAuth2AuthenticationSuccessHandler
    -oAuth2AuthenticationFailureHandler : OAuth2AuthenticationFailureHandler
    +configure() : void
  }
  class AppProperties {
    -auth : Auth
    -oauth2 : OAuth2
    -message : MessageProperties
    -baseUrl : String
    -gui : GUIProperties
    -tokenSecret : String
    -sessionAuthTokenName : String
    -tokenExpirationMsec : long
    -authorizedRedirectUris : List<String>
    +getTokenSecret() : String
    +setTokenSecret() : void
    +getTokenExpirationMsec() : long
    +setTokenExpirationMsec() : void
    +getSessionAuthTokenName() : String
    +setSessionAuthTokenName() : void
    +getAuthorizedRedirectUris() : List<String>
    +authorizedRedirectUris() : OAuth2
  }
  class MessageProperties {
    -email : Email
  }
  class GUIProperties {
  }
  class SwaggerConfig {
    +api() : Docket
  }
  class SwaggerUiWebMvcConfigurer {
    -baseUrl : String
    +addResourceHandlers() : void
    +addViewControllers() : void
    +addCorsMappings() : void
  }
  class AppConfig {
    -env : Environment
    +modelMapper() : ModelMapper
    +tokenAuthenticationFilter() : TokenAuthenticationFilter
  }
}

package com.tomo.mcauthentication.infrastructure.springboot.controller {
  class RestApiRoutes {
    -REST : String
    -PUBLIC : String
    -PRIVATE : String
    -FORM_REGISTRATION : String
    -CONFIRM_REGISTRATION : String
    -CREATE_PASSWORD_RECOVERY_CODE : String
    -PASSWORD_RESET : String
    -FORM_LOGIN : String
    -FACEBOOK_LOGIN : String
    -GOOGLE_LOGIN : String
  }
  class AuthenticationController <<Controller>> {
    -response : HttpServletResponse
    +formLogin() : ResponseEntity
    +facebookLogin() : ResponseEntity
    +googleLogin() : ResponseEntity
    +logout() : ResponseEntity
    +executeCommand() : SessionDto
  }
  class AbstractController {
    -authenticationModule : McAuthenticationModule
    -properties : AppProperties
    -request : HttpServletRequest
    -tokenProvider : TokenProvider
    +executeCommand() : Response
  }
  class RegistrationController <<Controller>> {
    +formRegister() : void
    +formRegisterConfirmation() : void
    +formRegisterRecovery() : void
    +passwordReset() : void
  }
  class UserController <<Controller>> {
    +user() : ResponseEntity
    +user() : ResponseEntity
  }
}

package com.tomo.mcauthentication.infrastructure.springboot.filter {
  class TokenAuthenticationFilter {
    -tokenProvider : TokenProvider
    -properties : AppProperties
    -logger : Logger
    +doFilterInternal() : void
  }
}

package com.tomo.mcauthentication.infrastructure.springboot.security {
  interface CurrentUser {
  }
  class OAuth2AuthenticationSuccessHandler {
    +onAuthenticationSuccess() : void
  }
  class UserAuthToken {
    -userPrincipal : UserAuthPrincipal
    +getCredentials() : Object
    +getPrincipal() : Object
  }
  class OAuth2AuthenticationFailureHandler {
    +onAuthenticationFailure() : void
  }
  class UserAuthPrincipal {
    -session : SessionDto
    -authorities : Collection<GrantedAuthority>
    -enabled : boolean
    +getSession() : SessionDto
    +getPassword() : String
    +getUsername() : String
    +isAccountNonExpired() : boolean
    +isAccountNonLocked() : boolean
    +isCredentialsNonExpired() : boolean
    +isEnabled() : boolean
  }
}

package com.tomo.mcauthentication.infrastructure.util {
  class CookieUtils {
    +getCookie() : Optional<Cookie>
    +addCookie() : void
    +updateCookie() : void
    +deleteCookie() : void
    +serialize() : String
  }
}

package com.tomo.mcauthentication.integration {
  class BaseIntegrationTest {
  }
}

package com.tomo.mcauthentication.integration.application {
  class AbstractApplicationServiceTest {
    -facebookLoginCommandHandler : FacebookLoginCommandHandler
    -googleLoginCommandHandler : GoogleLoginCommandHandler
    -emailLoginCommandHandler : EmailLoginCommandHandler
    -facebookOAuth2Authentication : FacebookOAuth2Authentication
    -googleOAuth2Authentication : GoogleOAuth2Authentication
    -confirmUserRegistrationCommandHandler : ConfirmUserRegistrationCommandHandler
    -registerNewUserCommandHandler : RegisterNewUserCommandHandler
    -userRegistrationRepository : UserRegistrationRepository
    -userRepository : UserRepository
    -sendRegistrationConfirmationEmailCommandHandler : SendRegistrationConfirmationEmailCommandHandler
    +createFormUser() : User
    +createUserRegistration() : UserRegistration
    +formLogin() : SessionDto
    +createFacbookUser() : User
    +createGoogleUser() : User
  }
}

package com.tomo.mcauthentication.integration.application.authentication {
  class LogoutCommandHandlerTest {
    +testLogout() : void
  }
  class SessionAuthenticationCommandHandlerTest {
    +testAuthenticateSession() : void
  }
  class GoogleLoginCommandHandlerTest {
    +testNewGoogleUserCreated() : void
    +testNewGoogleUserFailedWhenFacebookUserExists() : void
  }
  class FacebookLoginCommandHandlerTest {
    +testNewFacebookUserCreated() : void
    +testNewFacebookUserFailedWhenGoogleUserExists() : void
  }
  class EmailLoginCommandHandlerTest {
    +testUserFormLogin() : void
    +testNewFormUserFailedWhenGoogleUserExists() : void
  }
}

package com.tomo.mcauthentication.integration.application.recovery {
  class UpdatePasswordWithRecoveryCodeCommandHandlerTest {
    +testUpdatePasswordWithRecoveryCode() : void
  }
  class CreatePasswordRecoveryCodeCommandHandlerTest {
    +testRecoveryCodeCreated() : void
  }
  class GetUserRegistrationWithRecoveryCodeQueryHandlerTest {
    +testGetUserRegistrationWithRecoveryCode() : void
  }
}

package com.tomo.mcauthentication.integration.application.registration {
  class ConfirmUserRegistrationCommandHandlerTest {
    +testConfirmUserRegistration() : void
  }
  class ChangePasswordCommandHandlerTest {
    +testChangePassword() : void
  }
  class RegisterNewUserCommandHandlerTest {
    +testNewUserRegistrationCreated() : void
    +testNewUserRegistrationFailedWhenUserExists() : void
  }
}

package com.tomo.mcauthentication.integration.application.users {
  class ChangeUserDetailsCommandHandlerTest {
    +testChangeUserDetails() : void
  }
  class GetUserQueryHandlerTest {
    +testGetUser() : void
  }
}

package com.tomo.mcauthentication.smoke {
  class McAuthenticationApplicationSmokeTest {
  }
}

package com.tomo.mcauthentication.testdata {
  class CommandObjectMother {
    -faker : Faker
    +registerNewUserCommand() : RegisterNewUserCommand
    +registerNewUserCommandWithFakerEmail() : RegisterNewUserCommand
    +emailLoginCommand() : EmailLoginCommand
    +facebookLoginCommand() : FacebookLoginCommand
    +googleLoginCommand() : GoogleLoginCommand
    +createPasswordRecoveryCodeCommand() : CreatePasswordRecoveryCodeCommand
  }
  class StaticFields {
    -ACCESS_CODE : String
    -USER_OAUTH_ID : String
    -USER_FIRST_NAME : String
    -USER_LAST_NAME : String
    -USER_EMAIL : String
    -PASSWORD : String
    -NEW_PASS : String
    -RECOVERY_CODE : String
  }
}

package com.tomo.mcauthentication.unit.application.registration {
  class UserRegistrationCommandHandlerTest {
    -mockito : MockitoSession
    +setup() : void
    +tearDown() : void
    +setUp() : void
    +testCreateUserRegister() : void
  }
}

package com.tomo.mcauthentication.unit.domain {
  class AbstractUnitTest {
    -mockito : MockitoSession
  }
}

package com.tomo.mcauthentication.unit.domain.registration {
  class UserRegistrationTest {
    -setUpIsDone : boolean
    -WEAK_PASS : String
    +setUp() : void
    +after() : void
    +testCreateUserRegistration() : void
    +testCreateUserFromUserRegistration() : void
    +testCreateRecoveryCodeAndRecoverPassword() : void
    +testChangePassword() : void
  }
}

package com.tomo.mcauthentication.unit.domain.registration.rules {
  class PasswordRecoveryCodeShouldNotExpiredTest {
    +testRuleIsNotBroken() : void
    +testRuleIsBroken() : void
  }
  class UserRegistrationCannotBeConfirmedAfterExpirationTest {
    +testRuleIsNotBroken() : void
    +testRuleIsBroken() : void
  }
  class UserRegistrationCannotBeConfirmedMoreThanOnceTest {
    +testRuleIsNotBroken() : void
    +testRuleIsBroken() : void
  }
  class RecoveryCodeMustMatchTest {
    +testRuleIsNotBroken() : void
    +testRuleIsBroken() : void
  }
  class PasswordsMustMatchTest {
    +testRuleIsNotBroken() : void
    +testRuleIsBroken() : void
  }
  class UserRegistrationMustBeUniqueTest {
    +testRuleIsNotBroken() : void
    +testRuleIsBroken() : void
  }
  class UserRegistrationMustBeConfirmedTest {
    +testRuleIsNotBroken() : void
    +testRuleIsBroken() : void
  }
  class PasswordRecoveryCodeShouldBeExpiredOrNullTest {
    +testRuleIsNotBroken() : void
    +testRuleIsBroken() : void
  }
}

package com.tomo.mcauthentication.unit.domain.session.rules {
  class SessionCannotBeExpiredWhenRefreshTokenIsMissingTest {
    +testRuleIsNotBroken() : void
    +testRuleIsBroken() : void
  }
}

package com.tomo.mcauthentication.unit.domain.user.rules {
  class UserEmailMustBeUniqueTest {
    +testRuleIsNotBroken() : void
    +testRuleIsBroken() : void
  }
}

package com.tomo.mcauthentication.weblayer {
  class BaseWebLayerTest {
  }
}

package com.tomo.mcauthentication.weblayer.springboot.controller {
  class AbstractControllerTest {
    -emailMessageSender : EmailSender
    -randomServerPort : int
    -mockMvc : MockMvc
    -baseUrl : String
    +url() : URI
    +baseHeaders() : HttpHeaders
  }
  class RegistrationControllerTest {
    -objectMapper : ObjectMapper
    +shouldCreateUserRegistration() : void
  }
}

' --- Relatii ---
McAuthenticationApplicationSmokeTest --> UserController
CommandObjectMother --|> StaticFields
CommandObjectMother --> EmailLoginCommand
CommandObjectMother --> FacebookLoginCommand
CommandObjectMother --> GoogleLoginCommand
CommandObjectMother --> CreatePasswordRecoveryCodeCommand
CommandObjectMother --> RegisterNewUserCommand
UserRegistrationCommandHandlerTest --> DomainRegistry
UserRegistrationCommandHandlerTest --> EncryptionService
UserRegistrationCommandHandlerTest --> PasswordService
UserRegistrationCommandHandlerTest --> UserRegistration
UserRegistrationCommandHandlerTest --> UserRegistrationRepository
UserRegistrationCommandHandlerTest --> UserRegistrationStatus
UserRegistrationCommandHandlerTest --> UserRepository
UserRegistrationTest --> DomainRegistry
UserRegistrationTest --> EncryptionService
UserRegistrationTest --> PasswordService
UserRegistrationTest --> UserRegistration
UserRegistrationTest --> UserRegistrationRepository
UserRegistrationTest --> UserRegistrationStatus
UserRegistrationTest --> User
UserRegistrationTest --> UserId
UserRegistrationTest --> UserRepository
UserRegistrationTest --> StaticFields
PasswordRecoveryCodeShouldNotExpiredTest --|> AbstractUnitTest
PasswordRecoveryCodeShouldNotExpiredTest --> UserRegistration
PasswordRecoveryCodeShouldNotExpiredTest --> PasswordRecoveryCodeShouldNotExpired
PasswordRecoveryCodeShouldNotExpiredTest --> AbstractUnitTest
UserRegistrationCannotBeConfirmedAfterExpirationTest --|> AbstractUnitTest
UserRegistrationCannotBeConfirmedAfterExpirationTest --> UserRegistrationCannotBeConfirmedAfterExpiration
UserRegistrationCannotBeConfirmedAfterExpirationTest --> AbstractUnitTest
UserRegistrationCannotBeConfirmedMoreThanOnceTest --> UserRegistrationStatus
UserRegistrationCannotBeConfirmedMoreThanOnceTest --> UserRegistrationCannotBeConfirmedMoreThanOnce
RecoveryCodeMustMatchTest --|> AbstractUnitTest
RecoveryCodeMustMatchTest --> RecoveryCodeMustMatch
RecoveryCodeMustMatchTest --> AbstractUnitTest
PasswordsMustMatchTest --|> AbstractUnitTest
PasswordsMustMatchTest --> PasswordsMustMatch
PasswordsMustMatchTest --> AbstractUnitTest
UserRegistrationMustBeUniqueTest --|> AbstractUnitTest
UserRegistrationMustBeUniqueTest --> UserRegistrationRepository
UserRegistrationMustBeUniqueTest --> UserRegistrationMustBeUnique
UserRegistrationMustBeUniqueTest --> AbstractUnitTest
UserRegistrationMustBeConfirmedTest --> UserRegistrationStatus
UserRegistrationMustBeConfirmedTest --> UserRegistrationMustBeConfirmed
PasswordRecoveryCodeShouldBeExpiredOrNullTest --|> AbstractUnitTest
PasswordRecoveryCodeShouldBeExpiredOrNullTest --> UserRegistration
PasswordRecoveryCodeShouldBeExpiredOrNullTest --> PasswordRecoveryCodeShouldBeExpiredOrNull
PasswordRecoveryCodeShouldBeExpiredOrNullTest --> AbstractUnitTest
UserEmailMustBeUniqueTest --|> AbstractUnitTest
UserEmailMustBeUniqueTest --> User
UserEmailMustBeUniqueTest --> UserRepository
UserEmailMustBeUniqueTest --> UserEmailMustBeUnique
UserEmailMustBeUniqueTest --> AbstractUnitTest
SessionCannotBeExpiredWhenRefreshTokenIsMissingTest --|> AbstractUnitTest
SessionCannotBeExpiredWhenRefreshTokenIsMissingTest --> Session
SessionCannotBeExpiredWhenRefreshTokenIsMissingTest --> SessionCannotBeExpiredWhenRefreshTokenIsMissing
SessionCannotBeExpiredWhenRefreshTokenIsMissingTest --> AbstractUnitTest
AbstractApplicationServiceTest --|> BaseIntegrationTest
AbstractApplicationServiceTest --> EmailLoginCommandHandler
AbstractApplicationServiceTest --> FacebookLoginCommandHandler
AbstractApplicationServiceTest --> GoogleLoginCommandHandler
AbstractApplicationServiceTest --> SessionDto
AbstractApplicationServiceTest --> SendPasswordRecoveryEmailCommandHandler
AbstractApplicationServiceTest --> ConfirmUserRegistrationCommandHandler
AbstractApplicationServiceTest --> RegisterNewUserCommandHandler
AbstractApplicationServiceTest --> SendRegistrationConfirmationEmailCommandHandler
AbstractApplicationServiceTest --> ConfirmUserRegistrationCommand
AbstractApplicationServiceTest --> OAuth2Principal
AbstractApplicationServiceTest --> UserRegistration
AbstractApplicationServiceTest --> UserRegistrationRepository
AbstractApplicationServiceTest --> User
AbstractApplicationServiceTest --> UserRepository
AbstractApplicationServiceTest --> FacebookOAuth2Authentication
AbstractApplicationServiceTest --> GoogleOAuth2Authentication
AbstractApplicationServiceTest --> BaseIntegrationTest
AbstractApplicationServiceTest --> CommandObjectMother
AbstractApplicationServiceTest --> StaticFields
ConfirmUserRegistrationCommandHandlerTest --|> AbstractApplicationServiceTest
ConfirmUserRegistrationCommandHandlerTest --> User
ConfirmUserRegistrationCommandHandlerTest --> AbstractApplicationServiceTest
ChangePasswordCommandHandlerTest --|> AbstractApplicationServiceTest
ChangePasswordCommandHandlerTest --> EmailLoginCommand
ChangePasswordCommandHandlerTest --> SessionDto
ChangePasswordCommandHandlerTest --> Voidy
ChangePasswordCommandHandlerTest --> ChangePasswordCommandHandler
ChangePasswordCommandHandlerTest --> ChangePasswordCommand
ChangePasswordCommandHandlerTest --> AbstractApplicationServiceTest
ChangePasswordCommandHandlerTest --> StaticFields
RegisterNewUserCommandHandlerTest --|> AbstractApplicationServiceTest
RegisterNewUserCommandHandlerTest --> ConfirmUserRegistrationCommandHandler
RegisterNewUserCommandHandlerTest --> NewUserRegisteredEventHandler
RegisterNewUserCommandHandlerTest --> RegisterNewUserCommandHandler
RegisterNewUserCommandHandlerTest --> UserRegistration
RegisterNewUserCommandHandlerTest --> UserRegistrationRepository
RegisterNewUserCommandHandlerTest --> AbstractApplicationServiceTest
UpdatePasswordWithRecoveryCodeCommandHandlerTest --|> AbstractApplicationServiceTest
UpdatePasswordWithRecoveryCodeCommandHandlerTest --> EmailLoginCommand
UpdatePasswordWithRecoveryCodeCommandHandlerTest --> RecoveryPasswordDto
UpdatePasswordWithRecoveryCodeCommandHandlerTest --> SessionDto
UpdatePasswordWithRecoveryCodeCommandHandlerTest --> Voidy
UpdatePasswordWithRecoveryCodeCommandHandlerTest --> CreatePasswordRecoveryCodeCommandHandler
UpdatePasswordWithRecoveryCodeCommandHandlerTest --> UpdatePasswordWithRecoveryCodeCommandHandler
UpdatePasswordWithRecoveryCodeCommandHandlerTest --> UpdatePasswordWithRecoveryCodeCommand
UpdatePasswordWithRecoveryCodeCommandHandlerTest --> AbstractApplicationServiceTest
UpdatePasswordWithRecoveryCodeCommandHandlerTest --> CommandObjectMother
UpdatePasswordWithRecoveryCodeCommandHandlerTest --> StaticFields
CreatePasswordRecoveryCodeCommandHandlerTest --|> AbstractApplicationServiceTest
CreatePasswordRecoveryCodeCommandHandlerTest --> RecoveryPasswordDto
CreatePasswordRecoveryCodeCommandHandlerTest --> CreatePasswordRecoveryCodeCommandHandler
CreatePasswordRecoveryCodeCommandHandlerTest --> AbstractApplicationServiceTest
CreatePasswordRecoveryCodeCommandHandlerTest --> CommandObjectMother
GetUserRegistrationWithRecoveryCodeQueryHandlerTest --|> AbstractApplicationServiceTest
GetUserRegistrationWithRecoveryCodeQueryHandlerTest --> RecoveryPasswordDto
GetUserRegistrationWithRecoveryCodeQueryHandlerTest --> CreatePasswordRecoveryCodeCommandHandler
GetUserRegistrationWithRecoveryCodeQueryHandlerTest --> GetUserRegistrationWithRecoveryCodeQueryHandler
GetUserRegistrationWithRecoveryCodeQueryHandlerTest --> GetUserRegistrationWithRecoveryCodeQuery
GetUserRegistrationWithRecoveryCodeQueryHandlerTest --> UserRegistrationDto
GetUserRegistrationWithRecoveryCodeQueryHandlerTest --> AbstractApplicationServiceTest
GetUserRegistrationWithRecoveryCodeQueryHandlerTest --> CommandObjectMother
ChangeUserDetailsCommandHandlerTest --|> AbstractApplicationServiceTest
ChangeUserDetailsCommandHandlerTest --> SessionDto
ChangeUserDetailsCommandHandlerTest --> ChangeUserDetailsCommandHandler
ChangeUserDetailsCommandHandlerTest --> ChangeUserDetailsCommand
ChangeUserDetailsCommandHandlerTest --> User
ChangeUserDetailsCommandHandlerTest --> UserRepository
ChangeUserDetailsCommandHandlerTest --> AbstractApplicationServiceTest
ChangeUserDetailsCommandHandlerTest --> CommandObjectMother
GetUserQueryHandlerTest --|> AbstractApplicationServiceTest
GetUserQueryHandlerTest --> SessionDto
GetUserQueryHandlerTest --> GetUserQueryHandler
GetUserQueryHandlerTest --> GetUserQuery
GetUserQueryHandlerTest --> AbstractApplicationServiceTest
LogoutCommandHandlerTest --|> AbstractApplicationServiceTest
LogoutCommandHandlerTest --> LogoutCommandHandler
LogoutCommandHandlerTest --> LogoutCommand
LogoutCommandHandlerTest --> SessionDto
LogoutCommandHandlerTest --> SessionAuthenticationService
LogoutCommandHandlerTest --> AbstractApplicationServiceTest
SessionAuthenticationCommandHandlerTest --|> AbstractApplicationServiceTest
SessionAuthenticationCommandHandlerTest --> SessionAuthenticationCommandHandler
SessionAuthenticationCommandHandlerTest --> SessionAuthenticationCommand
SessionAuthenticationCommandHandlerTest --> SessionDto
SessionAuthenticationCommandHandlerTest --> SessionAuthenticationService
SessionAuthenticationCommandHandlerTest --> AbstractApplicationServiceTest
GoogleLoginCommandHandlerTest --|> AbstractApplicationServiceTest
GoogleLoginCommandHandlerTest --> AbstractApplicationServiceTest
FacebookLoginCommandHandlerTest --|> AbstractApplicationServiceTest
FacebookLoginCommandHandlerTest --> AbstractApplicationServiceTest
EmailLoginCommandHandlerTest --|> AbstractApplicationServiceTest
EmailLoginCommandHandlerTest --> AbstractApplicationServiceTest
AbstractControllerTest --|> BaseWebLayerTest
AbstractControllerTest --> BaseWebLayerTest
RegistrationControllerTest --|> AbstractControllerTest
RegistrationControllerTest --> RegisterNewUserCommand
RegistrationControllerTest --> CommandObjectMother
McAuthenticationApplication --> AppProperties
ConfirmUserRegistrationCommandHandler ..|> CommandHandler
ConfirmUserRegistrationCommandHandler --> CommandHandler
ConfirmUserRegistrationCommandHandler --> ConfirmUserRegistrationCommand
ConfirmUserRegistrationCommandHandler --> BaseUserDto
ConfirmUserRegistrationCommandHandler --> UserRegistration
ConfirmUserRegistrationCommandHandler --> UserRegistrationRepository
ConfirmUserRegistrationCommandHandler --> User
ConfirmUserRegistrationCommandHandler --> UserRepository
GetUserRegistrationQueryHandler ..|> QueryHandler
GetUserRegistrationQueryHandler --> QueryHandler
GetUserRegistrationQueryHandler --> UserRegistrationDto
GetUserRegistrationQueryHandler --> GetUserRegistrationQuery
NewUserRegisteredEventHandler --> McAuthenticationModule
NewUserRegisteredEventHandler --> SendRegistrationConfirmationEmailCommand
NewUserRegisteredEventHandler --> UserRegistrationRequested
RegisterNewUserCommandHandler --|> AbstractVoidyCommandHandler
RegisterNewUserCommandHandler --> AbstractVoidyCommandHandler
RegisterNewUserCommandHandler --> RegisterNewUserCommand
RegisterNewUserCommandHandler --> UserRegistration
RegisterNewUserCommandHandler --> UserRegistrationRepository
RegisterNewUserCommandHandler --> UserRepository
SendRegistrationConfirmationEmailCommandHandler --|> AbstractVoidyCommandHandler
SendRegistrationConfirmationEmailCommandHandler --> AbstractVoidyCommandHandler
SendRegistrationConfirmationEmailCommandHandler --> SendRegistrationConfirmationEmailCommand
ChangePasswordCommandHandler --|> AbstractVoidyCommandHandler
ChangePasswordCommandHandler --> AbstractVoidyCommandHandler
ChangePasswordCommandHandler --> ChangePasswordCommand
ChangePasswordCommandHandler --> EmailAuthenticationService
ChangePasswordCommandHandler --> UserRegistration
ChangePasswordCommandHandler --> UserRegistrationRepository
ChangePasswordCommandHandler --> Session
ChangePasswordCommandHandler --> SessionAuthenticationService
UserRegistrationDto ..|> Response
UserRegistrationDto --> Response
UserRegistrationDto --> UserRegistrationId
UserRegistrationDto --> UserRegistrationStatus
RegisterNewUserCommand --|> BaseCommand
RegisterNewUserCommand --> BaseCommand
ConfirmUserRegistrationCommand --|> BaseCommand
ConfirmUserRegistrationCommand --> BaseCommand
ChangePasswordCommand --|> BaseCommand
ChangePasswordCommand --> BaseCommand
SendRegistrationConfirmationEmailCommand --|> BaseCommand
SendRegistrationConfirmationEmailCommand --> BaseCommand
GetUserRegistrationQuery --|> BaseQuery
GetUserRegistrationQuery --> BaseQuery
AbstractVoidyCommandHandler --> Command
AbstractVoidyCommandHandler --> Voidy
RequestHandler --> Request
RequestHandler --> Response
QueryHandler --> Query
QueryHandler --> Response
CommandHandler --> Command
CommandHandler --> Response
UpdatePasswordWithRecoveryCodeCommandHandler --|> AbstractVoidyCommandHandler
UpdatePasswordWithRecoveryCodeCommandHandler --> UpdatePasswordWithRecoveryCodeCommand
UpdatePasswordWithRecoveryCodeCommandHandler --> AbstractVoidyCommandHandler
UpdatePasswordWithRecoveryCodeCommandHandler --> EmailAuthenticationService
CreatePasswordRecoveryCodeCommandHandler ..|> CommandHandler
CreatePasswordRecoveryCodeCommandHandler --> CreatePasswordRecoveryCodeCommand
CreatePasswordRecoveryCodeCommandHandler --> RecoveryPasswordDto
CreatePasswordRecoveryCodeCommandHandler --> CommandHandler
CreatePasswordRecoveryCodeCommandHandler --> EmailAuthenticationService
GetUserRegistrationWithRecoveryCodeQueryHandler --|> BaseMapper
GetUserRegistrationWithRecoveryCodeQueryHandler ..|> QueryHandler
GetUserRegistrationWithRecoveryCodeQueryHandler --> BaseMapper
GetUserRegistrationWithRecoveryCodeQueryHandler --> QueryHandler
GetUserRegistrationWithRecoveryCodeQueryHandler --> UserRegistrationDto
GetUserRegistrationWithRecoveryCodeQueryHandler --> GetUserRegistrationWithRecoveryCodeQuery
GetUserRegistrationWithRecoveryCodeQueryHandler --> EncryptionService
GetUserRegistrationWithRecoveryCodeQueryHandler --> UserRegistration
GetUserRegistrationWithRecoveryCodeQueryHandler --> UserRegistrationRepository
PasswordRecoveryCodeCreatedEventHandler --> McAuthenticationModule
PasswordRecoveryCodeCreatedEventHandler --> SendPasswordRecoveryEmailCommand
PasswordRecoveryCodeCreatedEventHandler --> PasswordRecoveryCodeCreated
SendPasswordRecoveryEmailCommandHandler --|> AbstractVoidyCommandHandler
SendPasswordRecoveryEmailCommandHandler --> AbstractVoidyCommandHandler
SendPasswordRecoveryEmailCommandHandler --> SendPasswordRecoveryEmailCommand
GetUserRegistrationWithRecoveryCodeQuery --|> BaseQuery
GetUserRegistrationWithRecoveryCodeQuery --> BaseQuery
CreatePasswordRecoveryCodeCommand --|> BaseCommand
CreatePasswordRecoveryCodeCommand --> BaseCommand
UpdatePasswordWithRecoveryCodeCommand --|> BaseCommand
UpdatePasswordWithRecoveryCodeCommand --> BaseCommand
SendPasswordRecoveryEmailCommand --|> BaseCommand
SendPasswordRecoveryEmailCommand --> BaseCommand
BaseQuery --|> BaseRequest
BaseQuery ..|> Query
Command --|> Request
BaseCommand --|> BaseRequest
BaseCommand ..|> Command
Query --|> Request
Voidy ..|> Response
BaseRequest ..|> Request
Request --|> Identifiable
AbstractAuthenticateRequest --|> BaseRequest
AbstractAuthenticateRequest ..|> Authenticate
AbstractAuthenticateRequest ..|> Request
AbstractAuthenticateRequest --> BaseRequest
AbstractAuthenticateRequest --> Command
AbstractAuthenticateRequest --> Request
AbstractAuthenticateQuery --|> AbstractAuthenticateRequest
AbstractAuthenticateQuery ..|> Query
AbstractAuthenticateQuery --> BaseRequest
AbstractAuthenticateQuery --> Command
AbstractAuthenticateQuery --> Query
AbstractAuthorizeQuery --|> AbstractAuthorizeRequest
AbstractAuthorizeQuery ..|> Query
AbstractAuthorizeQuery --> Command
AbstractAuthorizeQuery --> Query
AbstractAuthorizeCommand --|> AbstractAuthorizeRequest
AbstractAuthorizeCommand ..|> Command
AbstractAuthorizeCommand --> Command
AbstractAuthenticateCommand --|> AbstractAuthenticateRequest
AbstractAuthenticateCommand ..|> Command
AbstractAuthenticateCommand --> Command
AbstractAuthorizeRequest --|> AbstractAuthenticateRequest
AbstractAuthorizeRequest ..|> Request
AbstractAuthorizeRequest ..|> Authorize
AbstractAuthorizeRequest --> Command
AbstractAuthorizeRequest --> Request
Authorize --|> Authenticate
GetUserQueryHandler --|> BaseMapper
GetUserQueryHandler ..|> QueryHandler
GetUserQueryHandler --> BaseMapper
GetUserQueryHandler --> QueryHandler
GetUserQueryHandler --> BaseUserDto
GetUserQueryHandler --> GetUserQuery
GetUserQueryHandler --> User
GetUserQueryHandler --> UserRepository
ChangeUserDetailsCommandHandler --|> AbstractVoidyCommandHandler
ChangeUserDetailsCommandHandler --> AbstractVoidyCommandHandler
ChangeUserDetailsCommandHandler --> ChangeUserDetailsCommand
ChangeUserDetailsCommandHandler --> EmailAuthenticationService
ChangeUserDetailsCommandHandler --> TokenProvider
ChangeUserDetailsCommandHandler --> User
ChangeUserDetailsCommandHandler --> UserId
ChangeUserDetailsCommandHandler --> UserRepository
BaseUserDto ..|> Response
BaseUserDto --> Response
BaseUserDto --> UserId
ChangeUserDetailsCommand --|> AbstractAuthorizeCommand
ChangeUserDetailsCommand --> AbstractAuthorizeCommand
GetUserQuery --|> AbstractAuthenticateQuery
GetUserQuery --> AbstractAuthenticateQuery
GetUserQuery --> UserId
BaseLoginCommandHandler --|> BaseMapper
BaseLoginCommandHandler --> BaseMapper
BaseLoginCommandHandler --> SessionDto
BaseLoginCommandHandler --> Session
BaseLoginCommandHandler --> SessionRepository
BaseLoginCommandHandler --> TokenProvider
EmailLoginCommandHandler --|> BaseLoginCommandHandler
EmailLoginCommandHandler ..|> CommandHandler
EmailLoginCommandHandler --> EmailLoginCommand
EmailLoginCommandHandler --> SessionDto
EmailLoginCommandHandler --> CommandHandler
EmailLoginCommandHandler --> Session
EmailLoginCommandHandler --> SessionRepository
EmailLoginCommandHandler --> TokenProvider
EmailLoginCommandHandler --> EmailAuthenticationService
EmailLoginCommandHandler --> User
FacebookLoginCommandHandler --|> BaseLoginCommandHandler
FacebookLoginCommandHandler ..|> CommandHandler
FacebookLoginCommandHandler --> FacebookLoginCommand
FacebookLoginCommandHandler --> CommandHandler
FacebookLoginCommandHandler --> BaseUserDto
FacebookLoginCommandHandler --> OAuth2Service
FacebookLoginCommandHandler --> Session
FacebookLoginCommandHandler --> SessionRepository
FacebookLoginCommandHandler --> TokenProvider
FacebookLoginCommandHandler --> User
LogoutCommandHandler --|> AbstractVoidyCommandHandler
LogoutCommandHandler --> LogoutCommand
LogoutCommandHandler --> AbstractVoidyCommandHandler
LogoutCommandHandler --> SessionAuthenticationService
SessionAuthenticationCommandHandler --|> BaseMapper
SessionAuthenticationCommandHandler ..|> CommandHandler
SessionAuthenticationCommandHandler --> BaseMapper
SessionAuthenticationCommandHandler --> SessionAuthenticationCommand
SessionAuthenticationCommandHandler --> SessionDto
SessionAuthenticationCommandHandler --> CommandHandler
SessionAuthenticationCommandHandler --> Session
SessionAuthenticationCommandHandler --> SessionAuthenticationService
GoogleLoginCommandHandler --|> BaseLoginCommandHandler
GoogleLoginCommandHandler ..|> CommandHandler
GoogleLoginCommandHandler --> GoogleLoginCommand
GoogleLoginCommandHandler --> CommandHandler
GoogleLoginCommandHandler --> BaseUserDto
GoogleLoginCommandHandler --> OAuth2Service
GoogleLoginCommandHandler --> Session
GoogleLoginCommandHandler --> SessionRepository
GoogleLoginCommandHandler --> TokenProvider
GoogleLoginCommandHandler --> User
SessionDto --|> BaseUserDto
SessionDto --> BaseUserDto
SessionDto --> Session
SessionDto --> SessionId
SessionDto --> UserId
RecoveryPasswordDto ..|> Response
RecoveryPasswordDto --> Response
BaseLoginCommand --|> BaseCommand
BaseLoginCommand --> BaseCommand
FacebookLoginCommand --|> BaseLoginCommand
EmailLoginCommand --|> BaseLoginCommand
LogoutCommand --|> AbstractAuthenticateCommand
LogoutCommand --> AbstractAuthenticateCommand
GoogleLoginCommand --|> BaseLoginCommand
SessionAuthenticationCommand --|> AbstractAuthenticateCommand
SessionAuthenticationCommand --> AbstractAuthenticateCommand
McAuthenticationModuleExecutor ..|> McAuthenticationModule
McAuthenticationModuleExecutor --> CommandHandler
McAuthenticationModuleExecutor --> QueryHandler
McAuthenticationModuleExecutor --> Command
McAuthenticationModuleExecutor --> McAuthenticationModule
McAuthenticationModuleExecutor --> Query
McAuthenticationModuleExecutor --> Response
McAuthenticationModuleExecutor --> CommandHandlerPipelineBuilder
McAuthenticationModuleExecutor --> QueryHandlerPipelineBuilder
SecurityConfig --> OAuth2AuthenticationFailureHandler
SecurityConfig --> OAuth2AuthenticationSuccessHandler
AppConfig --> McAuthenticationModule
AppConfig --> OAuth2Service
AppConfig --> UserRegistrationRepository
AppConfig --> UserRepository
AppConfig --> McAuthenticationModuleExecutor
AppConfig --> FacebookOAuth2Authentication
AppConfig --> GoogleOAuth2Authentication
AppConfig --> UserJpaRepository
AppConfig --> UserRegistrationJpaRepository
AppConfig --> UserRegistrationJpaRepositoryAdapter
AppConfig --> UserRepositoryJpaAdapter
AppConfig --> CommandHandlerPipelineBuilder
AppConfig --> QueryHandlerPipelineBuilder
AppConfig --> TokenAuthenticationFilter
UserAuthToken --> User
UserAuthPrincipal --> SessionDto
UserAuthPrincipal --> User
AuthenticationController --|> AbstractController
AuthenticationController --> EmailLoginCommand
AuthenticationController --> FacebookLoginCommand
AuthenticationController --> GoogleLoginCommand
AuthenticationController --> LogoutCommand
AuthenticationController --> SessionDto
AuthenticationController --> Command
AuthenticationController --> CurrentUser
AuthenticationController --> UserAuthPrincipal
AuthenticationController --> CookieUtils
AbstractController --> Command
AbstractController --> McAuthenticationModule
AbstractController --> Query
AbstractController --> Request
AbstractController --> Response
AbstractController --> Authenticate
AbstractController --> TokenProvider
AbstractController --> AppProperties
AbstractController --> CookieUtils
RegistrationController --|> AbstractController
RegistrationController --> CreatePasswordRecoveryCodeCommand
RegistrationController --> UpdatePasswordWithRecoveryCodeCommand
RegistrationController --> ConfirmUserRegistrationCommand
RegistrationController --> RegisterNewUserCommand
UserController --|> AbstractController
UserController --> ChangeUserDetailsCommand
UserController --> BaseUserDto
UserController --> GetUserQuery
UserController --> User
TokenAuthenticationFilter --> SessionAuthenticationCommand
TokenAuthenticationFilter --> SessionDto
TokenAuthenticationFilter --> McAuthenticationModule
TokenAuthenticationFilter --> TokenProvider
TokenAuthenticationFilter --> UserId
TokenAuthenticationFilter --> UserRepository
TokenAuthenticationFilter --> AppProperties
TokenAuthenticationFilter --> UserAuthPrincipal
TokenAuthenticationFilter --> UserAuthToken
TokenAuthenticationFilter --> CookieUtils
LoggingQueryHandlerDecorator ..|> QueryHandler
LoggingQueryHandlerDecorator --> QueryHandler
LoggingQueryHandlerDecorator --> Query
LoggingQueryHandlerDecorator --> Response
LoggingCommandHandlerDecorator ..|> CommandHandler
LoggingCommandHandlerDecorator --> CommandHandler
LoggingCommandHandlerDecorator --> Command
LoggingCommandHandlerDecorator --> Response
ErrorCommandHandlerDecorator --> AbstractVoidyCommandHandler
ErrorCommandHandlerDecorator --> CommandHandler
ErrorCommandHandlerDecorator --> Command
CommandHandlerPipelineBuilder --|> AbstractPipelineBuilder
CommandHandlerPipelineBuilder --> CommandHandler
CommandHandlerPipelineBuilder --> Command
CommandHandlerPipelineBuilder --> LoggingCommandHandlerDecorator
CommandHandlerPipelineBuilder --> PipelineBuilder
QueryHandlerPipelineBuilder --|> AbstractPipelineBuilder
QueryHandlerPipelineBuilder --> QueryHandler
QueryHandlerPipelineBuilder --> Query
QueryHandlerPipelineBuilder --> LoggingQueryHandlerDecorator
QueryHandlerPipelineBuilder --> PipelineBuilder
AbstractPipelineBuilder --> RequestHandler
AbstractPipelineBuilder --> Request
AbstractPipelineBuilder --> PipelineBuilder
FacebookOAuth2Authentication --|> AbstractOAuth2Authentication
FacebookOAuth2Authentication ..|> OAuth2Authentication
FacebookOAuth2Authentication --> OAuth2Authentication
FacebookOAuth2Authentication --> OAuth2Principal
FacebookOAuth2Authentication --> FacebookOAuth2UserInfo
FacebookOAuth2Authentication --> OAuth2UserInfoFactory
GoogleOAuth2Authentication --|> AbstractOAuth2Authentication
GoogleOAuth2Authentication ..|> OAuth2Authentication
GoogleOAuth2Authentication --> OAuth2Authentication
GoogleOAuth2Authentication --> OAuth2Principal
GoogleOAuth2Authentication --> FacebookOAuth2UserInfo
GoogleOAuth2Authentication --> OAuth2UserInfoFactory
AbstractOAuth2Authentication --> OAuth2Principal
AbstractOAuth2Authentication --> OAuth2UserInfo
AbstractOAuth2Authentication --> OAuth2UserInfoFactory
OAuth2UserInfoFactory --> User
FacebookOAuth2UserInfo --|> OAuth2UserInfo
GoogleOAuth2UserInfo --|> OAuth2UserInfo
SessionRepositoryJpaAdapter --|> BaseJpaAdapter
SessionRepositoryJpaAdapter --> Session
SessionRepositoryJpaAdapter --> SessionId
SessionRepositoryJpaAdapter --> SessionRepository
SessionRepositoryJpaAdapter --> UserId
UserRegistrationJpaRepositoryAdapter --|> BaseJpaAdapter
UserRegistrationJpaRepositoryAdapter --> UserRegistration
UserRegistrationJpaRepositoryAdapter --> UserRegistrationRepository
UserRegistrationJpaRepositoryAdapter --> UserRegistrationStatus
UserRegistrationJpaRepositoryAdapter --> UserId
SessionJpaRepository --> Session
SessionJpaRepository --> SessionId
SessionJpaRepository --> UserId
UserRepositoryJpaAdapter --|> BaseJpaAdapter
UserRepositoryJpaAdapter --> User
UserRepositoryJpaAdapter --> UserId
UserRepositoryJpaAdapter --> UserRepository
UserRegistrationJpaRepository --> UserRegistration
UserRegistrationJpaRepository --> UserId
UserJpaRepository --> User
UserJpaRepository --> UserId
MD5EncryptionService ..|> EncryptionService
MD5EncryptionService --> EncryptionService
DomainRegistry --> PasswordService
DomainRegistry --> UserRegistrationRepository
DomainRegistry --> UserRegistrationMustBeUnique
DomainRegistry --> TokenProvider
DomainRegistry --> UserRepository
DomainRegistry --> UserEmailMustBeUnique
UserRegistrationRepository --> UserId
EmailAuthenticationService --> EncryptionService
EmailAuthenticationService --> PasswordsMustMatch
EmailAuthenticationService --> User
EmailAuthenticationService --> UserRepository
UserRegistration --> DomainRegistry
UserRegistration --> PasswordChanged
UserRegistration --> PasswordRecovered
UserRegistration --> PasswordRecoveryCodeCreated
UserRegistration --> UserRegistrationConfirmed
UserRegistration --> UserRegistrationRequested
UserRegistration --> PasswordRecoveryCodeShouldBeExpiredOrNull
UserRegistration --> PasswordRecoveryCodeShouldNotExpired
UserRegistration --> PasswordsMustMatch
UserRegistration --> RecoveryCodeMustMatch
UserRegistration --> UserRegistrationCannotBeConfirmedAfterExpiration
UserRegistration --> UserRegistrationCannotBeConfirmedMoreThanOnce
UserRegistration --> UserRegistrationMustBeConfirmed
UserRegistration --> User
UserRegistration --> UserId
UserRegistration --> UserRepository
UserRegistrationMustBeUnique --> UserRegistrationRepository
UserRegistrationMustBeUnique --> UserRegistrationStatus
PasswordRecoveryCodeShouldBeExpiredOrNull --> UserRegistration
PasswordRecoveryCodeShouldNotExpired --> UserRegistration
UserRegistrationMustBeConfirmed --> UserRegistrationStatus
UserRegistrationCannotBeConfirmedMoreThanOnce --> UserRegistrationStatus
UserRegistrationRequested --> UserRegistrationStatus
UserRegistrationConfirmed --> UserRegistrationStatus
UserRegistrationConfirmed --> UserId
OAuth2Service --> User
OAuth2Service --> UserRepository
OAuth2Service --> UserEmailMustBeUnique
User --> DomainRegistry
User --> UserCreated
User --> UserNameChanged
UserEmailMustBeUnique --> UserRepository
UserCreated --> User
UserCreated --> UserId
SessionAuthenticationService --> SessionCannotBeExpiredWhenRefreshTokenIsMissing
SessionAuthenticationService --> UserRepository
TokenProvider --> User
TokenProvider --> UserId
SessionRepository --> UserId
Session --> DomainRegistry
Session --> SessionCreated
Session --> User
Session --> UserId
JwtTokenProvider ..|> TokenProvider
JwtTokenProvider --> User
JwtTokenProvider --> UserId
JwtTokenProvider --> AppProperties
SessionCannotBeExpiredWhenRefreshTokenIsMissing --> Session
SessionCreated --> SessionId
SessionCreated --> UserId

@enduml