@startuml

package com.example.auth {
  class AuthApplicationTests {
  }
  class AuthApplication {
    +main() : void
  }
}

package com.example.auth.controllers {
  class ProductController <<Controller>> {
    +postProduct() : ResponseEntity
    +getAllProducts() : ResponseEntity
  }
  class AuthenticationController <<Controller>> {
    -authenticationManager : AuthenticationManager
    -repository : UserRepository
    -tokenService : TokenService
    +login() : ResponseEntity
    +register() : ResponseEntity
  }
}

package com.example.auth.domain.product {
  class Product <<Entity>> {
    -id : String
    -name : String
    -price : Integer
  }
}

package com.example.auth.domain.user {
  enum UserRole {
    -role : String
    +getRole() : String
  }
  class User <<Entity>> {
    -id : String
    -login : String
    -password : String
    -role : UserRole
    +getUsername() : String
    +isAccountNonExpired() : boolean
    +isAccountNonLocked() : boolean
    +isCredentialsNonExpired() : boolean
    +isEnabled() : boolean
  }
}

package com.example.auth.infra.security {
  class SecurityFilter {
    +doFilterInternal() : void
  }
  class SecurityConfigurations {
    +securityFilterChain() : SecurityFilterChain
    +authenticationManager() : AuthenticationManager
    +passwordEncoder() : PasswordEncoder
  }
  class TokenService <<Service>> {
    -secret : String
    +generateToken() : String
    +validateToken() : String
  }
}

package com.example.auth.repositories {
  interface ProductRepository {
  }
  interface UserRepository {
  }
}

package com.example.auth.services {
  class AuthorizationService <<Service>> {
    +loadUserByUsername() : UserDetails
  }
}

' --- Relatii ---
SecurityFilter --> UserRepository
TokenService --> User
ProductRepository --> Product
UserRepository --> User
ProductController --> Product
ProductController --> ProductRepository
AuthenticationController --> User
AuthenticationController --> TokenService
AuthenticationController --> UserRepository
AuthorizationService --> UserRepository

@enduml