@startuml

package com.qianmi.autotest.app {
  class AppTestApplication {
    +main() : void
    +getListeners() : List<ITestNGListener>
  }
}

package com.qianmi.autotest.app.common {
  class AppResourceLoader {
    +restartApp() : void
    +appiumDriver() : AppiumDriver
    +appAutotestProperties() : AppAutotestProperties
  }
  class AppAutotestProperties {
    -defaultAppFile : String
    +getActiveAppFile() : String
  }
  class AppPageTest {
    -pageFacade : AppPageFacade
    -appiumDriver : AppiumDriver
    -touchAction : TouchAction
    -inputData : DataProvider
    -outputData : DataProvider
    -resourceContainer : AppResourceLoader
    +logout() : void
    +login() : void
  }
}

package com.qianmi.autotest.app.page {
  class AppPageFacade {
    -LOGGER : Logger
    +logout() : void
  }
  class AppBasePage {
    +swipeLeft() : void
    +swipeUp() : void
    +swipeToDown() : void
  }
}

package com.qianmi.autotest.app.testng {
  class AppTestRetryAnalyzer {
    +restart() : void
  }
}

package com.qianmi.autotest.appium.common {
  class AppiumAutotestProperties {
    -driver : Properties
    -device : Properties
    -defaultDevice : String
    -appiumServerMngEnable : boolean
    -appiumServerMngUrl : String
    -appiumServerUrl : String
    -deviceConfig : Properties
    -driverConfig : Properties
    +getActiveDeviceName() : String
    +getDeviceConfig() : Properties
    +getDriverConfig() : Properties
  }
  class AppiumWait {
    -appiumDriver : AppiumDriver
    -autotestProperties : AppiumAutotestProperties
    +wait() : WebElement
    +wait() : WebElement
  }
  class AppiumResourceLoader {
    -restTemplate : RestTemplate
    -appiumAutotestProperties : AppiumAutotestProperties
    -appiumServerMngUrl : String
    +appiumAutotestProperties() : AppiumAutotestProperties
    +stopAppiumServer() : void
    +restTemplate() : RestTemplate
    +touchAction() : TouchAction
    +appiumWait() : AppiumWait
    +printStartLog() : void
    +getAppiumDriver() : AppiumDriver
    +setCapabilities() : void
  }
}

package com.qianmi.autotest.appium.data {
  class DataProvider {
    -originData : Properties
    +getProperty() : String
    +getProperty() : String
  }
  class DataInitialization {
    -input : Properties
    -output : Properties
    -device : Properties
    -appiumAutotestProperties : AppiumAutotestProperties
    +inputData() : DataProvider
    +outputData() : DataProvider
  }
}

package com.qianmi.autotest.appium.page {
  class AppiumBasePage {
    -driver : AppiumDriver
    -touchAction : TouchAction
    -autotestProperties : AppiumAutotestProperties
    -appiumWait : AppiumWait
    +sleep() : void
    +getPageInitTime() : int
    +afterConstruct() : void
    +wait() : WebElement
    +wait() : WebElement
    +wait() : WebElement
    +apply() : WebElement
    +isExist() : boolean
  }
}

package com.qianmi.autotest.appium.testng {
  class ScreenShotListener {
    +onTestStart() : void
    +onTestSuccess() : void
    +onTestFailure() : void
    +onTestSkipped() : void
    +onTestFailedButWithinSuccessPercentage() : void
    +onStart() : void
    +onFinish() : void
  }
}

package com.qianmi.autotest.base {
  class AbstractTestApplication {
    -driver : WebDriver
    +runTest() : void
    +getTestNGArgs() : String[]
    +getListeners() : List<ITestNGListener>
    +closeDriver() : void
  }
}

package com.qianmi.autotest.base.common {
  interface Logoutable {
  }
  interface Module {
  }
  class BasePageTest {
    +beforeLog() : void
    +afterLog() : void
  }
  class AutotestUtils {
    +getPrice() : BigDecimal
    +getPriceStr() : String
    +comparePrice() : boolean
    +getWebElementDesc() : String
    +sleep() : void
    +getScene() : Scene
    +getSceneName() : String
    +getModule() : Module
  }
  interface Scene {
  }
  class AutotestException {
    -code : int
    -message : String
  }
  class AutotestProperties {
    -elementLoadTimeInMills : int
    -refreshIntervalInMills : int
    -pageLoadTimeInMills : int
    -swipeTimeInMills : int
    -scanPackage : String
  }
  class BeanFactory {
    -applicationContext : ApplicationContext
    +setApplicationContext() : void
  }
}

package com.qianmi.autotest.base.page {
  interface PageObject {
  }
  interface AppLoginPage {
  }
}

package com.qianmi.autotest.base.testng {
  class QmDingNotifier {
    -testOutputDirectory : String
    -deviceName : String
    -operatorId : String
    -ip : String
    +onStart() : void
    +onFinish() : void
  }
  class TestRetryListener {
    +transform() : void
  }
  class DefaultReporter {
    -TIME_ZONE : String
    -SDF_DATE : SimpleDateFormat
    -SDF_TIME : SimpleDateFormat
    -INTEGER_FORMAT : NumberFormat
    -DECIMAL_FORMAT : NumberFormat
    -writer : PrintWriter
    -suiteResults : List<SuiteResult>
    -buffer : StringBuilder
    -outFileName : String
    -suiteName : String
    +generateReport() : void
  }
  class BaseTestRetryAnalyzer {
    -retryCount : int
    -maxRetryCount : int
    +retry() : boolean
    +restart() : void
  }
}

package com.qianmi.autotest.demo.app.jd.page {
  class SearchResultPage {
    -productItem : WebElement
    -backButton : WebElement
    +viewFirstProduct() : ProductPage
    +backToHomePage() : HomePage
  }
  class SearchPage {
    -searchField : WebElement
    -searchButton : WebElement
    +search() : SearchResultPage
  }
  class HomePage {
    -searchButton : WebElement
    +gotoSearchPage() : SearchPage
  }
  class NavigatePage {
    -homeButton : WebElement
    -categoryButton : WebElement
    -discoveryButton : WebElement
    -shoppingCartButton : WebElement
    -mineButton : WebElement
    +gotoCartPage() : ShoppingCartPage
    +gotoHomePage() : HomePage
  }
  class ProductPage {
    -addCartButton : WebElement
    -backButton : WebElement
    -okButton : WebElement
    +addCart() : ProductPage
    +backToSearchResultPage() : SearchResultPage
  }
  class ShoppingCartPage {
  }
}

package com.qianmi.autotest.demo.app.jd.test {
  class JdAppTest {
    +testSearchWhenLogout() : void
    +testAddCart() : void
  }
}

package com.qianmi.autotest.demo.html5.jd.page {
  class SearchResultPage {
    -firstProductItem : WebElement
    -backButton : WebElement
    +viewFirstProduct() : ProductPage
  }
  class SearchPage {
    -searchField : WebElement
    +search() : SearchResultPage
  }
  class HomePage {
    -searchButton : WebElement
    +gotoSearchPage() : SearchPage
  }
  class NavigatePage {
    -homePageButton : WebElement
    -categoryPageButton : WebElement
    -discoveryPageButton : WebElement
    -cartPageButton : WebElement
    -minePageButton : WebElement
    +gotoCartPage() : ShoppingCartPage
    +gotoHomePage() : HomePage
  }
  class ProductPage {
    -addCartButton : WebElement
    -cartButton : WebElement
    -backButton : WebElement
    -okButton : WebElement
    +addCart() : ProductPage
    +gotoCartPage() : ShoppingCartPage
    +backToSearchResultPage() : SearchResultPage
  }
  class ShoppingCartPage {
  }
}

package com.qianmi.autotest.demo.html5.jd.test {
  class JdHtml5Test {
    +testSearchWhenLogout() : void
    +testAddCart() : void
  }
}

package com.qianmi.autotest.demo.web.baidu.page {
  class SearchResultPage {
    -firstItem : WebElement
    +checkResult() : boolean
  }
  class HomePage {
    -inputField : WebElement
    -submitButton : WebElement
    +search() : SearchResultPage
  }
}

package com.qianmi.autotest.demo.web.baidu.test {
  class BaiduWebTest {
    +searchBaidu() : void
    +searchYouzhan() : void
  }
}

package com.qianmi.autotest.html5 {
  class Html5TestApplication {
    +main() : void
    +getListeners() : List<ITestNGListener>
  }
}

package com.qianmi.autotest.html5.common {
  class Html5ResourceLoader {
    -inputData : DataProvider
    +gotoPage() : void
    +appiumDriver() : AppiumDriver
  }
  class Html5PageTest {
    -pageFacade : Html5PageFacade
    -appiumDriver : AppiumDriver
    -inputData : DataProvider
    -outputData : DataProvider
    +login() : void
  }
}

package com.qianmi.autotest.html5.page {
  class Html5PageFacade {
    +logout() : void
  }
  class Html5Page {
    -ANDROID_BOUNDS_PATTERN : Pattern
    -IOS_BOUNDS_PATTERN : Pattern
    -NUMBER_PATTERN : Pattern
    -NATIVE_APP : String
    -WEB_VIEW_TOP : int
    -WEB_VIEW_BOTTOM : int
    -touchAction : TouchAction
    +pressEnterKey() : void
    +getPageInitTime() : int
    +isExist() : boolean
    +clickByNativePosition() : void
    +clickByNativeWebViewPosition() : void
    +clickNativeElement() : void
    +webSwipeUp() : void
    +webSwipeDown() : void
  }
}

package com.qianmi.autotest.html5.testng {
  class Html5TestRetryAnalyzer {
    +restart() : void
  }
}

package com.qianmi.autotest.web {
  class WebTestApplication {
    +main() : void
    +getListeners() : List<ITestNGListener>
  }
}

package com.qianmi.autotest.web.common {
  class WebPageTest {
    -pageFacade : WebPageFacade
    -webDriver : WebDriver
    -inputData : DataProvider
    -outputData : DataProvider
    +login() : void
  }
  class WebAutotestProperties {
    -driver : Properties
    -browser : Properties
    -defaultBrowserName : String
    -browserConfig : Properties
    -driverConfig : Properties
    +getActiveBrowserName() : String
    +getBrowserConfig() : Properties
    +getDriverConfig() : Properties
  }
  class WebResourceLoader {
    -webAutotestProperties : WebAutotestProperties
    +webAutotestProperties() : WebAutotestProperties
    +printStartLog() : void
    +gotoPage() : void
    +webDriver() : WebDriver
    +getWebDriver() : WebDriver
    +setCapabilities() : void
  }
}

package com.qianmi.autotest.web.data {
  class DataProvider {
    -originData : Properties
    +getProperty() : String
    +getProperty() : String
  }
  class DataInitialization {
    -input : Properties
    -output : Properties
    -browser : Properties
    -webAutotestProperties : WebAutotestProperties
    +inputData() : DataProvider
    +outputData() : DataProvider
  }
}

package com.qianmi.autotest.web.page {
  class WebPageFacade {
    +logout() : void
  }
  class WebBasePage {
    -driver : RemoteWebDriver
    -webProperties : WebAutotestProperties
    +sleep() : void
    +afterConstruct() : void
    +wait() : WebElement
    +wait() : WebElement
    +wait() : WebElement
    +apply() : WebElement
    +isExist() : boolean
    +isExist() : boolean
  }
}

package com.qianmi.autotest.web.testng {
  class WebTestRetryAnalyzer {
    +restart() : void
  }
  class ScreenShotListener {
    +onTestStart() : void
    +onTestSuccess() : void
    +onTestFailure() : void
    +onTestSkipped() : void
    +onTestFailedButWithinSuccessPercentage() : void
    +onStart() : void
    +onFinish() : void
  }
}

' --- Relatii ---
SearchResultPage --|> WebBasePage
SearchResultPage --> WebBasePage
HomePage --|> WebBasePage
HomePage --> WebBasePage
BaiduWebTest --|> WebPageTest
BaiduWebTest --> HomePage
BaiduWebTest --> SearchResultPage
BaiduWebTest --> WebPageTest
SearchResultPage --|> AppBasePage
SearchResultPage --> AppBasePage
SearchPage --|> AppBasePage
SearchPage --> AppBasePage
HomePage --|> NavigatePage
NavigatePage --|> AppBasePage
NavigatePage --> AppBasePage
ProductPage --|> AppBasePage
ProductPage --> AppBasePage
ShoppingCartPage --|> NavigatePage
JdAppTest --|> AppPageTest
JdAppTest --> AppPageTest
JdAppTest --> HomePage
SearchResultPage --|> Html5Page
SearchResultPage --> Html5Page
SearchPage --|> Html5Page
SearchPage --> Html5Page
HomePage --|> NavigatePage
NavigatePage --|> Html5Page
NavigatePage --> Html5Page
ProductPage --|> Html5Page
ProductPage --> Html5Page
ShoppingCartPage --|> NavigatePage
JdHtml5Test --|> Html5PageTest
JdHtml5Test --> HomePage
JdHtml5Test --> Html5PageTest
AppTestApplication --|> AbstractTestApplication
AppTestApplication --> AppTestRetryAnalyzer
AppTestApplication --> ScreenShotListener
AppTestApplication --> AbstractTestApplication
AppTestApplication --> DefaultReporter
AppTestApplication --> QmDingNotifier
AppTestApplication --> TestRetryListener
AppPageFacade --|> AppBasePage
AppPageFacade --> BeanFactory
AppPageFacade --> Logoutable
AppBasePage --|> AppiumBasePage
AppBasePage --> AppiumBasePage
AppTestRetryAnalyzer --|> BaseTestRetryAnalyzer
AppTestRetryAnalyzer --> AppPageTest
AppTestRetryAnalyzer --> AppResourceLoader
AppTestRetryAnalyzer --> BeanFactory
AppTestRetryAnalyzer --> BaseTestRetryAnalyzer
AppResourceLoader --|> AppiumResourceLoader
AppResourceLoader --> AppiumAutotestProperties
AppResourceLoader --> AppiumResourceLoader
AppResourceLoader --> AutotestException
AppPageTest --|> BasePageTest
AppPageTest --> AppTestApplication
AppPageTest --> AppPageFacade
AppPageTest --> DataProvider
AppPageTest --> AutotestUtils
AppPageTest --> BasePageTest
AppPageTest --> BeanFactory
AppPageTest --> AppLoginPage
WebTestApplication --|> AbstractTestApplication
WebTestApplication --> AbstractTestApplication
WebTestApplication --> DefaultReporter
WebTestApplication --> QmDingNotifier
WebTestApplication --> TestRetryListener
WebTestApplication --> ScreenShotListener
WebTestApplication --> WebTestRetryAnalyzer
WebPageFacade --|> WebBasePage
WebPageFacade --> BeanFactory
WebPageFacade --> Logoutable
WebBasePage ..|> PageObject
WebBasePage --> BeanFactory
WebBasePage --> PageObject
WebBasePage --> WebAutotestProperties
WebTestRetryAnalyzer --|> BaseTestRetryAnalyzer
WebTestRetryAnalyzer --> AutotestUtils
WebTestRetryAnalyzer --> BeanFactory
WebTestRetryAnalyzer --> BaseTestRetryAnalyzer
WebTestRetryAnalyzer --> WebResourceLoader
WebTestRetryAnalyzer --> DataProvider
ScreenShotListener --> BeanFactory
WebPageTest --|> BasePageTest
WebPageTest --> AutotestUtils
WebPageTest --> BasePageTest
WebPageTest --> BeanFactory
WebPageTest --> AppLoginPage
WebPageTest --> WebTestApplication
WebPageTest --> DataProvider
WebPageTest --> WebPageFacade
WebAutotestProperties --|> AutotestProperties
WebAutotestProperties --> AutotestProperties
WebResourceLoader --> AutotestException
WebResourceLoader --> BeanFactory
DataInitialization --> WebAutotestProperties
AppiumBasePage ..|> PageObject
AppiumBasePage --> AppiumAutotestProperties
AppiumBasePage --> AppiumWait
AppiumBasePage --> BeanFactory
AppiumBasePage --> PageObject
ScreenShotListener --> BeanFactory
AppiumAutotestProperties --|> AutotestProperties
AppiumAutotestProperties --> AutotestProperties
AppiumWait --> AutotestUtils
AppiumResourceLoader --> AutotestException
AppiumResourceLoader --> BeanFactory
DataInitialization --> AppiumAutotestProperties
Html5TestApplication --|> AbstractTestApplication
Html5TestApplication --> ScreenShotListener
Html5TestApplication --> AbstractTestApplication
Html5TestApplication --> DefaultReporter
Html5TestApplication --> QmDingNotifier
Html5TestApplication --> TestRetryListener
Html5TestApplication --> Html5TestRetryAnalyzer
Html5PageFacade --|> Html5Page
Html5PageFacade --> BeanFactory
Html5PageFacade --> Logoutable
Html5Page --|> AppiumBasePage
Html5Page --> AppiumBasePage
Html5Page --> AutotestUtils
Html5TestRetryAnalyzer --|> BaseTestRetryAnalyzer
Html5TestRetryAnalyzer --> DataProvider
Html5TestRetryAnalyzer --> AutotestUtils
Html5TestRetryAnalyzer --> BeanFactory
Html5TestRetryAnalyzer --> BaseTestRetryAnalyzer
Html5TestRetryAnalyzer --> Html5ResourceLoader
Html5ResourceLoader --|> AppiumResourceLoader
Html5ResourceLoader --> AppiumAutotestProperties
Html5ResourceLoader --> AppiumResourceLoader
Html5ResourceLoader --> DataProvider
Html5ResourceLoader --> AutotestException
Html5PageTest --|> BasePageTest
Html5PageTest --> DataProvider
Html5PageTest --> AutotestUtils
Html5PageTest --> BasePageTest
Html5PageTest --> BeanFactory
Html5PageTest --> AppLoginPage
Html5PageTest --> Html5TestApplication
Html5PageTest --> Html5PageFacade
AbstractTestApplication --> AutotestUtils
QmDingNotifier --> BeanFactory

@enduml