@startuml

package com.canthny.drools_kie_demo.test {
  class DroolKieTestDemo {
    +main() : void
  }
}

package com.tanghao.bigdata.drools {
  class DroolsStarter {
    +main() : void
  }
}

package com.tanghao.bigdata.drools.controller {
  class TestPayRule <<Controller>> {
    +testPayRule() : RuleResponse
  }
}

package com.tanghao.bigdata.drools.domain {
  class PhoneNoBlackObject {
    -serialVersionUID : long
    -phoneNo : String
    +getPhoneNo() : String
    +setPhoneNo() : void
  }
  class MobilePaymentInfo {
    -serialVersionUID : long
    -payOrderNo : String
    -accountNo : String
    -bankCardNo : String
    -mobile : String
    -amount : Integer
    -time : Date
    +getPayOrderNo() : String
    +setPayOrderNo() : void
    +getAccountNo() : String
    +setAccountNo() : void
    +getBankCardNo() : String
    +setBankCardNo() : void
    +getMobile() : String
    +setMobile() : void
  }
  class DefeatMapReduceObject {
    -serialVersionUID : long
    -id : String
    -value : Integer
    +getId() : String
    +setId() : void
    +getValue() : Integer
    +setValue() : void
  }
}

package com.tanghao.bigdata.drools.domain.request {
  class MobilePaymentRequest {
    -serialVersionUID : long
    -accountNo : String
    -bankCardNo : String
    -mobile : String
    -amount : Integer
    -outTradeDate : String
    +getAccountNo() : String
    +setAccountNo() : void
    +getBankCardNo() : String
    +setBankCardNo() : void
    +getMobile() : String
    +setMobile() : void
    +getAmount() : Integer
    +setAmount() : void
  }
  class BaseRequest {
    -serialVersionUID : long
    -response : RuleResponse
    +setResponse() : void
    +getResponse() : RuleResponse
  }
}

package com.tanghao.bigdata.drools.domain.response {
  class RuleResponse {
    -serialVersionUID : long
    -code : String
    -level : String
    -msg : String
    +getCode() : String
    +setCode() : void
    +getLevel() : String
    +setLevel() : void
    +getMsg() : String
    +setMsg() : void
    +checkIsNull() : Boolean
  }
}

package com.tanghao.bigdata.drools.enums {
  enum EnumRuleResponseLevel {
    -code : String
    -desc : String
    +getCode() : String
    +setCode() : void
    +getDesc() : String
    +setDesc() : void
    +getDescByCode() : String
  }
}

package com.tanghao.bigdata.drools.kafka.config {
  class MobilePaymentInfoConfig {
  }
}

package com.tanghao.bigdata.drools.kafka.listener {
  class MobilePaymentInfoListener {
    +onMessage() : void
  }
}

package com.tanghao.bigdata.drools.mongodb.config {
  class SpringMongoConfig {
  }
}

package com.tanghao.bigdata.drools.mongodb.service {
  interface MobilePaymentInfoService {
    +saveMobilePaymentInfo() : void
  }
}

package com.tanghao.bigdata.drools.mongodb.service.impl {
  class MobilePaymentInfoServiceImpl {
    +saveMobilePaymentInfo() : void
  }
}

package com.tanghao.bigdata.drools.redis {
  class RedisConfig {
    -charset : Charset
    +redisTemplate() : RedisTemplate
    +deserialize() : Integer
    +serialize() : byte[]
  }
}

package com.tanghao.bigdata.drools.service {
  class MobilePaymentRuleService {
    -redisTemplate : RedisTemplate
    -mongoTemplate : MongoTemplate
    -mobilePaymentRuleService : MobilePaymentRuleService
    +init() : void
    +getAvgAmountPerMonthByAccountNo() : Integer
    +getCountPerHourByAccountNo() : Integer
  }
  class PhoneNoBlacklistService {
    -redisTemplate : RedisTemplate
    -mongoTemplate : MongoTemplate
    -phoneNoBlacklistService : PhoneNoBlacklistService
    +init() : void
    +isBlack() : boolean
  }
}

package com.tanghao.bigdata.drools.test {
  class TestRuleService {
    +testPhoneNoBlacklistService() : void
    +testMobilePaymentRuleService() : void
  }
  class TestMongodb {
    +testSave() : void
    +insertPhoneNoBlackList() : void
    +testMapReduce() : void
    +findPhonenNoBlackList() : void
  }
  class TestKafkaProduct {
    +testSendMobilePaymentInfo() : void
  }
  class TestMongodbJob {
  }
  class TestDrools {
    +testCase1() : void
    +testCase2() : void
    +testCase3() : void
    +testCase4() : void
  }
}

package com.tanghao.bigdata.drools.util {
  class DateUtil {
    -log : Logger
    -TIME_PATTERN : String
    -TIME_PATTERN_ALL : String
    -TIME_YYYY_MM_DD_HH_MM_SS : String
    -TIME_YYYY_MM_DD : String
    -TIME_FORM_ALL : String
    -TIME_YYYY_MMDD_HHMMSS_SSS : String
    -TIME_FORM : String
    -DATE_FORM : String
    -dayNames : String[]
    +converTimestampToString() : String
    +converTimestampToString() : String
    +converStringToTimestamp() : Timestamp
    +getDateTimePattern() : String
    +getDate() : String
    +convertStringToDate() : Date
    +getTimeNow() : String
    +getCalendarToday() : Calendar
  }
}

package com.tanghao.flink.demo {
  class GetPayInfoJob {
    +main() : void
    +extractTimestamp() : long
  }
  class TestAction {
    +main() : void
  }
}

package com.tanghao.flink.demo.api.datastream {
  class FlatMapApiTest {
    +main() : void
    +flatMap() : void
  }
  class MapApiTest {
    +main() : void
  }
  class FilterApiTest {
    +main() : void
    +filter() : boolean
    +filter() : boolean
  }
  class KeyByApiTest {
    +main() : void
    +getKey() : String
    +reduce() : Message
  }
  class UnionAndSplitStreamTest {
    -outputTag1001 : OutputTag<Message>
    -outputTag2001 : OutputTag<Message>
    +main() : void
    +processElement() : void
  }
}

package com.tanghao.flink.demo.api.others {
  class BroadcastTableTest {
    +main() : void
    +map() : TransTypeInfo
    +map() : Message
    +processElement() : void
    +processBroadcastElement() : void
  }
}

package com.tanghao.flink.demo.api.window {
  class TumblingWindowAggregateFunctionTest {
    -userConsumerAmountPerMin : OutputTag<UserConsumerAmountPerMinute>
    +main() : void
    +map() : Message
    +getKey() : String
    +open() : void
    +createAccumulator() : TradeCountMinuteResult
    +add() : TradeCountMinuteResult
    +getResult() : TradeCountMinuteResult
    +merge() : TradeCountMinuteResult
  }
  class SlidingWindowTest {
    +main() : void
    +map() : Message
    +filter() : boolean
    +getKey() : String
    +getResult() : List<UserConsumerAmountPerMinute>
    +compare() : int
  }
  class TumblingWindowProcessWindowFunctionTest {
    -userConsumerAmountPerMin : OutputTag<UserConsumerAmountPerMinute>
    +main() : void
    +map() : Message
    +getKey() : String
    +process() : void
  }
  class GlobalWindowTest {
  }
  class SessionWindowTest {
  }
  class TumblingWindowUseEventTimeTest {
    +main() : void
    +map() : Message
    +extractAscendingTimestamp() : long
    +getKey() : String
  }
}

package com.tanghao.flink.demo.common {
  class UserConsumerAmountPerMinute {
    -userId : Long
    -amount : Long
    -currentMinute : String
    +getUserId() : Long
    +setUserId() : void
    +getAmount() : Long
    +setAmount() : void
    +getCurrentMinute() : String
    +setCurrentMinute() : void
  }
  class Message {
    -id : String
    -transCode : String
    -amount : Long
    -tradeTime : Date
    -userId : Long
    -class : inner
    +standalone() : and
    +getId() : String
    +setId() : void
    +getTransCode() : String
    +setTransCode() : void
    +getAmount() : Long
    +setAmount() : void
    +getTradeTime() : Date
  }
  class TransTypeInfo {
    -transCode : String
    -transName : String
    -isOpen : boolean
    +getTransCode() : String
    +setTransCode() : void
    +getTransName() : String
    +setTransName() : void
    +isOpen() : boolean
    +setOpen() : void
  }
  class ConstantKafka {
    -KAFKA_SINGLE : String
    -TRADE_MESSAGE_TOPIC : String
    -TRANS_TYPE_TOPIC : String
  }
  class MessageDeserializationSchema {
    +deserialize() : Message
    +isEndOfStream() : boolean
    +getProducedType() : TypeInformation<Message>
  }
  class TradeCountMinuteResult {
    -transCode : String
    -sumAmount : Long
    -currentMinute : String
    +getTransCode() : String
    +setTransCode() : void
    +getSumAmount() : Long
    +setSumAmount() : void
    +getCurrentMinute() : String
    +setCurrentMinute() : void
  }
}

package com.tanghao.flink.demo.source {
  class KafkaSource {
    +main() : void
  }
  class InnerSource {
    +main() : void
  }
}

package com.tanghao.flink.demo.test {
  class MsgProducerTest {
    -transCodes : String[]
    +main() : void
  }
  class BroadcastMsgProducerTest {
    +main() : void
  }
}

' --- Relatii ---
MsgProducerTest --> ConstantKafka
MsgProducerTest --> Message
BroadcastMsgProducerTest --> ConstantKafka
BroadcastMsgProducerTest --> Message
BroadcastMsgProducerTest --> TransTypeInfo
KafkaSource --> ConstantKafka
KafkaSource --> Message
KeyByApiTest --> Message
UnionAndSplitStreamTest --> Message
BroadcastTableTest --> ConstantKafka
BroadcastTableTest --> Message
BroadcastTableTest --> TransTypeInfo
TumblingWindowAggregateFunctionTest --> ConstantKafka
TumblingWindowAggregateFunctionTest --> Message
TumblingWindowAggregateFunctionTest --> TradeCountMinuteResult
TumblingWindowAggregateFunctionTest --> UserConsumerAmountPerMinute
SlidingWindowTest --> ConstantKafka
SlidingWindowTest --> Message
SlidingWindowTest --> UserConsumerAmountPerMinute
TumblingWindowProcessWindowFunctionTest --> ConstantKafka
TumblingWindowProcessWindowFunctionTest --> Message
TumblingWindowProcessWindowFunctionTest --> TradeCountMinuteResult
TumblingWindowProcessWindowFunctionTest --> UserConsumerAmountPerMinute
TumblingWindowUseEventTimeTest --> ConstantKafka
TumblingWindowUseEventTimeTest --> Message
TestRuleService --> DroolsStarter
TestRuleService --> MobilePaymentRuleService
TestRuleService --> PhoneNoBlacklistService
TestMongodb --> DroolsStarter
TestMongodb --> DefeatMapReduceObject
TestMongodb --> MobilePaymentInfo
TestMongodb --> PhoneNoBlackObject
TestMongodb --> MobilePaymentInfoService
TestMongodb --> PhoneNoBlacklistService
TestMongodb --> DateUtil
TestKafkaProduct --> DroolsStarter
TestKafkaProduct --> MobilePaymentInfo
TestDrools --> DroolsStarter
TestDrools --> MobilePaymentRequest
TestDrools --> DateUtil
MobilePaymentInfoService --> MobilePaymentInfo
MobilePaymentInfoServiceImpl ..|> MobilePaymentInfoService
MobilePaymentInfoServiceImpl --> MobilePaymentInfo
MobilePaymentInfoServiceImpl --> MobilePaymentInfoService
TestPayRule --> MobilePaymentRequest
TestPayRule --> RuleResponse
TestPayRule --> DateUtil
MobilePaymentInfoListener --> MobilePaymentInfo
MobilePaymentInfoListener --> MobilePaymentInfoService
MobilePaymentInfoConfig --> MobilePaymentInfoListener
MobilePaymentRuleService --> DefeatMapReduceObject
PhoneNoBlacklistService --> PhoneNoBlackObject
RuleResponse --> EnumRuleResponseLevel
MobilePaymentRequest --|> BaseRequest
BaseRequest --> RuleResponse

@enduml