@startuml

package com.blueskykong.chapter11.config.client {
  class Chapter11ConfigClientApplication {
    +main() : void
  }
}

package com.blueskykong.chapter11.config.client.rest {
  class TestController <<Controller>> {
    -version : String
    +from() : String
  }
}

package com.blueskykong.chapter11.config.client2 {
  class Chapter11ConfigClient2Application {
    +main() : void
  }
}

package com.blueskykong.chapter11.config.client2.rest {
  class TestController <<Controller>> {
    -version : String
    +from() : String
  }
}

package com.blueskykong.chapter11.config.server {
  class Chapter11ConfigServerApplication {
    +main() : void
  }
}

package com.blueskykong.chapter11.config.server.bus {
  class CustomRemoteApplicationEvent {
  }
  class BusConfiguration {
    +onUserRemoteApplicationEvent() : void
    +onRefreshRemoteApplicationEvent() : void
    +onEnvironmentChangeRemoteApplicationEvent() : void
  }
}

package com.blueskykong.chapter11.config.server.rest {
  class BusEventController <<Controller>> {
    -eventPublisher : ApplicationEventPublisher
    -applicationContext : ApplicationContext
    +publishUserEvent() : boolean
    +setApplicationEventPublisher() : void
    +setApplicationContext() : void
  }
}

package com.blueskykong.chapter3.springboot.demo {
  class Chapter3SpringbootDemoApplication <<Controller>> {
    -smsConfiguration : SMSConfiguration
    +main() : void
    +test() : String
  }
}

package com.blueskykong.chapter3.springboot.demo.config {
  class SMSConfiguration {
    -retryLimitationMinutes : int
    -validityMinute : int
    -types : List<String>
  }
}

package com.blueskykong.client.servicea {
  class Chapter13ClientServiceaApplication {
    +main() : void
  }
}

package com.blueskykong.client.servicea.feign {
  interface ServiceBClient {
    +fromB() : String
  }
}

package com.blueskykong.client.servicea.rest {
  class ServiceAController <<Controller>> {
    +fromServiceA() : String
    +fromServiceB() : String
  }
}

package com.blueskykong.client.serviceb {
  class Chapter13ClientServicebApplication {
    +main() : void
  }
}

package com.blueskykong.client.serviceb.feign {
  interface ServiceAClient {
    +fromA() : String
  }
}

package com.blueskykong.client.serviceb.rest {
  class ServiceBController <<Controller>> {
    +fromServiceB() : String
    +fromServiceA() : String
  }
}

package com.blueskykong.config.client {
  class ConfigClientApplication {
    +main() : void
  }
}

package com.blueskykong.config.client.rest {
  class TestController <<Controller>> {
    -version : String
    +getVersion() : String
  }
}

package com.blueskykong.config.server {
  class ConfigServerApplication {
    +main() : void
  }
}

package com.blueskykong.eureka.server {
  class EurekaServerApplication {
    +main() : void
  }
}

package com.blueskykong.gateway.server {
  class ThrottleGatewayFilterFactory {
    -log : Log
    -tokenBucket : TokenBucket
    +filter() : Mono<Void>
  }
  class GatewayServerApplication <<Controller>> {
    -name : String
    +main() : void
    +proxyFoos() : Mono<ResponseEntity<Object>>
    +foos() : List<Foo>
    +foo() : Foo
    +getName() : String
    +setName() : void
  }
}

package com.blueskykong.gateway.server.config {
  class RateLimitByIpGatewayFilter {
    +filter() : Mono<Void>
    +getOrder() : int
  }
  class RemoteAddrKeyResolver {
    -BEAN_NAME : String
    +resolve() : Mono<String>
  }
  class RouteConfiguration {
    +customRouteLocator() : RouteLocator
    +routeLocator() : RouteLocator
    +testFunRouterFunction() : RouterFunction<ServerResponse>
    +userKeyResolver() : KeyResolver
    +remoteAddrKeyResolver() : RemoteAddrKeyResolver
    +retryRouteLocator() : RouteLocator
    +getMessage() : String
    +setMessage() : void
  }
}

package com.blueskykong.gateway.server.entity {
  class User {
    -key : String
  }
}

package com.blueskykong.gateway.user {
  class GatewayUserApplication <<Controller>> {
    +main() : void
    +test() : String
    +testException() : String
    +testException() : String
  }
}

package com.blueskykong.zipkin.server {
  class ZipkinServerApplication {
    +main() : void
  }
}

package com.remcarpediem.ribbon.anotherserver {
  class OrderController <<Controller>> {
    +getOrderDetail() : Order
  }
  class AnotherServerApplication {
    +main() : void
  }
}

package com.remcarpediem.ribbon.client {
  class ClientApplication {
    +main() : void
  }
  class TestController <<Controller>> {
    +test() : String
  }
  class RibbonConfiguration {
    +ribbonPing() : IPing
    +ribbonRule() : IRule
  }
}

package com.remcarpediem.ribbon.common {
  class Order {
    -id : Long
    -content : String
    +getId() : Long
    +setId() : void
    +getContent() : String
    +setContent() : void
  }
}

package com.remcarpediem.ribbon.server {
  class ServerApplication {
    +main() : void
  }
  class OrderController <<Controller>> {
    +getOrderDetail() : Order
  }
}

package com.remcarpediem.rocket.rocketdemo {
  class Order {
    -id : Long
    -content : String
    +getId() : Long
    +setId() : void
    +getContent() : String
    +setContent() : void
  }
  class OrderHandler {
    +handle() : void
  }
  class TestController <<Controller>> {
    -source : Source
    +sendOrder() : void
  }
  class RocketDemoApplication {
    +main() : void
  }
}

package com.xuan.chapter.common.chapter5.dto {
  class Instance {
    -serviceId : String
    -host : String
    -port : int
    +getServiceId() : String
    +setServiceId() : void
    +getHost() : String
    +setHost() : void
    +getPort() : int
    +setPort() : void
  }
}

package com.xuan.chapter12.authorization.server {
  class Chapter12AuthorizationServerApplication {
    +main() : void
  }
}

package com.xuan.chapter12.authorization.server.config {
  class SecurityConfig {
    +configure() : void
    +authenticationManagerBean() : AuthenticationManager
    +configure() : void
    +passwordEncoder() : PasswordEncoder
  }
  class AuthorizationServerConfig {
    -RESOURCE_ID : String
    +configure() : void
    +configure() : void
    +accessTokenConverter() : JwtAccessTokenConverter
    +configure() : void
  }
}

package com.xuan.chapter12.oauth2.client {
  class Chapter12Oauth2ClientApplication {
    +main() : void
  }
}

package com.xuan.chapter12.oauth2.client.config {
  class SecurityConfig {
    +configure() : void
  }
}

package com.xuan.chapter12.oauth2.client.controller {
  class MainController <<Controller>> {
    +main() : String
    +index() : String
    +principal() : Principal
  }
}

package com.xuan.chapter12.resource.server {
  class Chapter12ResourceServerApplication {
    +main() : void
  }
}

package com.xuan.chapter12.resource.server.config {
  class ResourceServerConfig {
    +configure() : void
    +tokenServices() : ResourceServerTokenServices
    +handleError() : void
    +accessTokenConverter() : JwtAccessTokenConverter
    +configure() : void
  }
}

package com.xuan.chapter12.resource.server.controller {
  class ResourceController <<Controller>> {
    -logger : Logger
    -DEFAULT_NAME : String
    -DEFAULT_SERVICE_ID : String
    -DEFAULT_HOST : String
    -DEFAULT_PORT : int
    -request : HttpServletRequest
    +getUserByUserId() : User
    +getInstanceByServiceId() : Instance
    +userInfo() : Principal
  }
}

package com.xuan.chapter12.resource.server.dto {
  class User {
    -id : String
    -name : String
    +getId() : String
    +setId() : void
    +getName() : String
    +setName() : void
  }
}

package com.xuan.chapter3.logfilter.starter.annotation {
  interface EnableLogFilter {
  }
}

package com.xuan.chapter3.logfilter.starter.config {
  class EnableLogFilterImportSelector {
    -logger : Logger
    -beanClassLoader : ClassLoader
    -annotationClass : Class
    -environment : Environment
    +selectImports() : String[]
    +hasDefaultFactory() : boolean
    +isEnabled() : boolean
    +getSimpleName() : String
    +getAnnotationClass() : Class<EnableLogFilter>
    +getEnvironment() : Environment
    +setEnvironment() : void
    +setBeanClassLoader() : void
  }
  class LogFilterRegistrationBean {
  }
  class LogFilterAutoConfiguration {
    +logFilterRegistrationBean() : LogFilterRegistrationBean
  }
}

package com.xuan.chapter3.logfilter.starter.filter {
  class LogFilter {
    -logger : Logger
    +init() : void
    +doFilter() : void
    +destroy() : void
  }
}

package com.xuan.chapter4.eureka.client.service {
  class Chapter4EurekaClientServiceApplication {
    +main() : void
  }
}

package com.xuan.chapter4.eureka.client.service.controller {
  class SayHelloController <<Controller>> {
    +sayHello() : String
  }
}

package com.xuan.chapter5.feign.client {
  class Chapter5FeignClientApplication {
    +main() : void
  }
}

package com.xuan.chapter5.feign.client.client.api {
  interface FeignServiceClient {
    +getInstanceByServiceId() : Instance
    +deleteInstanceByServiceId() : String
    +createInstance() : String
    +updateInstanceByServiceId() : String
  }
}

package com.xuan.chapter5.feign.client.controller {
  class FeignClientController <<Controller>> {
    +getInstanceByServiceId() : Instance
    +deleteInstanceByServiceId() : String
    +createInstance() : String
    +updateInstanceByServiceId() : String
  }
}

package com.xuan.chapter5.feign.service {
  class Chapter5FeignServiceApplication {
    +main() : void
  }
}

package com.xuan.chapter5.feign.service.controller {
  class FeignServiceController <<Controller>> {
    -logger : Logger
    -DEFAULT_SERVICE_ID : String
    -DEFAULT_HOST : String
    -DEFAULT_PORT : int
    +getInstanceByServiceId() : Instance
    +deleteInstanceByServiceId() : String
    +createInstance() : String
    +updateInstanceByServiceId() : String
  }
}

package com.xuan.chapter6.hystrix {
  class Chapter6HystrixApplication {
    +main() : void
  }
}

package com.xuan.chapter6.hystrix.client.api {
  interface InstanceClient {
    +getInstanceByServiceId() : Instance
  }
}

package com.xuan.chapter6.hystrix.client.fallback {
  class InstanceClientFallBack {
    -logger : Logger
    +getInstanceByServiceId() : Instance
  }
}

package com.xuan.chapter6.hystrix.controller {
  class InstanceController <<Controller>> {
    -logger : Logger
    -restTemplate : RestTemplate
    +getInstanceByServiceIdWithRestTemplate() : Instance
    +getInstanceByServiceIdWithFeign() : Instance
    +getInstanceByServiceIdAsync() : Instance
    +getInstanceByServiceIdObservable() : Instance
    +getInstanceByServiceIdCustom() : Instance
    +getInstancesBatch1() : Instance
    +getInstancesBatch2() : Instance
  }
}

package com.xuan.chapter6.hystrix.service {
  class CustomHystrixObservableCommand {
    -logger : Logger
    -restTemplate : RestTemplate
    -serviceId : String
    +construct() : Observable<Instance>
    +resumeWithFallback() : Observable<Instance>
  }
  class InstanceService <<Service>> {
    -DEFAULT_SERVICE_ID : String
    -DEFAULT_HOST : String
    -DEFAULT_PORT : int
    -logger : Logger
    +getInstanceByServiceIdWithRestTemplate() : Instance
    +getInstanceByServiceIdObservable() : Observable<Instance>
    +getInstanceByServiceIdCustom() : Instance
    +getInstanceByServiceIdCustomObservable() : Instance
    +call() : void
    +instanceInfoGetFailObservable() : Observable<Instance>
    +getInstanceByServiceIdAsync() : Future<Instance>
    +invoke() : Instance
  }
  class CustomHystrixCommand {
    -logger : Logger
    -restTemplate : RestTemplate
    -serviceId : String
    +run() : Instance
    +getFallback() : Instance
  }
  class CustomCollapseCommand {
    -serviceId : String
    -serviceIds : List<String>
    -DEFAULT_SERVICE_ID : String
    -DEFAULT_HOST : String
    -DEFAULT_PORT : int
    -logger : Logger
    +getRequestArgument() : String
    +createCommand() : HystrixCommand<List<Instance>>
    +mapResponseToRequests() : void
    +run() : List<Instance>
  }
}

package com.xuan.eureka.client {
  class Chapter4EurekaClientApplication {
    +main() : void
  }
}

package com.xuan.eureka.client.controller {
  class AskController <<Controller>> {
    -name : String
    +ask() : String
    +restTemplate() : RestTemplate
  }
  class ServiceInstanceRestController <<Controller>> {
    -discoveryClient : DiscoveryClient
    +serviceInstancesByApplicationName() : List<ServiceInstance>
  }
}

package com.xuan.eureka.server {
  class Chapter4EurekaServerApplication {
    +main() : void
  }
}

package com.zt.stream {
  interface MsgSource {
  }
  class StreamApplication {
    +main() : void
  }
  class OrderHandler {
    +handle() : void
  }
  class TestPojoWithAnnotatedArguments {
    +receiveFoodOrder() : void
    +receiveComputeOrder() : void
  }
}

package com.zt.stream.beans {
  class Order {
  }
  class Vote {
  }
  class ComputeOrder {
  }
  class FoodOrder {
  }
  class VoteResult {
  }
}

package com.zt.stream.service {
  class OrderService <<Service>> {
    +handle() : void
  }
  class VotingService <<Service>> {
    +record() : VoteResult
  }
}

package org.springframework.cloud.stream.binder.rocket {
  class RocketMQBinderEnvironmentPostProcessor {
    -SPRING_ROCKETMQ : String
    -SPRING_ROCKETMQ_NAMESRV_ADDR : String
    -SPRING_ROCKETMQ_NAMESERVER_ADDRESS : String
    -SPRING_ROCKETMQ_PRODUCER : String
    -SPRING_ROCKETMQ_CONSUMER : String
    -SPRING_ROCKETMQ_PRODUCER_KEY_SERIALIZER : String
    -SPRING_ROCKETMQ_PRODUCER_VALUE_SERIALIZER : String
    -SPRING_ROCKETMQ_CONSUMER_KEY_DESERIALIZER : String
    -SPRING_ROCKETMQ_CONSUMER_VALUE_DESERIALIZER : String
    -ROCKETMQ_BINDER_DEFAULT_PROPERTIES : String
    +postProcessEnvironment() : void
  }
  class RawRecordHeaderErrorMessageStrategy {
    +buildErrorMessage() : ErrorMessage
  }
  class RocketMessageChannelBinder {
    -logger : Logger
    -X_ORIGINAL_TOPIC : String
    -X_EXCEPTION_MESSAGE : String
    -X_EXCEPTION_STACKTRACE : String
    -configurationProperties : RocketMQBinderConfigurationProperties
    -resourceManager : RocketMQResourceManager
    -extendedBindingProperties : RocketMQExtendedBindingProperties
    -destination : ProducerDestination
    -endpoint : AmqpOutboundEndpoint
    -destination : ProducerDestination
    +setExtendedBindingProperties() : void
    +getExtendedConsumerProperties() : RocketConsumerProperties
    +getExtendedProducerProperties() : RocketProducerProperties
    +createProducerMessageHandler() : MessageHandler
    +createConsumerEndpoint() : MessageProducer
    +getErrorMessageStrategy() : ErrorMessageStrategy
    +getErrorMessageHandler() : MessageHandler
    +handleMessage() : void
  }
}

package org.springframework.cloud.stream.binder.rocket.config {
  class RocketServiceAutoConfiguration {
  }
  class RocketMessageChannelBinderConfiguration {
    -configurationProperties : RocketMQBinderConfigurationProperties
    -extendedBindingProperties : RocketMQExtendedBindingProperties
  }
}

package org.springframework.cloud.stream.binder.rocket.properties {
  class RocketConsumerProperties {
    -autoRebalanceEnabled : boolean
    -autoCommitOffset : boolean
    -autoCommitOnError : Boolean
    -startOffset : String
    -enableDlq : boolean
    -dlqName : String
    -recoveryInterval : int
    -headerMode : HeaderMode
    -referencePoint : long
    +isAutoCommitOffset() : boolean
    +setAutoCommitOffset() : void
    +getStartOffset() : String
    +setStartOffset() : void
    +isEnableDlq() : boolean
    +setEnableDlq() : void
    +getAutoCommitOnError() : Boolean
    +setAutoCommitOnError() : void
  }
  class RocketMQExtendedBindingProperties {
    +setBindings() : void
    +getExtendedConsumerProperties() : RocketConsumerProperties
    +getExtendedProducerProperties() : RocketProducerProperties
  }
  class RocketCommonProperties {
    -groupName : String
    -tags : String
    +getTags() : String
    +setTags() : void
    +getGroupName() : String
    +setGroupName() : void
  }
  class RocketProducerProperties {
    -bufferSize : int
    -sync : boolean
    -batchTimeout : int
    +getBufferSize() : int
    +setBufferSize() : void
    +isSync() : boolean
    +setSync() : void
    +getBatchTimeout() : int
    +setBatchTimeout() : void
    +setConfiguration() : void
  }
  class RocketMQBinderConfigurationProperties {
    -nameSrvAddr : String[]
    -defaultNameSrvPort : String
    -brokers : String[]
    -defaultBrokerPort : String
    -headers : String[]
    -offsetUpdateTimeWindow : int
    -offsetUpdateCount : int
    -offsetUpdateShutdownTimeout : int
    -maxWait : int
    -autoCreateTopics : boolean
    +getNameSrvConnectionString() : String
    +getRocketMQConnectionString() : String
    +getHeaders() : String[]
    +getOffsetUpdateTimeWindow() : int
    +getOffsetUpdateCount() : int
    +getOffsetUpdateShutdownTimeout() : int
    +getNameSrvAddr() : String[]
    +setNameSrvAddr() : void
  }
  class RocketMQBindingProperties {
    -consumer : RocketConsumerProperties
    -producer : RocketProducerProperties
    +getConsumer() : RocketConsumerProperties
    +setConsumer() : void
    +getProducer() : RocketProducerProperties
    +setProducer() : void
  }
}

package org.springframework.cloud.stream.binder.rocket.provisioning {
  class RocketExchangeQueueProvisioner {
    -logger : Log
    -configurationProperties : RocketMQBinderConfigurationProperties
    -adminUtilsOperation : AdminUtilsOperation
    -metadataRetryOperations : RetryOperations
    -name : String
    -zkUtils : ZkUtils
    -name : String
    -group : String
    -topicName : String
    -partitionCount : int
    +setMetadataRetryOperations() : void
    +afterPropertiesSet() : void
    +provisionProducerDestination() : ProducerDestination
    +provisionConsumerDestination() : ConsumerDestination
    +getName() : String
    +getNameForPartition() : String
    +getName() : String
  }
}

package org.springframework.cloud.stream.binder.rocket.support {
  class RocketDelivery {
    -messageExt : Message
    +getMessage() : Message
  }
  class RocketTemplate {
    -resourceManager : RocketMQResourceManager
    -producerProperties : ExtendedProducerProperties<RocketProducerProperties>
    -producer : DefaultMQProducer
    -mapper : ObjectMapper
    -topics : List<TopicConfig>
    -logger : Logger
    +start() : void
    +stop() : void
    +getResourceManager() : RocketMQResourceManager
    +getProducerProperties() : ExtendedProducerProperties<RocketProducerProperties>
    +getProducer() : DefaultMQProducer
    +getMapper() : ObjectMapper
    +getTopics() : List<TopicConfig>
    +getLogger() : Logger
  }
  class RocketInboundChannelAdapter {
    -logger : Logger
    -listenerContainer : SimpleRocketMessageListenerContainer
    +onInit() : void
    +doStart() : void
    +doStop() : void
    +onMessage() : void
    +onMessage() : void
  }
  class RocketMessagePropertiesConverter {
  }
  class RocketMQResourceManager {
    -configurationProperties : RocketMQBinderConfigurationProperties
    -mapper : ObjectMapper
    -logger : Logger
    +getConfigurationProperties() : RocketMQBinderConfigurationProperties
  }
  class RocketMQMessage {
    -message : Message
    +getMessage() : Message
  }
  class RocketBlockingQueueConsumer {
    -logger : Logger
    -mapper : ObjectMapper
    -resourceManager : RocketMQResourceManager
    -topic : String
    -consumerGroup : String
    -extendedConsumerProperties : ExtendedConsumerProperties<RocketConsumerProperties>
    -consumer : DefaultMQPushConsumer
    -messageBuilderFactory : MessageBuilderFactory
    -queue : BlockingQueue<RocketDelivery>
    -objectMapper : ObjectMapper
    +setMapper() : void
    +setResourceManager() : void
    +setTopic() : void
    +setConsumerGroup() : void
    +setExtendedConsumerProperties() : void
    +setConsumer() : void
    +setMessageBuilderFactory() : void
    +setShutdown() : void
  }
  interface Listener {
  }
  class SimpleRocketMessageListenerContainer {
    -asyncMessageProcessingConsumer : AsyncMessageProcessingConsumer
    -executor : Executor
    -DEFAULT_RECEIVE_TIMEOUT : long
    -consumers : List<RocketBlockingQueueConsumer>
    -consumersMonitor : Object
    -receiveTimeout : long
    -txSize : int
    -resourceManager : RocketMQResourceManager
    -topic : String
    -consumerGroup : String
    +start() : void
    +doStart() : void
    +doInitialize() : void
    +doShutdown() : void
    +run() : void
    +setAsyncMessageProcessingConsumer() : void
    +setExecutor() : void
    +setConsumers() : void
  }
  class AmqpOutboundEndpoint {
    -resourceManager : RocketMQResourceManager
    -producerProperties : ExtendedProducerProperties<RocketProducerProperties>
    -mapper : ObjectMapper
    -topics : List<TopicConfig>
    -logger : Logger
    -charset : String
    -converter : MappingJackson2MessageConverter
    -rocketTemplate : RocketTemplate
    -objectMapper : ObjectMapper
    +isRunning() : boolean
    +start() : void
    +stop() : void
    +handleRequestMessage() : Object
    +currentContext() : Context
    +convert() : RocketMQMessage
  }
}

package org.springframework.cloud.stream.binder.rocket.utils {
  class RocketMQTopicUtils {
    +validateTopicName() : void
  }
  class CommonUtils {
    -ROCKETMQ_RAW_DATA : String
    +toArray() : byte[]
    +toArray() : byte[]
  }
}

' --- Relatii ---
ServerApplication --> Order
OrderController --> Order
OrderController --> Order
AnotherServerApplication --> Order
TestController --> Order
FeignClientController --> Instance
FeignClientController --> FeignServiceClient
FeignServiceClient --> Instance
FeignServiceController --> Instance
BusEventController --> CustomRemoteApplicationEvent
InstanceController --> Instance
InstanceController --> CustomCollapseCommand
InstanceController --> InstanceService
CustomHystrixObservableCommand --> Instance
InstanceService --> Instance
InstanceService --> InstanceClient
CustomHystrixCommand --> Instance
CustomCollapseCommand --> Instance
InstanceClientFallBack ..|> InstanceClient
InstanceClientFallBack --> Instance
InstanceClientFallBack --> InstanceClient
InstanceClient --> Instance
InstanceClient --> InstanceClientFallBack
Chapter3SpringbootDemoApplication --> SMSConfiguration
Chapter3SpringbootDemoApplication --> EnableLogFilter
EnableLogFilterImportSelector --> EnableLogFilter
LogFilterRegistrationBean --> LogFilter
LogFilterAutoConfiguration --> LogFilter
EnableLogFilter --> EnableLogFilterImportSelector
ServiceAController --> ServiceBClient
ServiceBController --> ServiceAClient
SecurityConfig --> User
ResourceController --> Instance
ResourceController --> User
RouteConfiguration --> ThrottleGatewayFilterFactory
OrderHandler --> Order
OrderHandler --> OrderService
TestPojoWithAnnotatedArguments --> ComputeOrder
TestPojoWithAnnotatedArguments --> FoodOrder
OrderService --> Order
VotingService --> Vote
VotingService --> VoteResult
RawRecordHeaderErrorMessageStrategy --> CommonUtils
RocketMessageChannelBinder --> RocketMQBinderConfigurationProperties
RocketMessageChannelBinder --> RocketMQExtendedBindingProperties
RocketMessageChannelBinder --> AmqpOutboundEndpoint
RocketMessageChannelBinder --> RocketInboundChannelAdapter
RocketMessageChannelBinder --> RocketMQResourceManager
RocketMessageChannelBinder --> RocketConsumerProperties
RocketMessageChannelBinder --> RocketProducerProperties
RocketMessageChannelBinder --> RocketExchangeQueueProvisioner
RocketMessageChannelBinder --> RocketTemplate
RocketMessageChannelBinder --> SimpleRocketMessageListenerContainer
RocketMessageChannelBinder --> CommonUtils
RocketMessageChannelBinderConfiguration --> RocketMessageChannelBinder
RocketMessageChannelBinderConfiguration --> RocketMQBinderConfigurationProperties
RocketMessageChannelBinderConfiguration --> RocketMQExtendedBindingProperties
RocketMessageChannelBinderConfiguration --> RocketExchangeQueueProvisioner
RocketTemplate --> RocketProducerProperties
RocketInboundChannelAdapter --> RocketConsumerProperties
RocketMQResourceManager --> RocketMQBinderConfigurationProperties
RocketBlockingQueueConsumer --> RocketConsumerProperties
SimpleRocketMessageListenerContainer --> RocketConsumerProperties
AmqpOutboundEndpoint --> RocketProducerProperties
RocketExchangeQueueProvisioner --> RocketMQTopicUtils
RocketConsumerProperties --|> RocketCommonProperties
RocketProducerProperties --|> RocketCommonProperties

@enduml