@startuml

  class influxdb2Test {
    -org : String
    +save() : void
    +saveLog() : void
    +addLog() : void
    +addLog2() : void
    +find() : void
    +findPojo() : void
    +findPojoAsync() : void
  }
  class httptest {
  }

package io.qyi.e5 {
  class E5ApplicationTest {
    +main() : void
  }
  class AutoGenerator_ {
    +scanner() : String
    +main() : void
    +initMap() : void
    +outputFile() : String
    +isCreate() : boolean
  }
  class E5Application {
    +main() : void
  }
}

package io.qyi.e5.bean.core {
  class WebExceptionAspect {
    -logger : Logger
    +handleThrowing() : void
    +writeContent() : void
  }
}

package io.qyi.e5.bean.result {
  enum ResultEnum {
    -code : Integer
    -msg : String
    +getCode() : Integer
    +setCode() : void
    +getMsg() : String
    +setMsg() : void
  }
  class Result {
    -code : Integer
    -msg : String
    -data : T
  }
}

package io.qyi.e5.config {
  class Start {
    -isdebug : boolean
    -threadPool : ExecutorService
    +init() : void
    +run() : void
    +rejectedExecution() : void
  }
  class ResultVO {
    -code : int
    -msg : String
    -data : T
  }
  class MybatisPlusConfig {
    +paginationInterceptor() : PaginationInterceptor
  }
  enum ResultCode {
    -code : int
    -msg : String
  }
  enum APiCode {
    -code : int
    -msg : String
  }
}

package io.qyi.e5.config.exception {
  class APIException {
    -code : int
    -msg : String
  }
  class ExceptionControllerAdvice {
    +APIExceptionHandler() : ResultVO<String>
    +MethodArgumentNotValidExceptionHandler() : ResultVO<String>
    +BindException() : ResultVO<String>
    +HttpMessageNotReadableException() : ResultVO<String>
    +supports() : boolean
    +beforeBodyWrite() : Object
  }
}

package io.qyi.e5.config.influx2 {
  class InfluxdbConfig {
    -influxDBUrl : String
    -token : String
    +influxDBClient() : InfluxDBClient
  }
}

package io.qyi.e5.config.redis {
  class RedisConfig {
    +cacheManager() : CacheManager
  }
}

package io.qyi.e5.config.security {
  class SecurityAuthenticationHandler {
    -gson : Gson
    +onAuthenticationSuccess() : void
    +onAuthenticationFailure() : void
    +onLogoutSuccess() : void
  }
  class UsernamePasswordAuthenticationProvider {
    -logger : Logger
    -tokenExpire : int
    +authenticate() : Authentication
    +supports() : boolean
  }
  class SecurityConfig {
    +configure() : void
    +configure() : void
    +configure() : void
  }
  class UsernamePasswordAuthenticationToken {
    -logger : Logger
    -code : String
    -state : String
    -name : String
    -avatar_url : String
    -Token : String
    -Authority : String
    -github_id : int
    +getToken() : String
    +setToken() : void
    +getCredentials() : String
    +getPrincipal() : String
    +getCode() : String
    +setCode() : void
    +getState() : String
    +setState() : void
  }
  class UrlInvocationSecurityMetadataSourceService <<Service>> {
    -securityAdmin : String[]
    -securityUser : String[]
    -securitAnonymous : String[]
    -map : List<CollectionBean>
    +loadResourceDefine() : void
    +getAttributes() : Collection<ConfigAttribute>
    +getAllConfigAttributes() : Collection<ConfigAttribute>
    +supports() : boolean
  }
  class UrlAccessDecisionManager <<Service>> {
    +decide() : void
    +supports() : boolean
    +supports() : boolean
  }
  class GithubAuth2AuthenticationConfig {
    +configure() : void
  }
}

package io.qyi.e5.config.security.bean {
  class CollectionBean {
    -url : String
    -configAttributes : Collection<ConfigAttribute>
  }
}

package io.qyi.e5.config.security.bean.dto {
  class PermissionDto {
    -roleId : int
    -roleName : String
  }
  class PermissionListDto {
  }
  class RoleMenuDto {
    -id : int
    -name : String
    -url : String
    -pid : int
    -data : List<Object>
  }
}

package io.qyi.e5.config.security.filter {
  class GithubLoginAuthenticationFilter {
    +attemptAuthentication() : Authentication
  }
  class LinkTokenAuthenticationFilter {
    +doFilterInternal() : void
  }
}

package io.qyi.e5.controller.admin {
  class AdminController <<Controller>> {
    -tokenExpire : int
    +send() : void
    +execute() : void
    +emptyRedis() : String
    +setAnnouncement() : String
    +getDebugAdminToken() : String
  }
}

package io.qyi.e5.controller.auth2 {
  class Auth <<Controller>> {
    +getGithubUrl() : Result
    +Receive() : Result
  }
}

package io.qyi.e5.controller.web {
  class WebController <<Controller>> {
    +index() : Result
    +delete() : Result
    +getAnnouncement() : String
  }
}

package io.qyi.e5.github.controller {
  class GithubController <<Controller>> {
  }
}

package io.qyi.e5.github.entity {
  class Github {
    -serialVersionUID : long
    -id : Integer
    -userId : Integer
    -accessToken : String
    -login : String
    -name : String
    -avatarUrl : String
    -githubId : Integer
  }
  class UserInfo {
  }
}

package io.qyi.e5.github.mapper {
  interface GithubMapper {
  }
}

package io.qyi.e5.github.service {
  interface IGithubService {
  }
}

package io.qyi.e5.github.service.impl {
  class GithubServiceImpl <<Service>> {
    -client_id : String
    -client_secret : String
    +getAccessToken() : String
    +getUserEmail() : String
    +getUserInfo() : UserInfo
    +selectOne() : Github
    +insert() : void
    +deleteInfo() : int
  }
}

package io.qyi.e5.outlook.bean {
  class OutlookMq {
    -githubId : int
    -outlookId : int
  }
  class OutlookListVo {
    -id : int
    -clientId : String
    -clientSecret : String
    -cronTimeRandomStart : Integer
    -cronTimeRandomEnd : Integer
    -name : String
    -describes : String
    -nextTime : Integer
    -status : int
  }
  class OutlookVo {
    -id : int
    -clientId : String
    -clientSecret : String
    -cronTimeRandomStart : Integer
    -cronTimeRandomEnd : Integer
    -step : Integer
    -status : Integer
  }
}

package io.qyi.e5.outlook.bean.bo {
  class insertOneBO {
    -name : String
    -describe : String
  }
  class SaveRandomBo {
    -outlookId : int
    -cronTime : int
    -crondomTime : String
  }
  class UpdateBo {
    -client_id : String
    -client_secret : String
    -outlook_id : int
  }
}

package io.qyi.e5.outlook.controller {
  class OutlookController <<Controller>> {
    +insertOne() : ResultVO
    +save() : ResultVO
    +saveRandomTime() : Result
    +getOutlookInfo() : Result
    +getOutlookList() : Result
    +setPause() : Result
    +setStart() : Result
    +delete() : Result
  }
  class AuthController <<Controller>> {
    +Receive() : Result
    +getAuthorizeUrl() : Result
  }
}

package io.qyi.e5.outlook.entity {
  class Outlook {
    -serialVersionUID : long
    -id : Integer
    -githubId : Integer
    -idToken : String
    -clientId : String
    -clientSecret : String
    -refreshToken : String
    -accessToken : String
    -cronTime : Integer
    -cronTimeRandomStart : Integer
  }
}

package io.qyi.e5.outlook.mapper {
  interface OutlookMapper {
  }
}

package io.qyi.e5.outlook.service {
  interface IOutlookService {
  }
}

package io.qyi.e5.outlook.service.impl {
  class OutlookServiceImpl <<Service>> {
    -logger : Logger
    -errorMsg : String[]
    +getTokenAndSave() : boolean
    +insertOne() : Outlook
    +save() : boolean
    +saveRandomTime() : boolean
    +findAll() : List<Outlook>
    +findRunOutlookList() : List<Outlook>
    +deleteInfo() : int
    +getMailList() : int
  }
}

package io.qyi.e5.outlook_log.bena {
  class LogVo {
    -callTime : int
    -result : int
    -msg : String
    -originalMsg : String
  }
}

package io.qyi.e5.outlook_log.controller {
  class OutlookLogController <<Controller>> {
    -outlookLogMapper : OutlookLogMapper
    -outlookLogService : IOutlookLogService
    -org : String
    -bucket : String
    -pageSize : int
    +findLog() : Result
  }
}

package io.qyi.e5.outlook_log.entity {
  class OutlookLog {
    -serialVersionUID : long
    -githubId : String
    -outlookId : String
    -callTime : long
    -result : Number
    -msg : String
    -originalMsg : String
  }
}

package io.qyi.e5.outlook_log.service {
  interface IOutlookLogService {
  }
}

package io.qyi.e5.outlook_log.service.impl {
  class OutlookLogServiceImpl <<Service>> {
    -influxDBClient : InfluxDBClient
    -org : String
    -bucket : String
    +addLog() : void
    +findAllList() : List<OutlookLog>
  }
}

package io.qyi.e5.service.task {
  interface ITask {
  }
}

package io.qyi.e5.service.task.impl {
  class TaskImpl <<Service>> {
    +updateOutlookExecDateTime() : void
    +sendTaskOutlookMQALL() : void
    +executeE5() : boolean
    +listen() : void
    +getRandom() : int
  }
}

package io.qyi.e5.user.controller {
  class RoleController <<Controller>> {
  }
  class UserController <<Controller>> {
  }
  class PermissionController <<Controller>> {
  }
}

package io.qyi.e5.user.entity {
  class User {
    -serialVersionUID : long
    -id : Integer
    -name : String
    -passwd : String
    -role : String
    -email : String
    -status : String
  }
  class Permission {
    -serialVersionUID : long
    -id : Integer
    -permission : String
  }
  class Role {
    -serialVersionUID : long
    -id : Integer
    -rolename : String
    -permission : String
  }
}

package io.qyi.e5.user.mapper {
  interface PermissionMapper {
  }
  interface UserMapper {
  }
  interface RoleMapper {
  }
}

package io.qyi.e5.user.service {
  interface IUserService {
  }
  interface IPermissionService {
  }
  interface IRoleService {
  }
}

package io.qyi.e5.user.service.impl {
  class RoleServiceImpl <<Service>> {
  }
  class PermissionServiceImpl <<Service>> {
  }
  class UserServiceImpl <<Service>> {
  }
}

package io.qyi.e5.util {
  class ResultUtil {
    +success() : Result
    +success() : Result
    +error() : Result
    +error() : Result
    +success() : Result
    +error() : Result
  }
  class VerifyCode {
    -CAPTCHA_WIDTH : int
    -CAPTCHA_HEIGHT : int
    -NUMBER_CNT : int
    -IMAGE_TYPE : String
    -r : Random
    -fontNames : String[]
    -fontNames : String[]
    -codes : String
    -bgColor : Color
    -text : String
    +getInstance() : VerifyCode
    +getCode() : String
    +getCode() : CaptchaCode
    +copyImage2Byte() : byte[]
    +copyByte2File() : boolean
    +getImage() : BufferedImage
    +getText() : String
    +output() : void
  }
  class NumConvertUtil {
    +bytesToHexString() : String
    +hexStringToByte() : byte[]
    +HexStringToInt() : int
    +IntToHexString() : String
    +strToBcd() : byte[]
    +strToDouble() : String
  }
  class StringUtil {
    +readTxt() : String
  }
  class DateUtil {
    +timeStamp2Date() : String
    +date2TimeStamp() : String
  }
  class SpringUtil {
    -applicationContext : ApplicationContext
    +setApplicationContext() : void
    +getApplicationContext() : ApplicationContext
    +getBean() : Object
  }
  class EncryptUtil {
    -MD5 : String
    -SHA1 : String
    -HmacMD5 : String
    -HmacSHA1 : String
    -DES : String
    -AES : String
    -charset : String
    -keysizeDES : int
    -keysizeAES : int
    -me : EncryptUtil
    +getInstance() : EncryptUtil
    +parseByte2HexStr() : String
    +parseHexStr2Byte() : byte[]
    +MD5() : String
    +MD5() : String
    +SHA1() : String
    +SHA1Hex() : String
    +SHA1() : String
  }
}

package io.qyi.e5.util.netRequest {
  class OkHttpClientUtil {
    -connTimeOut : int
    -readTimeOut : int
    -writeTimeOut : int
    -client : OkHttpClient
    +doGet() : String
    +doPost() : String
    +doPost() : String
    +doPut() : String
  }
  class SSLSocketClientUtil {
    +getSocketFactory() : SSLSocketFactory
    +getX509TrustManager() : X509TrustManager
    +checkClientTrusted() : void
    +checkServerTrusted() : void
    +getAcceptedIssuers() : X509Certificate[]
    +getHostnameVerifier() : HostnameVerifier
    +verify() : boolean
  }
  class OkHttpRequestUtils {
    -client : OkHttpClient
    +doGet() : String
    +doGet() : String
    +doGet() : String
    +doPost() : String
    +doPostFrom() : String
    +doPost() : String
    +doPost() : String
    +doPost() : String
  }
}

package io.qyi.e5.util.redis {
  class RedisUtil {
    +keys() : Set<String>
    +expire() : boolean
    +deleteALL() : void
    +getExpire() : long
    +hasKey() : boolean
    +del() : void
  }
}

' --- Relatii ---
influxdb2Test --> OutlookLog
ResultUtil --> Result
ResultUtil --> ResultEnum
Start --> OutlookMq
Start --> Outlook
Start --> IOutlookService
Start --> ITask
Start --> RedisUtil
SecurityAuthenticationHandler --> ResultUtil
SecurityAuthenticationHandler --> RedisUtil
UsernamePasswordAuthenticationProvider --> Github
UsernamePasswordAuthenticationProvider --> UserInfo
UsernamePasswordAuthenticationProvider --> IGithubService
UsernamePasswordAuthenticationProvider --> EncryptUtil
UsernamePasswordAuthenticationProvider --> RedisUtil
SecurityConfig --> LinkTokenAuthenticationFilter
UrlInvocationSecurityMetadataSourceService --> CollectionBean
UrlInvocationSecurityMetadataSourceService --> PermissionListDto
UrlInvocationSecurityMetadataSourceService --> SecurityConfig
GithubAuth2AuthenticationConfig --> GithubLoginAuthenticationFilter
GithubLoginAuthenticationFilter --> UsernamePasswordAuthenticationToken
LinkTokenAuthenticationFilter --> UsernamePasswordAuthenticationToken
LinkTokenAuthenticationFilter --> SpringUtil
LinkTokenAuthenticationFilter --> RedisUtil
APIException --> APiCode
ExceptionControllerAdvice --> ResultCode
ExceptionControllerAdvice --> ResultVO
WebExceptionAspect --> ResultUtil
PermissionMapper --> Permission
UserMapper --> User
RoleMapper --> Role
IUserService --> User
IPermissionService --> Permission
IRoleService --> Role
RoleServiceImpl --> Role
RoleServiceImpl --> RoleMapper
RoleServiceImpl --> IRoleService
PermissionServiceImpl --> Permission
PermissionServiceImpl --> PermissionMapper
PermissionServiceImpl --> IPermissionService
UserServiceImpl --> User
UserServiceImpl --> UserMapper
UserServiceImpl --> IUserService
OutlookLogController --> Result
OutlookLogController --> UsernamePasswordAuthenticationToken
OutlookLogController --> IOutlookService
OutlookLogController --> LogVo
OutlookLogController --> OutlookLog
OutlookLogController --> IOutlookLogService
OutlookLogController --> ResultUtil
IOutlookLogService --> OutlookLog
OutlookLogServiceImpl ..|> IOutlookLogService
OutlookLogServiceImpl --> OutlookLog
OutlookLogServiceImpl --> IOutlookLogService
Auth --> Result
Auth --> GithubMapper
Auth --> IGithubService
Auth --> UserMapper
Auth --> EncryptUtil
Auth --> ResultUtil
Auth --> RedisUtil
WebController --> Result
WebController --> UsernamePasswordAuthenticationToken
WebController --> IGithubService
WebController --> IOutlookService
WebController --> IOutlookLogService
WebController --> ResultUtil
WebController --> StringUtil
WebController --> RedisUtil
AdminController --> IOutlookService
AdminController --> ITask
AdminController --> EncryptUtil
AdminController --> RedisUtil
GithubMapper --> Github
IGithubService --> Github
IGithubService --> UserInfo
GithubServiceImpl --> Github
GithubServiceImpl --> UserInfo
GithubServiceImpl --> GithubMapper
GithubServiceImpl --> IGithubService
GithubServiceImpl --> StringUtil
ITask --> OutlookMq
ITask --> Outlook
TaskImpl ..|> ITask
TaskImpl --> OutlookMq
TaskImpl --> Outlook
TaskImpl --> IOutlookService
TaskImpl --> IOutlookLogService
TaskImpl --> ITask
TaskImpl --> RedisUtil
OutlookMapper --> Outlook
OutlookController --> Result
OutlookController --> ResultEnum
OutlookController --> ResultVO
OutlookController --> UsernamePasswordAuthenticationToken
OutlookController --> OutlookListVo
OutlookController --> OutlookVo
OutlookController --> SaveRandomBo
OutlookController --> UpdateBo
OutlookController --> insertOneBO
OutlookController --> Outlook
OutlookController --> IOutlookService
OutlookController --> ResultUtil
AuthController --> Result
AuthController --> APIException
AuthController --> UsernamePasswordAuthenticationToken
AuthController --> Outlook
AuthController --> IOutlookService
AuthController --> ITask
AuthController --> EncryptUtil
AuthController --> ResultUtil
AuthController --> RedisUtil
IOutlookService --> Outlook
OutlookServiceImpl --> APiCode
OutlookServiceImpl --> APIException
OutlookServiceImpl --> Outlook
OutlookServiceImpl --> OutlookMapper
OutlookServiceImpl --> IOutlookService
OutlookServiceImpl --> RedisUtil

@enduml