@startuml

package org.grpcmock {
  class GrpcMockServerStreamingMethodTest {
    +serverStreamingRpc() : void
  }
  class GrpcMockVerifyTest {
  }
  class GrpcMockUnaryMethodTest {
    +unaryRpc() : void
  }
  class GrpcMockClientStreamingMethodTest {
    +clientStreamingRpc() : StreamObserver<SimpleRequest>
  }
  class GrpcMockHeaderMatcherTest {
    -MARSHALLER : AsciiMarshaller<String>
    -object : SimpleRequest
  }
  class GrpcMockBidiStreamingMethodTest {
    +bidiStreamingRpc() : StreamObserver<SimpleRequest>
  }
  class TestBase {
    -HEADER_1 : String
    -HEADER_2 : String
    -RESPONSE_MESSAGE : String
    -RESPONSE_MESSAGE_2 : String
    -REQUEST_MESSAGE : String
    -REQUEST_MESSAGE_2 : String
    -request : SimpleRequest
    -request2 : SimpleRequest
    -response : SimpleResponse
    -response2 : SimpleResponse
  }
  class InProcessTest {
  }
  class GrpcMockBuilder {
    -delegateHandlerRegistry : DelegateHandlerRegistry
    -requestCaptureInterceptor : RequestCaptureInterceptor
    -serverBuilder : ServerBuilder
    +interceptor() : GrpcMockBuilder
    +executor() : GrpcMockBuilder
    +transportSecurity() : GrpcMockBuilder
    +build() : GrpcMock
  }
  class DelegateHandlerRegistry {
    -delegate : MutableHandlerRegistry
    +getDelegate() : MutableHandlerRegistry
  }
  class InProcessGrpcMockBuilder {
  }
  class GrpcMock {
    -log : Logger
    -INSTANCE : ThreadLocal<GrpcMock>
    -server : Server
    -handlerRegistry : MutableHandlerRegistry
    -requestCaptureInterceptor : RequestCaptureInterceptor
    +getPort() : int
    +getInProcessName() : String
    +start() : GrpcMock
    +stop() : GrpcMock
    +resetAll() : void
    +grpcMock() : GrpcMockBuilder
    +grpcMock() : GrpcMockBuilder
    +inProcessGrpcMock() : InProcessGrpcMockBuilder
  }
}

package org.grpcmock.definitions {
  interface BuilderStep {
  }
}

package org.grpcmock.definitions.matcher {
  class RequestMatcherBuilderImpl {
    -requestsPredicates : List<Predicate<List<ReqT>>>
    +withRequest() : RequestMatcherBuilderImpl<ReqT>
    +withRequests() : RequestMatcherBuilderImpl<ReqT>
    +clearRequestsPredicates() : void
    +build() : RequestMatcher<ReqT>
  }
  interface RequestMatcher {
  }
  interface StatusMatcher {
  }
  interface HeadersMatcher {
  }
  class HeadersMatcherBuilderImpl {
    -headerPredicates : List<Predicate<Metadata>>
    +build() : HeadersMatcher
  }
  class StatusMatcherBuilderImpl {
    -statusPredicates : List<Predicate<Status>>
    +withStatus() : StatusMatcherBuilderImpl
    +build() : StatusMatcher
  }
}

package org.grpcmock.definitions.matcher.steps {
  interface StreamRequestMatcherBuilderStep {
  }
  interface RequestMatcherBuilderStep {
  }
  interface StatusMatcherBuilderStep {
  }
  interface HeadersMatcherBuilderStep {
  }
  interface FirstRequestMatcherBuilderStep {
  }
}

package org.grpcmock.definitions.response {
  interface Response {
  }
  interface Traceable {
  }
  interface Delay {
  }
  class ResponseProxyImpl {
    -counter : AtomicInteger
    +execute() : void
    +execute() : StreamObserver<ReqT>
    +timesCalled() : int
  }
  class StreamResponseBuilderImpl {
    -responseActions : List<ResponseAction<RespT>>
    +and() : ObjectStreamResponseBuilderStep<RespT>
    +and() : ExceptionStreamResponseBuildersStep<RespT>
  }
  class ExceptionResponseActionBuilderImpl {
    -exception : Throwable
    -delay : Delay
    +withDelay() : ExceptionResponseActionBuilder
  }
  class ResponseImpl {
    -counter : AtomicInteger
    -responseActions : List<ResponseAction<RespT>>
    +timesCalled() : int
    +execute() : void
    +execute() : StreamObserver<ReqT>
  }
  interface TerminatingResponseAction {
  }
  interface ResponseAction {
  }
  class ObjectResponseActionBuilderImpl {
    -responseObject : RespT
    -delay : Delay
    +withDelay() : ObjectResponseActionBuilderImpl<RespT>
    +build() : ResponseAction<RespT>
  }
}

package org.grpcmock.definitions.response.steps {
  interface StreamResponseBuilder {
  }
  interface DelayBuilderStep {
  }
  interface ExceptionStreamResponseBuildersStep {
  }
  interface ObjectResponseActionBuilder {
  }
  interface ObjectStreamResponseBuilderStep {
  }
}

package org.grpcmock.definitions.stub {
  class ServerStreamingMethodStubBuilderImpl {
    -requestPatternBuilder : RequestPatternBuilderImpl<ReqT>
  }
  class ClientStreamingMethodStubBuilderImpl {
    -requestPatternBuilder : RequestPatternBuilderImpl<ReqT>
  }
  class MethodStub {
    -responseObserver : StreamObserver<RespT>
    -delegate : StreamObserver<ReqT>
    +serviceName() : String
    +fullMethodName() : String
    +onNext() : void
    +onError() : void
    +onCompleted() : void
  }
  class StubScenario {
    -requestPattern : RequestPattern<ReqT>
    +matches() : boolean
    +call() : void
    +call() : StreamObserver<ReqT>
  }
  class UnaryMethodStubBuilderImpl {
    -requestPatternBuilder : RequestPatternBuilderImpl<ReqT>
  }
  class ServiceStub {
    -serviceName : String
    +serverServiceDefinition() : ServerServiceDefinition
  }
  class BidiStreamingMethodStubBuilderImpl {
    -requestPatternBuilder : RequestPatternBuilderImpl<ReqT>
  }
}

package org.grpcmock.definitions.stub.steps {
  interface NextServerStreamingMethodResponseBuilderStep {
  }
  interface SingleRequestProxyResponseBuilderStep {
  }
  interface StreamRequestProxyResponseBuilderStep {
    +onNext() : void
    +onError() : void
    +onCompleted() : void
  }
  interface ClientStreamingMethodStubBuilderStep {
  }
  interface StreamResponseBuilderStep {
  }
  interface NextUnaryMethodResponseBuilderStep {
  }
  interface NextClientStreamingMethodResponseBuilderStep {
  }
  interface SingleResponseBuilderStep {
  }
  interface NextBidiStreamingMethodStubBuilderStep {
  }
  interface ServerStreamingMethodStubBuilderStep {
  }
  interface NextSingleResponseBuilderStep {
  }
  interface BidiStreamingMethodStubBuilderStep {
  }
  interface UnaryMethodStubBuilderStep {
  }
  interface MethodStubBuilder {
  }
  interface NextStreamResponseBuilderStep {
  }
  interface NextSingleRequestProxyResponseBuilderStep {
  }
  interface NextStreamRequestProxyResponseBuilderStep {
    +onNext() : void
    +onError() : void
    +onCompleted() : void
  }
}

package org.grpcmock.definitions.verification {
  class RequestPatternBuilderImpl {
    -statusMatcherBuilder : StatusMatcherBuilderImpl
    -headersMatcherBuilder : HeadersMatcherBuilderImpl
    -requestMatcherBuilder : RequestMatcherBuilderImpl<ReqT>
    +withStatus() : RequestPatternBuilderStep<ReqT>
    +withRequest() : RequestPatternBuilderImpl<ReqT>
    +withRequests() : RequestPatternBuilderStep<ReqT>
    +clearRequestsPredicates() : void
    +build() : RequestPattern<ReqT>
  }
  class RequestPattern {
    -statusMatcher : StatusMatcher
    -headersMatcher : HeadersMatcher
    -requestsMatcher : RequestMatcher<ReqT>
    +fullMethodName() : String
    +matches() : boolean
    +normalizedCapturedRequest() : CapturedRequest<ReqT>
  }
  class CountMatcher {
    -description : String
    -condition : IntPredicate
    +test() : boolean
    +times() : CountMatcher
    +once() : CountMatcher
    +twice() : CountMatcher
    +never() : CountMatcher
    +atLeast() : CountMatcher
    +atMost() : CountMatcher
  }
}

package org.grpcmock.definitions.verification.steps {
  interface RequestPatternBuilderStep {
  }
}

package org.grpcmock.examples.junit5.service {
  class DownstreamServiceTest {
    -channel : ManagedChannel
    -downstreamService : DownstreamService
  }
  class DownstreamService {
    -blockingStub : DownstreamServiceBlockingStub
    +getDownstreamMessage() : String
  }
}

package org.grpcmock.examples.spring {
  class Application {
    +main() : void
  }
  class Application {
    +main() : void
  }
}

package org.grpcmock.examples.spring.config {
  class NewsServicesProperties {
    -services : List<NewsServiceProperties>
    -host : String
    -apikey : String
    +getServices() : List<NewsServiceProperties>
    +getHost() : String
    +getApikey() : String
  }
  class NewsServicesConfig {
    +downstreamServices() : List<DownstreamNewsService>
  }
  class DownstreamServiceConfig {
    +downstreamServiceBlockingStub() : DownstreamServiceBlockingStub
  }
  class DownstreamServiceProperties {
    -host : String
    +getHost() : String
  }
}

package org.grpcmock.examples.spring.controller {
  class MessageControllerIT {
    +setUp() : void
  }
  class MessageController <<Controller>> {
    -downstreamService : DownstreamService
    +getDownstreamMessage() : String
  }
}

package org.grpcmock.examples.spring.interceptor {
  class ApikeyInterceptor {
    -MARSHALLER : AsciiMarshaller<String>
    -AUTHORIZATION_VALUE_PREFIX : String
    -apikey : String
    +start() : void
  }
}

package org.grpcmock.examples.spring.service {
  class NewsAggregatorServiceTest {
    -grpcPort : int
    -serverChannel : ManagedChannel
    +setup() : void
    +cleanup() : void
  }
  class DownstreamNewsService {
    -futureStub : NewsServiceFutureStub
    -completableFuture : CompletableFuture<T>
    +getNews() : CompletableFuture<GetNewsResponse>
    +onFailure() : void
    +onSuccess() : void
  }
  class NewsAggregatorService <<Service>> {
    -downstreamServices : List<DownstreamNewsService>
    +getAggregatedNews() : void
    +onNext() : void
    +onError() : void
    +onCompleted() : void
  }
  class DownstreamService <<Service>> {
    -blockingStub : DownstreamServiceBlockingStub
    +getDownstreamMessage() : String
  }
}

package org.grpcmock.exception {
  class UnimplementedStatusException {
  }
  class GrpcMockException {
  }
  class GrpcMockValidationException {
  }
  class GrpcMockVerificationError {
  }
}

package org.grpcmock.interceptors {
  class CapturedRequest {
    -headers : Metadata
    -requests : List<ReqT>
    -closeStatus : Status
    +headers() : Metadata
    +requests() : List<ReqT>
    +closeStatus() : Status
  }
  class RequestCaptureInterceptor {
    -log : Logger
    -SEPARATOR : String
    -capturedRequests : Queue<CapturedRequest>
    +callCountFor() : int
    +clear() : void
    +close() : void
    +onMessage() : void
  }
}

package org.grpcmock.junit5 {
  class GrpcMockExtension {
    -log : Logger
    -server : GrpcMock
    -port : int
    -executor : Executor
    -interceptors : List<ServerInterceptor>
    -certChain : File
    -privateKey : File
    +builder() : Builder
    +logServerStarted() : void
    +getPort() : int
    +getInstance() : GrpcMock
    +beforeAll() : void
    +afterAll() : void
    +afterEach() : void
    +withPort() : Builder
  }
  class InProcessGrpcMockExtension {
    -log : Logger
    +logServerStarted() : void
    +getInProcessName() : String
  }
}

package org.grpcmock.junit5.test {
  class InProcessExtensionTest {
  }
  class NestedTest {
  }
  class DefaultExtensionTest {
  }
  class ConfiguredExtensionTest {
    -MY_HEADER : String
    -HEADER_VALUE : String
    -grpcMockExtension : GrpcMockExtension
  }
  class TestBase {
    -serverChannel : ManagedChannel
  }
}

package org.grpcmock.springboot {
  class GrpcMockTestFixedPortResetFirst {
    -grpcMock : GrpcMock
  }
  class GrpcMockInProcessServerWithFixedNameTest {
    -grpcMock : GrpcMock
  }
  class TestExecutionListenerAllowsOtherBeforeActionsTest {
    -beforeAllRunSuccessful : boolean
    -applicationContextInitialized : boolean
    +onApplicationEvent() : void
  }
  class GrpcMockTestExecutorBeanTest {
    -myExecutor : Executor
    +myExecutor() : Executor
  }
  class GrpcMockInProcessServerWithRandomNameTest {
    -grpcMock : GrpcMock
  }
  class GrpcMockTestResetAfterTestMethod {
  }
  class GrpcMockTestInterceptorInsertTest {
    -MY_HEADER : String
    -HEADER_VALUE : String
  }
  class TestApplication {
    +main() : void
  }
  class GrpcMockTestDynamicPortResetSecond {
  }
  class GrpcMockTestFixedPortResetSecond {
    -grpcMock : GrpcMock
  }
  class GrpcMockTestNestedTest {
  }
  class GrpcMockTestDynamicPortResetFirst {
  }
  class TestBase {
    -grpcMockPort : int
    -inProcessName : String
    -serverChannel : ManagedChannel
  }
  class GrpcMockContextCustomizer {
    -GRPCMOCK_BEAN_NAME : String
    -log : Logger
    -properties : AutoConfigureGrpcMock
    +customizeContext() : void
  }
  interface AutoConfigureGrpcMock {
  }
  class GrpcMockTestExecutionListener {
    -log : Logger
    +prepareTestInstance() : void
    +afterTestClass() : void
    +afterTestMethod() : void
  }
  class GrpcMockContextCustomizerFactory {
    +createContextCustomizer() : ContextCustomizer
  }
}

package org.grpcmock.util {
  class FunctionalHelpers {
  }
  class FunctionalResponseObserver {
    -onNext : Consumer<V>
    -onError : Consumer<Throwable>
    -onCompleted : Runnable
    -onNext : Consumer<V>
    -onError : Consumer<Throwable>
    -onCompleted : Runnable
    +onNext() : void
    +onError() : void
    +onCompleted() : void
    +onNext() : Builder<V>
    +onError() : Builder<V>
    +onCompleted() : Builder<V>
    +build() : FunctionalResponseObserver<V>
  }
}

' --- Relatii ---
GrpcMockTestFixedPortResetFirst --|> TestBase
GrpcMockTestFixedPortResetFirst --> GrpcMock
GrpcMockInProcessServerWithFixedNameTest --|> TestBase
GrpcMockInProcessServerWithFixedNameTest --> GrpcMock
TestExecutionListenerAllowsOtherBeforeActionsTest --|> TestBase
GrpcMockTestExecutorBeanTest --|> TestBase
GrpcMockInProcessServerWithRandomNameTest --|> TestBase
GrpcMockInProcessServerWithRandomNameTest --> GrpcMock
GrpcMockTestResetAfterTestMethod --|> TestBase
GrpcMockTestInterceptorInsertTest --|> TestBase
GrpcMockTestDynamicPortResetSecond --|> TestBase
GrpcMockTestFixedPortResetSecond --|> TestBase
GrpcMockTestFixedPortResetSecond --> GrpcMock
GrpcMockTestNestedTest --|> TestBase
GrpcMockTestDynamicPortResetFirst --|> TestBase
GrpcMockContextCustomizer --> GrpcMock
GrpcMockContextCustomizer --> GrpcMockBuilder
GrpcMockContextCustomizer --> GrpcMockException
GrpcMockTestExecutionListener --> GrpcMock
InProcessExtensionTest --|> TestBase
InProcessExtensionTest --> GrpcMock
InProcessExtensionTest --> InProcessGrpcMockExtension
NestedTest --|> TestBase
NestedTest --> GrpcMockExtension
DefaultExtensionTest --|> TestBase
DefaultExtensionTest --> GrpcMockExtension
ConfiguredExtensionTest --|> TestBase
ConfiguredExtensionTest --> GrpcMockExtension
TestBase --> GrpcMock
GrpcMockExtension --> GrpcMock
GrpcMockExtension --> GrpcMockBuilder
InProcessGrpcMockExtension --|> GrpcMockExtension
InProcessGrpcMockExtension --> GrpcMock
GrpcMockServerStreamingMethodTest --|> TestBase
GrpcMockVerifyTest --|> TestBase
GrpcMockVerifyTest --> CapturedRequest
GrpcMockUnaryMethodTest --|> TestBase
GrpcMockClientStreamingMethodTest --|> TestBase
GrpcMockClientStreamingMethodTest --> FunctionalResponseObserver
GrpcMockHeaderMatcherTest --|> TestBase
GrpcMockHeaderMatcherTest --> HeadersMatcher
GrpcMockBidiStreamingMethodTest --|> TestBase
GrpcMockBidiStreamingMethodTest --> FunctionalResponseObserver
TestBase --> FunctionalResponseObserver
InProcessTest --|> TestBase
GrpcMockBuilder --> RequestCaptureInterceptor
DelegateHandlerRegistry --> FunctionalResponseObserver
InProcessGrpcMockBuilder --|> GrpcMockBuilder
GrpcMock --> Delay
GrpcMock --> ExceptionResponseActionBuilderImpl
GrpcMock --> ObjectResponseActionBuilderImpl
GrpcMock --> ResponseAction
GrpcMock --> StreamResponseBuilderImpl
GrpcMock --> ExceptionStreamResponseBuildersStep
GrpcMock --> ObjectResponseActionBuilder
GrpcMock --> ObjectStreamResponseBuilderStep
GrpcMock --> BidiStreamingMethodStubBuilderImpl
GrpcMock --> ClientStreamingMethodStubBuilderImpl
GrpcMock --> MethodStub
GrpcMock --> ServerStreamingMethodStubBuilderImpl
GrpcMock --> ServiceStub
GrpcMock --> UnaryMethodStubBuilderImpl
GrpcMock --> BidiStreamingMethodStubBuilderStep
GrpcMock --> ClientStreamingMethodStubBuilderStep
GrpcMock --> MethodStubBuilder
GrpcMock --> ServerStreamingMethodStubBuilderStep
GrpcMock --> UnaryMethodStubBuilderStep
GrpcMock --> CountMatcher
GrpcMock --> RequestPattern
GrpcMock --> RequestPatternBuilderImpl
GrpcMock --> RequestPatternBuilderStep
GrpcMock --> GrpcMockException
GrpcMock --> GrpcMockVerificationError
GrpcMock --> CapturedRequest
GrpcMock --> RequestCaptureInterceptor
RequestCaptureInterceptor --> GrpcMock
RequestCaptureInterceptor --> RequestPattern
Traceable --> StubScenario
StreamResponseBuilderImpl --> ExceptionStreamResponseBuildersStep
StreamResponseBuilderImpl --> ObjectResponseActionBuilder
StreamResponseBuilderImpl --> ObjectStreamResponseBuilderStep
ExceptionResponseActionBuilderImpl --> GrpcMockValidationException
ResponseImpl --> GrpcMockValidationException
ResponseImpl --> FunctionalResponseObserver
ObjectResponseActionBuilderImpl --> ObjectResponseActionBuilder
StreamResponseBuilder --> BuilderStep
StreamResponseBuilder --> Response
DelayBuilderStep --> BuilderStep
DelayBuilderStep --> Delay
DelayBuilderStep --> ResponseAction
ExceptionStreamResponseBuildersStep --> BuilderStep
ObjectResponseActionBuilder --> BuilderStep
ObjectResponseActionBuilder --> ResponseAction
ObjectStreamResponseBuilderStep --> GrpcMock
ObjectStreamResponseBuilderStep --> BuilderStep
ObjectStreamResponseBuilderStep --> ResponseAction
RequestMatcherBuilderImpl --> RequestMatcherBuilderStep
RequestMatcherBuilderImpl --> StreamRequestMatcherBuilderStep
HeadersMatcherBuilderImpl ..|> HeadersMatcherBuilderStep
HeadersMatcherBuilderImpl --> HeadersMatcherBuilderStep
StatusMatcherBuilderImpl ..|> StatusMatcherBuilderStep
StatusMatcherBuilderImpl --> StatusMatcherBuilderStep
StreamRequestMatcherBuilderStep --> BuilderStep
RequestMatcherBuilderStep --> BuilderStep
StatusMatcherBuilderStep --> BuilderStep
HeadersMatcherBuilderStep --> BuilderStep
FirstRequestMatcherBuilderStep --> BuilderStep
RequestPatternBuilderImpl --> HeadersMatcher
RequestPatternBuilderImpl --> HeadersMatcherBuilderImpl
RequestPatternBuilderImpl --> RequestMatcher
RequestPatternBuilderImpl --> RequestMatcherBuilderImpl
RequestPatternBuilderImpl --> StatusMatcher
RequestPatternBuilderImpl --> StatusMatcherBuilderImpl
RequestPatternBuilderImpl --> RequestPatternBuilderStep
RequestPatternBuilderImpl --> GrpcMockException
RequestPatternBuilderImpl --> CapturedRequest
RequestPattern --> HeadersMatcher
RequestPattern --> RequestMatcher
RequestPattern --> StatusMatcher
RequestPattern --> CapturedRequest
RequestPatternBuilderStep --> BuilderStep
RequestPatternBuilderStep --> HeadersMatcherBuilderStep
RequestPatternBuilderStep --> RequestMatcherBuilderStep
RequestPatternBuilderStep --> StatusMatcherBuilderStep
RequestPatternBuilderStep --> StreamRequestMatcherBuilderStep
RequestPatternBuilderStep --> RequestPattern
ServerStreamingMethodStubBuilderImpl --> Response
ServerStreamingMethodStubBuilderImpl --> ResponseImpl
ServerStreamingMethodStubBuilderImpl --> ResponseProxyImpl
ServerStreamingMethodStubBuilderImpl --> ObjectResponseActionBuilder
ServerStreamingMethodStubBuilderImpl --> StreamResponseBuilder
ServerStreamingMethodStubBuilderImpl --> NextServerStreamingMethodResponseBuilderStep
ServerStreamingMethodStubBuilderImpl --> ServerStreamingMethodStubBuilderStep
ServerStreamingMethodStubBuilderImpl --> RequestPatternBuilderImpl
ServerStreamingMethodStubBuilderImpl --> GrpcMockException
ClientStreamingMethodStubBuilderImpl --> Response
ClientStreamingMethodStubBuilderImpl --> ResponseImpl
ClientStreamingMethodStubBuilderImpl --> ResponseProxyImpl
ClientStreamingMethodStubBuilderImpl --> ObjectResponseActionBuilder
ClientStreamingMethodStubBuilderImpl --> ClientStreamingMethodStubBuilderStep
ClientStreamingMethodStubBuilderImpl --> NextClientStreamingMethodResponseBuilderStep
ClientStreamingMethodStubBuilderImpl --> RequestPatternBuilderImpl
ClientStreamingMethodStubBuilderImpl --> GrpcMockException
MethodStub --> GrpcMockException
MethodStub --> UnimplementedStatusException
MethodStub --> RequestCaptureInterceptor
StubScenario --> Response
StubScenario --> RequestPattern
StubScenario --> GrpcMockValidationException
StubScenario --> CapturedRequest
UnaryMethodStubBuilderImpl --> Response
UnaryMethodStubBuilderImpl --> ResponseImpl
UnaryMethodStubBuilderImpl --> ResponseProxyImpl
UnaryMethodStubBuilderImpl --> ObjectResponseActionBuilder
UnaryMethodStubBuilderImpl --> NextUnaryMethodResponseBuilderStep
UnaryMethodStubBuilderImpl --> UnaryMethodStubBuilderStep
UnaryMethodStubBuilderImpl --> RequestPatternBuilderImpl
UnaryMethodStubBuilderImpl --> GrpcMockException
ServiceStub --> GrpcMockException
BidiStreamingMethodStubBuilderImpl --> Response
BidiStreamingMethodStubBuilderImpl --> ResponseProxyImpl
BidiStreamingMethodStubBuilderImpl --> BidiStreamingMethodStubBuilderStep
BidiStreamingMethodStubBuilderImpl --> NextBidiStreamingMethodStubBuilderStep
BidiStreamingMethodStubBuilderImpl --> RequestPatternBuilderImpl
BidiStreamingMethodStubBuilderImpl --> GrpcMockException
NextServerStreamingMethodResponseBuilderStep --> BuilderStep
SingleRequestProxyResponseBuilderStep --> BuilderStep
SingleRequestProxyResponseBuilderStep --> Response
StreamRequestProxyResponseBuilderStep --> BuilderStep
StreamRequestProxyResponseBuilderStep --> Response
ClientStreamingMethodStubBuilderStep --> FirstRequestMatcherBuilderStep
ClientStreamingMethodStubBuilderStep --> HeadersMatcherBuilderStep
StreamResponseBuilderStep --> GrpcMock
StreamResponseBuilderStep --> BuilderStep
StreamResponseBuilderStep --> Delay
StreamResponseBuilderStep --> Response
StreamResponseBuilderStep --> ResponseAction
StreamResponseBuilderStep --> StreamResponseBuilder
NextUnaryMethodResponseBuilderStep --> BuilderStep
NextClientStreamingMethodResponseBuilderStep --> BuilderStep
SingleResponseBuilderStep --> GrpcMock
SingleResponseBuilderStep --> BuilderStep
SingleResponseBuilderStep --> Delay
SingleResponseBuilderStep --> Response
SingleResponseBuilderStep --> ObjectResponseActionBuilder
ServerStreamingMethodStubBuilderStep --> HeadersMatcherBuilderStep
ServerStreamingMethodStubBuilderStep --> RequestMatcherBuilderStep
NextSingleResponseBuilderStep --> GrpcMock
NextSingleResponseBuilderStep --> BuilderStep
NextSingleResponseBuilderStep --> Delay
NextSingleResponseBuilderStep --> Response
NextSingleResponseBuilderStep --> ObjectResponseActionBuilder
BidiStreamingMethodStubBuilderStep --> FirstRequestMatcherBuilderStep
BidiStreamingMethodStubBuilderStep --> HeadersMatcherBuilderStep
UnaryMethodStubBuilderStep --> HeadersMatcherBuilderStep
UnaryMethodStubBuilderStep --> RequestMatcherBuilderStep
MethodStubBuilder --> BuilderStep
MethodStubBuilder --> MethodStub
NextStreamResponseBuilderStep --> GrpcMock
NextStreamResponseBuilderStep --> BuilderStep
NextStreamResponseBuilderStep --> Delay
NextStreamResponseBuilderStep --> Response
NextStreamResponseBuilderStep --> ResponseAction
NextStreamResponseBuilderStep --> StreamResponseBuilder
NextSingleRequestProxyResponseBuilderStep --> BuilderStep
NextSingleRequestProxyResponseBuilderStep --> Response
NextStreamRequestProxyResponseBuilderStep --> BuilderStep
NextStreamRequestProxyResponseBuilderStep --> Response
GrpcMockValidationException --|> GrpcMockException
DownstreamServiceTest --> GrpcMock
DownstreamServiceTest --> GrpcMockExtension
NewsAggregatorServiceTest --> Application
NewsAggregatorServiceTest --> AutoConfigureGrpcMock
NewsServicesConfig --> ApikeyInterceptor
NewsServicesConfig --> DownstreamNewsService
MessageControllerIT --> Application
MessageControllerIT --> AutoConfigureGrpcMock
MessageController --> DownstreamService

@enduml