@startuml

  class MavenWrapperDownloader {
    -WRAPPER_VERSION : String
    -DEFAULT_DOWNLOAD_URL : String
    -MAVEN_WRAPPER_PROPERTIES_PATH : String
    -MAVEN_WRAPPER_JAR_PATH : String
    -PROPERTY_NAME_WRAPPER_URL : String
    +main() : void
    +getPasswordAuthentication() : PasswordAuthentication
  }

package com.bobocode {
  class AccountRestControllerTest {
    -applicationContext : WebApplicationContext
    -accountDao : InMemoryAccountDao
    -mockMvc : MockMvc
  }
  class WebAppConfigurationTest {
  }
  class EnableStringTrimmingTest {
    -id : Long
    -name : String
  }
  class implements {
  }
  class ApplicationConfigTest {
  }
  class ApplicationContextTest {
    -applicationContext : ApplicationContext
  }
  class AccountServiceDemoApp {
    +main() : void
  }
  class WebAppInitializerWrapper {
    +getServletMappings() : String[]
    +getRootConfigClasses() : Class[]
  }
  class WebAppConfigurationTest {
  }
  class DateServletTest {
    -request : HttpServletRequest
    -response : HttpServletResponse
    -dateServletObject : Object
    -SERVLET_PACKAGE : String
    -DATE_SERVLET : String
    +init() : void
  }
  class TestDataGenerator {
    +generateAccount() : Account
  }
}

package com.bobocode.annotation {
  interface Trimmed {
  }
  interface EnableStringTrimming {
  }
}

package com.bobocode.config {
  class RootConfig {
  }
  class WebConfig {
  }
  class AccountRestApiInitializer {
    +getServletMappings() : String[]
  }
  class TrimmingEnabledConfig {
  }
  class TrimmingNotEnabledConfig {
  }
  class ApplicationConfig {
  }
  class RootConfig {
  }
  class WebAppInitializer {
    +getServletMappings() : String[]
  }
  class WebConfig {
  }
}

package com.bobocode.dao {
  interface AccountDao {
  }
  class FakeAccountDao {
    -accounts : List<Account>
    +findAll() : List<Account>
  }
  interface AccountDao {
  }
}

package com.bobocode.dao.impl {
  class InMemoryAccountDao {
    -idSequence : long
    +findAll() : List<Account>
    +findById() : Account
    +save() : Account
    +remove() : void
    +clear() : void
  }
}

package com.bobocode.demo {
  class DemoWebApp {
    +main() : void
  }
}

package com.bobocode.exception {
  class EntityNotFountException {
  }
}

package com.bobocode.intro {
  class WelcomeToJavaWebCourseApp <<Controller>> {
    +main() : void
    +welcome() : String
  }
}

package com.bobocode.model {
  class Account {
    -id : Long
    -firstName : String
    -lastName : String
    -email : String
    -birthday : LocalDate
    -gender : Gender
    -creationTime : LocalDateTime
    -balance : BigDecimal
  }
  enum Gender {
  }
}

package com.bobocode.mvc {
  class HelloSpringMvcApp {
    +main() : void
  }
}

package com.bobocode.mvc.api {
  class NoteRestControllerTest {
    -notes : Notes
    -mockMvc : MockMvc
  }
  class NoteRestController {
    -notes : Notes
  }
}

package com.bobocode.mvc.controller {
  class NoteControllerTest {
    -notes : Notes
    -mockMvc : MockMvc
  }
  class NoteController {
    -notes : Notes
  }
}

package com.bobocode.mvc.data {
  class Notes {
    +getAll() : List<Note>
    +add() : void
  }
}

package com.bobocode.mvc.model {
  class Note {
    -id : UUID
    -title : String
    -text : String
    -createdOn : LocalDateTime
  }
}

package com.bobocode.net.client {
  class ClientUtilTest {
    +init() : void
  }
  class MessageBoardClient {
    -SERVER_ADDRESS : String
    -SERVER_PORT : int
    +main() : void
  }
  class that {
    +openSocket() : Socket
    +openConsoleReader() : BufferedReader
    +readMessage() : String
    +writeToSocket() : void
  }
}

package com.bobocode.net.server {
  class ServerUtilTest {
    +init() : void
  }
  class ServerUtil {
    -TIME_FORMATTER : DateTimeFormatter
    +getLocalHost() : String
    +createServerSocket() : ServerSocket
    +acceptClientSocket() : Socket
    +readMessageFromSocket() : String
    +printMessage() : void
  }
  class MessageBoardServer {
    -HOST : String
    -PORT : int
    +main() : void
  }
}

package com.bobocode.service {
  class TrimmedService <<Service>> {
    +getTheTrimmedString() : String
    +getNotTrimmedString() : String
  }
  class AccountService {
    -accountDao : AccountDao
    +findRichestAccount() : Account
  }
}

package com.bobocode.servlet {
  class from {
    +doGet() : void
  }
}

package com.bobocode.util {
  class ExerciseNotCompletedException {
  }
}

package com.bobocode.web.controller {
  class AccountRestController {
  }
  class WelcomeController {
    +welcome() : String
  }
}

' --- Relatii ---
NoteControllerTest --> Notes
NoteControllerTest --> Note
NoteRestControllerTest --> Notes
NoteRestControllerTest --> Note
NoteController --> Notes
NoteRestController --> Notes
Notes --> Note
AccountRestControllerTest --> RootConfig
AccountRestControllerTest --> WebConfig
AccountRestControllerTest --> AccountDao
AccountRestControllerTest --> InMemoryAccountDao
AccountRestControllerTest --> Account
AccountRestControllerTest --> AccountRestController
WebAppConfigurationTest --> RootConfig
WebAppConfigurationTest --> WebConfig
WebAppConfigurationTest --> InMemoryAccountDao
AccountRestController --> AccountDao
AccountDao --> Account
InMemoryAccountDao ..|> AccountDao
InMemoryAccountDao --> AccountDao
InMemoryAccountDao --> EntityNotFountException
InMemoryAccountDao --> Account
EnableStringTrimmingTest --> TrimmingEnabledConfig
EnableStringTrimmingTest --> TrimmingNotEnabledConfig
EnableStringTrimmingTest --> TrimmedService
TrimmingEnabledConfig --> EnableStringTrimming
TrimmedService --> Trimmed
implements --> Trimmed
ApplicationConfigTest --> ApplicationConfig
ApplicationConfigTest --> AccountDao
ApplicationConfigTest --> FakeAccountDao
ApplicationConfigTest --> AccountService
ApplicationContextTest --> AccountDao
ApplicationContextTest --> AccountService
AccountServiceDemoApp --> ApplicationConfig
AccountServiceDemoApp --> Account
AccountServiceDemoApp --> AccountService
ApplicationConfig --> TestDataGenerator
FakeAccountDao ..|> AccountDao
FakeAccountDao --> TestDataGenerator
FakeAccountDao --> Account
AccountDao --> Account
AccountService --> AccountDao
AccountService --> Account
WebAppInitializerWrapper --|> WebAppInitializer
WebAppInitializerWrapper --> WebAppInitializer
WebAppConfigurationTest --> RootConfig
WebAppConfigurationTest --> WebConfig
WebAppConfigurationTest --> WelcomeController
WebAppInitializer --> ExerciseNotCompletedException
TestDataGenerator --> Account
TestDataGenerator --> Gender
ServerUtil --> ExerciseNotCompletedException
MessageBoardClient --> MessageBoardServer
that --> ExerciseNotCompletedException

@enduml