@startuml

package com.cassiomolin.example {
  class ArquillianTest {
    -uri : URI
    -client : Client
    +createDeployment() : Archive<WebArchive>
    +beforeTest() : void
    +getTokenForAdmin() : String
    +getTokenForUser() : String
    +composeAuthorizationHeader() : String
  }
  class Application {
    -server : Undertow
    -deploymentManager : DeploymentManager
    -DEFAULT_PORT : int
    -LOGGER : Logger
    -args : String[]
    +main() : void
    +startServer() : void
    +stopServer() : void
  }
}

package com.cassiomolin.example.common.api.config {
  class JerseyConfig {
  }
}

package com.cassiomolin.example.common.api.model {
  class ApiErrorDetails {
    -status : Integer
    -title : String
    -message : String
    -path : String
    +getStatus() : Integer
    +setStatus() : void
    +getTitle() : String
    +setTitle() : void
    +getMessage() : String
    +setMessage() : void
    +getPath() : String
    +setPath() : void
  }
}

package com.cassiomolin.example.common.api.provider {
  class ObjectMapperProvider {
    -mapper : ObjectMapper
    +getContext() : ObjectMapper
  }
}

package com.cassiomolin.example.common.configuration {
  class ConfigurationProducer {
    -properties : Properties
    -e : IOException
    +init() : void
    +produceString() : String
    +produceInteger() : Integer
    +produceLong() : Long
    +produceBoolean() : Boolean
  }
  interface Configurable {
  }
}

package com.cassiomolin.example.common.persistence {
  class EntityManagerProducer {
    -factory : EntityManagerFactory
    +init() : void
    +createEntityManager() : EntityManager
    +closeEntityManager() : void
    +destroy() : void
    +init() : void
  }
}

package com.cassiomolin.example.greeting.api.resource {
  class GreetingResourceTest {
    +getPublicGreetingAsAnonymous() : void
    +getProtectedGreetingAsAnonymous() : void
    +getPublicGreetingAsAdmin() : void
    +getProtectedGreetingAsAdmin() : void
  }
  class GreetingResource {
    -securityContext : SecurityContext
    -greetingService : GreetingService
    +getPublicGreeting() : Response
    +getProtectedGreeting() : Response
  }
}

package com.cassiomolin.example.greeting.service {
  class GreetingService {
    +getPublicGreeting() : String
    +getGreetingForUser() : String
  }
}

package com.cassiomolin.example.security.api {
  class AuthenticatedUserDetails {
    -username : String
    -authorities : Set<Authority>
    +getAuthorities() : Set<Authority>
    +getName() : String
  }
  class TokenBasedSecurityContext {
    -authenticatedUserDetails : AuthenticatedUserDetails
    -authenticationTokenDetails : AuthenticationTokenDetails
    -secure : boolean
    +getUserPrincipal() : Principal
    +isUserInRole() : boolean
    +isSecure() : boolean
    +getAuthenticationScheme() : String
    +getAuthenticationTokenDetails() : AuthenticationTokenDetails
  }
  class AuthenticationTokenDetails {
    -id : String
    -username : String
    -authorities : Set<Authority>
    -issuedDate : ZonedDateTime
    -expirationDate : ZonedDateTime
    -refreshCount : int
    -refreshLimit : int
    -id : String
    -username : String
    -authorities : Set<Authority>
    +getId() : String
    +getUsername() : String
    +getAuthorities() : Set<Authority>
    +getIssuedDate() : ZonedDateTime
    +getExpirationDate() : ZonedDateTime
    +getRefreshCount() : int
    +getRefreshLimit() : int
    +isEligibleForRefreshment() : boolean
  }
}

package com.cassiomolin.example.security.api.exeptionmapper {
  class AuthenticationExceptionMapper {
    -uriInfo : UriInfo
    +toResponse() : Response
  }
  class AuthenticationTokenRefreshmentExceptionMapper {
    -uriInfo : UriInfo
    +toResponse() : Response
  }
  class AccessDeniedExceptionMapper {
    -uriInfo : UriInfo
    +toResponse() : Response
  }
}

package com.cassiomolin.example.security.api.filter {
  class AuthorizationFilter {
    -resourceInfo : ResourceInfo
    -requestContext : ContainerRequestContext
    -requestContext : ContainerRequestContext
    +filter() : void
  }
  class AuthenticationFilter {
    -userService : UserService
    -authenticationTokenService : AuthenticationTokenService
    +filter() : void
  }
}

package com.cassiomolin.example.security.api.model {
  class AuthenticationToken {
    -token : String
    +getToken() : String
    +setToken() : void
  }
  class UserCredentials {
    -username : String
    -password : String
    +getUsername() : String
    +setUsername() : void
    +getPassword() : String
    +setPassword() : void
  }
}

package com.cassiomolin.example.security.api.resource {
  class AuthenticationResourceTest {
    +authenticateWithValidCredentials() : void
    +authenticateWithInvalidCredentials() : void
  }
  class AuthenticationResource {
    -securityContext : SecurityContext
    -usernamePasswordValidator : UsernamePasswordValidator
    -authenticationTokenService : AuthenticationTokenService
    +authenticate() : Response
    +refresh() : Response
  }
}

package com.cassiomolin.example.security.domain {
  enum Authority {
  }
}

package com.cassiomolin.example.security.exception {
  class InvalidAuthenticationTokenException {
  }
  class AuthenticationException {
  }
  class AccessDeniedException {
  }
  class AuthenticationTokenRefreshmentException {
  }
}

package com.cassiomolin.example.security.service {
  class UsernamePasswordValidator {
    -userService : UserService
    -passwordEncoder : PasswordEncoder
    +validateCredentials() : User
  }
  class AuthenticationTokenIssuer {
    -settings : AuthenticationTokenSettings
    +issueToken() : String
  }
  class PasswordEncoder {
    +hashPassword() : String
    +checkPassword() : boolean
  }
  class AuthenticationTokenService {
    -validFor : Long
    -refreshLimit : Integer
    -tokenIssuer : AuthenticationTokenIssuer
    -tokenParser : AuthenticationTokenParser
    +issueToken() : String
    +parseToken() : AuthenticationTokenDetails
    +refreshToken() : String
  }
  class AuthenticationTokenParser {
    -settings : AuthenticationTokenSettings
    +parseToken() : AuthenticationTokenDetails
  }
  class AuthenticationTokenSettings {
    -secret : String
    -clockSkew : Long
    -audience : String
    -issuer : String
    -authoritiesClaimName : String
    -refreshCountClaimName : String
    -refreshLimitClaimName : String
    +getSecret() : String
    +getClockSkew() : Long
    +getAudience() : String
    +getIssuer() : String
    +getAuthoritiesClaimName() : String
    +getRefreshCountClaimName() : String
    +getRefreshLimitClaimName() : String
  }
}

package com.cassiomolin.example.user.api.model {
  class QueryUserResult {
    -id : Long
    -firstName : String
    -lastName : String
    -email : String
    -username : String
    -authorities : Set<Authority>
    -active : Boolean
    +getId() : Long
    +setId() : void
    +getFirstName() : String
    +setFirstName() : void
    +getLastName() : String
    +setLastName() : void
    +getEmail() : String
    +setEmail() : void
  }
}

package com.cassiomolin.example.user.api.resource {
  class UserResourceTest {
    +getUsersAsAnonymous() : void
    +getUsersAsAsUser() : void
    +getUsersAsAdmin() : void
    +getUserAsAnonymous() : void
    +getUserAsUser() : void
    +getUserAsAdmin() : void
    +getAuthenticatedUserAsAnonymous() : void
    +getAuthenticatedUserAsUser() : void
  }
  class UserResource {
    -uriInfo : UriInfo
    -securityContext : SecurityContext
    -userService : UserService
    +getUsers() : Response
    +getUser() : Response
    +getAuthenticatedUser() : Response
  }
}

package com.cassiomolin.example.user.domain {
  class User <<Entity>> {
    -id : Long
    -firstName : String
    -lastName : String
    -email : String
    -username : String
    -password : String
    -active : boolean
    -authorities : Set<Authority>
    +getId() : Long
    +setId() : void
    +getFirstName() : String
    +setFirstName() : void
    +getLastName() : String
    +setLastName() : void
    +getEmail() : String
    +setEmail() : void
  }
}

package com.cassiomolin.example.user.service {
  class UserService {
    -em : EntityManager
    +findByUsernameOrEmail() : User
    +findAll() : List<User>
    +findById() : Optional<User>
  }
}

' --- Relatii ---
ArquillianTest --> JerseyConfig
ArquillianTest --> UserCredentials
ArquillianTest --> AuthenticationToken
GreetingResourceTest --|> ArquillianTest
GreetingResourceTest --> ArquillianTest
AuthenticationResourceTest --|> ArquillianTest
AuthenticationResourceTest --> ArquillianTest
AuthenticationResourceTest --> AuthenticationToken
AuthenticationResourceTest --> UserCredentials
UserResourceTest --|> ArquillianTest
UserResourceTest --> ArquillianTest
UserResourceTest --> Authority
UserResourceTest --> QueryUserResult
Application --> JerseyConfig
GreetingResource --> GreetingService
AuthenticatedUserDetails --> Authority
TokenBasedSecurityContext --> Authority
AuthenticationTokenDetails --> Authority
AuthenticationExceptionMapper --> ApiErrorDetails
AuthenticationExceptionMapper --> AuthenticationException
AuthenticationTokenRefreshmentExceptionMapper --> ApiErrorDetails
AuthenticationTokenRefreshmentExceptionMapper --> AuthenticationTokenRefreshmentException
AccessDeniedExceptionMapper --> ApiErrorDetails
AccessDeniedExceptionMapper --> AccessDeniedException
AuthorizationFilter --> AccessDeniedException
AuthenticationFilter --> AuthenticatedUserDetails
AuthenticationFilter --> AuthenticationTokenDetails
AuthenticationFilter --> TokenBasedSecurityContext
AuthenticationFilter --> AuthenticationTokenService
AuthenticationFilter --> User
AuthenticationFilter --> UserService
AuthenticationResource --> AuthenticationTokenDetails
AuthenticationResource --> TokenBasedSecurityContext
AuthenticationResource --> AuthenticationToken
AuthenticationResource --> UserCredentials
AuthenticationResource --> AuthenticationTokenService
AuthenticationResource --> UsernamePasswordValidator
AuthenticationResource --> User
UsernamePasswordValidator --> AuthenticationException
UsernamePasswordValidator --> User
UsernamePasswordValidator --> UserService
AuthenticationTokenIssuer --> AuthenticationTokenDetails
AuthenticationTokenService --> Configurable
AuthenticationTokenService --> AuthenticationTokenDetails
AuthenticationTokenService --> Authority
AuthenticationTokenService --> AuthenticationTokenRefreshmentException
AuthenticationTokenParser --> AuthenticationTokenDetails
AuthenticationTokenParser --> Authority
AuthenticationTokenParser --> InvalidAuthenticationTokenException
AuthenticationTokenSettings --> Configurable
Authority --> User
QueryUserResult --> Authority
UserResource --> QueryUserResult
UserResource --> User
UserResource --> UserService
UserService --> User
User --> Authority
JerseyConfig --> ObjectMapperProvider
JerseyConfig --> GreetingResource
JerseyConfig --> AccessDeniedExceptionMapper
JerseyConfig --> AuthenticationExceptionMapper
JerseyConfig --> AuthenticationTokenRefreshmentExceptionMapper
JerseyConfig --> AuthenticationFilter
JerseyConfig --> AuthorizationFilter
JerseyConfig --> AuthenticationResource
JerseyConfig --> UserResource

@enduml