@startuml

package com.techprimers.security.jwtsecurity {
  class JwtSecurityApplicationTests {
    +contextLoads() : void
  }
  class JwtSecurityApplication {
    +main() : void
  }
}

package com.techprimers.security.jwtsecurity.config {
  class JwtSecurityConfig {
    -authenticationProvider : JwtAuthenticationProvider
    -entryPoint : JwtAuthenticationEntryPoint
    +authenticationManager() : AuthenticationManager
    +authenticationTokenFilter() : JwtAuthenticationTokenFilter
    +configure() : void
  }
}

package com.techprimers.security.jwtsecurity.controller {
  class HelloController <<Controller>> {
    +hello() : String
  }
  class TokenController <<Controller>> {
    -jwtGenerator : JwtGenerator
    -jwtUser : JwtUser
    +generate() : String
  }
}

package com.techprimers.security.jwtsecurity.model {
  class JwtUser {
    -userName : String
    -id : long
    -role : String
    +setUserName() : void
    +setId() : void
    +setRole() : void
    +getUserName() : String
    +getId() : long
    +getRole() : String
  }
  class JwtUserDetails {
    -userName : String
    -token : String
    -id : Long
    +getPassword() : String
    +getUsername() : String
    +isAccountNonExpired() : boolean
    +isAccountNonLocked() : boolean
    +isCredentialsNonExpired() : boolean
    +isEnabled() : boolean
    +getUserName() : String
    +getToken() : String
  }
  class JwtAuthenticationToken {
    -token : String
    +getToken() : String
    +setToken() : void
    +getCredentials() : Object
    +getPrincipal() : Object
  }
}

package com.techprimers.security.jwtsecurity.security {
  class JwtAuthenticationEntryPoint {
    +commence() : void
  }
  class JwtValidator {
    -secret : String
    +validate() : JwtUser
  }
  class JwtSuccessHandler {
    +onAuthenticationSuccess() : void
  }
  class JwtAuthenticationTokenFilter {
    +attemptAuthentication() : Authentication
    +successfulAuthentication() : void
  }
  class JwtAuthenticationProvider {
    -validator : JwtValidator
    +additionalAuthenticationChecks() : void
    +retrieveUser() : UserDetails
    +supports() : boolean
  }
  class JwtGenerator {
    +generate() : String
  }
}

' --- Relatii ---
JwtSecurityConfig --> JwtAuthenticationEntryPoint
JwtSecurityConfig --> JwtAuthenticationProvider
JwtSecurityConfig --> JwtAuthenticationTokenFilter
JwtSecurityConfig --> JwtSuccessHandler
JwtValidator --> JwtUser
JwtAuthenticationTokenFilter --> JwtAuthenticationToken
JwtAuthenticationProvider --> JwtAuthenticationToken
JwtAuthenticationProvider --> JwtUser
JwtAuthenticationProvider --> JwtUserDetails
JwtGenerator --> JwtUser
TokenController --> JwtUser
TokenController --> JwtGenerator

@enduml