@startuml

package org.zerhusen {
  class JwtDemoApplicationTest {
    +contextLoads() : void
  }
  class JwtDemoApplication {
    +main() : void
  }
}

package org.zerhusen.config {
  class WebSecurityConfig {
    -tokenProvider : TokenProvider
    -corsFilter : CorsFilter
    -authenticationErrorHandler : JwtAuthenticationEntryPoint
    -jwtAccessDeniedHandler : JwtAccessDeniedHandler
    +passwordEncoder() : PasswordEncoder
    +configure() : void
    +configure() : void
  }
  class CorsConfig {
    +corsFilter() : CorsFilter
  }
}

package org.zerhusen.rest {
  class PersonRestControllerTest {
    -token : String
    -token : String
    +getPersonForUser() : void
    +getPersonForAdmin() : void
    +getPersonForAnonymous() : void
  }
  class AdminProtectedRestControllerTest {
    -token : String
    -token : String
    +getAdminProtectedGreetingForUser() : void
    +getAdminProtectedGreetingForAdmin() : void
    +getAdminProtectedGreetingForAnonymous() : void
  }
  class PersonRestController <<Controller>> {
    -name : String
    -email : String
    +getPerson() : ResponseEntity<Person>
    +getName() : String
    +getEmail() : String
  }
  class AdminProtectedRestController <<Controller>> {
    -message : String
    +getAdminProtectedGreeting() : ResponseEntity<HiddenMessage>
    +getMessage() : String
  }
}

package org.zerhusen.security {
  class SecurityUtilsTest {
    +getCurrentUsername() : void
    +getCurrentUsernameForNoAuthenticationInContext() : void
  }
  class JwtAuthenticationEntryPoint {
    +commence() : void
  }
  class UserModelDetailsService {
    -log : Logger
    -userRepository : UserRepository
    -login : String
    +loadUserByUsername() : UserDetails
  }
  class JwtAccessDeniedHandler {
    +handle() : void
  }
  class SecurityUtils {
    -LOG : Logger
    -authentication : Authentication
    +getCurrentUsername() : Optional<String>
  }
  class UserNotActivatedException {
    -serialVersionUID : long
  }
}

package org.zerhusen.security.jwt {
  class JWTConfigurer {
    -tokenProvider : TokenProvider
    +configure() : void
  }
  class JWTFilter {
    -LOG : Logger
    -AUTHORIZATION_HEADER : String
    -tokenProvider : TokenProvider
    +doFilter() : void
  }
  class TokenProvider {
    -log : Logger
    -AUTHORITIES_KEY : String
    -base64Secret : String
    -tokenValidityInMilliseconds : long
    -tokenValidityInMillisecondsForRememberMe : long
    -key : Key
    +afterPropertiesSet() : void
    +createToken() : String
    +getAuthentication() : Authentication
    +validateToken() : boolean
  }
}

package org.zerhusen.security.model {
  class User <<Entity>> {
    -id : Long
    -username : String
    -password : String
    -firstname : String
    -lastname : String
    -email : String
    -activated : boolean
    -authorities : Set<Authority>
    +getId() : Long
    +setId() : void
    +getUsername() : String
    +setUsername() : void
    +getPassword() : String
    +setPassword() : void
    +getFirstname() : String
    +setFirstname() : void
  }
  class Authority <<Entity>> {
    -name : String
    +getName() : String
    +setName() : void
  }
}

package org.zerhusen.security.repository {
  interface AuthorityRepository {
  }
  interface UserRepository {
  }
}

package org.zerhusen.security.rest {
  class UserRestControllerTest {
    -token : String
    +setUp() : void
    +getActualUserForUserWithToken() : void
    +getActualUserForUserWithoutToken() : void
  }
  class AuthenticationRestControllerTest {
    +successfulAuthenticationWithUser() : void
    +successfulAuthenticationWithAdmin() : void
    +unsuccessfulAuthenticationWithDisabled() : void
    +unsuccessfulAuthenticationWithWrongPassword() : void
    +unsuccessfulAuthenticationWithNotExistingUser() : void
  }
  class UserRestController <<Controller>> {
    -userService : UserService
    +getActualUser() : ResponseEntity<User>
  }
  class AuthenticationRestController <<Controller>> {
    -tokenProvider : TokenProvider
    -authenticationManagerBuilder : AuthenticationManagerBuilder
    -idToken : String
    +authorize() : ResponseEntity<JWTToken>
  }
}

package org.zerhusen.security.rest.dto {
  class LoginDto {
    -username : String
    -password : String
    -rememberMe : Boolean
    +getUsername() : String
    +setUsername() : void
    +getPassword() : String
    +setPassword() : void
    +isRememberMe() : Boolean
    +setRememberMe() : void
  }
}

package org.zerhusen.security.service {
  class UserService <<Service>> {
    -userRepository : UserRepository
    +getUserWithAuthorities() : Optional<User>
  }
}

package org.zerhusen.util {
  class LogInUtils {
    -OBJECT_MAPPER : ObjectMapper
    -idToken : String
    +getTokenForLogin() : String
    +setIdToken() : void
    +getIdToken() : String
  }
  class AbstractRestControllerTest {
    -mockMvc : MockMvc
    +setUp() : void
    +getMockMvc() : MockMvc
  }
}

' --- Relatii ---
UserRestControllerTest --|> AbstractRestControllerTest
UserRestControllerTest --> AbstractRestControllerTest
AuthenticationRestControllerTest --|> AbstractRestControllerTest
AuthenticationRestControllerTest --> AbstractRestControllerTest
PersonRestControllerTest --|> AbstractRestControllerTest
PersonRestControllerTest --> AbstractRestControllerTest
AdminProtectedRestControllerTest --|> AbstractRestControllerTest
AdminProtectedRestControllerTest --> AbstractRestControllerTest
WebSecurityConfig --> JwtAccessDeniedHandler
WebSecurityConfig --> JwtAuthenticationEntryPoint
WebSecurityConfig --> JWTConfigurer
WebSecurityConfig --> TokenProvider
UserModelDetailsService --> User
UserModelDetailsService --> UserRepository
TokenProvider --> User
AuthorityRepository --> Authority
UserRepository --> User
UserService --> SecurityUtils
UserService --> User
UserService --> UserRepository
UserRestController --> User
UserRestController --> UserService
AuthenticationRestController --> LoginDto
AuthenticationRestController --> JWTFilter
AuthenticationRestController --> TokenProvider

@enduml