@startuml

package io.tpd.kafkaexample {
  class KafkaExampleApplicationTests {
    +contextLoads() : void
  }
  class HelloKafkaController <<Controller>> {
    -logger : Logger
    -topicName : String
    -messagesPerRequest : int
    -latch : CountDownLatch
    -topicName : String
    -messagesPerRequest : int
    +hello() : String
    +listenAsObject() : void
    +listenasString() : void
    +listenAsByteArray() : void
  }
  class KafkaExampleApplication {
    -kafkaProperties : KafkaProperties
    -topicName : String
    -jsonDeserializer : JsonDeserializer<Object>
    +main() : void
    +adviceTopic() : NewTopic
  }
}

' --- Relatii ---

@enduml