@startuml

  class MavenWrapperDownloader {
    -WRAPPER_VERSION : String
    -DEFAULT_DOWNLOAD_URL : String
    -MAVEN_WRAPPER_PROPERTIES_PATH : String
    -MAVEN_WRAPPER_JAR_PATH : String
    -PROPERTY_NAME_WRAPPER_URL : String
    +main() : void
    +getPasswordAuthentication() : PasswordAuthentication
  }

package ink.markidea.note {
  class NoteApplicationTests {
  }
  class NoteApplication {
    +main() : void
  }
}

package ink.markidea.note.constant {
  interface UserConstant {
  }
  interface RegisterConstant {
  }
}

package ink.markidea.note.context.config {
  class InterceptorConfig {
    -authorityInterceptor : HandlerInterceptor
    -httpRequestInterceptor : HandlerInterceptor
    -adminUserInterceptor : HandlerInterceptor
    +addInterceptors() : void
  }
  class CacheConfig {
    -HOUR_DURATION_IN_NANO_SECONDS : long
    -fileService : IFileService
    -articleService : IArticleService
    -notesDir : String
    +expireAfterCreate() : long
    +expireAfterUpdate() : long
    +expireAfterRead() : long
    +setTokenExpireTimeInHour() : void
    +setEnvironment() : void
  }
  class ContextPropertyLoader {
    +postProcessEnvironment() : void
    +getOrder() : int
  }
}

package ink.markidea.note.context.filter {
  class CorsFilter {
    +doFilter() : void
  }
}

package ink.markidea.note.context.interceptor {
  class AuthorityInterceptor {
    -userService : IUserService
    +preHandle() : boolean
  }
  class GlobalExceptionHandler {
    +handleException() : ServerResponse
    +handleNullException() : ServerResponse
    +handleIllegalArgs() : ServerResponse
    +handleNoAuthority() : ServerResponse
    +handlePromptException() : ServerResponse
  }
  class HttpRequestInterceptor {
    +preHandle() : boolean
    +postHandle() : void
  }
  class AdminUserInterceptor {
    -userService : IUserService
    +preHandle() : boolean
  }
}

package ink.markidea.note.context.task {
  class NoteTimer {
    -userRepository : UserRepository
    -notesDir : String
    -sshKeysDir : String
    -username : String
    -privateKeyPath : String
    -remoteRepoUrl : String
    -localRepoPath : String
    +pushLocalChangesToRemote() : void
    +onApplicationEvent() : void
    +checkPushTaskStatus() : Boolean
    +run() : void
  }
}

package ink.markidea.note.controller {
  class AdminController <<Controller>> {
    -adminService : IAdminService
    -userService : IUserService
    +pullWebsiteConfig() : ServerResponse<WebsiteConfigDto>
    +updateWebsiteConfig() : ServerResponse
    +listUser() : ServerResponse<Page<UserVo>>
  }
  class NoteController <<Controller>> {
    -noteService : INoteService
    +saveNote() : ServerResponse
    +searchNote() : ServerResponse<List<NoteVo>>
    +getNotebooks() : ServerResponse<List<NotebookVo>>
    +getNotes() : ServerResponse<List<NoteVo>>
    +getNote() : ServerResponse<String>
    +getNoteHistory() : ServerResponse<List<NoteVersionVo>>
    +createNotebook() : ServerResponse
    +copyOrMoveNote() : ServerResponse
  }
  class ArticleController <<Controller>> {
  }
  class DelNoteController <<Controller>> {
    -noteService : INoteService
    +getDelNotes() : ServerResponse<List<DeletedNoteVo>>
    +clearAllDelNotes() : ServerResponse
    +clearDelNote() : ServerResponse
  }
  class FileController <<Controller>> {
    -fileService : IFileService
    +upload() : ServerResponse<String>
    +upload() : VditorFileUploadResponse
    +listUserFiles() : ServerResponse<UserFileVo>
    +batchDelete() : ServerResponse<Void>
  }
  class HistoryController <<Controller>> {
    -noteService : INoteService
    +queryHistoryContent() : ServerResponse<String>
  }
  class UserController <<Controller>> {
    -adminService : IAdminService
    -userService : IUserService
    +login() : ServerResponse<UserVo>
    +validate() : ServerResponse
    +register() : ServerResponse<UserVo>
    +changePassword() : ServerResponse
    +logout() : ServerResponse
    +setRemoteRepoUrl() : ServerResponse
    +getRemoteRepoUrl() : ServerResponse
    +genSshKeys() : ServerResponse<String>
  }
}

package ink.markidea.note.dao {
  interface ArticleRepository <<Repository>> {
  }
  interface DelNoteRepository <<Repository>> {
  }
  interface UserRepository <<Repository>> {
  }
}

package ink.markidea.note.db.sqlite {
  class SQLiteMetadataBuilderInitializer {
    -logger : Logger
    -dialect : SQLiteDialect
    -resolver : DialectResolver
    +contribute() : void
    +resolveDialect() : Dialect
  }
  class SQLiteDialectIdentityColumnSupport {
    +supportsIdentityColumns() : boolean
    +supportsInsertSelectIdentity() : boolean
    +hasDataTypeInIdentityColumn() : boolean
    +appendIdentitySelectToInsert() : String
    +getIdentitySelectString() : String
    +getIdentityColumnString() : String
  }
  class SQLiteDialect {
    -uniqueDelegate : UniqueDelegate
    -IDENTITY_COLUMN_SUPPORT : SQLiteDialectIdentityColumnSupport
    -LIMIT_HANDLER : AbstractLimitHandler
    -hasOffset : boolean
    -SQLITE_BUSY : int
    -SQLITE_LOCKED : int
    -SQLITE_IOERR : int
    -SQLITE_CORRUPT : int
    -SQLITE_NOTFOUND : int
    -SQLITE_FULL : int
    +resolveBothSpaceTrimFunction() : SQLFunction
    +resolveBothSpaceTrimFromFunction() : SQLFunction
    +resolveLeadingSpaceTrimFunction() : SQLFunction
    +resolveTrailingSpaceTrimFunction() : SQLFunction
    +resolveBothTrimFunction() : SQLFunction
    +resolveLeadingTrimFunction() : SQLFunction
    +resolveTrailingTrimFunction() : SQLFunction
    +getCastTypeName() : String
  }
}

package ink.markidea.note.entity {
  class DelNoteDo <<Entity>> {
    -id : Integer
    -title : String
    -notebook : String
    -content : String
    -lastRef : String
    -username : String
  }
  class ArticleDo <<Entity>> {
    -id : Integer
    -notebookName : String
    -articleTitle : String
    -noteTitle : String
    -username : String
  }
  class UserDo <<Entity>> {
    -id : Integer
    -username : String
    -password : String
    -status : Integer
    -remoteRepository : String
    -push : boolean
    -editorConfig : String
  }
}

package ink.markidea.note.entity.dto {
  class NotePreviewInfo {
  }
  class WebsiteConfigDto {
    -websiteTitle : String
    -registerStrategy : Integer
    -maxUploadFileSize : String
    -tokenExpireTimeInHour : int
  }
  class EditorConfigDto {
    -customStylePath : String
    -enableCustomStyle : boolean
    -enableCounter : boolean
    -enableOutline : boolean
    -editMode : String
    -enableHighLight : boolean
    -codeStyle : String
    -enableLineNumber : boolean
    -outlinePosition : String
  }
  class UserNoteKey {
    -username : String
    -notebookName : String
    -noteTitle : String
  }
}

package ink.markidea.note.entity.exception {
  class NoAuthorityException {
  }
  class PromptException {
  }
}

package ink.markidea.note.entity.req {
  class EditorConfigReq {
  }
  class NoteSearchRequest {
  }
  class RemoteRepoRequest {
    -remoteRepoUrl : String
  }
  class QueryHistoryContentReq {
    -notebookName : String
    -noteTitle : String
    -versionRef : String
  }
  class UserRequest {
    -username : String
    -password : String
    -token : String
    -newPassword : String
  }
  class ArticleCreateReq {
    -notebookName : String
    -noteTitle : String
  }
  class BatchFileDeleteRequest {
    -username : String
    -fileNames : List<String>
  }
  class BatchDelArticleReq {
    -articleList : List<ArticleVo>
  }
  class NoteRequest {
    -delNoteId : Integer
    -noteTitle : String
    -notebookName : String
    -content : String
    -lastRef : String
    -versionRef : String
    -srcNotebook : String
    -srcTitle : String
    -move : Boolean
    -tmpSave : boolean
  }
  class WebsiteConfigReq {
  }
}

package ink.markidea.note.entity.resp {
  class VditorFileUploadResponse {
    -msg : String
    -code : int
  }
  class ServerResponse {
    -code : Integer
    -msg : String
    -data : T
    -code : int
    +buildSuccessResponse() : ServerResponse
    +buildErrorResponse() : ServerResponse
    +isSuccess() : boolean
  }
}

package ink.markidea.note.entity.vo {
  class NoteVo {
    -STATUS_PRIVATE : int
    -STATUS_PUBLIC : int
    -STATUS_TMP_SAVED : int
    -title : String
    -status : int
    -content : String
    -previewContent : String
    -lastModifiedTime : String
    -notebookName : String
    -searchCount : int
  }
  class DeletedNoteVo {
    -id : Integer
    -title : String
    -notebook : String
    -lastRef : String
    -username : String
    -content : String
  }
  class NoteVersionVo {
    -ref : String
    -date : String
    -msg : String
  }
  class UserVo {
    -username : String
    -token : String
    -type : int
    -editorConfig : EditorConfigDto
  }
  class NotebookVo {
    -notebookName : String
    -noteList : List<NoteVo>
  }
  class UserFileVo {
  }
  class ArticleVo {
    -articleId : Integer
    -notebookName : String
    -noteTitle : String
    -content : String
    -previewContent : String
  }
}

package ink.markidea.note.service {
  interface IUserService {
  }
  interface IAdminService {
  }
  interface IFileService {
  }
  interface IArticleService {
  }
  interface INoteService {
  }
}

package ink.markidea.note.service.impl {
  class LocalFileServiceImpl <<Service>> {
    -filePath : String
    -DIR_PREFIX : String
    +upload() : String
    +uploadFile() : File
    +writeStringToFile() : boolean
    +createTmpEmptyDir() : File
    +getContentFromFile() : String
    +deleteFile() : void
    +batchDelete() : void
    +listUserFiles() : UserFileVo
  }
  class ArticleService <<Service>> {
    +findByNotebookAndNoteTitle() : ArticleDo
    +findByArticleIdAndUsername() : ArticleVo
    +listArticles() : Page<ArticleVo>
    +listArticles() : Page<ArticleVo>
    +findOrCreateArticle() : ArticleVo
    +moveArticle() : void
    +deleteArticle() : void
    +batchDeleteArticle() : void
  }
  class UserServiceImpl <<Service>> {
    -adminUsername : String
    -adminPassword : String
    -userRepository : UserRepository
    -TOKEN_PREFIX : String
    +login() : ServerResponse<UserVo>
    +validate() : ServerResponse
    +checkAdminUser() : boolean
    +logout() : ServerResponse
    +register() : ServerResponse<UserVo>
    +changePassword() : ServerResponse
    +setRegisterStrategy() : void
    +getEditorConfig() : EditorConfigDto
  }
  class NoteServiceImpl <<Service>> {
    -notesDir : String
    -fileService : IFileService
    -delNoteRepository : DelNoteRepository
    -NOTEBOOK_FLAG_FILE : String
    -articleService : IArticleService
    +listNotebooks() : ServerResponse<List<String>>
    +listNotes() : ServerResponse<List<NoteVo>>
    +search() : ServerResponse<List<NoteVo>>
    +createNotebook() : ServerResponse
    +createNote() : ServerResponse
    +saveNote() : ServerResponse
    +tmpSaveNote() : void
    +delTmpSavedNote() : void
  }
  class AdminServiceImpl <<Service>> {
    -notesDir : String
    -frontDir : String
    -noteTimer : NoteTimer
    -sshKeysDir : String
    -configDir : String
    -userRepository : UserRepository
    -userService : IUserService
    +setRemoteRepoUrl() : ServerResponse
    +stopPushToRemoteRepo() : ServerResponse
    +generateSshKey() : ServerResponse<String>
    +checkPushTaskStatus() : ServerResponse
    +startPushToRemoteRepo() : ServerResponse
    +getRemoteRepoUrl() : ServerResponse
    +pullFromRemote() : ServerResponse
    +getWebsiteConfig() : WebsiteConfigDto
  }
}

package ink.markidea.note.util {
  class JsonUtil {
    -objectMapper : ObjectMapper
  }
  class GitUtil {
    -DEFAULT_REMOTE_ALIAS_NAME : String
    -DEFAULT_LOCAL_BRANCH_NAME : String
    -DEFAULT_REMOTE_BRANCH_NAME : String
    -GIT_FLAG_FILE : String
    -privateKeyPath : String
    -changeType : Integer
    -fileName : String
    -oldFileName : String
    -newFileName : String
    -prevRef : String
    +getOrInitGit() : Git
    +getOrInitGit() : Git
    +getNoteHistory() : List<NoteVersionVo>
    +addAndCommit() : boolean
    +mvAndCommit() : boolean
    +rmAndCommit() : boolean
    +resetAndCommit() : boolean
    +recoverDeletedFile() : void
  }
  class SshUtil {
    +genAndStoreKeyPair() : String
    +genAndStoreKeyPair() : String
  }
  class FileUtil {
    -KB_LIMIT : long
    -MB_LIMIT : long
    -GB_LIMIT : long
    -TB_LIMIT : long
    +readFileAsString() : String
    +writeStringToFile() : boolean
    +deleteFileOrDirectory() : void
    +deleteChildFiles() : void
    +copyDirectory() : void
    +unzip() : void
    +unzip() : void
    +getFileSizeStr() : String
  }
  class MD5Util {
    -PASSWORD_SALT : String
    -HEX_DIGITS : String[]
    +MD5EncodeUtf8() : String
  }
  class DateTimeUtil {
    -DEFAULT_FORMAT : String
    +strToDate() : Date
    +dateToStr() : String
    +strToDate() : Date
    +dateToStr() : String
  }
  class ThreadLocalUtil {
    -threadLocalUsername : ThreadLocal<String>
    +setUsername() : void
    +getUsername() : String
    +clearUsername() : void
  }
}

' --- Relatii ---
CacheConfig --> ArticleDo
CacheConfig --> NotePreviewInfo
CacheConfig --> UserNoteKey
CacheConfig --> UserVo
CacheConfig --> IArticleService
CacheConfig --> IFileService
ContextPropertyLoader --> WebsiteConfigDto
ContextPropertyLoader --> FileUtil
ContextPropertyLoader --> JsonUtil
NoteTimer --> UserRepository
NoteTimer --> UserDo
NoteTimer --> GitUtil
AuthorityInterceptor --> NoAuthorityException
AuthorityInterceptor --> IUserService
GlobalExceptionHandler --> NoAuthorityException
GlobalExceptionHandler --> PromptException
GlobalExceptionHandler --> ServerResponse
HttpRequestInterceptor --> ThreadLocalUtil
AdminUserInterceptor --> NoAuthorityException
AdminUserInterceptor --> IUserService
GitUtil --> PromptException
GitUtil --> NoteVersionVo
UserDo --> UserConstant
UserVo --> UserConstant
UserVo --> EditorConfigDto
EditorConfigReq --|> EditorConfigDto
EditorConfigReq --> EditorConfigDto
BatchDelArticleReq --> ArticleVo
WebsiteConfigReq --|> WebsiteConfigDto
WebsiteConfigReq --> WebsiteConfigDto
ArticleRepository --> ArticleDo
DelNoteRepository --> DelNoteDo
UserRepository --> UserDo
AdminController --> WebsiteConfigDto
AdminController --> RemoteRepoRequest
AdminController --> WebsiteConfigReq
AdminController --> ServerResponse
AdminController --> UserVo
AdminController --> IAdminService
AdminController --> IFileService
AdminController --> INoteService
AdminController --> IUserService
AdminController --> FileUtil
NoteController --> NoteRequest
NoteController --> NoteSearchRequest
NoteController --> ServerResponse
NoteController --> NoteVersionVo
NoteController --> NoteVo
NoteController --> NotebookVo
NoteController --> INoteService
ArticleController --> ArticleCreateReq
ArticleController --> BatchDelArticleReq
ArticleController --> ServerResponse
ArticleController --> ArticleVo
ArticleController --> IArticleService
ArticleController --> INoteService
DelNoteController --> ServerResponse
DelNoteController --> DeletedNoteVo
DelNoteController --> INoteService
FileController --> BatchFileDeleteRequest
FileController --> ServerResponse
FileController --> VditorFileUploadResponse
FileController --> UserFileVo
FileController --> IFileService
HistoryController --> QueryHistoryContentReq
HistoryController --> ServerResponse
HistoryController --> INoteService
UserController --> EditorConfigDto
UserController --> EditorConfigReq
UserController --> RemoteRepoRequest
UserController --> UserRequest
UserController --> ServerResponse
UserController --> UserVo
UserController --> IAdminService
UserController --> IUserService
IUserService --> UserDo
IUserService --> EditorConfigDto
IUserService --> EditorConfigReq
IUserService --> ServerResponse
IUserService --> UserVo
IAdminService --> WebsiteConfigDto
IAdminService --> WebsiteConfigReq
IAdminService --> ServerResponse
IFileService --> UserFileVo
IArticleService --> ArticleDo
IArticleService --> ArticleVo
INoteService --> ServerResponse
INoteService --> DeletedNoteVo
INoteService --> NoteVersionVo
INoteService --> NoteVo
LocalFileServiceImpl ..|> IFileService
LocalFileServiceImpl --> PromptException
LocalFileServiceImpl --> UserFileVo
LocalFileServiceImpl --> IFileService
LocalFileServiceImpl --> DateTimeUtil
LocalFileServiceImpl --> FileUtil
LocalFileServiceImpl --> ThreadLocalUtil
ArticleService ..|> IArticleService
ArticleService --> ArticleRepository
ArticleService --> ArticleDo
ArticleService --> NotePreviewInfo
ArticleService --> UserNoteKey
ArticleService --> ArticleVo
ArticleService --> IArticleService
ArticleService --> ThreadLocalUtil
UserServiceImpl ..|> IUserService
UserServiceImpl --> RegisterConstant
UserServiceImpl --> UserConstant
UserServiceImpl --> UserRepository
UserServiceImpl --> UserDo
UserServiceImpl --> EditorConfigDto
UserServiceImpl --> NoAuthorityException
UserServiceImpl --> PromptException
UserServiceImpl --> EditorConfigReq
UserServiceImpl --> ServerResponse
UserServiceImpl --> UserVo
UserServiceImpl --> IUserService
UserServiceImpl --> JsonUtil
UserServiceImpl --> MD5Util
UserServiceImpl --> ThreadLocalUtil
NoteServiceImpl ..|> INoteService
NoteServiceImpl --> DelNoteRepository
NoteServiceImpl --> DelNoteDo
NoteServiceImpl --> NotePreviewInfo
NoteServiceImpl --> UserNoteKey
NoteServiceImpl --> PromptException
NoteServiceImpl --> ServerResponse
NoteServiceImpl --> DeletedNoteVo
NoteServiceImpl --> NoteVersionVo
NoteServiceImpl --> NoteVo
NoteServiceImpl --> IArticleService
NoteServiceImpl --> IFileService
NoteServiceImpl --> INoteService
NoteServiceImpl --> DateTimeUtil
NoteServiceImpl --> FileUtil
NoteServiceImpl --> GitUtil
NoteServiceImpl --> ThreadLocalUtil
AdminServiceImpl ..|> IAdminService
AdminServiceImpl --> RegisterConstant
AdminServiceImpl --> CacheConfig
AdminServiceImpl --> NoteTimer
AdminServiceImpl --> UserRepository
AdminServiceImpl --> WebsiteConfigDto
AdminServiceImpl --> PromptException
AdminServiceImpl --> WebsiteConfigReq
AdminServiceImpl --> ServerResponse
AdminServiceImpl --> IAdminService
AdminServiceImpl --> IUserService

@enduml