@startuml

package org.springframework.integration.microservices.circuitbreaker {
  class CircuitBreakerApplicationTests {
  }
  class CircuitBreakerApplication {
    -retryTemplateBuilder : RetryTemplateBuilder
    -retryAdvice : RequestHandlerRetryAdvice
    -circuitBreakerAdvice : RequestHandlerCircuitBreakerAdvice
    -service : MessageHandler
    +main() : void
    +setThreshold() : void
    +setHalfOpenAfter() : void
    +setRetryPolicy() : void
    +setBackOffPolicy() : void
    +setRecoveryChannel() : void
  }
}

package org.springframework.integration.microservices.distributedtracing {
  class DistributedTracingApplicationTests {
    -LOCAL_STACK_CONTAINER : LocalStackContainer
  }
  class DistributedTracingApplication {
    -LOGGER : Log
    +main() : void
    +httpSupplierFlow() : Publisher<Message<String>>
    +kinesisSupplier() : Supplier<Flux<Message<String>>>
    +consumerFlow() : IntegrationFlow
    +jdbcFlow() : IntegrationFlow
    +jmsFlow() : IntegrationFlow
  }
}

package org.springframework.integration.microservices.framer {
  class FramerApplicationTests {
  }
  class FramerApplication {
    -messageGroupStore : MessageGroupStore
    -messageSequence : AtomicLong
    +main() : void
    +slidingWindows() : List<MessageBuilder<Object>>
  }
}

package org.springframework.integration.microservices.mrpc {
  class MrpcApplicationTests {
    -RABBITMQ : RabbitMQContainer
  }
  class MrpcApplication {
    +main() : void
  }
}

package org.springframework.integration.microservices.normalizer {
  class NormalizerApplicationTests {
  }
  class CreditCardTransaction {
    -id : Long
    -cardNumber : String
    -transactionDate : Date
    -amount : BigDecimal
    -merchant : String
    +getId() : Long
    +setId() : void
    +getCardNumber() : String
    +setCardNumber() : void
    +getTransactionDate() : Date
    +setTransactionDate() : void
    +getAmount() : BigDecimal
    +setAmount() : void
  }
  class NormalizerApplication {
    -objectMapper : ObjectMapper
    -jaxb2Marshaller : Jaxb2Marshaller
    +main() : void
    +setBeanClassLoader() : void
    +afterPropertiesSet() : void
  }
}

package org.springframework.integration.microservices.outbox {
  class OutboxApplicationTests {
    -consumedOrders : BlockingQueue<ShoppingOrder>
  }
  class ShoppingOrder <<Entity>> {
    -id : long
    -name : String
    -amount : BigDecimal
    +getId() : long
    +setId() : void
    +getName() : String
    +setName() : void
    +getAmount() : BigDecimal
    +setAmount() : void
  }
  class OutboxApplication {
    -businessDataHandler : MessageHandler
    -messagePublisherHandler : MessageHandler
    -channelMessageStore : ChannelMessageStore
    +main() : void
  }
}

' --- Relatii ---

@enduml