@startuml

package cn.attackme.myuploader {
  class MyUploaderApplicationTests {
    +contextLoads() : void
  }
  class MyUploaderApplication {
    +main() : void
  }
}

package cn.attackme.myuploader.config {
  class UploadConfig {
    -path : String
    +setPath() : void
  }
  class LogAspect {
    +logPoint() : void
  }
}

package cn.attackme.myuploader.controller {
  class BigFileUploadController <<Controller>> {
    -fileService : FileService
    +upload() : void
  }
  class TestExceptionController <<Controller>> {
    +aspect() : int
    +util() : void
  }
  class FileUploadController <<Controller>> {
    -fileService : FileService
    +upload() : void
  }
  class QuickUploadController <<Controller>> {
    -fileService : FileService
    +upload() : boolean
  }
}

package cn.attackme.myuploader.dao {
  class FileDaoTests {
    -fileDao : FileDao
    -testFile : File
    +generateFile() : void
    +testSaveSuccess() : void
    +testSaveExceptionByNameIsNull() : void
    +testUpdateSuccess() : void
    +testUpdateNoExceptionByMd5IsNull() : void
    +testGetByIdSuccess() : void
    +testGetByNotExitsIdReturnNull() : void
    +testDeleteByIdSuccess() : void
  }
  interface FileDao {
  }
}

package cn.attackme.myuploader.model {
  class File {
    -serialVersionUID : long
    -id : Long
    -name : String
    -md5 : String
    -path : String
    -uploadTime : Date
  }
}

package cn.attackme.myuploader.service {
  class FileService <<Service>> {
    -fileDao : FileDao
    +upload() : void
    +uploadWithBlock() : void
    +checkMd5() : boolean
  }
}

package cn.attackme.myuploader.utils {
  class FileUtils {
    +write() : void
    +writeWithBlok() : void
    +generateFileName() : String
  }
  class UploadUtils {
    +isUploaded() : boolean
    +addChunk() : void
    +removeKey() : void
    +getFileName() : String
  }
  class LogUtils {
    +logToFile() : void
    +logToFile() : void
  }
}

' --- Relatii ---
FileDaoTests --> File
FileDao --> File
BigFileUploadController --> FileService
FileUploadController --> FileService
QuickUploadController --> FileService
FileService --> UploadConfig
FileService --> FileDao
FileService --> File
FileService --> FileUtils

@enduml