@startuml

  class MavenWrapperDownloader {
    -WRAPPER_VERSION : String
    -DEFAULT_DOWNLOAD_URL : String
    -MAVEN_WRAPPER_PROPERTIES_PATH : String
    -MAVEN_WRAPPER_JAR_PATH : String
    -PROPERTY_NAME_WRAPPER_URL : String
    +main() : void
    +getPasswordAuthentication() : PasswordAuthentication
  }
  class MavenWrapperDownloader {
    -WRAPPER_VERSION : String
    -DEFAULT_DOWNLOAD_URL : String
    -MAVEN_WRAPPER_PROPERTIES_PATH : String
    -MAVEN_WRAPPER_JAR_PATH : String
    -PROPERTY_NAME_WRAPPER_URL : String
    +main() : void
    +getPasswordAuthentication() : PasswordAuthentication
  }
  class MavenWrapperDownloader {
    -WRAPPER_VERSION : String
    -DEFAULT_DOWNLOAD_URL : String
    -MAVEN_WRAPPER_PROPERTIES_PATH : String
    -MAVEN_WRAPPER_JAR_PATH : String
    -PROPERTY_NAME_WRAPPER_URL : String
    +main() : void
    +getPasswordAuthentication() : PasswordAuthentication
  }
  class MavenWrapperDownloader {
    -WRAPPER_VERSION : String
    -DEFAULT_DOWNLOAD_URL : String
    -MAVEN_WRAPPER_PROPERTIES_PATH : String
    -MAVEN_WRAPPER_JAR_PATH : String
    -PROPERTY_NAME_WRAPPER_URL : String
    +main() : void
    +getPasswordAuthentication() : PasswordAuthentication
  }
  class MavenWrapperDownloader {
    -WRAPPER_VERSION : String
    -DEFAULT_DOWNLOAD_URL : String
    -MAVEN_WRAPPER_PROPERTIES_PATH : String
    -MAVEN_WRAPPER_JAR_PATH : String
    -PROPERTY_NAME_WRAPPER_URL : String
    +main() : void
    +getPasswordAuthentication() : PasswordAuthentication
  }
  class MavenWrapperDownloader {
    -WRAPPER_VERSION : String
    -DEFAULT_DOWNLOAD_URL : String
    -MAVEN_WRAPPER_PROPERTIES_PATH : String
    -MAVEN_WRAPPER_JAR_PATH : String
    -PROPERTY_NAME_WRAPPER_URL : String
    +main() : void
    +getPasswordAuthentication() : PasswordAuthentication
  }
  class MavenWrapperDownloader {
    -WRAPPER_VERSION : String
    -DEFAULT_DOWNLOAD_URL : String
    -MAVEN_WRAPPER_PROPERTIES_PATH : String
    -MAVEN_WRAPPER_JAR_PATH : String
    -PROPERTY_NAME_WRAPPER_URL : String
    +main() : void
    +getPasswordAuthentication() : PasswordAuthentication
  }

package com.soares.microservice.api.config {
  class MicroserviceConfigApplicationTests {
  }
  class MicroserviceConfigApplication {
    +main() : void
  }
}

package com.soares.microservice.api.gateway {
  class ApiGatewayApplicationTests {
  }
  class ApiGatewayApplication {
    +main() : void
  }
}

package com.soares.microservice.api.gateway.security {
  class WebSecurity {
    -env : Environment
    +configure() : void
  }
  class AuthorizationFilter {
    +doFilterInternal() : void
  }
}

package com.soares.microservice.category.api {
  class CategoryMicroserviceApplicationTests {
  }
  class CategoryMicroserviceApplication {
    +main() : void
    +bCryptPasswordEncoder() : BCryptPasswordEncoder
  }
}

package com.soares.microservice.category.api.controller {
  class CategoryController <<Controller>> {
    -service : ICategoryService
    +insert() : ResponseEntity<CategoryDTO>
    +getById() : ResponseEntity<CategoryDTO>
    +getAll() : ResponseEntity<List<CategoryDTO>>
    +update() : ResponseEntity<CategoryDTO>
    +delete() : ResponseEntity<Void>
  }
}

package com.soares.microservice.category.api.repository {
  class for {
  }
}

package com.soares.microservice.category.api.request {
  class CategoryCreateRequestModel {
    -name : String
    +getName() : String
    +setName() : void
  }
  class CategoryUpdateRequestModel {
    -id : String
    +getId() : String
    +setId() : void
  }
}

package com.soares.microservice.category.api.service {
  class CategoryServiceImpl <<Service>> {
    -repository : ICategoryJpaRepository
    +insert() : CategoryDTO
    +update() : CategoryDTO
    +findById() : CategoryDTO
    +getAll() : List<CategoryDTO>
    +delete() : void
  }
  interface ICategoryService <<Service>> {
    +insert() : CategoryDTO
    +update() : CategoryDTO
    +getAll() : List<CategoryDTO>
    +findById() : CategoryDTO
    +delete() : void
  }
}

package com.soares.microservice.commons {
  class AppTest {
    +suite() : Test
    +testApp() : void
  }
}

package com.soares.microservice.commons.dto {
  class CategoryDTO {
    -id : String
    -name : String
    -movies : List<MovieDTO>
    +getId() : String
    +setId() : void
    +getName() : String
    +setName() : void
    +getMovies() : List<MovieDTO>
    +setMovies() : void
  }
  class MovieDTO {
    -id : String
    -title : String
    -category : CategoryDTO
    +getId() : String
    +setId() : void
    +getTitle() : String
    +setTitle() : void
    +getCategory() : CategoryDTO
    +setCategory() : void
  }
}

package com.soares.microservice.commons.entity {
  class MovieEntity <<Entity>> {
    -serialVersionUID : long
    -id : String
    -title : String
    -category : CategoryEntity
    +getId() : String
    +setId() : void
    +getTitle() : String
    +setTitle() : void
    +getCategory() : CategoryEntity
    +setCategory() : void
  }
  class CategoryEntity <<Entity>> {
    -serialVersionUID : long
    -id : String
    -name : String
    -movies : List<MovieEntity>
    +getId() : String
    +setId() : void
    +getName() : String
    +setName() : void
    +getMovies() : List<MovieEntity>
    +setMovies() : void
    +getSerialversionuid() : long
  }
}

package com.soares.microservice.discovery {
  class EurekaServiceDiscoveryApplicationTests {
  }
  class EurekaServiceDiscoveryApplication {
    +main() : void
  }
  class WebSecurity {
    +configure() : void
  }
}

package com.soares.microservice.movie.api {
  class UserMicroserviceApplicationTests {
  }
  class MovieMicroserviceApplication {
    +main() : void
  }
}

package com.soares.microservice.movie.api.controller {
  class MovieController <<Controller>> {
    -service : IMovieService
    +insert() : ResponseEntity<MovieDTO>
    +getById() : ResponseEntity<MovieDTO>
    +getAll() : ResponseEntity<List<MovieDTO>>
    +update() : ResponseEntity<MovieDTO>
    +delete() : ResponseEntity<Void>
  }
}

package com.soares.microservice.movie.api.repository {
  class for {
  }
}

package com.soares.microservice.movie.api.request {
  class MovieUpdateRequestModel {
    -id : String
    +getId() : String
    +setId() : void
  }
  class MovieCreateRequestModel {
    -title : String
    -categoryId : String
    +getTitle() : String
    +setTitle() : void
    +getCategoryId() : String
    +setCategoryId() : void
  }
}

package com.soares.microservice.movie.api.service {
  interface IMovieService <<Service>> {
    +getAll() : List<MovieDTO>
    +findById() : MovieDTO
    +delete() : void
  }
  class MovieServiceImpl <<Service>> {
    -repository : IMovieJpaRepository
    +insert() : MovieDTO
    +update() : MovieDTO
    +findById() : MovieDTO
    +getAll() : List<MovieDTO>
    +delete() : void
  }
}

package com.soares.microservices.user.api {
  class UserMicroserviceApplicationTests {
  }
  class UserMicroserviceApplication {
    +main() : void
    +bCryptPasswordEncoder() : BCryptPasswordEncoder
  }
}

package com.soares.microservices.user.api.controller {
  class UserController <<Controller>> {
    -service : IUserService
    +insert() : ResponseEntity<UserDTO>
    +getById() : ResponseEntity<UserDTO>
  }
}

package com.soares.microservices.user.api.model.dto {
  class UserDTO {
    -serialVersionUID : long
    -id : String
    -firstName : String
    -lastName : String
    -email : String
    -password : String
    +getId() : String
    +setId() : void
    +getFirstName() : String
    +setFirstName() : void
    +getLastName() : String
    +setLastName() : void
    +getEmail() : String
    +setEmail() : void
  }
}

package com.soares.microservices.user.api.model.entity {
  class UserEntity {
    -serialVersionUID : long
    -id : String
    -firstName : String
    -lastName : String
    -email : String
    -encryptedPassword : String
    +getId() : String
    +setId() : void
    +getFirstName() : String
    +setFirstName() : void
    +getLastName() : String
    +setLastName() : void
    +getEmail() : String
    +setEmail() : void
  }
}

package com.soares.microservices.user.api.model.request {
  class UserCreateRequestModel {
    -firstName : String
    -lastName : String
    -email : String
    -password : String
    +getFirstName() : String
    +setFirstName() : void
    +getLastName() : String
    +setLastName() : void
    +getEmail() : String
    +setEmail() : void
    +getPassword() : String
    +setPassword() : void
  }
  class LoginRequestModel {
    -email : String
    -password : String
    +getEmail() : String
    +setEmail() : void
    +getPassword() : String
    +setPassword() : void
  }
}

package com.soares.microservices.user.api.repository {
  interface IUserJpaRepository {
  }
}

package com.soares.microservices.user.api.security {
  class WebSecurity {
    -userService : IUserService
    -env : Environment
    -encoder : BCryptPasswordEncoder
    +configure() : void
    +configure() : void
  }
  class AuthenticationFilter {
    -env : Environment
    +attemptAuthentication() : Authentication
    +successfulAuthentication() : void
  }
}

package com.soares.microservices.user.api.service {
  interface IUserService {
  }
  class UserServiceImpl <<Service>> {
    +insert() : UserDTO
    +loadUserByUsername() : UserDetails
    +findByEmail() : UserDTO
    +findById() : UserDTO
  }
}

' --- Relatii ---
IUserJpaRepository --> UserEntity
WebSecurity --> IUserService
AuthenticationFilter --> UserDTO
AuthenticationFilter --> LoginRequestModel
AuthenticationFilter --> IUserService
UserController --> UserDTO
UserController --> UserCreateRequestModel
UserController --> IUserService
IUserService --> UserDTO
UserServiceImpl ..|> IUserService
UserServiceImpl --> UserDTO
UserServiceImpl --> UserEntity
UserServiceImpl --> IUserJpaRepository
for --> MovieEntity
MovieController --> CategoryDTO
MovieController --> MovieDTO
MovieController --> MovieCreateRequestModel
MovieController --> MovieUpdateRequestModel
MovieController --> IMovieService
MovieUpdateRequestModel --|> MovieCreateRequestModel
IMovieService --> MovieDTO
MovieServiceImpl ..|> IMovieService
MovieServiceImpl --> MovieDTO
MovieServiceImpl --> MovieEntity
for --> CategoryEntity
CategoryController --> CategoryCreateRequestModel
CategoryController --> CategoryUpdateRequestModel
CategoryController --> ICategoryService
CategoryController --> CategoryDTO
CategoryUpdateRequestModel --|> CategoryCreateRequestModel
CategoryServiceImpl ..|> ICategoryService
CategoryServiceImpl --> CategoryDTO
CategoryServiceImpl --> CategoryEntity
ICategoryService --> CategoryDTO

@enduml