@startuml

package com.github.mkopylec.recaptcha {
  class TestApplication {
    +main() : void
    +cookieProcessorCustomizer() : WebServerFactoryCustomizer<TomcatServletWebServerFactory>
  }
  class Strings {
    -REMOTE_IP_ADDRESS : String
    -VALID_CAPTCHA_RESPONSE : String
    -INVALID_CAPTCHA_RESPONSE : String
    -VALID_SECRET : String
    -INVALID_SECRET : String
    -RESPONSE_DATA_MESSAGE : String
  }
  class RecaptchaProperties {
    -validation : Validation
    -security : Security
    -testing : Testing
    -secretKey : String
    -responseParameter : String
    -verificationUrl : String
    -timeout : Timeout
    -connect : Duration
    -read : Duration
    -write : Duration
    +getValidation() : Validation
    +setValidation() : void
    +getSecurity() : Security
    +setSecurity() : void
    +getTesting() : Testing
    +setTesting() : void
    +getSecretKey() : String
    +setSecretKey() : void
  }
}

package com.github.mkopylec.recaptcha.security {
  class AccessConfiguration {
    -enhancer : FormLoginConfigurerEnhancer
    +configure() : void
    +configure() : void
  }
  class ResponseData {
    -message : String
    +getMessage() : String
  }
  class SecurityController <<Controller>> {
    +getResponseData() : ResponseData
  }
  class RecaptchaAuthenticationFilter {
    -log : Logger
    -recaptchaValidator : RecaptchaValidator
    -recaptcha : RecaptchaProperties
    -failuresManager : LoginFailuresManager
    +attemptAuthentication() : Authentication
    +setAuthenticationSuccessHandler() : void
    +setAuthenticationFailureHandler() : void
    +setUsernameParameter() : void
    +afterPropertiesSet() : void
    +obtainRecaptchaResponse() : String
  }
  class RecaptchaAuthenticationException {
    -errorCodes : List<ErrorCode>
    +getErrorCodes() : List<ErrorCode>
  }
  class SecurityConfiguration {
    -recaptcha : RecaptchaProperties
    +formLoginConfigurerEnhancer() : FormLoginConfigurerEnhancer
    +loginFailuresManager() : LoginFailuresManager
    +loginFailuresCountingHandler() : LoginFailuresCountingHandler
    +loginFailuresClearingHandler() : LoginFailuresClearingHandler
    +recaptchaAwareRedirectStrategy() : RecaptchaAwareRedirectStrategy
  }
}

package com.github.mkopylec.recaptcha.security.login {
  class LoginFailuresClearingHandler {
    -failuresManager : LoginFailuresManager
    +onAuthenticationSuccess() : void
  }
  class RecaptchaAwareRedirectStrategy {
    -RECAPTCHA_ERROR_PARAMETER_NAME : String
    -SHOW_RECAPTCHA_QUERY_PARAM : String
    -failuresManager : LoginFailuresManager
    +sendRedirect() : void
    +getAuthenticationException() : AuthenticationException
  }
  class InMemoryLoginFailuresManager {
    -log : Logger
    +addLoginFailure() : void
    +getLoginFailuresCount() : int
    +clearLoginFailures() : void
  }
  class LoginFailuresCountingHandler {
    -failuresManager : LoginFailuresManager
    +onAuthenticationFailure() : void
    +setRedirectStrategy() : void
  }
  class FormLoginConfigurerEnhancer {
    -DEFAULT_USERNAME_PARAMETER : String
    -AUTHENTICATION_PROCESSING_FILTER_FIELD : String
    -authenticationFilter : RecaptchaAuthenticationFilter
    -successHandler : LoginFailuresClearingHandler
    -failureHandler : LoginFailuresCountingHandler
    +addRecaptchaSupport() : FormLoginConfigurer<HttpSecurity>
  }
  class LoginFailuresManager {
    -log : Logger
    -security : Security
    -usernameParameter : String
    +addLoginFailure() : void
    +getLoginFailuresCount() : int
    +clearLoginFailures() : void
    +isRecaptchaRequired() : boolean
    +setUsernameParameter() : void
    +getUsername() : String
  }
}

package com.github.mkopylec.recaptcha.testing {
  class TestingController <<Controller>> {
    -recaptchaValidator : RecaptchaValidator
    +validate() : ValidationResult
  }
  class TestRecaptchaValidator {
    -testing : Testing
    +validate() : ValidationResult
    +validate() : ValidationResult
    +validate() : ValidationResult
    +validate() : ValidationResult
    +validate() : ValidationResult
    +validate() : ValidationResult
    +validate() : ValidationResult
  }
  class TestingConfiguration {
    -recaptcha : RecaptchaProperties
    +userResponseValidator() : RecaptchaValidator
  }
}

package com.github.mkopylec.recaptcha.validation {
  class ValidationController <<Controller>> {
    -recaptchaValidator : RecaptchaValidator
    +validateUsingUserResponse() : ValidationResult
    +validateUsingUserResponseAndIp() : ValidationResult
  }
  enum ErrorCode {
    -log : Logger
    -text : String
    +getText() : String
  }
  interface RecaptchaValidator {
  }
  class ValidationResult {
    -success : boolean
    -errorCodes : List<ErrorCode>
    +isSuccess() : boolean
    +isFailure() : boolean
    +getErrorCodes() : List<ErrorCode>
    +hasError() : boolean
  }
  class RecaptchaValidationException {
  }
  class DefaultRecaptchaValidator {
    -log : Logger
    -restTemplate : RestTemplate
    -validation : Validation
    -ipAddressResolver : IpAddressResolver
    +validate() : ValidationResult
    +validate() : ValidationResult
    +validate() : ValidationResult
    +validate() : ValidationResult
    +validate() : ValidationResult
    +validate() : ValidationResult
    +validate() : ValidationResult
  }
  class ValidationConfiguration {
    -recaptcha : RecaptchaProperties
    +userResponseValidator() : RecaptchaValidator
    +ipAddressResolver() : IpAddressResolver
    +createRestTemplate() : RestTemplate
    +toMilliseconds() : int
  }
  class IpAddressResolver {
    -X_FORWARDED_FOR_HEADER : String
    +resolveClientIp() : String
  }
}

' --- Relatii ---
AccessConfiguration --> FormLoginConfigurerEnhancer
TestingController --> RecaptchaValidator
TestingController --> ValidationResult
RecaptchaProperties --> ErrorCode
RecaptchaAuthenticationFilter --> RecaptchaProperties
RecaptchaAuthenticationFilter --> LoginFailuresClearingHandler
RecaptchaAuthenticationFilter --> LoginFailuresCountingHandler
RecaptchaAuthenticationFilter --> LoginFailuresManager
RecaptchaAuthenticationFilter --> RecaptchaValidationException
RecaptchaAuthenticationFilter --> RecaptchaValidator
RecaptchaAuthenticationFilter --> ValidationResult
RecaptchaAuthenticationException --> ErrorCode
SecurityConfiguration --> RecaptchaProperties
SecurityConfiguration --> FormLoginConfigurerEnhancer
SecurityConfiguration --> InMemoryLoginFailuresManager
SecurityConfiguration --> LoginFailuresClearingHandler
SecurityConfiguration --> LoginFailuresCountingHandler
SecurityConfiguration --> LoginFailuresManager
SecurityConfiguration --> RecaptchaAwareRedirectStrategy
SecurityConfiguration --> RecaptchaValidator
RecaptchaAwareRedirectStrategy --> RecaptchaAuthenticationException
InMemoryLoginFailuresManager --|> LoginFailuresManager
InMemoryLoginFailuresManager --> RecaptchaProperties
LoginFailuresCountingHandler --> RecaptchaProperties
FormLoginConfigurerEnhancer --> RecaptchaAuthenticationFilter
LoginFailuresManager --> RecaptchaProperties
TestRecaptchaValidator ..|> RecaptchaValidator
TestRecaptchaValidator --> RecaptchaProperties
TestRecaptchaValidator --> RecaptchaValidator
TestRecaptchaValidator --> ValidationResult
TestingConfiguration --> RecaptchaProperties
TestingConfiguration --> RecaptchaValidator
DefaultRecaptchaValidator ..|> RecaptchaValidator
DefaultRecaptchaValidator --> RecaptchaProperties
ValidationConfiguration --> RecaptchaProperties

@enduml