@startuml

package example {
  class TNameStandardSchemeFactory {
    -firstName : String
    -secondName : String
    -status : TStatus
    -_thriftId : short
    -_fieldName : String
    +findByThriftId() : _Fields
    +findByThriftIdOrThrow() : _Fields
    +findByName() : _Fields
    +getThriftFieldId() : short
    +getFieldName() : String
    +deepCopy() : TName
    +clear() : void
    +getFirstName() : String
  }
  class TGreetingService {
    -name : TName
    -LOGGER : Logger
    -LOGGER : Logger
    -fb : AsyncFrameBuffer
    -seqid : int
    -name : TName
    -_thriftId : short
    -_fieldName : String
    -success : String
    -_thriftId : short
    +greet() : String
    +greet() : void
    +getClient() : Client
    +getClient() : Client
    +greet() : String
    +send_greet() : void
    +recv_greet() : String
    +getAsyncClient() : AsyncClient
  }
}

package info.developerblog.examples.thirft.poolfactory {
  class PoolFactoryTests {
    -thriftClientsPool : ThriftClientPool
    -thriftClientKey : ThriftClientKey
    +postConstruct() : void
    +poolFactoryFullObjectLifecycleTest() : void
    +poolFactoryNonstandardObjectLifecycleTest() : void
    +poolFactoryOverlappingObjectLifecyclesTest() : void
  }
}

package info.developerblog.examples.thirft.proxyclient.async {
  class TAsyncGreetingServiceHandlerTests {
    -asyncGreetingService : AsyncGreetingService
    +testAsyncInjectionFail() : void
  }
}

package info.developerblog.examples.thirft.simpleclient {
  class TGreetingServiceHandlerTests {
    -context : WebApplicationContext
    -maxThreads : int
    -maxIdleThreads : int
    -maxTotalThreads : int
    +testSimpleCall() : void
    +testCallWithTimeout() : void
    +testMappedClient() : void
    +testMappedClientWithTimeout() : void
    +testMisconfiguredClient() : void
    +testClientWithDefaultRetries() : void
    +testClientWithMultipleRetries() : void
    +testClientThreadCount() : void
  }
  class AsyncGreetingService <<Service>> {
    +getGreeting() : Future<String>
  }
  class GreetingService <<Service>> {
    +getGreeting() : String
    +getGreetingWithTimeout() : String
    +getOneOffGreetingWithTimeout() : String
    +getRetriableGreetingWithTimeout() : String
    +getGreetingForKey() : String
    +getGreetingWithMisconfguration() : String
  }
  class SimpleClientApplication {
    +main() : void
  }
  class DiscoveryClientAutoConfiguration {
    -simpleDiscoveryClient : DiscoveryClient
    +onApplicationEvent() : void
  }
  class SampleMapper {
    +init() : void
  }
  class TGreetingServiceHandlerTests {
    +setUp() : void
    +testSimpleCall() : void
    +testThrowException() : void
  }
  class GreetingMessageService <<Service>> {
    +constructGreeting() : String
  }
  class Application {
    +main() : void
  }
}

package info.developerblog.examples.thirft.simpleclient.configuration {
  class CountingAspect {
    -counter : AtomicInteger
    +before() : void
  }
  class TestAspectConfiguration {
    +countingAspect() : CountingAspect
  }
}

package info.developerblog.spring.thrift.annotation {
  interface ThriftClientsMap {
  }
  interface ThriftClient {
  }
}

package info.developerblog.spring.thrift.client {
  class ThriftClientBeanRegistererBeanPostProcessor {
    -service : ThriftClientBeanPostProcessorService
    +postProcessBeforeInstantiation() : Object
  }
  class ThriftClientFieldInjectorBeanPostProcessor {
    -service : ThriftClientBeanPostProcessorService
    +postProcessBeforeInitialization() : Object
    +postProcessAfterInitialization() : Object
  }
  class ThriftClientsMapBeanPostProcessor {
    -beanFactory : DefaultListableBeanFactory
    +postProcessBeforeInitialization() : Object
    +postProcessAfterInitialization() : Object
  }
  class PoolConfiguration {
    -protocolFactory : TProtocolFactory
    -loadBalancerClient : LoadBalancerClient
    -propertyResolver : PropertyResolver
    -maxThreads : int
    -maxIdleThreads : int
    -maxTotalThreads : int
    -tracer : Tracer
    -propagator : Propagator
  }
  class ThriftClientBeanPostProcessorService {
    -beanFactory : DefaultListableBeanFactory
    -result : Object
    -instance : Object
    +getThriftClientInstanceBy() : Object
    +registerThriftClientInstanceBy() : void
    +registerThriftClientInstanceBy() : void
  }
  class AbstractThriftClientKeyMapper {
  }
}

package info.developerblog.spring.thrift.client.pool {
  class ThriftClientPooledObjectFactory {
    -DEFAULT_CONNECTION_TIMEOUT : int
    -DEFAULT_READ_TIMEOUT : int
    -DEFAULT_MAX_RETRIES : int
    -protocolFactory : TProtocolFactory
    -loadBalancerClient : LoadBalancerClient
    -propertyResolver : PropertyResolver
    -tracer : Tracer
    -propagator : Propagator
    -loadBalancerClient : TLoadBalancerClient
    -httpClient : THttpClient
    +create() : TServiceClient
    +wrap() : PooledObject<TServiceClient>
    +activateObject() : void
    +passivateObject() : void
  }
  class ThriftClientPool {
  }
  class ThriftClientKey {
    -serviceName : String
    -path : String
    +getServiceName() : String
    +getPath() : String
  }
  class ThriftClientPooledObject {
    -span : Span
    +getSpan() : Span
    +setSpan() : void
  }
}

package info.developerblog.spring.thrift.transport {
  class TLoadBalancerClient {
    -loadBalancerClient : LoadBalancerClient
    -serviceName : String
    -path : String
    -requestBuffer_ : ByteArrayOutputStream
    -inputStream_ : InputStream
    -connectTimeout_ : int
    -readTimeout_ : int
    -maxRetries_ : int
    +setConnectTimeout() : void
    +setReadTimeout() : void
    +setMaxRetries() : void
    +setCustomHeaders() : void
    +setCustomHeader() : void
    +open() : void
    +close() : void
    +isOpen() : boolean
  }
}

package ru.trylogic.spring.boot.thrift {
  class ThriftAutoConfiguration {
    -meterRegistry : MeterRegistry
    -loggingThriftMethodInterceptor : LoggingThriftMethodInterceptor
    -applicationContext : ApplicationContext
    -protocolFactory : TProtocolFactory
    -thriftConfigurer : ThriftConfigurer
    +configureProxyFactory() : void
    +getDescription() : String
    +register() : void
    +register() : void
    +getServlet() : TServlet
  }
}

package ru.trylogic.spring.boot.thrift.annotation {
  interface ThriftController {
  }
}

package ru.trylogic.spring.boot.thrift.aop {
  class MetricsThriftMethodInterceptor {
    -THRIFT_REQUEST_DURATION_METRIC : String
    -meterRegistry : MeterRegistry
    -startTime : long
    -result : Object
    +invoke() : Object
  }
  class LoggingThriftMethodInterceptor {
    +before() : void
    +afterReturning() : void
    +afterThrowing() : void
  }
}

' --- Relatii ---
TGreetingServiceHandlerTests --> CountingAspect
TGreetingServiceHandlerTests --> TestAspectConfiguration
TAsyncGreetingServiceHandlerTests --> AsyncGreetingService
TAsyncGreetingServiceHandlerTests --> SimpleClientApplication
PoolFactoryTests --> TGreetingService
PoolFactoryTests --> SimpleClientApplication
PoolFactoryTests --> ThriftClientKey
PoolFactoryTests --> ThriftClientPool
AsyncGreetingService --> TGreetingService
AsyncGreetingService --> ThriftClient
GreetingService --> TGreetingService
GreetingService --> ThriftClient
GreetingService --> ThriftClientsMap
SimpleClientApplication --> TGreetingService
SimpleClientApplication --> ThriftClient
SampleMapper --|> AbstractThriftClientKeyMapper
SampleMapper --> TGreetingService
SampleMapper --> AbstractThriftClientKeyMapper
SampleMapper --> ThriftClientKey
TGreetingServiceHandlerTests --> TGreetingService
ThriftAutoConfiguration --> ThriftController
ThriftAutoConfiguration --> LoggingThriftMethodInterceptor
ThriftAutoConfiguration --> MetricsThriftMethodInterceptor
ThriftClientsMap --> AbstractThriftClientKeyMapper
ThriftClientFieldInjectorBeanPostProcessor --> ThriftClient
ThriftClientsMapBeanPostProcessor --> ThriftClientsMap
ThriftClientsMapBeanPostProcessor --> ThriftClientKey
PoolConfiguration --> ThriftClientKey
PoolConfiguration --> ThriftClientPool
PoolConfiguration --> ThriftClientPooledObjectFactory
ThriftClientBeanPostProcessorService --> ThriftClient
ThriftClientBeanPostProcessorService --> ThriftClientKey
AbstractThriftClientKeyMapper --> ThriftClientKey
ThriftClientPooledObjectFactory --> TLoadBalancerClient

@enduml