@startuml

  class EcommerceStarterApplicationTests {
    +contextLoads() : void
  }

package net.vatri.ecommerce {
  class EcommerceStarterApplication {
    -redisHost : String
    -redisPort : int
    -redisPassword : String
    +main() : void
    +sessionFactory() : HibernateJpaSessionFactoryBean
    +productValidator() : Validator
    +groupValidator() : Validator
    +orderValidator() : Validator
    +cacheObject() : Cache
  }
}

package net.vatri.ecommerce.cache {
  class RedisCacheTest {
    -cache : RedisCache
    -id : int
    +setUp() : void
    +testGetList() : void
    +testGetItem() : void
    +testAddObjectToList() : void
    +testRemoveObjectFromList() : void
    +testAddingObjectToCache() : void
  }
  class RedisCache {
    -objectMapper : ObjectMapper
    -jedis : Jedis
    +getObjectMapper() : ObjectMapper
    +setObjectMapper() : void
    +getJedis() : Jedis
    +setJedis() : void
    +getItem() : Object
    +setItem() : Object
    +removeItem() : void
    +getList() : Collection<Object>
  }
  interface Cache {
    +getItem() : Object
    +setItem() : Object
    +removeItem() : void
    +getList() : Collection<Object>
    +addItemToList() : Collection<Object>
    +removeItemFromList() : Collection<Object>
  }
}

package net.vatri.ecommerce.cart {
  class CartServiceImpl <<Service>> {
    -ecommerceService : EcommerceService
    -cache : Cache
    +createNewCart() : String
    +addProduct() : void
    +removeProduct() : void
    +setProductQuantity() : void
    +getItems() : Set<CartItem>
    +createOrder() : Order
  }
  interface CartService {
    +createNewCart() : String
    +addProduct() : void
    +removeProduct() : void
    +setProductQuantity() : void
    +getItems() : Set<CartItem>
    +createOrder() : Order
  }
  class CartItem {
    -productId : long
    -variantId : long
    -quantity : int
    +getProductId() : long
    +setProductId() : void
    +getVariantId() : long
    +setVariantId() : void
    +getQuantity() : int
    +setQuantity() : void
  }
  class Cart {
    -items : List<CartItem>
    +getItems() : List<CartItem>
    +setItems() : void
  }
}

package net.vatri.ecommerce.config {
  class WebSecurityConfig {
    -authenticationSuccessHandler : AuthenticationSuccessHandler
    -authenticationFailureHandler : AuthenticationFailureHandler
    +bCryptPasswordEncoder() : BCryptPasswordEncoder
    +jwtAuthenticationTokenFilter() : TokenAuthenticationFilter
    +configure() : void
  }
  class MySwaggerConfig {
    +api() : Docket
  }
}

package net.vatri.ecommerce.controllers {
  class ProductController <<Controller>> {
    -ecommerceService : EcommerceService
    -storageService : StorageService
    -sessionFactory : SessionFactory
    +initBinder() : void
    +index() : List<ProductResource>
    +create() : Product
    +view() : ResourceSupport
    +edit() : Product
    +viewImages() : List<ProductImage>
    +serveFile() : ResponseEntity<Resource>
    +handleFileUpload() : String
  }
  class OrderController <<Controller>> {
    -ecommerceService : EcommerceService
    +initBinder() : void
    +index() : List<OrderResource>
    +create() : Order
    +view() : OrderResource
    +edit() : Order
  }
  class CartController <<Controller>> {
    +initBinder() : void
    +create() : String
    +addProduct() : String
    +getCartItems() : Set<CartItem>
    +removeItem() : String
    +setProductQuantity() : String
    +createOrder() : OrderResource
  }
  class CoreController {
    +createHateoasLink() : Link
  }
  class GroupController <<Controller>> {
    +initBinder() : void
    +index() : List<GroupResource>
    +view() : GroupResource
    +edit() : ProductGroup
    +create() : ProductGroup
  }
}

package net.vatri.ecommerce.hateoas {
  class OrderResource {
    -id : long
    -name : String
    -address : String
    -city : String
    -zip : String
    -status : String
    -comment : String
    -totalPrice : String
    -type : String
    -created : String
  }
  class GroupResource {
    -id : long
    -groupName : String
    -price : String
    -variants : List<GroupVariant>
  }
  class ProductResource {
    -id : long
    -name : String
    -price : String
    -description : String
    -group : Object
  }
}

package net.vatri.ecommerce.models {
  class Order <<Entity>> {
    -id : long
    -name : String
    -address : String
    -city : String
    -zip : String
    -status : String
    -comment : String
    -totalPrice : String
    -type : String
    -created : String
    +getId() : long
    +setId() : void
    +getName() : String
    +setName() : void
    +getAddress() : String
    +setAddress() : void
    +getCity() : String
    +setCity() : void
  }
  class OrderItem <<Entity>> {
    -id : Integer
    -price : String
    -order : Order
    -product : Product
    -groupVariant : GroupVariant
    +getId() : Integer
    +setId() : void
    +getPrice() : String
    +setPrice() : void
    +getOrder() : Order
    +setOrder() : void
    +getProduct() : Product
    +setProduct() : void
  }
  class StockModel {
    -product_name : String
    -variant_name : String
    -stock : String
    +getProductName() : String
    +setProductName() : void
    +getVariantName() : String
    +setVariantName() : void
    +getStock() : String
    +setStock() : void
  }
  class Product <<Entity>> {
    -id : long
    -name : String
    -created : String
    -price : String
    -description : String
    -group : ProductGroup
    -userId : String
    -user : User
    +getId() : long
    +setId() : void
    +getName() : String
    +setName() : void
    +getCreated() : String
    +setCreated() : void
    +getPrice() : String
    +setPrice() : void
  }
  class ProductImage <<Entity>> {
    -id : long
    -productId : long
    -path : String
    +getId() : long
    +setId() : void
    +getProductId() : long
    +setProductId() : void
    +getPath() : String
    +setPath() : void
  }
  class User <<Entity>> {
    -id : Integer
    -name : String
    -email : String
    -password : String
    -accessToken : String
    -created : String
    +getId() : Integer
    +setId() : void
    +getName() : String
    +setName() : void
    +getEmail() : String
    +setEmail() : void
    +getPassword() : String
    +setPassword() : void
  }
  class ProductGroup <<Entity>> {
    -id : Long
    -groupName : String
    -price : String
    -created : String
    -groupVariants : List<GroupVariant>
    +getId() : Long
    +setId() : void
    +getGroupName() : String
    +setGroupName() : void
    +getPrice() : String
    +setPrice() : void
    +getCreated() : String
    +setCreated() : void
  }
  class GroupVariant <<Entity>> {
    -id : long
    -variantName : String
    -group : ProductGroup
    +getId() : long
    +setId() : void
    +getVariantName() : String
    +setVariantName() : void
    +getGroup() : ProductGroup
    +setGroup() : void
  }
}

package net.vatri.ecommerce.repositories {
  interface OrderRepository {
    +findOneWithItems() : Order
  }
  interface ProductRepository <<Repository>> {
  }
  interface GroupRepository <<Repository>> {
  }
  interface UserRepository <<Repository>> {
  }
}

package net.vatri.ecommerce.security {
  class TokenBasedAuthentication {
    -token : String
    -principle : UserDetails
    +getToken() : String
    +setToken() : void
    +isAuthenticated() : boolean
    +getCredentials() : Object
    +getPrincipal() : UserDetails
  }
  class AuthenticationSuccessHandler {
    -EXPIRES_IN : int
    -jws : String
    -expires : int
    +onAuthenticationSuccess() : void
    +getJws() : String
    +setJws() : void
    +getExpires() : int
    +setExpires() : void
  }
  class AnonAuthentication {
    +getCredentials() : Object
    +getPrincipal() : Object
    +isAuthenticated() : boolean
  }
  class TokenAuthenticationFilter {
    -AUTH_HEADER : String
    +doFilterInternal() : void
  }
  class AuthenticationFailureHandler {
    +onAuthenticationFailure() : void
  }
  class TokenHelper {
    -APP_NAME : String
    -SECRET : String
    -EXPIRES_IN : int
    -SIGNATURE_ALGORITHM : SignatureAlgorithm
    -claims : Claims
    +getUsernameFromToken() : String
    +generateToken() : String
    +getClaimsFromToken() : Claims
  }
}

package net.vatri.ecommerce.services {
  class EcommerceService <<Service>> {
    -sessionFactory : SessionFactory
    -productId : String
    -filename : String
    +getProducts() : List<Product>
    +getProduct() : Product
    +saveProduct() : Product
    +addProductImage() : String
    +getGroups() : List<ProductGroup>
    +getGroup() : ProductGroup
    +saveGroup() : ProductGroup
    +getOrders() : List<Order>
  }
  class UserDetailServiceImpl <<Service>> {
    -userRepository : UserRepository
    -cache : Cache
    -objectMapper : ObjectMapper
    +loadUserByUsername() : UserDetails
  }
}

package net.vatri.ecommerce.storage {
  class FileSystemStorageService <<Service>> {
    -rootLocation : Path
    -location : Path
    +store() : String
    +loadAll() : Stream<Path>
    +load() : Path
    +loadAsResource() : Resource
    +deleteAll() : void
    +init() : void
  }
  class StorageProperties {
    -location : String
    +getLocation() : String
    +setLocation() : void
  }
  class StorageException {
  }
  class StorageFileNotFoundException {
  }
  interface StorageService {
  }
}

package net.vatri.ecommerce.validators {
  class GroupValidator {
    +supports() : boolean
    +validate() : void
  }
  class OrderValidator {
    +supports() : boolean
    +validate() : void
  }
  class ProductValidator {
    +supports() : boolean
    +validate() : void
  }
}

' --- Relatii ---
EcommerceStarterApplication --> Cache
EcommerceStarterApplication --> RedisCache
EcommerceStarterApplication --> StorageProperties
EcommerceStarterApplication --> StorageService
EcommerceStarterApplication --> GroupValidator
EcommerceStarterApplication --> OrderValidator
EcommerceStarterApplication --> ProductValidator
RedisCache ..|> Cache
WebSecurityConfig --> AuthenticationFailureHandler
WebSecurityConfig --> AuthenticationSuccessHandler
WebSecurityConfig --> TokenAuthenticationFilter
AuthenticationSuccessHandler --> User
OrderRepository --> Order
ProductRepository --> Product
GroupRepository --> ProductGroup
UserRepository --> Product
UserRepository --> User
OrderItem --> Product
FileSystemStorageService ..|> StorageService
StorageFileNotFoundException --|> StorageException
CartServiceImpl ..|> CartService
CartServiceImpl --> Cache
CartServiceImpl --> GroupVariant
CartServiceImpl --> Order
CartServiceImpl --> OrderItem
CartServiceImpl --> Product
CartServiceImpl --> EcommerceService
CartService --> CartItem
CartService --> Order
GroupValidator --> ProductGroup
OrderValidator --> Order
ProductValidator --> Product
ProductController --|> CoreController
ProductController --> ProductResource
ProductController --> Product
ProductController --> ProductImage
ProductController --> EcommerceService
ProductController --> StorageService
OrderController --|> CoreController
OrderController --> OrderResource
OrderController --> Order
OrderController --> EcommerceService
CartController --|> CoreController
CartController --> CartItem
CartController --> CartService
CartController --> OrderResource
CartController --> Order
GroupController --|> CoreController
GroupController --> GroupResource
GroupController --> ProductGroup
GroupController --> EcommerceService
OrderResource --> Order
OrderResource --> OrderItem
GroupResource --> GroupVariant
GroupResource --> ProductGroup
ProductResource --> Product
EcommerceService --> Order
EcommerceService --> Product
EcommerceService --> ProductGroup
EcommerceService --> ProductImage
EcommerceService --> GroupRepository
EcommerceService --> OrderRepository
EcommerceService --> ProductRepository
UserDetailServiceImpl --> Cache
UserDetailServiceImpl --> User
UserDetailServiceImpl --> UserRepository

@enduml