@startuml

  class MavenWrapperDownloader {
    -DEFAULT_DOWNLOAD_URL : String
    -MAVEN_WRAPPER_PROPERTIES_PATH : String
    -MAVEN_WRAPPER_JAR_PATH : String
    -PROPERTY_NAME_WRAPPER_URL : String
    +main() : void
  }

package com.programming.techie.springredditclone {
  class BaseTest {
    -mySQLContainer : MySQLContainer
  }
  class SpringRedditCloneApplication {
    +main() : void
  }
}

package com.programming.techie.springredditclone.config {
  class SecurityConfig {
    +authenticationManager() : AuthenticationManager
    +securityFilterChain() : SecurityFilterChain
  }
  class WebConfig {
    +addCorsMappings() : void
    +addResourceHandlers() : void
  }
  class OpenAPIConfiguration {
    +expenseAPI() : OpenAPI
  }
}

package com.programming.techie.springredditclone.controller {
  class PostControllerTest {
    -postService : PostService
    -mockMvc : MockMvc
  }
  class VoteController <<Controller>> {
    -voteService : VoteService
    +vote() : ResponseEntity<Void>
  }
  class AuthController <<Controller>> {
    -authService : AuthService
    -refreshTokenService : RefreshTokenService
    +signup() : ResponseEntity<String>
    +verifyAccount() : ResponseEntity<String>
    +login() : AuthenticationResponse
    +refreshTokens() : AuthenticationResponse
    +logout() : ResponseEntity<String>
  }
  class PostController <<Controller>> {
    -postService : PostService
    +createPost() : ResponseEntity<Void>
    +getAllPosts() : ResponseEntity<List<PostResponse>>
    +getPost() : ResponseEntity<PostResponse>
    +getPostsBySubreddit() : ResponseEntity<List<PostResponse>>
    +getPostsByUsername() : ResponseEntity<List<PostResponse>>
  }
  class CommentsController <<Controller>> {
    -commentService : CommentService
    +createComment() : ResponseEntity<Void>
    +getAllCommentsForPost() : ResponseEntity<List<CommentsDto>>
    +getAllCommentsForUser() : ResponseEntity<List<CommentsDto>>
  }
  class SubredditController <<Controller>> {
    -subredditService : SubredditService
    +createSubreddit() : ResponseEntity<SubredditDto>
    +getAllSubreddits() : ResponseEntity<List<SubredditDto>>
    +getSubreddit() : ResponseEntity<SubredditDto>
  }
}

package com.programming.techie.springredditclone.dto {
  class VoteDto {
    -voteType : VoteType
    -postId : Long
  }
  class PostResponse {
    -id : Long
    -postName : String
    -url : String
    -description : String
    -userName : String
    -subredditName : String
    -voteCount : Integer
    -commentCount : Integer
    -duration : String
    -upVote : boolean
  }
  class SubredditDto {
    -id : Long
    -name : String
    -description : String
    -numberOfPosts : Integer
  }
  class LogoutRequest {
    -refreshToken : String
  }
  class RegisterRequest {
    -email : String
    -username : String
    -password : String
  }
  class AuthenticationResponse {
    -authenticationToken : String
    -refreshToken : String
    -expiresAt : Instant
    -username : String
  }
  class LoginRequest {
    -username : String
    -password : String
  }
  class PostRequest {
    -postId : Long
    -subredditName : String
    -postName : String
    -url : String
    -description : String
  }
  class CommentsDto {
    -id : Long
    -postId : Long
    -createdDate : Instant
    -text : String
    -userName : String
  }
  class RefreshTokenRequest {
    -refreshToken : String
    -username : String
  }
}

package com.programming.techie.springredditclone.exceptions {
  class SubredditNotFoundException {
  }
  class SpringRedditException {
  }
  class PostNotFoundException {
  }
}

package com.programming.techie.springredditclone.mapper {
  interface CommentMapper {
  }
  class PostMapper {
    -commentRepository : CommentRepository
    -voteRepository : VoteRepository
    -authService : AuthService
    +map() : Post
    +mapToDto() : PostResponse
  }
  interface SubredditMapper {
  }
}

package com.programming.techie.springredditclone.model {
  class Post <<Entity>> {
    -postId : Long
    -postName : String
    -url : String
    -description : String
    -voteCount : Integer
    -user : User
    -createdDate : Instant
    -subreddit : Subreddit
  }
  class RefreshToken <<Entity>> {
    -id : Long
    -token : String
    -createdDate : Instant
  }
  class Vote <<Entity>> {
    -voteId : Long
    -voteType : VoteType
    -post : Post
    -user : User
  }
  class User <<Entity>> {
    -userId : Long
    -username : String
    -password : String
    -email : String
    -created : Instant
    -enabled : boolean
  }
  class NotificationEmail {
    -subject : String
    -recipient : String
    -body : String
  }
  class VerificationToken <<Entity>> {
    -id : Long
    -token : String
    -user : User
    -expiryDate : Instant
  }
  class Comment <<Entity>> {
    -id : Long
    -text : String
    -post : Post
    -createdDate : Instant
    -user : User
  }
  class Subreddit <<Entity>> {
    -id : Long
    -name : String
    -description : String
    -posts : List<Post>
    -createdDate : Instant
    -user : User
  }
  enum VoteType {
    -direction : int
    +lookup() : VoteType
    +getDirection() : Integer
  }
}

package com.programming.techie.springredditclone.repository {
  class PostRepositoryTest {
    -postRepository : PostRepository
    +shouldSavePost() : void
  }
  class UserRepositoryTest {
    -userRepository : UserRepository
    +shouldSavePost() : void
  }
  interface CommentRepository <<Repository>> {
  }
  interface VoteRepository <<Repository>> {
  }
  interface RefreshTokenRepository {
  }
  interface PostRepository <<Repository>> {
  }
  interface UserRepository <<Repository>> {
  }
  interface VerificationTokenRepository <<Repository>> {
  }
  interface SubredditRepository <<Repository>> {
  }
}

package com.programming.techie.springredditclone.security {
  class JwtProvider <<Service>> {
    -jwtEncoder : JwtEncoder
    -jwtExpirationInMillis : Long
    +generateToken() : String
    +generateTokenWithUserName() : String
    +getJwtExpirationInMillis() : Long
  }
}

package com.programming.techie.springredditclone.service {
  class PostServiceTest {
    -postRepository : PostRepository
    -subredditRepository : SubredditRepository
    -userRepository : UserRepository
    -authService : AuthService
    -postMapper : PostMapper
    -postArgumentCaptor : ArgumentCaptor<Post>
    -postService : PostService
    +setup() : void
  }
  class CommentServiceTest {
  }
  class VoteService <<Service>> {
    -voteRepository : VoteRepository
    -postRepository : PostRepository
    -authService : AuthService
    +vote() : void
  }
  class MailService <<Service>> {
    -mailSender : JavaMailSender
    -mailContentBuilder : MailContentBuilder
  }
  class CommentService <<Service>> {
    -POST_URL : String
    -postRepository : PostRepository
    -userRepository : UserRepository
    -authService : AuthService
    -commentMapper : CommentMapper
    -commentRepository : CommentRepository
    -mailContentBuilder : MailContentBuilder
    -mailService : MailService
    +save() : void
    +getAllCommentsForPost() : List<CommentsDto>
    +getAllCommentsForUser() : List<CommentsDto>
    +containsSwearWords() : boolean
  }
  class SubredditService <<Service>> {
    -subredditRepository : SubredditRepository
    -subredditMapper : SubredditMapper
    +save() : SubredditDto
    +getAll() : List<SubredditDto>
    +getSubreddit() : SubredditDto
  }
  class AuthService <<Service>> {
    -passwordEncoder : PasswordEncoder
    -userRepository : UserRepository
    -verificationTokenRepository : VerificationTokenRepository
    -mailService : MailService
    -authenticationManager : AuthenticationManager
    -jwtProvider : JwtProvider
    -refreshTokenService : RefreshTokenService
    +signup() : void
    +getCurrentUser() : User
    +verifyAccount() : void
    +login() : AuthenticationResponse
    +refreshToken() : AuthenticationResponse
    +isLoggedIn() : boolean
  }
  class RefreshTokenService <<Service>> {
    -refreshTokenRepository : RefreshTokenRepository
    +generateRefreshToken() : RefreshToken
    +deleteRefreshToken() : void
  }
  class MailContentBuilder <<Service>> {
    -templateEngine : TemplateEngine
    +build() : String
  }
  class UserDetailsServiceImpl <<Service>> {
    -userRepository : UserRepository
    +loadUserByUsername() : UserDetails
  }
  class PostService <<Service>> {
    -postRepository : PostRepository
    -subredditRepository : SubredditRepository
    -userRepository : UserRepository
    -authService : AuthService
    -postMapper : PostMapper
    +save() : void
    +getPost() : PostResponse
    +getAllPosts() : List<PostResponse>
    +getPostsBySubreddit() : List<PostResponse>
    +getPostsByUsername() : List<PostResponse>
  }
}

' --- Relatii ---
PostRepositoryTest --|> BaseTest
PostRepositoryTest --> BaseTest
PostRepositoryTest --> Post
UserRepositoryTest --|> BaseTest
UserRepositoryTest --> BaseTest
UserRepositoryTest --> User
PostControllerTest --> PostResponse
PostControllerTest --> PostService
PostServiceTest --> PostRequest
PostServiceTest --> PostResponse
PostServiceTest --> PostMapper
PostServiceTest --> Post
PostServiceTest --> Subreddit
PostServiceTest --> User
PostServiceTest --> PostRepository
PostServiceTest --> SubredditRepository
PostServiceTest --> UserRepository
CommentServiceTest --> SpringRedditException
SpringRedditCloneApplication --> OpenAPIConfiguration
VoteDto --> VoteType
CommentRepository --> Comment
CommentRepository --> Post
CommentRepository --> User
VoteRepository --> Post
VoteRepository --> User
VoteRepository --> Vote
RefreshTokenRepository --> RefreshToken
PostRepository --> Post
PostRepository --> Subreddit
PostRepository --> User
UserRepository --> User
VerificationTokenRepository --> VerificationToken
SubredditRepository --> Subreddit
JwtProvider --> User
CommentMapper --> CommentsDto
CommentMapper --> Comment
CommentMapper --> Post
CommentMapper --> User
PostMapper --> PostRequest
PostMapper --> PostResponse
PostMapper --> CommentRepository
PostMapper --> VoteRepository
PostMapper --> AuthService
SubredditMapper --> SubredditDto
SubredditMapper --> Post
SubredditMapper --> Subreddit
VoteController --> VoteDto
VoteController --> VoteService
AuthController --> AuthenticationResponse
AuthController --> LoginRequest
AuthController --> RefreshTokenRequest
AuthController --> RegisterRequest
AuthController --> AuthService
AuthController --> RefreshTokenService
PostController --> PostRequest
PostController --> PostResponse
PostController --> PostService
CommentsController --> CommentsDto
CommentsController --> CommentService
SubredditController --> SubredditDto
SubredditController --> SubredditService
VoteType --> SpringRedditException
VoteService --> VoteDto
VoteService --> PostNotFoundException
VoteService --> SpringRedditException
VoteService --> Post
VoteService --> Vote
VoteService --> PostRepository
VoteService --> VoteRepository
MailService --> SpringRedditException
MailService --> NotificationEmail
CommentService --> CommentsDto
CommentService --> PostNotFoundException
CommentService --> SpringRedditException
CommentService --> CommentMapper
CommentService --> Comment
CommentService --> NotificationEmail
CommentService --> Post
CommentService --> User
CommentService --> CommentRepository
CommentService --> PostRepository
CommentService --> UserRepository
SubredditService --> SubredditDto
SubredditService --> SpringRedditException
SubredditService --> SubredditMapper
SubredditService --> Subreddit
SubredditService --> SubredditRepository
AuthService --> AuthenticationResponse
AuthService --> LoginRequest
AuthService --> RefreshTokenRequest
AuthService --> RegisterRequest
AuthService --> SpringRedditException
AuthService --> NotificationEmail
AuthService --> User
AuthService --> VerificationToken
AuthService --> UserRepository
AuthService --> VerificationTokenRepository
AuthService --> JwtProvider
RefreshTokenService --> SpringRedditException
RefreshTokenService --> RefreshToken
RefreshTokenService --> RefreshTokenRepository
UserDetailsServiceImpl --> User
UserDetailsServiceImpl --> UserRepository
PostService --> PostRequest
PostService --> PostResponse
PostService --> PostNotFoundException
PostService --> SubredditNotFoundException
PostService --> PostMapper
PostService --> Post
PostService --> Subreddit
PostService --> User
PostService --> PostRepository
PostService --> SubredditRepository
PostService --> UserRepository

@enduml