@startuml

package com.app {
  class BaseTest {
    -LOG : Logger
  }
  class AppTests {
    +contextLoads() : void
  }
  class App {
    +main() : void
  }
}

package com.app.configuration {
  class RestConfiguration {
    +corsFilter() : CorsFilter
  }
  class WebSecurityConfiguration {
    -unauthorizedHandler : JwtAuthenticationEntryPoint
    -userDetailsService : UserDetailsService
    +configureAuthentication() : void
    +passwordEncoder() : PasswordEncoder
    +authenticationTokenFilterBean() : JwtAuthenticationTokenFilter
    +configure() : void
  }
}

package com.app.controller {
  class AuthControllerTest {
    -passwordEncoder : BCryptPasswordEncoder
    -authenticationManager : AuthenticationManager
    -jwtTokenUtil : JwtUtil
    -userDetailsService : UserDetailsService
    -userService : UserService
    -authController : AuthController
    -TOKEN : String
    +setUp() : void
    +signUpTest() : void
    +signInTest() : void
    +refreshTest() : void
  }
  class BaseControllerTest {
    -mvc : MockMvc
    +setUp() : void
  }
  class IndexController <<Controller>> {
    +index() : String
  }
  class AuthController <<Controller>> {
    -tokenHeader : String
    -SIGNUP_URL : String
    -SIGNIN_URL : String
    -REFRESH_TOKEN_URL : String
    -authenticationManager : AuthenticationManager
    -jwtUtil : JwtUtil
    -userDetailsService : UserDetailsService
    -userService : UserService
    -name : String
    -email : String
    +setAuthenticationManager() : void
    +setJwtTokenUtil() : void
    +setUserDetailsService() : void
    +setUserService() : void
    +createAuthenticationToken() : ResponseEntity
    +getAuthenticationToken() : ResponseEntity
    +refreshAuthenticationToken() : ResponseEntity
  }
  class BaseController {
    -LOG : Logger
  }
}

package com.app.entity {
  class User <<Entity>> {
    -id : Long
    -name : String
    -email : String
    -password : String
    -role : Role
    +getPassword() : String
    +setPassword() : void
  }
  class Role <<Entity>> {
    -id : Long
    -label : String
  }
}

package com.app.exception {
  class UserNotFoundException {
  }
  class UserAlreadyExistsException {
  }
  class InvalidPasswordException {
  }
}

package com.app.repository {
  class BaseRepositoryTest {
  }
  class UserRepositoryTest {
    -userRepository : UserRepository
    +findByIdTest() : void
    +findByEmailTest() : void
    +findByNameTest() : void
    +existsTest() : void
    +countTest() : void
    +findAllTest() : void
    +saveTest() : void
    +changeUsernameTest() : void
  }
  interface UserRepository <<Repository>> {
  }
}

package com.app.security.auth {
  class JwtUtil {
    -CLAIM_KEY_USERNAME : String
    -CLAIM_KEY_ID : String
    -CLAIM_KEY_ROLE : String
    -CLAIM_KEY_CREATED : String
    -secret : String
    -expiration : Long
    -claims : Claims
    -claims : Claims
    -claims : Claims
    -claims : Claims
    +getUserIdFromToken() : Long
    +getUsernameFromToken() : String
    +getCreationDateFromToken() : Date
    +getExpirationDateFromToken() : Date
    +generateToken() : String
    +refreshToken() : String
    +validateToken() : Boolean
  }
  class JwtAuthenticationRequest {
    -username : String
    -email : String
    -password : String
  }
  class JwtAuthenticationEntryPoint {
    +commence() : void
  }
  class JwtUser {
    -id : Long
    -name : String
    -password : String
    -email : String
    +getId() : Long
    +getUsername() : String
    +isAccountNonExpired() : boolean
    +isAccountNonLocked() : boolean
    +isCredentialsNonExpired() : boolean
    +getEmail() : String
    +getPassword() : String
    +isEnabled() : boolean
  }
  class JwtAuthenticationTokenFilter {
    -userDetailsService : UserDetailsService
    -jwtTokenUtil : JwtUtil
    -tokenHeader : String
    +setUserDetailsService() : void
    +setJwtTokenUtil() : void
    +doFilterInternal() : void
  }
  class JwtUserFactory {
    +create() : JwtUser
  }
  class JwtAuthenticationResponse {
    -token : String
    +getToken() : String
  }
}

package com.app.service {
  class JwtUserDetailsServiceTest {
    -userRepository : UserRepository
    -jwtUserDetailsService : UserDetailsService
    +setUp() : void
    +loadUserByUsernameTest() : void
    +loadUserWhichNotExistsTest() : void
  }
  class UserServiceTest {
    -userRepository : UserRepository
    -userService : UserService
    -passwordEncoder : BCryptPasswordEncoder
    +setUp() : void
    +findByIdTest() : void
    +findByIdNotExistsTest() : void
    +findByNameTest() : void
    +findByEmailTest() : void
    +findAllTest() : void
    +addUserTest() : void
    +updateUserTest() : void
  }
  interface UserService <<Service>> {
  }
  class JwtUserDetailsServiceImpl <<Service>> {
    -userRepository : UserRepository
    +setUserRepository() : void
    +loadUserByUsername() : UserDetails
  }
  class UserServiceImpl <<Service>> {
    -userRepository : UserRepository
    +setUserRepository() : void
    +findAll() : List<User>
    +findById() : User
    +findByEmail() : User
    +findByName() : User
    +save() : User
    +delete() : void
  }
}

package com.app.util {
  class DummyDataGenerator {
    +getUsers() : List<User>
    +getUsers() : List<User>
  }
  class JsonMapper {
    -mapper : ObjectMapper
    +toJson() : String
    +toJsonIgnoreAnnotations() : String
  }
}

' --- Relatii ---
AppTests --|> BaseTest
BaseRepositoryTest --|> BaseTest
BaseRepositoryTest --> BaseTest
UserRepositoryTest --|> BaseRepositoryTest
UserRepositoryTest --> User
DummyDataGenerator --> Role
DummyDataGenerator --> User
AuthControllerTest --|> BaseControllerTest
AuthControllerTest --> User
AuthControllerTest --> JwtAuthenticationRequest
AuthControllerTest --> JwtAuthenticationResponse
AuthControllerTest --> JwtUtil
AuthControllerTest --> JwtUser
AuthControllerTest --> UserService
BaseControllerTest --|> BaseTest
BaseControllerTest --> BaseTest
JwtUserDetailsServiceTest --|> BaseTest
JwtUserDetailsServiceTest --> BaseTest
JwtUserDetailsServiceTest --> User
JwtUserDetailsServiceTest --> UserRepository
UserServiceTest --|> BaseTest
UserServiceTest --> BaseTest
UserServiceTest --> User
UserServiceTest --> UserNotFoundException
UserServiceTest --> UserRepository
WebSecurityConfiguration --> JwtAuthenticationEntryPoint
WebSecurityConfiguration --> JwtAuthenticationTokenFilter
UserRepository --> User
JwtUserFactory --> Role
JwtUserFactory --> User
AuthController --|> BaseController
AuthController --> Role
AuthController --> User
AuthController --> InvalidPasswordException
AuthController --> UserAlreadyExistsException
AuthController --> UserNotFoundException
AuthController --> JwtAuthenticationRequest
AuthController --> JwtAuthenticationResponse
AuthController --> JwtUtil
AuthController --> JwtUser
AuthController --> UserService
UserService --> User
JwtUserDetailsServiceImpl --> User
JwtUserDetailsServiceImpl --> UserRepository
JwtUserDetailsServiceImpl --> JwtUserFactory
UserServiceImpl ..|> UserService
UserServiceImpl --> User
UserServiceImpl --> UserNotFoundException
UserServiceImpl --> UserRepository

@enduml