@startuml

package cn.kiiwii.framework {
  class Application <<Controller>> {
    -logger : Logger
    +txManager() : PlatformTransactionManager
    +configure() : SpringApplicationBuilder
    +main() : void
  }
  class Application {
    +main() : void
  }
  class Application <<Controller>> {
    -logger : Logger
    +main() : void
  }
  class AppTest {
    +suite() : Test
    +testApp() : void
  }
  class Application <<Controller>> {
    -logger : Logger
    +main() : void
  }
  class Application {
    +main() : void
  }
}

package cn.kiiwii.framework.aop {
  class ServiceAop {
    -logger : Logger
    -tlocal : ThreadLocal<OperatorLog>
    -optLogService : OptLogService
    +webRequestLog() : void
    +doBefore() : void
    +doAfterReturning() : void
    +around() : Object
  }
  class WebAspect {
    -logger : Logger
    +webAspect() : void
    +doBefore() : void
    +doAfterReturning() : void
    +around() : Object
  }
}

package cn.kiiwii.framework.controller {
  class TestController <<Controller>> {
    -testService : ITestService
    -logger : Logger
    +greeting() : String
    +testTrans() : String
  }
  class UserController <<Controller>> {
    +view() : String
    +view() : String
  }
  class TestController <<Controller>> {
    -testService : ITestService
    -logger : Logger
    +greeting() : String
  }
  class TestController <<Controller>> {
    -testService : ITestService
    -logger : Logger
    +greeting() : String
  }
  class TestController <<Controller>> {
    -testService : ITestService
    -logger : Logger
    +greeting() : String
    +testTrans() : String
    +testJpa() : String
  }
}

package cn.kiiwii.framework.dao {
  interface ITestDAO {
  }
  interface ITestDAO {
  }
  interface ITestDAO {
  }
  interface ITestDAO {
  }
  interface TestRepository <<Repository>> {
  }
}

package cn.kiiwii.framework.dao.impl {
  class TestDAOImpl <<Repository>> {
    -jdbcTemplate : JdbcTemplate
    +test() : void
    +save() : void
  }
  class TestDAOImpl <<Repository>> {
    -jdbcTemplate : JdbcTemplate
    +testMaster() : void
    +testSlave1() : void
    +testSlave2() : void
  }
  class TestDAOImpl <<Repository>> {
    -jdbcTemplate : JdbcTemplate
    +test() : void
  }
}

package cn.kiiwii.framework.druid {
  class DruidDataSourceProperties {
    -driverClassName : String
    -url : String
    -username : String
    -password : String
    -initialSize : int
    -minIdle : int
    -maxActive : int
    -maxWait : long
    -timeBetweenEvictionRunsMillis : long
    -minEvictableIdleTimeMillis : long
    +getInitialSize() : int
    +setInitialSize() : void
    +getMinIdle() : int
    +setMinIdle() : void
    +getMaxActive() : int
    +setMaxActive() : void
    +getMaxWait() : long
    +setMaxWait() : void
  }
  class DruidConfiguration {
    -properties : DruidDataSourceProperties
    +druidDataSource() : DataSource
    +druidServlet() : ServletRegistrationBean
    +filterRegistrationBean() : FilterRegistrationBean
  }
  class DruidConfiguration {
    +druidServlet() : ServletRegistrationBean
    +filterRegistrationBean() : FilterRegistrationBean
  }
  class DruidConfiguration {
    -driver : String
    +druidServlet() : ServletRegistrationBean
    +druidDataSource() : DataSource
    +filterRegistrationBean() : FilterRegistrationBean
  }
  class DruidConfiguration {
    -driver : String
    +druidDataSource() : DataSource
    +druidServlet() : ServletRegistrationBean
    +filterRegistrationBean() : FilterRegistrationBean
  }
}

package cn.kiiwii.framework.druid.DynamicDataSource {
  class DynamicDataSourceContextHolder {
    -contextHolder : ThreadLocal<String>
    -dataSourceIds : List<String>
    +setDataSourceType() : void
    +getDataSourceType() : String
    +clearDataSourceType() : void
    +containsDataSource() : boolean
  }
  class MTransactionInterceptor {
  }
  class DynamicDataSource {
    +determineCurrentLookupKey() : Object
  }
  interface TargetDataSource {
  }
  class MProxyTransactionManagementConfiguration {
  }
  class DynamicDataSourceAspect {
    -logger : Logger
    +changeDataSource() : void
    +restoreDataSource() : void
  }
  class DynamicDataSourceRegister {
    -initialSize : int
    -minIdle : int
    -maxActive : int
    -maxWait : long
    -timeBetweenEvictionRunsMillis : long
    -minEvictableIdleTimeMillis : long
    -validationQuery : String
    -testWhileIdle : boolean
    -testOnBorrow : boolean
    -testOnReturn : boolean
    +registerBeanDefinitions() : void
    +buildDataSource() : DataSource
    +setEnvironment() : void
  }
}

package cn.kiiwii.framework.dubbo {
  class DubboProperties {
    -application : ApplicationConfigProperties
    -protocol : ProtocolConfigProperties
    -provider : ProviderConfigProperties
    -registry : RegistryConfigProperties
    -monitor : MonitorConfigProperties
    -annotation : AnnotationConfigProperties
    -consumer : ConsumerConfigProperties
    -packageName : String
    -name : String
    -version : String
    +getPackageName() : String
    +setPackageName() : void
    +getName() : String
    +setName() : void
    +getVersion() : String
    +setVersion() : void
    +getOwner() : String
    +setOwner() : void
  }
  class AnnotationBeanConfiguration {
    +annotationBean() : AnnotationBean
  }
}

package cn.kiiwii.framework.dubbo.api {
  interface IPerson {
  }
}

package cn.kiiwii.framework.dubbo.consumer {
  class DubboComsumerConfiguration {
    -dubboProperties : DubboProperties
    +applicationConfig() : ApplicationConfig
    +registryConfig() : RegistryConfig
    +consumerConfig() : ConsumerConfig
  }
}

package cn.kiiwii.framework.dubbo.provider {
  class DubboProviderConfiguration {
    -dubboProperties : DubboProperties
    +registryConfig() : RegistryConfig
    +applicationConfig() : ApplicationConfig
    +protocolConfig() : ProtocolConfig
    +providerConfig() : ProviderConfig
    +monitorConfig() : MonitorConfig
  }
  class Application {
    +main() : void
  }
}

package cn.kiiwii.framework.dubbo.provider.dao {
  interface ITestDAO {
    +test() : Object
  }
}

package cn.kiiwii.framework.dubbo.provider.dao.impl {
  class TestDAOImpl <<Repository>> {
    -jdbcTemplate : JdbcTemplate
    +test() : Object
  }
}

package cn.kiiwii.framework.dubbo.provider.druid {
  class DruidDataSourceProperties {
    -driverClassName : String
    -url : String
    -username : String
    -password : String
    -initialSize : int
    -minIdle : int
    -maxActive : int
    -maxWait : long
    -timeBetweenEvictionRunsMillis : long
    -minEvictableIdleTimeMillis : long
    +getInitialSize() : int
    +setInitialSize() : void
    +getMinIdle() : int
    +setMinIdle() : void
    +getMaxActive() : int
    +setMaxActive() : void
    +getMaxWait() : long
    +setMaxWait() : void
  }
  class DruidConfiguration {
    -properties : DruidDataSourceProperties
    +druidDataSource() : DataSource
    +druidServlet() : ServletRegistrationBean
    +filterRegistrationBean() : FilterRegistrationBean
  }
}

package cn.kiiwii.framework.dubbo.provider.service {
  class PersonServiceImpl <<Service>> {
    +getFullName() : String
    +getNickName() : String
  }
}

package cn.kiiwii.framework.freemarker {
  class Application {
    -logger : Logger
    +main() : void
    +configure() : SpringApplicationBuilder
  }
}

package cn.kiiwii.framework.freemarker.controller {
  class WebController <<Controller>> {
    +index() : String
  }
  class ApiController <<Controller>> {
    +newsList() : Object
  }
}

package cn.kiiwii.framework.freemarker.model {
  class User {
    -id : int
    -name : String
    -account : String
    -password : String
    +getId() : int
    +setId() : void
    +getName() : String
    +setName() : void
    +getAccount() : String
    +setAccount() : void
    +getPassword() : String
    +setPassword() : void
  }
}

package cn.kiiwii.framework.freemarker.service {
  interface IApiService {
  }
}

package cn.kiiwii.framework.freemarker.service.impl {
  class ApiServiceImpl {
  }
}

package cn.kiiwii.framework.hibernate {
  class Application {
    -logger : Logger
    +configure() : SpringApplicationBuilder
    +main() : void
  }
}

package cn.kiiwii.framework.hibernate.aop {
  class ServiceAop {
    -logger : Logger
    -tlocal : ThreadLocal<Long>
    +webRequestLog() : void
    +doBefore() : void
    +doAfterReturning() : void
    +around() : Object
  }
}

package cn.kiiwii.framework.hibernate.conf {
  class HibernatePropertes {
    -showSql : boolean
    -formatSql : boolean
    -useSqlComments : String
    -dialect : String
    -useOuterJoin : boolean
    -hbm2ddl : Hbm2ddl
    -PackagesToScan : String[]
    -value : String
    -fetchSize : int
    -batchSize : int
    +getFetchSize() : int
    +setFetchSize() : void
    +getBatchSize() : int
    +setBatchSize() : void
    +isBatchVersionedData() : boolean
    +setBatchVersionedData() : void
    +getFactoryClass() : String
  }
  class DruidDataSourceProperties {
    -driverClassName : String
    -url : String
    -username : String
    -password : String
    -initialSize : int
    -minIdle : int
    -maxActive : int
    -maxWait : long
    -timeBetweenEvictionRunsMillis : long
    -minEvictableIdleTimeMillis : long
    +getInitialSize() : int
    +setInitialSize() : void
    +getMinIdle() : int
    +setMinIdle() : void
    +getMaxActive() : int
    +setMaxActive() : void
    +getMaxWait() : long
    +setMaxWait() : void
  }
  class ApplicationConfiguration {
    -druidDataSourceProperties : DruidDataSourceProperties
    -hibernatePropertes : HibernatePropertes
    +setDataSource() : DataSource
    +setSessionFactory() : LocalSessionFactoryBean
    +setHibernateTransactionManager() : HibernateTransactionManager
  }
}

package cn.kiiwii.framework.hibernate.controller {
  class TestController <<Controller>> {
    -testService : ITestService
    -logger : Logger
    +greeting() : String
    +testTrans() : String
  }
}

package cn.kiiwii.framework.hibernate.dao {
  interface ITestDAO {
  }
}

package cn.kiiwii.framework.hibernate.dao.impl {
  class TestDAOImpl <<Repository>> {
    +setMySessionFactory() : void
    +test() : void
    +save() : void
  }
}

package cn.kiiwii.framework.hibernate.model {
  class SpringBootWithHinernateTest2 <<Entity>> {
    -id : Integer
    -userName : String
    -createTime : Timestamp
    +getId() : Integer
    +setId() : void
    +getUserName() : String
    +setUserName() : void
    +getCreateTime() : Timestamp
    +setCreateTime() : void
  }
  class SpringBootWithHinernateTest <<Entity>> {
    -id : Integer
    -userName : String
    -createTime : Timestamp
    +getId() : Integer
    +setId() : void
    +getUserName() : String
    +setUserName() : void
    +getCreateTime() : Timestamp
    +setCreateTime() : void
  }
}

package cn.kiiwii.framework.hibernate.service {
  interface ITestService {
  }
}

package cn.kiiwii.framework.hibernate.service.impl {
  class TestServiceImpl <<Service>> {
    +test() : void
    +testTransaction() : void
  }
}

package cn.kiiwii.framework.model {
  class Test <<Entity>> {
    -id : Integer
    -testName : String
    -testNum : Integer
    -testTime : Timestamp
    +getId() : Integer
    +setId() : void
    +getTestName() : String
    +setTestName() : void
    +getTestNum() : Integer
    +setTestNum() : void
    +getTestTime() : Timestamp
    +setTestTime() : void
  }
}

package cn.kiiwii.framework.mybatis {
  class TestServiceTest {
    -testService : ITestService
    -testXmlService : ITestXmlService
    +testInsert() : void
    +testXmlInsert() : void
    +testTransfer() : void
    +testFind() : void
    +testList() : void
    +testXmlList() : void
  }
  class Application {
    -logger : Logger
    +configure() : SpringApplicationBuilder
    +main() : void
  }
}

package cn.kiiwii.framework.mybatis.aop {
  class ServiceAop {
    -logger : Logger
    -timeLocal : ThreadLocal<Long>
    +webRequestLog() : void
    +doBefore() : void
    +doAfterReturning() : void
    +around() : Object
  }
}

package cn.kiiwii.framework.mybatis.controller {
  class TestController <<Controller>> {
    -testService : ITestService
    -testXmlService : ITestXmlService
    +test() : List<Account>
    +testXml() : List<Account>
  }
}

package cn.kiiwii.framework.mybatis.druid {
  class DruidConfiguration {
    -driver : String
    +druidDataSource() : DataSource
    +druidServlet() : ServletRegistrationBean
    +filterRegistrationBean() : FilterRegistrationBean
  }
}

package cn.kiiwii.framework.mybatis.mapper {
  interface TestMapper {
    +addMoney() : int
    +minusMoney() : int
    +insertAccount() : int
    +getAccountById() : Account
    +findAccountsById() : List<Account>
  }
  interface TestXmlMapper {
    +addMoney() : int
    +minusMoney() : int
    +insertAccount() : int
    +getAccountById() : Account
    +findAccountsById() : List<Account>
  }
}

package cn.kiiwii.framework.mybatis.model {
  class Account {
    -id : int
    -name : String
    -money : double
    +getId() : int
    +setId() : void
    +getName() : String
    +setName() : void
    +getMoney() : double
    +setMoney() : void
  }
}

package cn.kiiwii.framework.mybatis.service {
  interface ITestXmlService {
    +insertAccount() : int
    +findAccountById() : Account
    +findAccountsById() : List<Account>
  }
  interface ITestService {
    +test() : void
    +transfer() : boolean
    +insertAccount() : int
    +findAccountById() : Account
    +findAccountsById() : List<Account>
  }
}

package cn.kiiwii.framework.mybatis.service.impl {
  class TestServiceImpl <<Service>> {
    -testMapper : TestMapper
    +test() : void
    +transfer() : boolean
    +insertAccount() : int
    +findAccountById() : Account
    +findAccountsById() : List<Account>
  }
  class TestXmlServiceImpl <<Service>> {
    -testXmlDAO : TestXmlMapper
    +test() : void
    +insertAccount() : int
    +findAccountById() : Account
    +findAccountsById() : List<Account>
  }
}

package cn.kiiwii.framework.schedule {
  class Scheduling {
    -logger : Logger
    -testService : ITestService
    +scheduler() : void
  }
}

package cn.kiiwii.framework.service {
  interface ITestService {
  }
  interface ITestService {
  }
  interface ITestService {
  }
}

package cn.kiiwii.framework.service.impl {
  class TestServiceImpl <<Service>> {
    +test() : void
    +testTransaction() : void
  }
  class TestServiceImpl <<Service>> {
    +test() : void
  }
  class TestServiceImpl <<Service>> {
    +test() : void
  }
}

' --- Relatii ---
Application --> ApplicationConfiguration
TestDAOImpl ..|> ITestDAO
TestDAOImpl --> ITestDAO
TestDAOImpl --> SpringBootWithHinernateTest
TestController --> ITestService
TestServiceImpl ..|> ITestService
TestServiceImpl --> ITestDAO
TestServiceImpl --> SpringBootWithHinernateTest
TestServiceImpl --> SpringBootWithHinernateTest2
TestServiceImpl --> ITestService
TestDAOImpl ..|> ITestDAO
TestDAOImpl --> ITestDAO
TestController --> ITestService
TestServiceImpl ..|> ITestService
TestServiceImpl --> ITestDAO
TestServiceImpl --> ITestService
DubboProviderConfiguration --> DubboProperties
DubboComsumerConfiguration --> DubboProperties
UserController --> IPerson
TestDAOImpl ..|> ITestDAO
TestDAOImpl --> ITestDAO
PersonServiceImpl ..|> IPerson
PersonServiceImpl --> IPerson
PersonServiceImpl --> ITestDAO
TestServiceTest --> Account
TestServiceTest --> ITestService
TestServiceTest --> ITestXmlService
TestServiceTest --> Test
TestMapper --> Account
TestXmlMapper --> Account
TestController --> Account
TestController --> ITestService
TestController --> ITestXmlService
ITestXmlService --> Account
ITestService --> Account
TestServiceImpl ..|> ITestService
TestServiceImpl --> TestMapper
TestServiceImpl --> Account
TestServiceImpl --> ITestService
TestXmlServiceImpl ..|> ITestXmlService
TestXmlServiceImpl --> TestXmlMapper
TestXmlServiceImpl --> Account
TestXmlServiceImpl --> ITestXmlService
Application --> DynamicDataSourceRegister
Application --> MProxyTransactionManagementConfiguration
TestDAOImpl ..|> ITestDAO
TestDAOImpl --> TargetDataSource
TestDAOImpl --> ITestDAO
TestController --> ITestService
TestServiceImpl ..|> ITestService
TestServiceImpl --> ITestDAO
TestServiceImpl --> ITestService
AppTest --> Test
Scheduling --> ITestService
TestDAOImpl ..|> ITestDAO
TestDAOImpl --> ITestDAO
TestController --> ITestService
TestServiceImpl ..|> ITestService
TestServiceImpl --> ITestDAO
TestServiceImpl --> ITestService
ApiServiceImpl ..|> IApiService
ApiServiceImpl --> IApiService
TestRepository --> Test
TestController --> ITestService

@enduml