@startuml
package com.springboilerplate.app.auth; {
class AccountCredentials {
}

class AuthController {
}

class JwtAuthenticationResponse {
}

class AuthControllerTest {
}

}

package com.springboilerplate.app.passwordRestToken; {
class PasswordDto {
}

class PasswordResetToken {
}

class PasswordResetTokenController {
}

class PasswordResetTokenRepository {
}

class PasswordResetTokenService {
}

class PasswordResetTokenServiceImpl {
}

}

package com.springboilerplate.app.role; {
class Role {
}

class RoleRepository {
}

class RoleType {
}

class RoleMocks {
}

class RoleRepositoryTest {
}

class RoleStubs {
}

}

package com.springboilerplate.app.search; {
class HibernateSearchService {
}

class UserSearchService {
}

class UserSearchServiceTest {
}

}

package com.springboilerplate.app.user; {
class User {
}

class UserController {
}

class UserDto {
}

class UserDtoMapper {
}

class UserRepository {
}

class UserService {
}

class UserServiceImpl {
}

class EnvironmentMocks {
}

class MailServiceMocks {
}

class UserMocks {
}

class UserRepositoryTest {
}

class UserServiceImplTest {
}

class UserStubs {
}

}

package com.springboilerplate.app.userRole; {
class UserRole {
}

class UserRoleRepository {
}

class UserRoleRepositoryTest {
}

class UserRoleStubs {
}

}

package com.springboilerplate.config; {
class HibernateSearchConfig {
}

class MailConfig {
}

class MethodSecurityConfig {
}

class ModelMapperConfig {
}

class ObjectMapperConfig {
}

class SwaggerConfig {
}

class WebMvcConfig {
}

class WebSecurityConfig {
}

}

package com.springboilerplate.exceptions; {
class ApiError {
}

class CentralizedExceptionHandler {
}

class ExpiredTokenException {
}

class InvalidPasswordResetToken {
}

class InvalidTokenException {
}

class NoTokenException {
}

class RoleDoesNotExistException {
}

class SendingTokenException {
}

}

package com.springboilerplate.helper; {
class AsyncMailer {
}

class MailData {
}

class MailService {
}

class MailServiceImpl {
}

class SecurityHelper {
}

class MailServiceImplTest {
}

}

package com.springboilerplate.security; {
class CustomUserService {
}

class JwtAuthenticationEntryPoint {
}

class JwtAuthorizationTokenFilter {
}

class JwtTokenUtil {
}

class JwtUserDetailsService {
}

class CustomUserDetailsServiceTest {
}

class JwtTokenUtilTest {
}

class SecurityHelperMocks {
}

class UserDetailsStub {
}

}

package com.springboilerplate; {
class SpringBoilerplateApplication {
}

}

package com.springboilerplate.utils; {
class DbSeed {
}

class JsonUtils {
}

class SecurityUtils {
}

}

package com.springboilerplate.app.passwordResetToken; {
class PasswordResetTokenMocks {
}

class PasswordResetTokenRepositoryTest {
}

class PasswordResetTokenServiceImplTest {
}

class PasswordResetTokenStubs {
}

}

package com.springboilerplate.dtoMapper; {
class MapperMocks {
}

class UserDtoMapperTest {
}

}

package com.springboilerplate.mocks; {
class DataGenerator {
}

}

AuthController -- AccountCredentials
AuthController -- JwtAuthenticationResponse
AuthController -- User
AuthController -- UserService
AuthController -- CustomUserService
AuthController -- JwtTokenUtil
PasswordResetToken -- User
PasswordResetTokenController -- PasswordResetToken
PasswordResetTokenController -- PasswordResetTokenService
PasswordResetTokenController -- User
PasswordResetTokenController -- SecurityUtils
PasswordResetTokenRepository -- PasswordResetToken
PasswordResetTokenService -- PasswordResetToken
PasswordResetTokenService -- User
PasswordResetTokenServiceImpl -- PasswordResetToken
PasswordResetTokenServiceImpl -- PasswordResetTokenRepository
PasswordResetTokenServiceImpl -- PasswordResetTokenService
PasswordResetTokenServiceImpl -- User
PasswordResetTokenServiceImpl -- MailService
PasswordResetTokenServiceImpl -- SecurityHelper
Role -- RoleType
Role -- User
Role -- UserRole
RoleRepository -- Role
RoleRepository -- RoleType
UserSearchService -- HibernateSearchService
UserSearchService -- User
User -- UserRole
UserController -- PasswordDto
UserController -- Role
UserController -- RoleType
UserController -- UserSearchService
UserController -- User
UserController -- UserDto
UserController -- UserService
UserController -- SecurityUtils
UserDto -- User
UserDtoMapper -- User
UserDtoMapper -- UserDto
UserRepository -- User
UserService -- PasswordDto
UserService -- Role
UserService -- RoleType
UserService -- User
UserService -- UserDto
UserServiceImpl -- PasswordDto
UserServiceImpl -- Role
UserServiceImpl -- RoleRepository
UserServiceImpl -- RoleType
UserServiceImpl -- User
UserServiceImpl -- UserDto
UserServiceImpl -- UserDtoMapper
UserServiceImpl -- UserRepository
UserServiceImpl -- UserService
UserServiceImpl -- UserRole
UserServiceImpl -- RoleDoesNotExistException
UserRoleRepository -- Role
UserRoleRepository -- RoleRepository
UserRoleRepository -- User
UserRoleRepository -- UserRole
HibernateSearchConfig -- HibernateSearchService
MailConfig -- User
WebSecurityConfig -- User
WebSecurityConfig -- UserService
WebSecurityConfig -- JwtAuthenticationEntryPoint
WebSecurityConfig -- JwtAuthorizationTokenFilter
WebSecurityConfig -- JwtTokenUtil
WebSecurityConfig -- JwtUserDetailsService
CentralizedExceptionHandler -- PasswordResetToken
CentralizedExceptionHandler -- Role
CentralizedExceptionHandler -- ApiError
CentralizedExceptionHandler -- ExpiredTokenException
CentralizedExceptionHandler -- InvalidPasswordResetToken
CentralizedExceptionHandler -- InvalidTokenException
CentralizedExceptionHandler -- NoTokenException
CentralizedExceptionHandler -- RoleDoesNotExistException
CentralizedExceptionHandler -- SendingTokenException
InvalidPasswordResetToken -- PasswordResetToken
RoleDoesNotExistException -- Role
AsyncMailer -- MailData
MailServiceImpl -- AsyncMailer
MailServiceImpl -- MailData
MailServiceImpl -- MailService
SecurityHelper -- PasswordResetToken
SecurityHelper -- User
CustomUserService -- User
CustomUserService -- UserService
JwtAuthorizationTokenFilter -- User
JwtAuthorizationTokenFilter -- ExpiredTokenException
JwtAuthorizationTokenFilter -- InvalidTokenException
JwtAuthorizationTokenFilter -- JwtTokenUtil
JwtTokenUtil -- User
JwtUserDetailsService -- User
JwtUserDetailsService -- UserRepository
JwtUserDetailsService -- UserService
JwtUserDetailsService -- CustomUserService
DbSeed -- Role
DbSeed -- RoleRepository
DbSeed -- RoleType
DbSeed -- User
DbSeed -- UserRole
DbSeed -- UserRoleRepository
SecurityUtils -- User
AuthControllerTest -- AccountCredentials
AuthControllerTest -- AuthController
AuthControllerTest -- Role
AuthControllerTest -- RoleType
AuthControllerTest -- User
AuthControllerTest -- UserRole
AuthControllerTest -- JwtTokenUtil
AuthControllerTest -- JwtUserDetailsService
AuthControllerTest -- JsonUtils
PasswordResetTokenMocks -- PasswordResetToken
PasswordResetTokenMocks -- PasswordResetTokenRepository
PasswordResetTokenMocks -- PasswordResetTokenStubs
PasswordResetTokenRepositoryTest -- PasswordResetToken
PasswordResetTokenRepositoryTest -- PasswordResetTokenRepository
PasswordResetTokenRepositoryTest -- Role
PasswordResetTokenRepositoryTest -- User
PasswordResetTokenRepositoryTest -- PasswordResetTokenStubs
PasswordResetTokenRepositoryTest -- UserStubs
PasswordResetTokenServiceImplTest -- PasswordResetToken
PasswordResetTokenServiceImplTest -- PasswordResetTokenRepository
PasswordResetTokenServiceImplTest -- PasswordResetTokenService
PasswordResetTokenServiceImplTest -- PasswordResetTokenServiceImpl
PasswordResetTokenServiceImplTest -- User
PasswordResetTokenServiceImplTest -- MailService
PasswordResetTokenServiceImplTest -- SecurityHelper
PasswordResetTokenServiceImplTest -- PasswordResetTokenMocks
PasswordResetTokenServiceImplTest -- PasswordResetTokenStubs
PasswordResetTokenServiceImplTest -- MailServiceMocks
PasswordResetTokenServiceImplTest -- UserStubs
PasswordResetTokenServiceImplTest -- SecurityHelperMocks
PasswordResetTokenStubs -- PasswordResetToken
PasswordResetTokenStubs -- User
PasswordResetTokenStubs -- UserStubs
RoleMocks -- Role
RoleMocks -- RoleRepository
RoleMocks -- RoleType
RoleMocks -- RoleStubs
RoleRepositoryTest -- Role
RoleRepositoryTest -- RoleRepository
RoleRepositoryTest -- RoleType
RoleRepositoryTest -- RoleStubs
RoleStubs -- Role
RoleStubs -- RoleType
UserSearchServiceTest -- Role
UserSearchServiceTest -- RoleRepository
UserSearchServiceTest -- HibernateSearchService
UserSearchServiceTest -- UserSearchService
UserSearchServiceTest -- User
UserSearchServiceTest -- UserRepository
UserSearchServiceTest -- DataGenerator
MailServiceMocks -- MailService
UserMocks -- Role
UserMocks -- RoleType
UserMocks -- User
UserMocks -- UserDto
UserMocks -- UserRepository
UserMocks -- UserService
UserMocks -- UserStubs
UserRepositoryTest -- Role
UserRepositoryTest -- User
UserRepositoryTest -- UserRepository
UserRepositoryTest -- UserStubs
UserServiceImplTest -- Role
UserServiceImplTest -- RoleRepository
UserServiceImplTest -- RoleType
UserServiceImplTest -- User
UserServiceImplTest -- UserDto
UserServiceImplTest -- UserDtoMapper
UserServiceImplTest -- UserRepository
UserServiceImplTest -- UserService
UserServiceImplTest -- UserServiceImpl
UserServiceImplTest -- RoleMocks
UserServiceImplTest -- UserMocks
UserServiceImplTest -- UserStubs
UserServiceImplTest -- MapperMocks
UserStubs -- Role
UserStubs -- User
UserStubs -- UserDto
UserStubs -- UserRole
UserStubs -- RoleStubs
UserStubs -- UserRoleStubs
UserRoleRepositoryTest -- Role
UserRoleRepositoryTest -- RoleRepository
UserRoleRepositoryTest -- User
UserRoleRepositoryTest -- UserRole
UserRoleRepositoryTest -- UserRoleRepository
UserRoleRepositoryTest -- RoleRepositoryTest
UserRoleRepositoryTest -- RoleStubs
UserRoleRepositoryTest -- UserStubs
UserRoleStubs -- Role
UserRoleStubs -- User
UserRoleStubs -- UserRole
UserRoleStubs -- RoleStubs
MapperMocks -- User
MapperMocks -- UserDto
MapperMocks -- UserDtoMapper
MapperMocks -- UserStubs
UserDtoMapperTest -- User
UserDtoMapperTest -- UserDto
UserDtoMapperTest -- UserDtoMapper
UserDtoMapperTest -- UserStubs
MailServiceImplTest -- AsyncMailer
MailServiceImplTest -- MailData
MailServiceImplTest -- MailService
MailServiceImplTest -- MailServiceImpl
DataGenerator -- Role
DataGenerator -- RoleRepository
DataGenerator -- RoleType
DataGenerator -- User
DataGenerator -- UserRepository
DataGenerator -- UserRole
DataGenerator -- UserRoleRepository
DataGenerator -- RoleStubs
DataGenerator -- UserStubs
DataGenerator -- UserRoleStubs
CustomUserDetailsServiceTest -- User
CustomUserDetailsServiceTest -- UserRepository
CustomUserDetailsServiceTest -- JwtUserDetailsService
CustomUserDetailsServiceTest -- UserMocks
JwtTokenUtilTest -- User
JwtTokenUtilTest -- JwtTokenUtil
JwtTokenUtilTest -- UserDetailsStub
SecurityHelperMocks -- PasswordResetToken
SecurityHelperMocks -- User
SecurityHelperMocks -- SecurityHelper
UserDetailsStub -- User
@enduml