@startuml

package com.alibou.security {
  class SecurityApplicationTests {
  }
  class SecurityApplication {
    +main() : void
    +commandLineRunner() : CommandLineRunner
  }
}

package com.alibou.security.auditing {
  class ApplicationAuditAware {
    +getCurrentAuditor() : Optional<Integer>
  }
}

package com.alibou.security.auth {
  class AuthenticationController <<Controller>> {
    -service : AuthenticationService
    +register() : ResponseEntity<AuthenticationResponse>
    +authenticate() : ResponseEntity<AuthenticationResponse>
    +refreshToken() : void
  }
  class RegisterRequest {
    -firstname : String
    -lastname : String
    -email : String
    -password : String
    -role : Role
  }
  class AuthenticationResponse {
    -accessToken : String
    -refreshToken : String
  }
  class AuthenticationRequest {
    -email : String
  }
  class AuthenticationService <<Service>> {
    -repository : UserRepository
    -tokenRepository : TokenRepository
    -passwordEncoder : PasswordEncoder
    -jwtService : JwtService
    -authenticationManager : AuthenticationManager
    -authHeader : String
    -refreshToken : String
    -userEmail : String
    +register() : AuthenticationResponse
    +authenticate() : AuthenticationResponse
    +refreshToken() : void
  }
}

package com.alibou.security.book {
  interface BookRepository {
  }
  class Book <<Entity>> {
    -id : Integer
    -author : String
    -isbn : String
    -createDate : LocalDateTime
    -lastModified : LocalDateTime
    -createdBy : Integer
    -lastModifiedBy : Integer
  }
  class BookRequest {
    -id : Integer
    -author : String
    -isbn : String
  }
  class BookController <<Controller>> {
    -service : BookService
    +findAllBooks() : ResponseEntity<List<Book>>
  }
  class BookService <<Service>> {
    -repository : BookRepository
    +save() : void
    +findAll() : List<Book>
  }
}

package com.alibou.security.config {
  class ApplicationConfig {
    -repository : UserRepository
    +userDetailsService() : UserDetailsService
    +authenticationProvider() : AuthenticationProvider
    +auditorAware() : AuditorAware<Integer>
    +authenticationManager() : AuthenticationManager
    +passwordEncoder() : PasswordEncoder
  }
  class LogoutService <<Service>> {
    -tokenRepository : TokenRepository
    -authHeader : String
    -jwt : String
    +logout() : void
  }
  class JwtService <<Service>> {
    -secretKey : String
    -jwtExpiration : long
    -refreshExpiration : long
    -claims : Claims
    -username : String
    +extractUsername() : String
    +generateToken() : String
    +generateToken() : String
    +generateRefreshToken() : String
    +isTokenValid() : boolean
  }
  class OpenApiConfig {
  }
  class JwtAuthenticationFilter {
    -jwtService : JwtService
    -userDetailsService : UserDetailsService
    -tokenRepository : TokenRepository
    -authHeader : String
    -jwt : String
    -userEmail : String
    +doFilterInternal() : void
  }
  class SecurityConfiguration {
    -WHITE_LIST_URL : String[]
    -jwtAuthFilter : JwtAuthenticationFilter
    -authenticationProvider : AuthenticationProvider
    -logoutHandler : LogoutHandler
    +securityFilterChain() : SecurityFilterChain
  }
}

package com.alibou.security.demo {
  class AdminController <<Controller>> {
    +post() : String
    +put() : String
    +delete() : String
  }
  class DemoController <<Controller>> {
    +sayHello() : ResponseEntity<String>
  }
  class ManagementController <<Controller>> {
    +post() : String
    +put() : String
    +delete() : String
  }
}

package com.alibou.security.token {
  enum TokenType {
  }
  interface TokenRepository {
  }
  class Token <<Entity>> {
    -id : Integer
    -token : String
    -tokenType : TokenType
    -revoked : boolean
    -expired : boolean
    -user : User
  }
}

package com.alibou.security.user {
  class ChangePasswordRequest {
    -currentPassword : String
    -newPassword : String
    -confirmationPassword : String
  }
  class UserService <<Service>> {
    -passwordEncoder : PasswordEncoder
    -repository : UserRepository
    +changePassword() : void
  }
  class User <<Entity>> {
    -id : Integer
    -firstname : String
    -lastname : String
    -email : String
    -password : String
    -role : Role
    -tokens : List<Token>
    +getPassword() : String
    +getUsername() : String
    +isAccountNonExpired() : boolean
    +isAccountNonLocked() : boolean
    +isCredentialsNonExpired() : boolean
    +isEnabled() : boolean
  }
  enum Permission {
    -permission : String
  }
  interface UserRepository {
  }
  enum Role {
    -permissions : Set<Permission>
    +getAuthorities() : List<SimpleGrantedAuthority>
  }
  class UserController <<Controller>> {
    -service : UserService
  }
}

' --- Relatii ---
SecurityApplication --> AuthenticationService
SecurityApplication --> RegisterRequest
SecurityApplication --> Role
Token --> User
ApplicationConfig --> ApplicationAuditAware
ApplicationConfig --> UserRepository
LogoutService --> TokenRepository
JwtAuthenticationFilter --> TokenRepository
RegisterRequest --> Role
AuthenticationService --> JwtService
AuthenticationService --> Token
AuthenticationService --> TokenRepository
AuthenticationService --> TokenType
AuthenticationService --> Role
AuthenticationService --> User
AuthenticationService --> UserRepository
User --> Token
ApplicationAuditAware --> User

@enduml