@startuml

package org.training.account.service {
  class AccountServiceApplicationTests {
  }
  class AccountServiceApplication {
    +main() : void
  }
}

package org.training.account.service.configuration {
  class FeignClientErrorDecoder {
    +decode() : Exception
  }
}

package org.training.account.service.controller {
  class AccountController <<Controller>> {
    -accountService : AccountService
    +createAccount() : ResponseEntity<Response>
    +updateAccountStatus() : ResponseEntity<Response>
    +readByAccountNumber() : ResponseEntity<AccountDto>
    +updateAccount() : ResponseEntity<Response>
    +accountBalance() : ResponseEntity<String>
    +getTransactionsFromAccountId() : ResponseEntity<List<TransactionResponse>>
    +closeAccount() : ResponseEntity<Response>
    +readAccountByUserId() : ResponseEntity<AccountDto>
  }
}

package org.training.account.service.exception {
  class GlobalErrorCode {
    -NOT_FOUND : String
    -CONFLICT : String
    -BAD_REQUEST : String
  }
  class GlobalException {
    -errorCode : String
    -errorMessage : String
    +getErrorCode() : String
    +getErrorMessage() : String
  }
  class AccountClosingException {
  }
  class GlobalExceptionHandler {
    -badRequest : String
    -conflict : String
    -notFound : String
    +handleMethodArgumentNotValid() : ResponseEntity<Object>
    +handleGlobalException() : ResponseEntity<Object>
  }
  class InSufficientFunds {
  }
  class ErrorResponse {
    -errorCode : String
    -message : String
  }
  class AccountStatusException {
  }
  class ResourceConflict {
  }
  class ResourceNotFound {
  }
}

package org.training.account.service.external {
  interface UserService {
  }
  interface TransactionService {
  }
  interface SequenceService {
  }
}

package org.training.account.service.model {
  enum AccountStatus {
  }
  enum AccountType {
  }
  class Constants {
    -ACC_PREFIX : String
  }
}

package org.training.account.service.model.dto {
  class AccountDto {
    -accountId : Long
    -accountNumber : String
    -accountType : String
    -accountStatus : String
    -availableBalance : BigDecimal
    -userId : Long
  }
  class AccountStatusUpdate {
  }
}

package org.training.account.service.model.dto.external {
  class TransactionResponse {
    -referenceId : String
    -accountId : String
    -transactionType : String
    -amount : BigDecimal
    -localDateTime : LocalDateTime
    -transactionStatus : String
    -comments : String
  }
  class UserDto {
    -userId : Long
    -firstName : String
    -lastName : String
    -emailId : String
    -password : String
    -identificationNumber : String
    -authId : String
  }
  class SequenceDto {
    -sequenceId : long
    -accountNumber : long
  }
}

package org.training.account.service.model.dto.response {
  class Response {
    -responseCode : String
    -message : String
  }
}

package org.training.account.service.model.entity {
  class Account <<Entity>> {
    -accountId : Long
    -accountNumber : String
    -accountType : AccountType
    -accountStatus : AccountStatus
    -openingDate : LocalDate
    -availableBalance : BigDecimal
    -userId : Long
  }
}

package org.training.account.service.model.mapper {
  class AccountMapper {
    +convertToEntity() : Account
    +convertToDto() : AccountDto
  }
  class BaseMapper {
    +convertToEntity() : E
    +convertToDto() : D
    +convertToEntity() : Collection<E>
    +convertToDto() : Collection<D>
    +convertToEntityList() : List<E>
    +convertToDtoList() : List<D>
  }
}

package org.training.account.service.repository {
  interface AccountRepository {
  }
}

package org.training.account.service.service {
  interface AccountService {
  }
}

package org.training.account.service.service.implementation {
  class AccountServiceImpl <<Service>> {
    -userService : UserService
    -accountRepository : AccountRepository
    -sequenceService : SequenceService
    -transactionService : TransactionService
    -accountMapper : AccountMapper
    -success : String
    +createAccount() : Response
    +updateStatus() : Response
    +readAccountByAccountNumber() : AccountDto
    +updateAccount() : Response
    +getBalance() : String
    +getTransactionsFromAccountId() : List<TransactionResponse>
    +closeAccount() : Response
    +readAccountByUserId() : AccountDto
  }
}

package org.training.api.gateway {
  class ApiGatewayApplicationTests {
  }
  class ApiGatewayApplication {
    +main() : void
  }
}

package org.training.api.gateway.config {
  class SecurityConfig {
    +securityWebFilterChain() : SecurityWebFilterChain
  }
}

package org.training.fundtransfer {
  class FundTransferApplication {
    +main() : void
  }
}

package org.training.fundtransfer.configuration {
  class FeignClientErrorDecoder {
    +decode() : Exception
  }
}

package org.training.fundtransfer.controller {
  class FundTransferController <<Controller>> {
    -fundTransferService : FundTransferService
    +fundTransfer() : ResponseEntity<FundTransferResponse>
    +getTransferDetailsFromReferenceId() : ResponseEntity<FundTransferDto>
    +getAllTransfersByAccountId() : ResponseEntity<List<FundTransferDto>>
  }
}

package org.training.fundtransfer.exception {
  class GlobalErrorCode {
    -NOT_FOUND : String
    -NOT_ACCEPTABLE : String
  }
  class GlobalException {
    -errorCode : String
    -message : String
  }
  class GlobalExceptionHandler {
    -badRequest : String
    +handleMethodArgumentNotValid() : ResponseEntity<Object>
    +handleGlobalException() : ResponseEntity<Object>
  }
  class InsufficientBalance {
  }
  class ErrorResponse {
    -errorCode : String
    -message : String
  }
  class ResourceNotFound {
  }
  class AccountUpdateException {
  }
}

package org.training.fundtransfer.external {
  interface AccountService {
  }
  interface TransactionService {
  }
}

package org.training.fundtransfer.model {
  enum TransactionStatus {
  }
  enum TransferType {
  }
}

package org.training.fundtransfer.model.dto {
  class FundTransferDto {
    -transactionReference : String
    -fromAccount : String
    -toAccount : String
    -amount : BigDecimal
    -status : TransactionStatus
    -transferType : TransferType
    -transferredOn : LocalDateTime
  }
  class Account {
    -accountId : Long
    -accountNumber : String
    -accountType : String
    -accountStatus : String
    -availableBalance : BigDecimal
    -userId : Long
  }
  class Transaction {
    -accountId : String
    -transactionType : String
    -amount : BigDecimal
    -description : String
  }
}

package org.training.fundtransfer.model.dto.request {
  class FundTransferRequest {
    -fromAccount : String
    -toAccount : String
    -amount : BigDecimal
  }
}

package org.training.fundtransfer.model.dto.response {
  class Response {
    -responseCode : String
    -message : String
  }
  class FundTransferResponse {
    -transactionId : String
    -message : String
  }
}

package org.training.fundtransfer.model.entity {
  class FundTransfer <<Entity>> {
    -fundTransferId : Long
    -transactionReference : String
    -fromAccount : String
    -toAccount : String
    -amount : BigDecimal
    -status : TransactionStatus
    -transferType : TransferType
    -transferredOn : LocalDateTime
  }
}

package org.training.fundtransfer.model.mapper {
  class BaseMapper {
    +convertToEntity() : E
    +convertToDto() : D
    +convertToEntity() : Collection<E>
    +convertToDto() : Collection<D>
    +covertToEntityList() : List<E>
    +convertToDtoList() : List<D>
    +convertToEntitySet() : Set<E>
  }
  class FundTransferMapper {
    +convertToEntity() : FundTransfer
    +convertToDto() : FundTransferDto
  }
}

package org.training.fundtransfer.repository {
  interface FundTransferRepository {
  }
}

package org.training.fundtransfer.service {
  interface FundTransferService {
  }
}

package org.training.fundtransfer.service.implementation {
  class FundTransferServiceImpl <<Service>> {
    -accountService : AccountService
    -fundTransferRepository : FundTransferRepository
    -transactionService : TransactionService
    -ok : String
    -fundTransferMapper : FundTransferMapper
    +fundTransfer() : FundTransferResponse
    +getTransferDetailsFromReferenceId() : FundTransferDto
    +getAllTransfersByAccountId() : List<FundTransferDto>
  }
}

package org.training.sequence.generator {
  class SequenceGeneratorApplication {
    +main() : void
  }
}

package org.training.sequence.generator.controller {
  class SequenceController <<Controller>> {
    -sequenceService : SequenceService
    +generateAccountNumber() : Sequence
  }
}

package org.training.sequence.generator.model.entity {
  class Sequence <<Entity>> {
    -sequenceId : long
    -accountNumber : long
  }
}

package org.training.sequence.generator.reporitory {
  interface SequenceRepository {
  }
}

package org.training.sequence.generator.service {
  interface SequenceService {
  }
}

package org.training.sequence.generator.service.implementation {
  class SequenceServiceImpl <<Service>> {
    -sequenceRepository : SequenceRepository
    +create() : Sequence
  }
}

package org.training.service.registry {
  class ServiceRegistryApplicationTests {
  }
  class ServiceRegistryApplication {
    +main() : void
  }
}

package org.training.transactions {
  class TransactionServiceApplication {
    +main() : void
  }
}

package org.training.transactions.configuration {
  class FeignClientErrorDecoder {
    +decode() : Exception
  }
}

package org.training.transactions.controller {
  class TransactionController <<Controller>> {
    -transactionService : TransactionService
    +addTransactions() : ResponseEntity<Response>
    +makeInternalTransaction() : ResponseEntity<Response>
    +getTransactions() : ResponseEntity<List<TransactionRequest>>
    +getTransactionByTransactionReference() : ResponseEntity<List<TransactionRequest>>
  }
}

package org.training.transactions.exception {
  class GlobalErrorCode {
    -NOT_FOUND : String
    -BAD_REQUEST : String
  }
  class GlobalException {
    -errorCode : String
    -message : String
  }
  class GlobalExceptionHandler {
    +handleGlobalException() : ResponseEntity<Object>
  }
  class InsufficientBalance {
  }
  class ErrorResponse {
    -errorCode : String
    -message : String
  }
  class AccountStatusException {
  }
  class ResourceNotFound {
  }
}

package org.training.transactions.external {
  interface AccountService {
  }
}

package org.training.transactions.model {
  enum TransactionStatus {
  }
  enum TransactionType {
  }
}

package org.training.transactions.model.dto {
  class TransactionDto {
    -accountId : String
    -transactionType : String
    -amount : BigDecimal
    -description : String
  }
}

package org.training.transactions.model.entity {
  class Transaction <<Entity>> {
    -transactionId : Long
    -referenceId : String
    -accountId : String
    -transactionType : TransactionType
    -amount : BigDecimal
    -transactionDate : LocalDateTime
    -status : TransactionStatus
    -comments : String
  }
}

package org.training.transactions.model.external {
  class Account {
    -accountId : Long
    -accountNumber : String
    -accountType : String
    -accountStatus : String
    -availableBalance : BigDecimal
    -userId : Long
  }
}

package org.training.transactions.model.mapper {
  class TransactionMapper {
    +convertToEntity() : Transaction
    +convertToDto() : TransactionDto
  }
  class BaseMapper {
    +convertToEntity() : E
    +convertToDto() : D
    +convertToEntity() : Collection<E>
    +convertToDto() : Collection<D>
    +convertToEntityList() : List<E>
    +convertToDtoList() : List<D>
  }
}

package org.training.transactions.model.response {
  class Response {
    -responseCode : String
    -message : String
  }
  class TransactionRequest {
    -referenceId : String
    -accountId : String
    -transactionType : String
    -amount : BigDecimal
    -localDateTime : LocalDateTime
    -transactionStatus : String
    -comments : String
  }
}

package org.training.transactions.repository {
  interface TransactionRepository {
  }
}

package org.training.transactions.service {
  interface TransactionService {
  }
}

package org.training.transactions.service.implementation {
  class TransactionServiceImpl <<Service>> {
    -transactionRepository : TransactionRepository
    -accountService : AccountService
    -transactionMapper : TransactionMapper
    -ok : String
    +addTransaction() : Response
    +internalTransaction() : Response
    +getTransaction() : List<TransactionRequest>
    +getTransactionByTransactionReference() : List<TransactionRequest>
  }
}

package org.training.user.service {
  class UserServiceApplication {
    +main() : void
  }
}

package org.training.user.service.config {
  class Configurations {
    +passwordEncoder() : BCryptPasswordEncoder
  }
  class KeyCloakManager {
    -keyCloakProperties : KeyCloakProperties
    +getKeyCloakInstanceWithRealm() : RealmResource
  }
  class KeyCloakProperties {
    -serverUrl : String
    -realm : String
    -clientId : String
    -clientSecret : String
    -keycloakInstance : Keycloak
    +getKeycloakInstance() : Keycloak
    +getRealm() : String
  }
  class FeignClientErrorDecoder {
    +decode() : Exception
  }
}

package org.training.user.service.controller {
  class UserController <<Controller>> {
    -userService : UserService
    +createUser() : ResponseEntity<Response>
    +readAllUsers() : ResponseEntity<List<UserDto>>
    +readUserByAuthId() : ResponseEntity<UserDto>
    +updateUserStatus() : ResponseEntity<Response>
    +updateUser() : ResponseEntity<Response>
    +readUserById() : ResponseEntity<UserDto>
    +readUserByAccountId() : ResponseEntity<UserDto>
  }
}

package org.training.user.service.exception {
  class GlobalException {
    -message : String
    -errorCode : String
  }
  class GlobalExceptionHandler {
    -errorCodeBadRequest : String
    -errorCodeConflict : String
    -errorCodeNotFound : String
    +handleMethodArgumentNotValid() : ResponseEntity<Object>
    +handleGlobalException() : ResponseEntity<Object>
  }
  class GlobalError {
    -NOT_FOUND : String
  }
  class ResourceConflictException {
  }
  class EmptyFields {
  }
  class ErrorResponse {
    -errorCode : String
    -errorMessage : String
  }
  class ResourceNotFound {
  }
}

package org.training.user.service.external {
  interface AccountService {
  }
}

package org.training.user.service.model {
  enum Status {
  }
}

package org.training.user.service.model.dto {
  class UserUpdateStatus {
    -status : Status
  }
  class CreateUser {
    -firstName : String
    -lastName : String
    -contactNumber : String
    -emailId : String
    -password : String
  }
  class UserProfileDto {
    -firstName : String
    -lastName : String
    -gender : String
    -address : String
    -occupation : String
    -martialStatus : String
    -nationality : String
  }
  class UserUpdate {
    -firstName : String
    -lastName : String
    -contactNo : String
    -address : String
    -gender : String
    -occupation : String
    -martialStatus : String
    -nationality : String
  }
  class UserDto {
    -userId : Long
    -emailId : String
    -password : String
    -identificationNumber : String
    -authId : String
    -status : Status
    -userProfileDto : UserProfileDto
  }
}

package org.training.user.service.model.dto.external {
  class AccountResponse {
    -accountNumber : String
    -actualBalance : BigDecimal
    -id : Integer
    -type : String
    -status : String
    -availableBalance : BigDecimal
  }
  class UserCreate {
    -userId : Long
    -firstName : String
    -lastName : String
    -identificationNumber : String
  }
}

package org.training.user.service.model.dto.response {
  class Response {
    -responseCode : String
    -responseMessage : String
  }
  class ReadUser {
    -firstName : String
    -lastName : String
    -emailId : String
    -contactNumber : String
    -status : Status
  }
}

package org.training.user.service.model.entity {
  class User <<Entity>> {
    -userId : Long
    -emailId : String
    -contactNo : String
    -authId : String
    -identificationNumber : String
    -creationOn : LocalDate
    -status : Status
    -userProfile : UserProfile
  }
  class UserProfile <<Entity>> {
    -userProfileId : Long
    -firstName : String
    -lastName : String
    -gender : String
    -address : String
    -occupation : String
    -martialStatus : String
    -nationality : String
  }
}

package org.training.user.service.model.external {
  class Account {
    -accountId : Long
    -accountNumber : String
    -accountType : String
    -accountStatus : String
    -availableBalance : BigDecimal
    -userId : Long
  }
}

package org.training.user.service.model.mapper {
  class BaseMapper {
    +convertToEntity() : E
    +convertToDto() : D
    +convertToEntity() : Collection<E>
    +convertToDto() : Collection<D>
    +covertToEntityList() : List<E>
    +convertToDtoList() : List<D>
    +convertToEntitySet() : Set<E>
    +convertToDtoSet() : Set<D>
  }
  class UserMapper {
    -mapper : ModelMapper
    +convertToEntity() : User
    +convertToDto() : UserDto
  }
}

package org.training.user.service.repository {
  interface UserRepository {
  }
}

package org.training.user.service.service {
  interface UserService {
  }
  interface KeycloakService {
  }
}

package org.training.user.service.service.implementation {
  class KeycloakServiceImpl <<Service>> {
    -keyCloakManager : KeyCloakManager
    +createUser() : Integer
    +readUserByEmail() : List<UserRepresentation>
    +readUsers() : List<UserRepresentation>
    +readUser() : UserRepresentation
    +updateUser() : void
  }
  class UserServiceImpl <<Service>> {
    -userRepository : UserRepository
    -keycloakService : KeycloakService
    -accountService : AccountService
    -userMapper : UserMapper
    -responseCodeSuccess : String
    -responseCodeNotFound : String
    +createUser() : Response
    +readAllUsers() : List<UserDto>
    +readUser() : UserDto
    +updateUserStatus() : Response
    +readUserById() : UserDto
    +updateUser() : Response
    +readUserByAccountId() : UserDto
  }
}

package org.training.user.service.utils {
  class FieldChecker {
    +hasEmptyFields() : boolean
  }
}

' --- Relatii ---
FeignClientErrorDecoder --> Response
FeignClientErrorDecoder --> GlobalException
FundTransferRepository --> FundTransfer
FundTransferController --> FundTransferDto
FundTransferController --> FundTransferRequest
FundTransferController --> FundTransferResponse
FundTransferController --> FundTransferService
FundTransferDto --> TransactionStatus
FundTransferDto --> TransferType
FundTransfer --> TransactionStatus
FundTransfer --> TransferType
FundTransferMapper --|> BaseMapper
FundTransferMapper --> FundTransferDto
FundTransferMapper --> FundTransfer
AccountService --> Account
AccountService --> Response
TransactionService --> Transaction
TransactionService --> Response
FundTransferService --> FundTransferDto
FundTransferService --> FundTransferRequest
FundTransferService --> FundTransferResponse
FundTransferServiceImpl ..|> FundTransferService
FundTransferServiceImpl --> AccountUpdateException
FundTransferServiceImpl --> GlobalErrorCode
FundTransferServiceImpl --> InsufficientBalance
FundTransferServiceImpl --> ResourceNotFound
FundTransferServiceImpl --> AccountService
FundTransferServiceImpl --> TransactionService
FundTransferServiceImpl --> FundTransferMapper
FundTransferServiceImpl --> TransactionStatus
FundTransferServiceImpl --> TransferType
FundTransferServiceImpl --> Account
FundTransferServiceImpl --> FundTransferDto
FundTransferServiceImpl --> Transaction
FundTransferServiceImpl --> FundTransferRequest
FundTransferServiceImpl --> FundTransferResponse
FundTransferServiceImpl --> FundTransfer
FundTransferServiceImpl --> FundTransferRepository
FundTransferServiceImpl --> FundTransferService
InsufficientBalance --|> GlobalException
ResourceNotFound --|> GlobalException
AccountUpdateException --|> GlobalException
FeignClientErrorDecoder --> Response
FeignClientErrorDecoder --> GlobalException
AccountRepository --> AccountType
AccountRepository --> Account
AccountController --> AccountDto
AccountController --> AccountStatusUpdate
AccountController --> Response
AccountController --> TransactionResponse
AccountController --> AccountService
AccountStatusUpdate --> AccountStatus
Account --> AccountStatus
Account --> AccountType
AccountMapper --|> BaseMapper
AccountMapper --> AccountDto
AccountMapper --> Account
UserService --> UserDto
TransactionService --> TransactionResponse
SequenceService --> SequenceDto
AccountService --> AccountDto
AccountService --> AccountStatusUpdate
AccountService --> Response
AccountService --> TransactionResponse
AccountServiceImpl ..|> AccountService
AccountServiceImpl --> SequenceService
AccountServiceImpl --> TransactionService
AccountServiceImpl --> UserService
AccountServiceImpl --> AccountStatus
AccountServiceImpl --> AccountType
AccountServiceImpl --> AccountDto
AccountServiceImpl --> AccountStatusUpdate
AccountServiceImpl --> UserDto
AccountServiceImpl --> Response
AccountServiceImpl --> Account
AccountServiceImpl --> AccountMapper
AccountServiceImpl --> TransactionResponse
AccountServiceImpl --> AccountRepository
AccountServiceImpl --> AccountService
AccountClosingException --|> GlobalException
InSufficientFunds --|> GlobalException
AccountStatusException --|> GlobalException
ResourceConflict --|> GlobalException
ResourceNotFound --|> GlobalException
FeignClientErrorDecoder --> Response
FeignClientErrorDecoder --> GlobalException
TransactionRepository --> Transaction
TransactionController --> TransactionDto
TransactionController --> Response
TransactionController --> TransactionRequest
TransactionController --> TransactionService
TransactionDto --> TransactionType
Transaction --> TransactionStatus
Transaction --> TransactionType
TransactionMapper --|> BaseMapper
TransactionMapper --> TransactionDto
TransactionMapper --> Transaction
AccountService --> Account
AccountService --> Response
TransactionService --> TransactionDto
TransactionService --> Response
TransactionService --> TransactionRequest
TransactionServiceImpl ..|> TransactionService
TransactionServiceImpl --> AccountStatusException
TransactionServiceImpl --> GlobalErrorCode
TransactionServiceImpl --> InsufficientBalance
TransactionServiceImpl --> ResourceNotFound
TransactionServiceImpl --> AccountService
TransactionServiceImpl --> TransactionStatus
TransactionServiceImpl --> TransactionType
TransactionServiceImpl --> TransactionDto
TransactionServiceImpl --> Transaction
TransactionServiceImpl --> Account
TransactionServiceImpl --> TransactionMapper
TransactionServiceImpl --> Response
TransactionServiceImpl --> TransactionRequest
TransactionServiceImpl --> TransactionRepository
TransactionServiceImpl --> TransactionService
InsufficientBalance --|> GlobalException
AccountStatusException --|> GlobalException
ResourceNotFound --|> GlobalException
SequenceRepository --> Sequence
SequenceController --> Sequence
SequenceController --> SequenceService
SequenceService --> Sequence
SequenceServiceImpl ..|> SequenceService
SequenceServiceImpl --> Sequence
SequenceServiceImpl --> SequenceRepository
SequenceServiceImpl --> SequenceService
UserRepository --> User
FeignClientErrorDecoder --> Response
FeignClientErrorDecoder --> GlobalException
UserController --> CreateUser
UserController --> UserDto
UserController --> UserUpdate
UserController --> UserUpdateStatus
UserController --> Response
UserController --> UserService
UserUpdateStatus --> Status
UserDto --> Status
ReadUser --> Status
User --> Status
UserMapper --|> BaseMapper
UserMapper --> UserDto
UserMapper --> UserProfileDto
UserMapper --> User
UserMapper --> UserProfile
AccountService --> Account
UserService --> CreateUser
UserService --> UserDto
UserService --> UserUpdate
UserService --> UserUpdateStatus
UserService --> Response
KeycloakServiceImpl ..|> KeycloakService
KeycloakServiceImpl --> KeyCloakManager
KeycloakServiceImpl --> KeycloakService
UserServiceImpl ..|> UserService
UserServiceImpl --> EmptyFields
UserServiceImpl --> ResourceConflictException
UserServiceImpl --> ResourceNotFound
UserServiceImpl --> AccountService
UserServiceImpl --> Status
UserServiceImpl --> CreateUser
UserServiceImpl --> UserDto
UserServiceImpl --> UserUpdate
UserServiceImpl --> UserUpdateStatus
UserServiceImpl --> Response
UserServiceImpl --> User
UserServiceImpl --> UserProfile
UserServiceImpl --> Account
UserServiceImpl --> UserMapper
UserServiceImpl --> UserRepository
UserServiceImpl --> KeycloakService
UserServiceImpl --> UserService
UserServiceImpl --> FieldChecker
ResourceConflictException --|> GlobalException
EmptyFields --|> GlobalException
ResourceNotFound --|> GlobalException

@enduml