@startuml

  class MavenWrapperDownloader {
    -WRAPPER_VERSION : String
    -DEFAULT_DOWNLOAD_URL : String
    -MAVEN_WRAPPER_PROPERTIES_PATH : String
    -MAVEN_WRAPPER_JAR_PATH : String
    -PROPERTY_NAME_WRAPPER_URL : String
    +main() : void
    +getPasswordAuthentication() : PasswordAuthentication
  }

package com.bezkoder.spring.jwt.mongodb {
  class SpringBootSecurityJwtMongodbApplicationTests {
  }
  class SpringBootSecurityJwtMongodbApplication {
    +main() : void
  }
}

package com.bezkoder.spring.jwt.mongodb.controllers {
  class AuthController <<Controller>> {
  }
  class TestController <<Controller>> {
    +allAccess() : String
    +userAccess() : String
    +moderatorAccess() : String
    +adminAccess() : String
  }
}

package com.bezkoder.spring.jwt.mongodb.models {
  class User {
    -id : String
    -username : String
    -email : String
    -password : String
    -roles : Set<Role>
    +getId() : String
    +setId() : void
    +getUsername() : String
    +setUsername() : void
    +getEmail() : String
    +setEmail() : void
    +getPassword() : String
    +setPassword() : void
  }
  enum ERole {
  }
  class Role {
    -id : String
    -name : ERole
    +getId() : String
    +setId() : void
    +getName() : ERole
    +setName() : void
  }
}

package com.bezkoder.spring.jwt.mongodb.payload.request {
  class SignupRequest {
    -username : String
    -email : String
    -roles : Set<String>
    -password : String
    +getUsername() : String
    +setUsername() : void
    +getEmail() : String
    +setEmail() : void
    +getPassword() : String
    +setPassword() : void
    +getRoles() : Set<String>
    +setRole() : void
  }
  class LoginRequest {
    -username : String
    -password : String
    +getUsername() : String
    +setUsername() : void
    +getPassword() : String
    +setPassword() : void
  }
}

package com.bezkoder.spring.jwt.mongodb.payload.response {
  class MessageResponse {
    -message : String
    +getMessage() : String
    +setMessage() : void
  }
  class JwtResponse {
    -token : String
    -type : String
    -id : String
    -username : String
    -email : String
    -roles : List<String>
    +getAccessToken() : String
    +setAccessToken() : void
    +getTokenType() : String
    +setTokenType() : void
    +getId() : String
    +setId() : void
    +getEmail() : String
    +setEmail() : void
  }
}

package com.bezkoder.spring.jwt.mongodb.repository {
  interface RoleRepository {
  }
  interface UserRepository {
  }
}

package com.bezkoder.spring.jwt.mongodb.security {
  class WebSecurityConfig {
    -unauthorizedHandler : AuthEntryPointJwt
    +authenticationJwtTokenFilter() : AuthTokenFilter
    +configure() : void
    +authenticationProvider() : DaoAuthenticationProvider
    +authenticationManagerBean() : AuthenticationManager
    +authenticationManager() : AuthenticationManager
    +passwordEncoder() : PasswordEncoder
    +configure() : void
    +filterChain() : SecurityFilterChain
  }
}

package com.bezkoder.spring.jwt.mongodb.security.jwt {
  class JwtUtils {
    -logger : Logger
    -jwtSecret : String
    -jwtExpirationMs : int
    +generateJwtToken() : String
    +getUserNameFromJwtToken() : String
    +validateJwtToken() : boolean
  }
  class AuthEntryPointJwt {
    -logger : Logger
    +commence() : void
  }
  class AuthTokenFilter {
    -jwtUtils : JwtUtils
    -userDetailsService : UserDetailsServiceImpl
    -logger : Logger
    +doFilterInternal() : void
  }
}

package com.bezkoder.spring.jwt.mongodb.security.services {
  class UserDetailsServiceImpl <<Service>> {
    +loadUserByUsername() : UserDetails
  }
  class UserDetailsImpl {
    -serialVersionUID : long
    -id : String
    -username : String
    -email : String
    -password : String
    +build() : UserDetailsImpl
    +getId() : String
    +getEmail() : String
    +getPassword() : String
    +getUsername() : String
    +isAccountNonExpired() : boolean
    +isAccountNonLocked() : boolean
    +isCredentialsNonExpired() : boolean
  }
}

' --- Relatii ---
RoleRepository --> ERole
RoleRepository --> Role
UserRepository --> User
WebSecurityConfig --> AuthEntryPointJwt
WebSecurityConfig --> AuthTokenFilter
WebSecurityConfig --> UserDetailsServiceImpl
JwtUtils --> UserDetailsImpl
AuthTokenFilter --> UserDetailsServiceImpl
UserDetailsServiceImpl --> User
UserDetailsServiceImpl --> UserRepository
UserDetailsImpl --> User
AuthController --> ERole
AuthController --> Role
AuthController --> User
AuthController --> LoginRequest
AuthController --> SignupRequest
AuthController --> JwtResponse
AuthController --> MessageResponse
AuthController --> RoleRepository
AuthController --> UserRepository
AuthController --> JwtUtils
AuthController --> UserDetailsImpl

@enduml