@startuml

  class PasswordEncryptor {
    -passwordEncoder : PasswordEncoder
    -admin : String
    -user : String
    +encode() : void
  }
  class RsaEncryptor {
    -rsaUtil : RsaUtils
    -publicKey : PublicKey
    -privateKey : PrivateKey
    -data : String
    -encrypted : byte[]
    -decrypted : byte[]
    -data : String
    -keyPair : KeyPair
    -publicKey : PublicKey
    -privateKey : PrivateKey
    +loadPem() : void
    +genKeyAndUsing() : void
  }
  class JasyptStringEncryptor {
    -stringEncryptor : StringEncryptor
    -mysql : String
    -name : String
    -password : String
    +encode() : void
  }
  class CodeGenerator {
    -DATABASE : String
    -JDBC_URL : String
    -JDBC_USERNAME : String
    -JDBC_PASSWORD : String
    -JDBC_DIVER_CLASS_NAME : String
    -PROJECT_PATH : String
    -TEMPLATE_FILE_PATH : String
    -JAVA_PATH : String
    -RESOURCES_PATH : String
    -PACKAGE_PATH_SERVICE : String
    +main() : void
  }

package com.zoctan.seedling {
  class AccountControllerTest {
    -resource : String
    -targetUrl : String
    -account : AccountDTO
    -targetUrl : String
    -accountLogin : AccountLoginDTO
    -targetUrl : String
    -accountLogin : AccountLoginDTO
    -token : String
    -targetUrl : String
    -accountDTO : AccountDTO
    +register() : void
    +login() : void
    +logout() : void
    +update() : void
    +detail() : void
    +list() : void
    +delete() : void
  }
  interface WithCustomUser {
  }
  class WithCustomSecurityContextFactory {
    -userDetailsService : UserDetailsServiceImpl
    -customUser : WithCustomUser
    -context : SecurityContext
    -userDetails : UserDetails
    -auth : Authentication
    +createSecurityContext() : SecurityContext
  }
  class BaseControllerTest {
    -context : WebApplicationContext
    -corsFilter : CorsFilter
    -authenticationFilter : AuthenticationFilter
    -mockMvc : MockMvc
    -method : HttpMethod
    -targetUrl : String
    -args : Object
    -token : String
    -builders : MockHttpServletRequestBuilder
    -targetUrl : String
    +setUp() : void
    +post() : Result
    +delete() : Result
    +patch() : Result
  }
  class Application {
    -args : String[]
    -builder : SpringApplicationBuilder
    +main() : void
    +configure() : SpringApplicationBuilder
  }
}

package com.zoctan.seedling.aspect {
  class ControllerLogAspect {
    -startTime : LocalDateTime
    -joinPoint : JoinPoint
    -attributes : ServletRequestAttributes
    -request : HttpServletRequest
    -result : Object
    -difference : long
    -e : Throwable
    +controllers() : void
    +doBefore() : void
    +doAfterReturning() : void
    +doAfterThrowing() : void
  }
}

package com.zoctan.seedling.controller {
  class RoleController <<Controller>> {
    -roleService : RoleService
    -roleDTO : RoleDTO
    -id : Long
    -roleDTO : RoleDTO
    -id : Long
    -role : RoleDO
    -page : Integer
    -size : Integer
    -list : List<RoleDO>
    -pageInfo : PageInfo<RoleDO>
    +add() : Result
    +delete() : Result
    +update() : Result
    +detail() : Result
    +list() : Result
  }
  class AccountController <<Controller>> {
    -accountService : AccountService
    -userDetailsService : UserDetailsServiceImpl
    -jwtUtil : JwtUtil
    -accountDTO : AccountDTO
    -bindingResult : BindingResult
    -userDetails : UserDetails
    -token : String
    -accountLoginDTO : AccountLoginDTO
    -bindingResult : BindingResult
    -name : String
    +register() : Result
    +login() : Result
    +logout() : Result
    +update() : Result
    +delete() : Result
    +detail() : Result
    +list() : Result
  }
  class UploadController <<Controller>> {
    -uploadProperties : UploadConfigurationProperties
    -file : MultipartFile
    -fileSize : DataSize
    -maxData : DataSize
    -minData : DataSize
    -localPath : String
    -filePath : Path
    -e : IOException
    -name : String
    -httpServletResponse : HttpServletResponse
    +uploadImage() : Result
    +getImage() : Result
    +removeImage() : Result
  }
}

package com.zoctan.seedling.core.cache {
  class MyRedisCacheManager {
    -STRING_SERIALIZER : StringRedisSerializer
    -FASTJSON_SERIALIZER : GenericFastJsonRedisSerializer
    -applicationContext : ApplicationContext
    -cacheWriter : RedisCacheWriter
    -defaultCacheConfiguration : RedisCacheConfiguration
    -cacheWriter : RedisCacheWriter
    -defaultCacheConfiguration : RedisCacheConfiguration
    -name : String
    -cache : Cache
    -applicationContext : ApplicationContext
    +getCache() : Cache
    +setApplicationContext() : void
    +afterPropertiesSet() : void
    +loadCaches() : Collection<RedisCache>
    +getName() : String
    +getNativeCache() : Object
    +put() : void
  }
  interface CacheExpire {
  }
}

package com.zoctan.seedling.core.config {
  class WebMvcConfig {
    -converter : FastJsonHttpMessageConverter
    -config : FastJsonConfig
    -supportedMediaTypes : List<MediaType>
    -registry : ResourceHandlerRegistry
    +configureMessageConverters() : void
    +addResourceHandlers() : void
    +addViewControllers() : void
  }
  class WebSecurityConfig {
    -ANONYMOUS_LIST : String[]
    -myAuthenticationEntryPoint : MyAuthenticationEntryPoint
    -authenticationFilter : AuthenticationFilter
    -auth : AuthenticationManagerBuilder
    -http : HttpSecurity
    +passwordEncoder() : PasswordEncoder
    +userDetailsService() : UserDetailsServiceImpl
    +configure() : void
    +configure() : void
  }
  class ValidatorConfig {
    -postProcessor : MethodValidationPostProcessor
    +methodValidationPostProcessor() : MethodValidationPostProcessor
    +validatorFailFast() : Validator
  }
  class RedisConfig {
    -redisProperties : RedisProperties
    -jedisPoolConfig : JedisPoolConfig
    -redisStandaloneConfiguration : RedisStandaloneConfiguration
    -jedisClientConfiguration : JedisClientConfiguration
    -factory : RedisConnectionFactory
    -stringSerializer : StringRedisSerializer
    -fastSerializer : GenericFastJsonRedisSerializer
    +jedisPoolConfig() : JedisPoolConfig
    +redisConnectionFactory() : RedisConnectionFactory
    +redisTemplate() : RedisTemplate
  }
  class YamlPropertySourceFactory {
    -name : String
    -resource : EncodedResource
    -factory : YamlPropertiesFactoryBean
    -ymlProperties : Properties
    -propertyName : String
  }
  class Swagger3Config {
    -activeProfile : String
    -applicationName : String
    -applicationVersion : String
    -applicationDescription : String
    -applicationServiceUrl : String
    -applicationLicense : String
    -applicationLicenseUrl : String
    -selector : String
    -authorName : String
    -authorUrl : String
    +docket() : Docket
  }
  class JasyptConfig {
    -passwordEncryptedByBase64AndRsa : String
    -rsaUtils : RsaUtils
    -passwordEncryptedByRsa : byte[]
    -password : String
    -config : SimpleStringPBEConfig
    -encryptor : PooledPBEStringEncryptor
    +myStringEncryptor() : StringEncryptor
  }
  class RedisCacheConfig {
    -redisConnectionFactory : RedisConnectionFactory
    -redisCacheWriter : RedisCacheWriter
    -defaultCacheConfig : RedisCacheConfiguration
    -dot : String
    -sb : StringBuilder
    -e : RuntimeException
    -cache : Cache
    -key : Object
    -e : RuntimeException
    -cache : Cache
    +cacheManager() : CacheManager
    +keyGenerator() : KeyGenerator
    +errorHandler() : CacheErrorHandler
    +handleCacheGetError() : void
    +handleCachePutError() : void
    +handleCacheEvictError() : void
    +handleCacheClearError() : void
  }
}

package com.zoctan.seedling.core.constant {
  class ProjectConstant {
    -SPRING_PROFILE_DEVELOPMENT : String
    -SPRING_PROFILE_PRODUCTION : String
    -SPRING_PROFILE_TEST : String
    -BASE_PACKAGE : String
    -ENTITY_PACKAGE : String
    -MAPPER_PACKAGE : String
    -FILTER_PACKAGE : String
    -SERVICE_PACKAGE : String
    -SERVICE_IMPL_PACKAGE : String
    -CONTROLLER_PACKAGE : String
  }
}

package com.zoctan.seedling.core.dto {
  class AbstractConverter {
    -doClass : Class<DO>
    -theDTO : DTO
    -theDO : DO
    -parameterizedType : ParameterizedType
    -theDTO : DTO
    -theDO : DO
    -ignored : Exception
    -aDO : DO
    +setDTO() : DTO
    +doForward() : DO
    +doBackward() : DTO
    +convertToDO() : DO
    +convertFor() : DTO
  }
}

package com.zoctan.seedling.core.exception {
  class ServiceException {
    -serialVersionUID : long
    -resultCode : ResultCode
    -message : String
    -message : String
    -cause : Throwable
    -resultCode : ResultCode
    -message : String
    -resultCode : ResultCode
    -resultCode : ResultCode
    +getResultCode() : ResultCode
    +setResultCode() : void
  }
  class UsernameNotFoundException2 {
    -serialVersionUID : long
    -DEFAULT_MESSAGE : String
    -message : String
    -message : String
    -cause : Throwable
  }
  class ExceptionResolver {
    -e : ConstraintViolationException
    -msg : String
    -e : ServiceException
    -e : Throwable
    -e : Throwable
    -e : Throwable
    -e : Throwable
    -e : Throwable
    -request : HttpServletRequest
    -request : HttpServletRequest
    +validatorException() : Result
    +serviceException() : Result
    +resourcesException() : Result
    +databaseException() : Result
    +authException() : Result
    +accountException() : Result
    +apiNotFoundException() : Result
    +globalException() : Result
  }
  class YamlNotFoundException {
    -serialVersionUID : long
    -DEFAULT_MESSAGE : String
    -message : String
    -message : String
    -cause : Throwable
  }
  class RsaException {
    -serialVersionUID : long
    -DEFAULT_MESSAGE : String
    -message : String
    -message : String
    -cause : Throwable
  }
  class ResourcesNotFoundException {
    -serialVersionUID : long
    -DEFAULT_MESSAGE : String
    -message : String
    -message : String
    -cause : Throwable
  }
}

package com.zoctan.seedling.core.jasypt {
  class MyEncryptablePropertyDetector {
    -PREFIX : String
    -SUFFIX : String
    -property : String
    -trimmedProperty : String
    -property : String
    +isEncrypted() : boolean
    +unwrapEncryptedValue() : String
  }
}

package com.zoctan.seedling.core.jwt {
  class JwtUtil {
    -jwtProperties : JwtConfigurationProperties
    -redisUtils : RedisUtils
    -rsaUtils : RsaUtils
    -token : String
    -claims : Optional<Claims>
    -name : String
    -createToken : Supplier<String>
    -token : String
    -isValidate : boolean
    -name : String
    +getName() : Optional<String>
    +sign() : String
    +invalidRedisToken() : void
    +getTokenFromRequest() : String
    +getAuthentication() : UsernamePasswordAuthenticationToken
    +validateToken() : boolean
  }
  class JwtConfigurationProperties {
    -claimKeyAuth : String
    -tokenType : String
    -header : String
    -expireTime : Duration
  }
}

package com.zoctan.seedling.core.mapper {
  interface MyMapper {
  }
}

package com.zoctan.seedling.core.response {
  enum ResultCode {
    -value : int
    -reason : String
    -value : int
    -reason : String
    +getValue() : int
    +getReason() : String
    +format() : String
  }
  class Result {
    -code : Integer
    -message : String
    -data : T
    -code : Integer
    -message : String
    -data : T
    +getCode() : Integer
    +setCode() : Result<T>
    +getMessage() : String
    +setMessage() : Result<T>
    +getData() : T
    +setData() : Result<T>
  }
  class ResultGenerator {
    -data : T
    -code : int
    -message : String
    -resultCode : ResultCode
    -resultCode : ResultCode
    -message : String
    -message : String
  }
}

package com.zoctan.seedling.core.rsa {
  class RsaUtils {
    -ALGORITHM : String
    -resourceLoader : ResourceLoader
    -rsaProperties : RsaConfigurationProperties
    -keyLength : int
    -keyPairGenerator : KeyPairGenerator
    -content : byte[]
    -publicKey : PublicKey
    -cipher : Cipher
    -content : byte[]
    -privateKey : PrivateKey
    +genKeyPair() : KeyPair
    +encrypt() : byte[]
    +decrypt() : byte[]
    +encrypt() : byte[]
    +decrypt() : byte[]
    +loadPublicKey() : PublicKey
    +loadPrivateKey() : PrivateKey
  }
  class RsaConfigurationProperties {
    -publicKeyHead : String
    -publicKeyTail : String
    -privateKeyHead : String
    -privateKeyTail : String
    -publicKeyPath : String
    -privateKeyPath : String
    -useFile : boolean
    -privateKey : String
    -publicKey : String
  }
}

package com.zoctan.seedling.core.service {
  class AbstractService {
    -entityClass : Class<T>
    -mapper : MyMapper<T>
    -pt : ParameterizedType
    -statement : boolean
    -statement : boolean
    -statement : boolean
    -fieldName : String
    -value : Object
    -entity : T
    -field : Field
    +assertById() : void
    +assertBy() : void
    +assertByIds() : void
    +countByIds() : int
    +countByCondition() : int
    +save() : void
    +save() : void
    +deleteById() : void
  }
  interface Service {
  }
}

package com.zoctan.seedling.core.upload {
  class UploadConfigurationProperties {
    -localPath : String
    -min : DataSize
    -max : DataSize
  }
}

package com.zoctan.seedling.dto {
  class AccountDTO {
    -serialVersionUID : long
    -id : Long
    -email : String
    -name : String
    -password : String
    +setDTO() : AccountDTO
  }
  class RoleDTO {
    -serialVersionUID : long
    -id : Long
    -name : String
    +setDTO() : RoleDTO
  }
  class AccountLoginDTO {
    -serialVersionUID : long
    -name : String
    -password : String
    +setDTO() : AccountLoginDTO
  }
}

package com.zoctan.seedling.entity {
  class AccountDO {
    -id : Long
    -email : String
    -name : String
    -password : String
    -registerTime : Timestamp
    -loginTime : Timestamp
  }
  class AccountWithRoleDO {
    -roles : List<RoleDO>
  }
  class Test {
    -id : Long
    -name : String
    +getId() : Long
    +setId() : void
    +getName() : String
    +setName() : void
  }
  class RoleDO {
    -id : Long
    -name : String
  }
}

package com.zoctan.seedling.filter {
  class MyAuthenticationEntryPoint {
    -request : HttpServletRequest
    -response : HttpServletResponse
    -authException : AuthenticationException
    +commence() : void
  }
  class RequestWrapper {
    -body : StringBuilder
    -request : HttpServletRequest
    -bufferedReader : BufferedReader
    -byteArrayInputStream : ByteArrayInputStream
    -readListener : ReadListener
    +getInputStream() : ServletInputStream
    +read() : int
    +isFinished() : boolean
    +isReady() : boolean
    +setReadListener() : void
    +getReader() : BufferedReader
    +getJson() : String
  }
  class CorsFilter {
    -activeProfile : String
    -filterConfig : FilterConfig
    -servletRequest : ServletRequest
    -servletResponse : ServletResponse
    -filterChain : FilterChain
    -request : HttpServletRequest
    -response : HttpServletResponse
    +init() : void
    +doFilter() : void
    +destroy() : void
  }
  class AuthenticationFilter {
    -jwtUtil : JwtUtil
    -filterConfig : FilterConfig
    -servletRequest : ServletRequest
    -servletResponse : ServletResponse
    -filterChain : FilterChain
    -request : HttpServletRequest
    -response : HttpServletResponse
    -token : String
    -name : Optional<String>
    -authentication : UsernamePasswordAuthenticationToken
    +init() : void
    +doFilter() : void
    +destroy() : void
  }
}

package com.zoctan.seedling.mapper {
  interface AccountMapper {
  }
  interface RoleMapper {
  }
}

package com.zoctan.seedling.query {
  class AccountQuery {
    -serialVersionUID : long
    -id : Long
    -email : String
    -name : String
    -password : String
  }
}

package com.zoctan.seedling.service {
  interface AccountService {
  }
  interface RoleService {
  }
}

package com.zoctan.seedling.service.impl {
  class AccountServiceImpl <<Service>> {
    -accountMapper : AccountMapper
    -roleService : RoleService
    -passwordEncoder : PasswordEncoder
    -accountDTO : AccountDTO
    -accountDO : AccountDO
    -accountDTO : AccountDTO
    -accountDO : AccountDO
    -name : String
    -condition : Condition
    -id : Long
    +save() : void
    +updateByName() : void
    +getByIdWithRole() : AccountWithRoleDO
    +getByNameWithRole() : AccountWithRoleDO
    +verifyPassword() : boolean
    +updateLoginTimeByName() : boolean
  }
  class RoleServiceImpl <<Service>> {
    -roleMapper : RoleMapper
    -accountId : Long
    -success : boolean
    -roleDTO : RoleDTO
    -role : RoleDO
    -roleDTO : RoleDTO
    -role : RoleDO
    +saveAsDefaultRole() : void
    +save() : void
    +update() : void
  }
  class UserDetailsServiceImpl <<Service>> {
    -accountService : AccountService
    -name : String
    -account : AccountWithRoleDO
    -authorities : List<SimpleGrantedAuthority>
    +loadUserByUsername() : UserDetails
  }
}

package com.zoctan.seedling.util {
  class JsonUtilsTest {
    -account1 : AccountDO
    -account2 : AccountDO
    -accountList : List<JSONObject>
    -accountList : List<JSONObject>
    +keepFields() : void
    +deleteFields() : void
  }
  class IdUtils {
    -DTF_TIMES : DateTimeFormatter
    -uuid : UUID
    -bb : ByteBuffer
    +uuid16() : String
    +uuid64() : String
    +timeId() : String
  }
  class FileUtils {
    -serialVersionUID : long
    -file : File
    -b : byte[]
    -is : InputStream
    -e : IOException
    -fileBytes : byte[]
    -fileTypeHex : String
    -fileTypeHexValue : String
    -b : byte[]
    -stringBuilder : StringBuilder
    +getFileType() : String
    +getFileType() : String
    +getFileHexString() : String
    +exist() : Boolean
  }
  class RedisUtils {
    -key : String
    -timeout : Duration
    -key : String
    -key : String
    -key : String
    -key : String
    -value : Object
    -key : String
    -value : Object
    -timeout : Duration
    +setExpire() : Boolean
    +getExpire() : Long
    +hasKey() : Boolean
    +delete() : Boolean
    +getValue() : Object
    +setValue() : void
    +setValue() : void
    +incrementValue() : Long
  }
  class UrlUtils {
    -request : ServletRequest
    -request : HttpServletRequest
    +getMappingUrl() : String
    +getMappingUrl() : String
  }
  class IpUtils {
    -UNKNOWN : String
    -LOCALHOST_IPV4 : String
    -LOCALHOST_IPV6 : String
    -request : HttpServletRequest
    -ignored : UnknownHostException
    -ch : String
    -ip : String
    -url : URL
    -connection : HttpURLConnection
    -in : InputStream
    +getIpAddress() : String
    +getIpAddress() : String
    +getInfoByIP() : String
  }
  class AssertUtils {
    -statement : boolean
    -resultCode : ResultCode
    -message : String
    -statement : boolean
    -resultCode : ResultCode
    -resultCode : ResultCode
    -statement : boolean
    -resultCode : ResultCode
    +throwIf() : void
    +throwIf() : void
    +toThrow() : RuntimeException
    +asserts() : void
  }
  class ContextUtils {
    -attributes : ServletRequestAttributes
    +getRequest() : HttpServletRequest
  }
  class IdCardUtils {
    -LAST_CODE : String[]
    -POWER : int[]
    -args : String[]
    -idCard : String
    -idCard17 : String
    -idCard18Code : String
    -lastCode : String
    -string : String
    -cs : char[]
    -idCard : String
    +main() : void
    +validate() : Boolean
    +getProvince() : String
    +getBirthday() : String
    +getSex() : String
  }
  class DateUtils {
    -DTF_YEAR : DateTimeFormatter
    -DTF_DAY : DateTimeFormatter
    -DTF_DAYS : DateTimeFormatter
    -DTF_TIME : DateTimeFormatter
    -DTF_TIMES : DateTimeFormatter
    -dateString : String
    -dateString : String
    -dateString : String
    -dateString : String
    -dateString : String
    +getThisYear() : String
    +validateYear() : Boolean
    +getThisDay() : String
    +validateDay() : Boolean
    +getThisDays() : String
    +validateDays() : Boolean
    +getThisTime() : String
    +validateTime() : Boolean
  }
  class JsonUtils {
    -target : Object
    -clz : Class<T>
    -filter : SimplePropertyPreFilter
    -target : Object
    -clz : Class<T>
    -filter : SimplePropertyPreFilter
    -target : Object
    -clz : Class<T>
    -filter : SimplePropertyPreFilter
    -jsonString : String
  }
}

' --- Relatii ---
PasswordEncryptor --> Application
PasswordEncryptor --> Test
RsaEncryptor --> RsaUtils
RsaEncryptor --> Test
JasyptStringEncryptor --> Application
JasyptStringEncryptor --> Test
CodeGenerator --> FileUtils
AccountControllerTest --|> BaseControllerTest
AccountControllerTest --> AccountDTO
AccountControllerTest --> AccountLoginDTO
WithCustomSecurityContextFactory --> UserDetailsServiceImpl
BaseControllerTest --> Result
BaseControllerTest --> AuthenticationFilter
BaseControllerTest --> CorsFilter
JsonUtilsTest --> AccountDO
JsonUtilsTest --> Test
AccountDTO --|> AbstractConverter
AccountDTO --> AbstractConverter
AccountDTO --> AccountDO
RoleDTO --|> AbstractConverter
RoleDTO --> AbstractConverter
RoleDTO --> RoleDO
AccountLoginDTO --|> AbstractConverter
AccountLoginDTO --> AbstractConverter
AccountLoginDTO --> AccountDO
JwtUtil --> RsaUtils
JwtUtil --> RedisUtils
WebSecurityConfig --> AuthenticationFilter
WebSecurityConfig --> MyAuthenticationEntryPoint
WebSecurityConfig --> UserDetailsServiceImpl
RedisConfig --> MyRedisCacheManager
YamlPropertySourceFactory --> YamlNotFoundException
JasyptConfig --> RsaUtils
RedisCacheConfig --> MyRedisCacheManager
RsaUtils --> RsaException
AbstractService --> ResourcesNotFoundException
AbstractService --> ServiceException
AbstractService --> MyMapper
AbstractService --> ResultCode
AbstractService --> AssertUtils
Service --> ResourcesNotFoundException
ServiceException --> ResultCode
ExceptionResolver --> Result
ExceptionResolver --> ResultCode
ExceptionResolver --> ResultGenerator
ExceptionResolver --> UrlUtils
AssertUtils --> ServiceException
AssertUtils --> ResultCode
AccountWithRoleDO --|> AccountDO
AccountMapper --|> MyMapper
AccountMapper --> MyMapper
AccountMapper --> AccountDO
AccountMapper --> AccountWithRoleDO
AccountMapper --> AccountQuery
RoleMapper --|> MyMapper
RoleMapper --> MyMapper
RoleMapper --> RoleDO
RoleController --> Result
RoleController --> ResultGenerator
RoleController --> RoleDTO
RoleController --> RoleDO
RoleController --> RoleService
AccountController --> CacheExpire
AccountController --> JwtUtil
AccountController --> Result
AccountController --> ResultGenerator
AccountController --> AccountDTO
AccountController --> AccountLoginDTO
AccountController --> AccountDO
AccountController --> AccountWithRoleDO
AccountController --> AccountService
AccountController --> UserDetailsServiceImpl
AccountController --> JsonUtils
UploadController --> Result
UploadController --> ResultGenerator
UploadController --> UploadConfigurationProperties
ControllerLogAspect --> IpUtils
MyAuthenticationEntryPoint --> ResultCode
MyAuthenticationEntryPoint --> ResultGenerator
CorsFilter --> IpUtils
CorsFilter --> UrlUtils
AuthenticationFilter --> JwtUtil
AuthenticationFilter --> IpUtils
AuthenticationFilter --> UrlUtils
AccountService --|> Service
AccountService --> Service
AccountService --> AccountDTO
AccountService --> AccountDO
AccountService --> AccountWithRoleDO
RoleService --|> Service
RoleService --> Service
RoleService --> RoleDTO
RoleService --> RoleDO
AccountServiceImpl --|> AbstractService
AccountServiceImpl --> ResultCode
AccountServiceImpl --> AbstractService
AccountServiceImpl --> AccountDTO
AccountServiceImpl --> AccountDO
AccountServiceImpl --> AccountWithRoleDO
AccountServiceImpl --> AccountMapper
AccountServiceImpl --> AccountQuery
AccountServiceImpl --> AccountService
AccountServiceImpl --> RoleService
AccountServiceImpl --> AssertUtils
AccountServiceImpl --> Service
RoleServiceImpl --|> AbstractService
RoleServiceImpl --> ResultCode
RoleServiceImpl --> AbstractService
RoleServiceImpl --> RoleDTO
RoleServiceImpl --> RoleDO
RoleServiceImpl --> RoleMapper
RoleServiceImpl --> RoleService
RoleServiceImpl --> AssertUtils
RoleServiceImpl --> Service
UserDetailsServiceImpl --> UsernameNotFoundException2
UserDetailsServiceImpl --> AccountWithRoleDO
UserDetailsServiceImpl --> AccountService
UserDetailsServiceImpl --> Service

@enduml