@startuml

package me.zhulin.shopapi {
  class ShopApiApplicationTests {
  }
  class ShopApiApplication {
    +passwordEncoder() : PasswordEncoder
    +corsConfigurer() : WebMvcConfigurer
    +addCorsMappings() : void
    +main() : void
  }
}

package me.zhulin.shopapi.api {
  class CartControllerTest {
    +getCart() : void
  }
  class ProductController <<Controller>> {
    +findAll() : Page<ProductInfo>
    +showOne() : ProductInfo
    +create() : ResponseEntity
    +edit() : ResponseEntity
    +delete() : ResponseEntity
  }
  class OrderController <<Controller>> {
    +orderList() : Page<OrderMain>
    +cancel() : ResponseEntity<OrderMain>
    +finish() : ResponseEntity<OrderMain>
    +show() : ResponseEntity
  }
  class CartController <<Controller>> {
    +mergeCart() : ResponseEntity<Cart>
    +getCart() : Cart
    +addToCart() : boolean
    +modifyItem() : ProductInOrder
    +deleteItem() : void
    +checkout() : ResponseEntity
  }
  class CategoryController <<Controller>> {
    +showOne() : CategoryPage
  }
  class UserController <<Controller>> {
    +login() : ResponseEntity<JwtResponse>
    +save() : ResponseEntity<User>
    +update() : ResponseEntity<User>
    +getProfile() : ResponseEntity<User>
  }
}

package me.zhulin.shopapi.entity {
  class OrderMain <<Entity>> {
    -serialVersionUID : long
    -orderId : Long
    -products : Set<ProductInOrder>
    -buyerEmail : String
    -buyerName : String
    -buyerPhone : String
    -buyerAddress : String
    -orderAmount : BigDecimal
    -orderStatus : Integer
    -createTime : LocalDateTime
  }
  class User <<Entity>> {
    -serialVersionUID : long
    -id : Long
    -email : String
    -password : String
    -name : String
    -phone : String
    -address : String
    -active : boolean
    -role : String
    -cart : Cart
  }
  class ProductInOrder <<Entity>> {
    -id : Long
    -cart : Cart
    -orderMain : OrderMain
    -productId : String
    -productName : String
    -productDescription : String
    -productIcon : String
    -categoryType : Integer
    -productPrice : BigDecimal
    -productStock : Integer
  }
  class Cart <<Entity>> {
    -cartId : long
    -user : User
    -products : Set<ProductInOrder>
  }
  class ProductCategory <<Entity>> {
    -categoryId : Integer
    -categoryName : String
    -categoryType : Integer
    -createTime : Date
    -updateTime : Date
  }
  class ProductInfo <<Entity>> {
    -productId : String
    -productName : String
    -productPrice : BigDecimal
    -productStock : Integer
    -productDescription : String
    -productIcon : String
    -productStatus : Integer
    -categoryType : Integer
    -createTime : Date
    -updateTime : Date
  }
}

package me.zhulin.shopapi.enums {
  enum OrderStatusEnum {
    -code : int
    -msg : String
    +getCode() : Integer
  }
  enum ProductStatusEnum {
    -code : Integer
    -message : String
    +getStatus() : String
    +getCode() : Integer
  }
  enum ResultEnum {
    -code : Integer
    -message : String
  }
  interface CodeEnum {
  }
}

package me.zhulin.shopapi.exception {
  class MyException {
    -code : Integer
  }
}

package me.zhulin.shopapi.form {
  class ItemForm {
    -quantity : Integer
    -productId : String
  }
}

package me.zhulin.shopapi.repository {
  interface OrderRepository {
  }
  interface ProductCategoryRepository {
  }
  interface CartRepository {
  }
  interface ProductInfoRepository {
  }
  interface ProductInOrderRepository {
  }
  interface UserRepository {
  }
}

package me.zhulin.shopapi.security {
  class SpringSecurityConfig {
    -accessDenyHandler : JwtEntryPoint
    -passwordEncoder : PasswordEncoder
    -usersQuery : String
    -rolesQuery : String
    +configure() : void
    +authenticationManagerBean() : AuthenticationManager
    +configure() : void
  }
}

package me.zhulin.shopapi.security.JWT {
  class JwtEntryPoint {
    -logger : Logger
    +commence() : void
  }
  class JwtFilter {
    -jwtProvider : JwtProvider
    -userService : UserService
    +doFilterInternal() : void
  }
  class JwtProvider {
    -logger : Logger
    -jwtSecret : String
    -jwtExpiration : int
    +generate() : String
    +validate() : boolean
    +getUserAccount() : String
  }
}

package me.zhulin.shopapi.service {
  interface UserService {
  }
  interface CartService {
  }
  interface ProductService {
  }
  interface OrderService {
  }
  interface ProductInOrderService {
  }
  interface CategoryService {
  }
}

package me.zhulin.shopapi.service.impl {
  class UserServiceImplTest {
    -userService : UserServiceImpl
    -userRepository : UserRepository
    -passwordEncoder : PasswordEncoder
    -cartRepository : CartRepository
    -user : User
    +setUp() : void
    +createUserTest() : void
    +createUserExceptionTest() : void
    +updateTest() : void
  }
  class CategoryServiceImplTest {
    -categoryService : CategoryServiceImpl
    -productCategoryRepository : ProductCategoryRepository
    +findByCategoryTypeTest() : void
    +findByCategoryTypeExceptionTest() : void
  }
  class OrderServiceImplTest {
    -orderRepository : OrderRepository
    -productInfoRepository : ProductInfoRepository
    -productService : ProductService
    -orderService : OrderServiceImpl
    -orderMain : OrderMain
    -productInfo : ProductInfo
    +setUp() : void
    +finishSuccessTest() : void
    +finishStatusCanceledTest() : void
    +finishStatusFinishedTest() : void
    +cancelSuccessTest() : void
    +cancelNoProduct() : void
    +cancelStatusCanceledTest() : void
    +cancelStatusFinishTest() : void
  }
  class CartServiceImplTest {
    -cartService : CartServiceImpl
    -productService : ProductService
    -productInOrderRepository : ProductInOrderRepository
    -cartRepository : CartRepository
    -orderRepository : OrderRepository
    -user : User
    -productInOrder : ProductInOrder
    -set : Set<ProductInOrder>
    -cart : Cart
    +setUp() : void
    +mergeLocalCartTest() : void
    +mergeLocalCartTwoProductTest() : void
    +mergeLocalCartNoProductTest() : void
    +deleteTest() : void
    +deleteNoProductTest() : void
    +deleteNoUserTest() : void
    +checkoutTest() : void
  }
  class ProductServiceImplTest {
    -productService : ProductServiceImpl
    -productInfoRepository : ProductInfoRepository
    -categoryService : CategoryService
    -productInfo : ProductInfo
    +setUp() : void
    +increaseStockTest() : void
    +increaseStockExceptionTest() : void
    +decreaseStockTest() : void
    +decreaseStockValueLesserEqualTest() : void
    +decreaseStockExceptionTest() : void
    +offSaleTest() : void
    +offSaleStatusDownTest() : void
  }
  class ProductInOrderServiceImplTest {
    -productInOrderRepository : ProductInOrderRepository
    -productInOrderService : ProductInOrderServiceImpl
    -user : User
    -productInOrder : ProductInOrder
    +setUp() : void
    +updateTest() : void
    +findOneTest() : void
  }
  class OrderServiceImpl <<Service>> {
    +findAll() : Page<OrderMain>
    +findByStatus() : Page<OrderMain>
    +findByBuyerEmail() : Page<OrderMain>
    +findByBuyerPhone() : Page<OrderMain>
    +findOne() : OrderMain
    +finish() : OrderMain
    +cancel() : OrderMain
  }
  class CartServiceImpl <<Service>> {
    +getCart() : Cart
    +mergeLocalCart() : void
    +delete() : void
    +checkout() : void
  }
  class ProductInOrderServiceImpl <<Service>> {
    +update() : void
    +findOne() : ProductInOrder
  }
  class CategoryServiceImpl <<Service>> {
    +findAll() : List<ProductCategory>
    +findByCategoryType() : ProductCategory
    +findByCategoryTypeIn() : List<ProductCategory>
    +save() : ProductCategory
  }
  class UserServiceImpl <<Service>> {
    -passwordEncoder : PasswordEncoder
    +findOne() : User
    +findByRole() : Collection<User>
    +save() : User
    +update() : User
  }
  class ProductServiceImpl <<Service>> {
    +findOne() : ProductInfo
    +findUpAll() : Page<ProductInfo>
    +findAll() : Page<ProductInfo>
    +findAllInCategory() : Page<ProductInfo>
    +increaseStock() : void
    +decreaseStock() : void
    +offSale() : ProductInfo
    +onSale() : ProductInfo
  }
}

package me.zhulin.shopapi.vo.request {
  class LoginForm {
    -username : String
    -password : String
  }
}

package me.zhulin.shopapi.vo.response {
  class CategoryPage {
    -category : String
    -page : Page<ProductInfo>
    +getCategory() : String
    +setCategory() : void
    +getPage() : Page<ProductInfo>
    +setPage() : void
  }
  class JwtResponse {
    -token : String
    -type : String
    -account : String
    -name : String
    -role : String
  }
}

' --- Relatii ---
UserServiceImplTest --> User
UserServiceImplTest --> MyException
UserServiceImplTest --> CartRepository
UserServiceImplTest --> UserRepository
CategoryServiceImplTest --> ProductCategory
CategoryServiceImplTest --> MyException
CategoryServiceImplTest --> ProductCategoryRepository
OrderServiceImplTest --> OrderMain
OrderServiceImplTest --> ProductInOrder
OrderServiceImplTest --> ProductInfo
OrderServiceImplTest --> OrderStatusEnum
OrderServiceImplTest --> MyException
OrderServiceImplTest --> OrderRepository
OrderServiceImplTest --> ProductInfoRepository
OrderServiceImplTest --> ProductService
CartServiceImplTest --> Cart
CartServiceImplTest --> ProductInOrder
CartServiceImplTest --> User
CartServiceImplTest --> MyException
CartServiceImplTest --> CartRepository
CartServiceImplTest --> OrderRepository
CartServiceImplTest --> ProductInOrderRepository
CartServiceImplTest --> ProductService
ProductServiceImplTest --> ProductInfo
ProductServiceImplTest --> ProductStatusEnum
ProductServiceImplTest --> MyException
ProductServiceImplTest --> ProductInfoRepository
ProductServiceImplTest --> CategoryService
ProductInOrderServiceImplTest --> Cart
ProductInOrderServiceImplTest --> ProductInOrder
ProductInOrderServiceImplTest --> User
ProductInOrderServiceImplTest --> ProductInOrderRepository
CategoryPage --> ProductInfo
OrderRepository --> OrderMain
ProductCategoryRepository --> ProductCategory
CartRepository --> Cart
ProductInfoRepository --> ProductInfo
ProductInOrderRepository --> ProductInOrder
UserRepository --> User
SpringSecurityConfig --> JwtEntryPoint
SpringSecurityConfig --> JwtFilter
JwtFilter --> User
JwtFilter --> UserService
OrderStatusEnum ..|> CodeEnum
ProductStatusEnum ..|> CodeEnum
ProductController --> ProductInfo
ProductController --> CategoryService
ProductController --> ProductService
OrderController --> OrderMain
OrderController --> ProductInOrder
OrderController --> OrderService
OrderController --> UserService
CartController --> Cart
CartController --> ProductInOrder
CartController --> User
CartController --> ItemForm
CartController --> ProductInOrderRepository
CartController --> CartService
CartController --> ProductInOrderService
CartController --> ProductService
CartController --> UserService
CategoryController --> ProductCategory
CategoryController --> ProductInfo
CategoryController --> CategoryService
CategoryController --> ProductService
CategoryController --> CategoryPage
UserController --> User
UserController --> JwtProvider
UserController --> UserService
UserController --> LoginForm
UserController --> JwtResponse
UserService --> User
CartService --> Cart
CartService --> ProductInOrder
CartService --> User
ProductService --> ProductInfo
OrderService --> OrderMain
ProductInOrderService --> ProductInOrder
ProductInOrderService --> User
CategoryService --> ProductCategory
OrderServiceImpl ..|> OrderService
OrderServiceImpl --> OrderMain
OrderServiceImpl --> ProductInOrder
OrderServiceImpl --> ProductInfo
OrderServiceImpl --> OrderStatusEnum
OrderServiceImpl --> ResultEnum
OrderServiceImpl --> MyException
OrderServiceImpl --> OrderRepository
OrderServiceImpl --> ProductInOrderRepository
OrderServiceImpl --> ProductInfoRepository
OrderServiceImpl --> UserRepository
OrderServiceImpl --> OrderService
OrderServiceImpl --> ProductService
CartServiceImpl ..|> CartService
CartServiceImpl --> Cart
CartServiceImpl --> OrderMain
CartServiceImpl --> ProductInOrder
CartServiceImpl --> User
CartServiceImpl --> ResultEnum
CartServiceImpl --> MyException
CartServiceImpl --> CartRepository
CartServiceImpl --> OrderRepository
CartServiceImpl --> ProductInOrderRepository
CartServiceImpl --> UserRepository
CartServiceImpl --> CartService
CartServiceImpl --> ProductService
CartServiceImpl --> UserService
ProductInOrderServiceImpl ..|> ProductInOrderService
ProductInOrderServiceImpl --> ProductInOrder
ProductInOrderServiceImpl --> User
ProductInOrderServiceImpl --> ProductInOrderRepository
ProductInOrderServiceImpl --> ProductInOrderService
CategoryServiceImpl ..|> CategoryService
CategoryServiceImpl --> ProductCategory
CategoryServiceImpl --> ResultEnum
CategoryServiceImpl --> MyException
CategoryServiceImpl --> ProductCategoryRepository
CategoryServiceImpl --> CategoryService
UserServiceImpl ..|> UserService
UserServiceImpl --> Cart
UserServiceImpl --> User
UserServiceImpl --> ResultEnum
UserServiceImpl --> MyException
UserServiceImpl --> CartRepository
UserServiceImpl --> UserRepository
UserServiceImpl --> UserService
ProductServiceImpl ..|> ProductService
ProductServiceImpl --> ProductInfo
ProductServiceImpl --> ProductStatusEnum
ProductServiceImpl --> ResultEnum
ProductServiceImpl --> MyException
ProductServiceImpl --> ProductInfoRepository
ProductServiceImpl --> CategoryService
ProductServiceImpl --> ProductService
MyException --> ResultEnum

@enduml