@startuml

package com.in28minutes.springboot.web {
  class SpringBootFirstWebApplicationTests {
    +contextLoads() : void
  }
  class SpringBootFirstWebApplication {
    +main() : void
  }
}

package com.in28minutes.springboot.web.controller {
  class WelcomeController <<Controller>> {
    +showWelcomePage() : String
  }
  class TodoController <<Controller>> {
    +initBinder() : void
    +showTodos() : String
    +showAddTodoPage() : String
    +deleteTodo() : String
    +showUpdateTodoPage() : String
    +updateTodo() : String
    +addTodo() : String
  }
  class ErrorController <<Controller>> {
    +handleException() : ModelAndView
  }
  class LogoutController <<Controller>> {
    +logout() : String
  }
}

package com.in28minutes.springboot.web.model {
  class Todo {
    -id : int
    -user : String
    -desc : String
    -targetDate : Date
    -isDone : boolean
    -prime : int
    +getId() : int
    +setId() : void
    +getUser() : String
    +setUser() : void
    +getDesc() : String
    +setDesc() : void
    +getTargetDate() : Date
    +setTargetDate() : void
  }
}

package com.in28minutes.springboot.web.security {
  class SecurityConfiguration {
    +configureGlobalSecurity() : void
    +configure() : void
  }
}

package com.in28minutes.springboot.web.service {
  class TodoService <<Service>> {
    -todos : List<Todo>
    -todoCount : int
    +retrieveTodos() : List<Todo>
    +retrieveTodo() : Todo
    +updateTodo() : void
    +addTodo() : void
    +deleteTodo() : void
  }
}

' --- Relatii ---
TodoController --> Todo
TodoController --> TodoService
TodoService --> Todo

@enduml