@startuml

package io.dubbo.springboot {
  class DubboProperties {
    -scan : String
    -application : ApplicationConfig
    -registry : RegistryConfig
    -protocol : ProtocolConfig
    -monitor : MonitorConfig
    -provider : ProviderConfig
    -module : ModuleConfig
    -method : MethodConfig
    -consumer : ConsumerConfig
    +getScan() : String
    +setScan() : void
    +getApplication() : ApplicationConfig
    +setApplication() : void
    +getRegistry() : RegistryConfig
    +setRegistry() : void
    +getProtocol() : ProtocolConfig
    +setProtocol() : void
  }
  class DubboConfigurationApplicationContextInitializer {
    +initialize() : void
  }
  class DubboAutoConfiguration {
    -dubboProperties : DubboProperties
    +requestApplicationConfig() : ApplicationConfig
    +requestRegistryConfig() : RegistryConfig
    +requestProtocolConfig() : ProtocolConfig
    +requestMonitorConfig() : MonitorConfig
    +requestProviderConfig() : ProviderConfig
    +requestModuleConfig() : ModuleConfig
    +requestMethodConfig() : MethodConfig
    +requestConsumerConfig() : ConsumerConfig
  }
  class DubboHolderListener {
    -LOGGER : Logger
    -holdThread : Thread
    -running : Boolean
    +onApplicationEvent() : void
    +run() : void
    +stopApplicationContext() : void
  }
}

' --- Relatii ---

@enduml