@startuml

package org.springframework.boot.autoconfigure.klock {
  class KlockAutoConfiguration {
    -klockConfig : KlockConfig
    +lockInfoProvider() : LockInfoProvider
    +businessKeyProvider() : BusinessKeyProvider
    +lockFactory() : LockFactory
  }
  class KlockConfiguration {
    +lockInfoProvider() : LockInfoProvider
    +businessKeyProvider() : BusinessKeyProvider
    +lockFactory() : LockFactory
    +klockConfig() : KlockConfig
  }
}

package org.springframework.boot.autoconfigure.klock.annotation {
  interface KlockKey {
  }
  interface Klock {
  }
}

package org.springframework.boot.autoconfigure.klock.config {
  class KlockConfig {
    -PREFIX : String
    -address : String
    -password : String
    -database : int
    -clusterServer : ClusterServer
    -waitTime : long
    -leaseTime : long
    -nodeAddresses : String[]
    +getAddress() : String
    +setAddress() : void
    +getPassword() : String
    +setPassword() : void
    +getWaitTime() : long
    +setWaitTime() : void
    +getLeaseTime() : long
    +setLeaseTime() : void
  }
}

package org.springframework.boot.autoconfigure.klock.core {
  class KlockAspectHandler {
    -logger : Logger
    -lockInfoProvider : LockInfoProvider
    -lockInfo : LockInfo
    -lock : Lock
    -res : Boolean
    +around() : Object
    +afterReturning() : void
    +afterThrowing() : void
    +getLock() : Lock
    +setLock() : void
  }
  class BusinessKeyProvider {
    -nameDiscoverer : ParameterNameDiscoverer
    -parser : ExpressionParser
    +getKeyName() : String
  }
  class LockInfoProvider {
    -LOCK_NAME_PREFIX : String
    -LOCK_NAME_SEPARATOR : String
    -klockConfig : KlockConfig
    -businessKeyProvider : BusinessKeyProvider
    -logger : Logger
  }
}

package org.springframework.boot.autoconfigure.klock.handler {
  class KlockTimeoutException {
  }
  class KlockInvocationException {
  }
}

package org.springframework.boot.autoconfigure.klock.handler.lock {
  interface LockTimeoutHandler {
  }
}

package org.springframework.boot.autoconfigure.klock.handler.release {
  interface ReleaseTimeoutHandler {
  }
}

package org.springframework.boot.autoconfigure.klock.lock {
  class WriteLock {
    -rLock : RReadWriteLock
    -lockInfo : LockInfo
    -redissonClient : RedissonClient
    +acquire() : boolean
    +release() : boolean
  }
  class LockFactory {
    -redissonClient : RedissonClient
    +getLock() : Lock
  }
  class ReentrantLock {
    -rLock : RLock
    -lockInfo : LockInfo
    -redissonClient : RedissonClient
    +acquire() : boolean
    +release() : boolean
    +getKey() : String
  }
  class FairLock {
    -rLock : RLock
    -lockInfo : LockInfo
    -redissonClient : RedissonClient
    +acquire() : boolean
    +release() : boolean
  }
  interface Lock {
  }
  class ReadLock {
    -rLock : RReadWriteLock
    -lockInfo : LockInfo
    -redissonClient : RedissonClient
    +acquire() : boolean
    +release() : boolean
  }
}

package org.springframework.boot.autoconfigure.klock.model {
  enum ReleaseTimeoutStrategy {
    +handle() : void
    +handle() : void
  }
  enum LockTimeoutStrategy {
    -DEFAULT_INTERVAL : long
    -DEFAULT_MAX_INTERVAL : long
    +handle() : void
    +handle() : void
    +handle() : void
  }
  enum LockType {
  }
  class LockInfo {
    -type : LockType
    -name : String
    -waitTime : long
    -leaseTime : long
    +getName() : String
    +setName() : void
    +getWaitTime() : long
    +setWaitTime() : void
    +getLeaseTime() : long
    +setLeaseTime() : void
    +getType() : LockType
    +setType() : void
  }
}

package org.springframework.boot.autoconfigure.klock.test {
  class KlockTests {
    -exception : ExpectedException
    +multithreadingTest() : void
    +jvm1() : void
    +jvm2() : void
    +jvm3() : void
    +businessKeyJvm1() : void
    +businessKeyJvm2() : void
    +businessKeyJvm3() : void
    +businessKeyJvm4() : void
  }
  class User {
    -id : int
    -name : String
    +getId() : int
    +setId() : void
    +getName() : String
    +setName() : void
  }
  class TimeoutService <<Service>> {
    -logger : Logger
    +foo1() : void
    +foo2() : void
    +foo3() : void
    +foo4() : String
    +foo5() : void
    +foo6() : void
    +foo7() : void
    +foo8() : String
  }
  class KlockTestApplication {
    +main() : void
  }
  class TestService <<Service>> {
    +getValue() : String
    +getValue() : String
    +getValue() : String
  }
}

' --- Relatii ---
KlockTests --> KlockTimeoutException
TimeoutService --> Klock
TimeoutService --> LockTimeoutStrategy
TimeoutService --> ReleaseTimeoutStrategy
TestService --> Klock
TestService --> KlockKey
TestService --> LockTimeoutStrategy
KlockAutoConfiguration --> KlockConfig
KlockAutoConfiguration --> BusinessKeyProvider
KlockAutoConfiguration --> KlockAspectHandler
KlockAutoConfiguration --> LockInfoProvider
KlockAutoConfiguration --> LockFactory
KlockConfiguration --> KlockConfig
KlockConfiguration --> BusinessKeyProvider
KlockConfiguration --> KlockAspectHandler
KlockConfiguration --> LockInfoProvider
KlockConfiguration --> LockFactory
LockTimeoutHandler --> Lock
LockTimeoutHandler --> LockInfo
ReleaseTimeoutHandler --> LockInfo
KlockAspectHandler --> Klock
KlockAspectHandler --> KlockInvocationException
KlockAspectHandler --> Lock
KlockAspectHandler --> LockFactory
KlockAspectHandler --> LockInfo
BusinessKeyProvider --> Klock
BusinessKeyProvider --> KlockKey
LockInfoProvider --> Klock
LockInfoProvider --> KlockConfig
LockInfoProvider --> LockInfo
LockInfoProvider --> LockType
WriteLock ..|> Lock
WriteLock --> LockInfo
LockFactory --> LockInfo
ReentrantLock ..|> Lock
ReentrantLock --> LockInfo
FairLock ..|> Lock
FairLock --> LockInfo
ReadLock ..|> Lock
ReadLock --> LockInfo
Klock --> LockTimeoutStrategy
Klock --> LockType
Klock --> ReleaseTimeoutStrategy
ReleaseTimeoutStrategy ..|> ReleaseTimeoutHandler
ReleaseTimeoutStrategy --> KlockTimeoutException
ReleaseTimeoutStrategy --> ReleaseTimeoutHandler
LockTimeoutStrategy ..|> LockTimeoutHandler
LockTimeoutStrategy --> KlockTimeoutException
LockTimeoutStrategy --> LockTimeoutHandler
LockTimeoutStrategy --> Lock

@enduml