@startuml

package com.softdev.system.configcenter {
  class ConfigCenterApplication {
    +main() : void
  }
}

package com.softdev.system.configcenter.controller {
  class ParamsController <<Controller>> {
    -miniProgramUrl : String
    +getparam() : String
  }
}

package com.softdev.system.demo {
  class SpringCloudStudyDemoApplication {
    +main() : void
  }
  class DemoApplication {
    +main() : void
  }
  class SecurityApp {
    +main() : void
  }
  class SpringCloudStudyApplication {
    +main() : void
  }
  class SpringCloudStudyDemoApplication {
    +main() : void
  }
  class SpringCloudStudyMybatisApplication {
    +main() : void
  }
  class DroolsApplication {
    +main() : void
  }
  class ElasticSearchApp {
    +main() : void
  }
  class SpringCloudStudyDemoApplication {
    +main() : void
  }
  class DemoApplication {
    +main() : void
  }
  class LogstashApplication {
    +main() : void
  }
  class SecurityApp {
    +main() : void
  }
  class EmptyApplication {
    +main() : void
  }
  class NettyUdpApplication {
    +main() : void
  }
  class EmptyApplication {
    +main() : void
  }
  class SpringAopApp {
    +main() : void
  }
}

package com.softdev.system.demo.client {
  class ChineseProverbClient {
    +run() : void
    +main() : void
  }
}

package com.softdev.system.demo.config {
  class ConfigurationFilter {
    +remoteIpFilter() : RemoteIpFilter
    +testFilterRegistration() : FilterRegistrationBean<MyFilter>
    +testFilterRegistration2() : FilterRegistrationBean<HttpPutFormContentFilter>
    +testFilterRegistration3() : FilterRegistrationBean<HiddenHttpMethodFilter>
    +destroy() : void
    +doFilter() : void
    +init() : void
  }
  class CorsFilter {
    +doFilter() : void
    +init() : void
    +destroy() : void
  }
  class FastjsonConverter {
    +customConverters() : HttpMessageConverters
  }
  class GlobalDefaultExceptionHandler {
    +defaultExceptionHandler() : ApiReturnObject
  }
  class WebSocketConfig {
    +serverEndpointExporter() : ServerEndpointExporter
  }
  class FastjsonConverter {
    +customConverters() : HttpMessageConverters
  }
  class WebSocketServer {
    -log : Log
    -onlineCount : int
    -session : Session
    -userId : String
    +onOpen() : void
    +onClose() : void
    +onMessage() : void
    +onError() : void
    +sendMessage() : void
    +sendInfo() : void
  }
  class WebSecurityConfig {
    -jwtAuthenticationEntryPoint : JwtAuthenticationEntryPoint
    -jwtUserDetailsService : JwtUserDetailsService
    -jwtRequestFilter : JwtRequestFilter
    -tokenHeader : String
    -authenticationPath : String
    +configureGlobal() : void
    +passwordEncoder() : PasswordEncoder
    +authenticationManagerBean() : AuthenticationManager
    +configure() : void
    +configure() : void
  }
  class JwtTokenUtil {
    -serialVersionUID : long
    -JWT_TOKEN_VALIDITY : long
    -secret : String
    -claims : Claims
    -expiration : Date
    -username : String
    +getUsernameFromToken() : String
    +getExpirationDateFromToken() : Date
    +generateToken() : String
    +validateToken() : Boolean
  }
  class JwtAuthenticationEntryPoint {
    -serialVersionUID : long
    +commence() : void
  }
  class JwtRequestFilter {
    -jwtUserDetailsService : JwtUserDetailsService
    -jwtTokenUtil : JwtTokenUtil
    -authenticationPath : String
    -requestTokenHeader : String
    +doFilterInternal() : void
  }
  class FastjsonConverter {
    +customConverters() : HttpMessageConverters
  }
  class JmsConfig {
    +jacksonJmsMessageConverter() : MessageConverter
    +main() : void
  }
  class ConfigurationFilter {
    +remoteIpFilter() : RemoteIpFilter
    +testFilterRegistration() : FilterRegistrationBean<MyFilter>
    +testFilterRegistration2() : FilterRegistrationBean<HttpPutFormContentFilter>
    +testFilterRegistration3() : FilterRegistrationBean<HiddenHttpMethodFilter>
    +destroy() : void
    +doFilter() : void
    +init() : void
  }
  class CorsFilter {
    +doFilter() : void
    +init() : void
    +destroy() : void
  }
  class FastjsonConverter {
    +customConverters() : HttpMessageConverters
  }
  class GlobalDefaultExceptionHandler {
    +defaultExceptionHandler() : ApiReturnObject
  }
  class CorsFilter {
    +doFilter() : void
    +init() : void
    +destroy() : void
  }
  class FastjsonConverter {
    +customConverters() : HttpMessageConverters
  }
  class SwaggerConfig {
    +createRestApi() : Docket
  }
  class ConfigurationFilter {
    +remoteIpFilter() : RemoteIpFilter
    +testFilterRegistration() : FilterRegistrationBean<MyFilter>
    +testFilterRegistration2() : FilterRegistrationBean<HttpPutFormContentFilter>
    +testFilterRegistration3() : FilterRegistrationBean<HiddenHttpMethodFilter>
    +destroy() : void
    +doFilter() : void
    +init() : void
  }
  class CorsFilter {
    +doFilter() : void
    +init() : void
    +destroy() : void
  }
  class FastjsonConverter {
    +customConverters() : HttpMessageConverters
  }
  class GlobalDefaultExceptionHandler {
    +defaultExceptionHandler() : ApiReturnObject
  }
  class MybatisPlusConfig {
    +paginationInterceptor() : PaginationInterceptor
  }
  class DruidConfiguration {
    -logger : Logger
    -DB_PREFIX : String
    -url : String
    -username : String
    -password : String
    -driverClassName : String
    -initialSize : int
    -minIdle : int
    -maxActive : int
    -maxWait : int
    +druidServlet() : ServletRegistrationBean
    +filterRegistrationBean() : FilterRegistrationBean
    +dataSource() : DataSource
    +getUrl() : String
    +setUrl() : void
    +getUsername() : String
    +setUsername() : void
    +getPassword() : String
  }
  class TaxiFareConfiguration {
    -drlFile : String
    +kieContainer() : KieContainer
  }
  class FastjsonConverter {
    +customConverters() : HttpMessageConverters
  }
  class FastjsonConverter {
    +customConverters() : HttpMessageConverters
  }
  class SwaggerConfig {
    +createRestApi() : Docket
  }
  class WebSocketConfig {
    +serverEndpointExporter() : ServerEndpointExporter
  }
  class ConfigurationFilter {
    +remoteIpFilter() : RemoteIpFilter
    +testFilterRegistration() : FilterRegistrationBean<MyFilter>
    +testFilterRegistration2() : FilterRegistrationBean<HttpPutFormContentFilter>
    +testFilterRegistration3() : FilterRegistrationBean<HiddenHttpMethodFilter>
    +destroy() : void
    +doFilter() : void
    +init() : void
  }
  class CorsFilter {
    +doFilter() : void
    +init() : void
    +destroy() : void
  }
  class FastjsonConverter {
    +customConverters() : HttpMessageConverters
  }
  class GlobalDefaultExceptionHandler {
    +defaultExceptionHandler() : ApiReturnObject
  }
  class WebSocketConfig {
    +serverEndpointExporter() : ServerEndpointExporter
  }
  class FastjsonConverter {
    +customConverters() : HttpMessageConverters
  }
  class WebSocketServer {
    -log : Log
    -onlineCount : int
    -session : Session
    -userId : String
    -siteId : String
    -wsMessageRepository : WsMessageRepository
    -wsSiteRepository : WsSiteRepository
    +onOpen() : void
    +onClose() : void
    +onMessage() : void
    +onError() : void
    +sendMessage() : void
    +sendInfo() : void
  }
  class DruidConfiguration {
    -logger : Logger
    -DB_PREFIX : String
    -url : String
    -username : String
    -password : String
    -driverClassName : String
    -initialSize : int
    -minIdle : int
    -maxActive : int
    -maxWait : int
    +druidServlet() : ServletRegistrationBean
    +filterRegistrationBean() : FilterRegistrationBean
    +dataSource() : DataSource
    +getUrl() : String
    +setUrl() : void
    +getUsername() : String
    +setUsername() : void
    +getPassword() : String
  }
  class FastjsonConverter {
    +customConverters() : HttpMessageConverters
  }
  class WebSecurityConfig {
    +configure() : void
  }
  class FastjsonConverter {
    +customConverters() : HttpMessageConverters
  }
  class CustomFromLoginFilter {
    +attemptAuthentication() : Authentication
  }
  class FastjsonConverter {
    +customConverters() : HttpMessageConverters
  }
  class FastjsonConverter {
    +customConverters() : HttpMessageConverters
  }
  class GlobalDefaultExceptionHandler {
    +defaultExceptionHandler() : ApiReturnObject
  }
  class FastjsonConverter {
    +customConverters() : HttpMessageConverters
  }
  class AspectConfig {
    +index_log() : void
    +doBefore() : void
    +doAfterReturning() : void
    +doAfterThrowing() : void
    +doAroundAdvice() : Object
  }
  class ConfigurationFilter {
    +remoteIpFilter() : RemoteIpFilter
    +testFilterRegistration() : FilterRegistrationBean<MyFilter>
    +testFilterRegistration2() : FilterRegistrationBean<HttpPutFormContentFilter>
    +testFilterRegistration3() : FilterRegistrationBean<HiddenHttpMethodFilter>
    +destroy() : void
    +doFilter() : void
    +init() : void
  }
  class CorsFilter {
    +doFilter() : void
    +init() : void
    +destroy() : void
  }
  class FastjsonConverter {
    +customConverters() : HttpMessageConverters
  }
  class GlobalDefaultExceptionHandler {
    +defaultExceptionHandler() : ApiReturnObject
  }
}

package com.softdev.system.demo.controller {
  class PoiController <<Controller>> {
    +generateWord() : ApiReturnObject
  }
  class DemoController <<Controller>> {
    +index() : ResponseEntity<String>
    +page() : ModelAndView
    +pushToWeb() : ResponseEntity<String>
  }
  class JwtAuthenticationController <<Controller>> {
    -authenticationManager : AuthenticationManager
    -jwtTokenUtil : JwtTokenUtil
    -userDetailsService : JwtUserDetailsService
    -tokenHeader : String
    -userDetails : UserDetails
    -token : String
    +getAuthenticatedUser() : JwtUser
  }
  class UserController <<Controller>> {
    +index() : ModelAndView
    +login() : ModelAndView
    +userList() : ModelAndView
  }
  class Receiver {
    +receiveMessage() : void
  }
  class TestController <<Controller>> {
    -jmsTemplate : JmsTemplate
    +updateItem() : Email
  }
  class IndexController <<Controller>> {
    +index() : ModelAndView
  }
  class UserController <<Controller>> {
    -userMapper : UserMapper
    +init() : ApiReturnObject
    +find() : ApiReturnObject
  }
  class TaxiController <<Controller>> {
    -taxiFareCalculatorService : TaxiFareCalculatorService
    +calTaxiFare() : ResponseEntity<Object>
  }
  class ArticleController <<Controller>> {
    -elasticsearchTemplate : ElasticsearchTemplate
    -articleRepository : ArticleRepository
    +newArticle() : Object
    +save() : Object
    +search() : Object
    +originSearch() : Object
  }
  class DemoController <<Controller>> {
    +index() : ApiReturnObject
    +sockethtml() : ModelAndView
    +basePath() : ApiReturnObject
    +getData() : ApiReturnObject
  }
  class DemoSocketServer {
    -onlineCount : int
    -webSocketSet : CopyOnWriteArraySet<DemoSocketServer>
    -session : Session
    +onOpen() : void
    +onClose() : void
    +onMessage() : void
    +onError() : void
    +sendMessage() : void
    +sendInfo() : void
  }
  class DemoController <<Controller>> {
    -wsMessageRepository : WsMessageRepository
    -wsSiteRepository : WsSiteRepository
    +index() : ResponseEntity<String>
    +page() : ModelAndView
    +pushToWeb() : ResponseEntity<String>
    +pushAll() : ResponseEntity<String>
    +scheduledCheck() : void
  }
  class DemoController <<Controller>> {
    -log : Logger
    +index() : Object
  }
  class UserController <<Controller>> {
    +index() : ModelAndView
    +login() : ModelAndView
    +userList() : ModelAndView
  }
  class DemoController <<Controller>> {
    +index() : ResponseEntity<String>
    +save() : Cert
    +find() : Cert
    +getType() : List<CertType>
    +clean() : List<CertType>
  }
  class DemoController <<Controller>> {
    +index() : ResponseEntity<String>
  }
  class DemoController <<Controller>> {
    +index() : ApiReturnObject
  }
}

package com.softdev.system.demo.entity {
  class JwtUser {
    -serialVersionUID : long
    -id : String
    -username : String
    -password : String
    -enabled : boolean
    +getId() : String
    +getUsername() : String
    +isAccountNonExpired() : boolean
    +isAccountNonLocked() : boolean
    +isCredentialsNonExpired() : boolean
    +getPassword() : String
    +isEnabled() : boolean
  }
  class JwtRequest {
    -serialVersionUID : long
    -username : String
    -password : String
  }
  class JwtResponse {
    -serialVersionUID : long
    -jwttoken : String
  }
  class Email {
    -serialVersionUID : long
    -to : String
    -body : String
    +getTo() : String
    +setTo() : void
    +getBody() : String
    +setBody() : void
  }
  class UserRole {
    -serialVersionUID : long
    -id : int
    -userId : String
    -roleId : String
    +getId() : int
    +setId() : void
    +getUserId() : String
    +setUserId() : void
    +getRoleId() : String
    +setRoleId() : void
  }
  class User {
    -serialVersionUID : long
    -id : int
    -userId : String
    -userName : String
    -passWord : String
    -name : String
    -tell : String
    -status : int
    +getUserId() : String
    +setUserId() : void
    +getId() : int
    +setId() : void
    +getUserName() : String
    +setUserName() : void
    +getPassWord() : String
    +setPassWord() : void
  }
  class Role {
    -serialVersionUID : long
    -id : int
    -roleId : String
    -roleName : String
    +getId() : int
    +setId() : void
    +getRoleId() : String
    +setRoleId() : void
    +getRoleName() : String
    +setRoleName() : void
  }
  class TaxiFare {
    -nightSurcharge : BigDecimal
    -rideFare : BigDecimal
    +total() : BigDecimal
  }
  class TaxiRide {
    -isNightSurcharge : Boolean
    -distanceInMile : BigDecimal
  }
  class Article {
    -id : Integer
    -title : String
    -text : String
    -createtime : Date
    -author : String
  }
  class WsSite <<Entity>> {
    -serialVersionUID : long
    -siteId : String
    -userId : String
    -createTime : Date
  }
  class WsMessage <<Entity>> {
    -serialVersionUID : long
    -id : String
    -fromUserId : String
    -toUserId : String
    -createTime : Date
    -readTime : Date
    -message : String
    -status : boolean
    -siteId : String
  }
  class CertType {
  }
  class Cert {
  }
}

package com.softdev.system.demo.handler {
  class MyWebSocketHandler {
    +channelActive() : void
    +channelInactive() : void
    +channelRead() : void
    +channelRead0() : void
  }
  class NettyServer {
    -port : int
    +start() : void
    +initChannel() : void
  }
  class MyChannelHandlerPool {
    -channelGroup : ChannelGroup
  }
  class ChineseProverbServerHandler {
    -DICTIONARY : String[]
    +channelRead0() : void
    +exceptionCaught() : void
  }
  class ChineseProverClientHandler {
    +channelRead0() : void
    +exceptionCaught() : void
  }
}

package com.softdev.system.demo.mapper {
  interface UserMapper <<Repository>> {
  }
}

package com.softdev.system.demo.repository {
  interface ArticleRepository <<Repository>> {
  }
  interface WsSiteRepository <<Repository>> {
    +findWsSiteUser() : List<WsSite>
  }
  interface WsMessageRepository <<Repository>> {
    +findWsMessages() : List<WsMessage>
    +deleteWsMessages() : int
  }
}

package com.softdev.system.demo.server {
  class ChineseProverbServer {
    +run() : void
    +main() : void
  }
}

package com.softdev.system.demo.service {
  class JwtUserDetailsService <<Service>> {
    +loadUserByUsername() : UserDetails
  }
  class TaxiFareCalculatorService <<Service>> {
    -kieContainer : KieContainer
    +calculateFare() : BigDecimal
  }
}

package com.softdev.system.demo.util {
  class ApiReturnUtil {
    -serialVersionUID : long
    +error() : ApiReturnObject
    +error() : ApiReturnObject
    +success() : ApiReturnObject
    +success() : ApiReturnObject
  }
  class BasePath {
    -contextPath : String
    -basePath : String
    -realPath : String
    +getBasePath() : String
    +getRealPath() : String
    +getMyRealPath() : String
  }
  class ApiReturnObject {
    -serialVersionUID : long
    +getErrorCode() : String
    +setErrorCode() : void
    +getErrorMessage() : Object
    +setErrorMessage() : void
    +getReturnObject() : Object
    +setReturnObject() : void
  }
  class ApiReturnUtil {
    -serialVersionUID : long
    +error() : ApiReturnObject
    +error() : ApiReturnObject
    +success() : ApiReturnObject
    +success() : ApiReturnObject
  }
  class ApiReturnObject {
    -serialVersionUID : long
    +getErrorCode() : String
    +setErrorCode() : void
    +getErrorMessage() : Object
    +setErrorMessage() : void
    +getReturnObject() : Object
    +setReturnObject() : void
  }
  class ApiReturnUtil {
    -serialVersionUID : long
    +error() : ApiReturnObject
    +error() : ApiReturnObject
    +success() : ApiReturnObject
    +success() : ApiReturnObject
  }
  class BasePath {
    -contextPath : String
    -basePath : String
    -realPath : String
    +getBasePath() : String
    +getRealPath() : String
    +getMyRealPath() : String
  }
  class SerializeUtil {
    +serialize() : byte[]
    +unSerialize() : Object
  }
  class ApiReturnObject {
    -serialVersionUID : long
    +getErrorCode() : String
    +setErrorCode() : void
    +getErrorMessage() : Object
    +setErrorMessage() : void
    +getReturnObject() : Object
    +setReturnObject() : void
  }
  class ApiReturnUtil {
    -serialVersionUID : long
    +error() : ApiReturnObject
    +error() : ApiReturnObject
    +success() : ApiReturnObject
    +success() : ApiReturnObject
  }
  class BasePath {
    -contextPath : String
    -basePath : String
    -realPath : String
    +getBasePath() : String
    +getRealPath() : String
    +getMyRealPath() : String
  }
  class ApiReturnObject {
    -serialVersionUID : long
    +getErrorCode() : String
    +setErrorCode() : void
    +getErrorMessage() : Object
    +setErrorMessage() : void
    +getReturnObject() : Object
    +setReturnObject() : void
  }
  class ApiReturnUtil {
    -serialVersionUID : long
    +error() : ApiReturnObject
    +error() : ApiReturnObject
    +success() : ApiReturnObject
    +success() : ApiReturnObject
  }
  class ApiReturnObject {
    -serialVersionUID : long
    +getErrorCode() : String
    +setErrorCode() : void
    +getErrorMessage() : Object
    +setErrorMessage() : void
    +getReturnObject() : Object
    +setReturnObject() : void
  }
  class ApiReturnUtil {
    -serialVersionUID : long
    +error() : ApiReturnObject
    +error() : ApiReturnObject
    +success() : ApiReturnObject
    +success() : ApiReturnObject
  }
  class BasePath {
    -contextPath : String
    -basePath : String
    -realPath : String
    +getBasePath() : String
    +getRealPath() : String
    +getMyRealPath() : String
  }
  class ApiReturnObject {
    -serialVersionUID : long
    +getErrorCode() : String
    +setErrorCode() : void
    +getErrorMessage() : Object
    +setErrorMessage() : void
    +getReturnObject() : Object
    +setReturnObject() : void
  }
  class SpringUtils {
    -beanFactory : ConfigurableListableBeanFactory
    +postProcessBeanFactory() : void
    +getBeanFactory() : ConfigurableListableBeanFactory
    +containsBean() : boolean
    +isSingleton() : boolean
    +getAliases() : String[]
  }
  class ApiReturnUtil {
    -serialVersionUID : long
    +error() : ApiReturnObject
    +error() : ApiReturnObject
    +success() : ApiReturnObject
    +success() : ApiReturnObject
  }
  class ApiReturnObject {
    -serialVersionUID : long
    +getErrorCode() : String
    +setErrorCode() : void
    +getErrorMessage() : Object
    +setErrorMessage() : void
    +getReturnObject() : Object
    +setReturnObject() : void
  }
  class ApiReturnUtil {
    -serialVersionUID : long
    +error() : ApiReturnObject
    +error() : ApiReturnObject
    +success() : ApiReturnObject
    +success() : ApiReturnObject
  }
  class ApiReturnObject {
    -serialVersionUID : long
    +getErrorCode() : String
    +setErrorCode() : void
    +getErrorMessage() : Object
    +setErrorMessage() : void
    +getReturnObject() : Object
    +setReturnObject() : void
  }
}

package com.softdev.system.eureka {
  class EurekaApplication {
    +main() : void
  }
}

package com.softdev.system.feign {
  class SpringCloudStudyFeignApplication {
    +main() : void
  }
}

package com.softdev.system.feign.config {
  class SwaggerConfig {
    +createRestApi() : Docket
  }
  class WebSocketConfig {
    +serverEndpointExporter() : ServerEndpointExporter
  }
  class ConfigurationFilter {
    +remoteIpFilter() : RemoteIpFilter
    +testFilterRegistration() : FilterRegistrationBean<MyFilter>
    +testFilterRegistration2() : FilterRegistrationBean<HttpPutFormContentFilter>
    +testFilterRegistration3() : FilterRegistrationBean<HiddenHttpMethodFilter>
    +destroy() : void
    +doFilter() : void
    +init() : void
  }
  class CorsFilter {
    +doFilter() : void
    +init() : void
    +destroy() : void
  }
  class FastjsonConverter {
    +customConverters() : HttpMessageConverters
  }
  class GlobalDefaultExceptionHandler {
    +defaultExceptionHandler() : ApiReturnObject
  }
}

package com.softdev.system.feign.controller {
  class FeignController <<Controller>> {
    +basePath() : ApiReturnObject
  }
  interface DemoRemoteClient {
    +getData() : ApiReturnObject
  }
}

package com.softdev.system.feign.util {
  class ApiReturnUtil {
    -serialVersionUID : long
    +error() : ApiReturnObject
    +error() : ApiReturnObject
    +success() : ApiReturnObject
    +success() : ApiReturnObject
  }
  class BasePath {
    -contextPath : String
    -basePath : String
    -realPath : String
    +getBasePath() : String
    +getRealPath() : String
    +getMyRealPath() : String
  }
  class ApiReturnObject {
    -serialVersionUID : long
    +getErrorCode() : String
    +setErrorCode() : void
    +getErrorMessage() : Object
    +setErrorMessage() : void
    +getReturnObject() : Object
    +setReturnObject() : void
  }
}

package com.softdev.system.jpa {
  class SpringCloudStudyJpaApplication {
    +main() : void
  }
}

package com.softdev.system.jpa.config {
  class SwaggerConfig {
    +createRestApi() : Docket
  }
  class ConfigurationFilter {
    +remoteIpFilter() : RemoteIpFilter
    +testFilterRegistration() : FilterRegistrationBean<MyFilter>
    +testFilterRegistration2() : FilterRegistrationBean<HttpPutFormContentFilter>
    +testFilterRegistration3() : FilterRegistrationBean<HiddenHttpMethodFilter>
    +destroy() : void
    +doFilter() : void
    +init() : void
  }
  class CorsFilter {
    +doFilter() : void
    +init() : void
    +destroy() : void
  }
  class FastjsonConverter {
    +customConverters() : HttpMessageConverters
  }
  class GlobalDefaultExceptionHandler {
    +defaultExceptionHandler() : ApiReturnObject
  }
}

package com.softdev.system.jpa.controller {
  class UserController <<Controller>> {
    +getuserRoleList() : ApiReturnObject
    +insertOrUpdate() : ApiReturnObject
    +init() : ApiReturnObject
  }
}

package com.softdev.system.jpa.entity {
  interface UserRoleList {
  }
  class UserRole <<Entity>> {
    -serialVersionUID : long
    -id : int
    -userId : String
    -roleId : String
    +getId() : int
    +setId() : void
    +getUserId() : String
    +setUserId() : void
    +getRoleId() : String
    +setRoleId() : void
  }
  class User <<Entity>> {
    -serialVersionUID : long
    -id : int
    -userId : String
    -userName : String
    -passWord : String
    -name : String
    -tell : String
    -status : int
    +getUserId() : String
    +setUserId() : void
    +getId() : int
    +setId() : void
    +getUserName() : String
    +setUserName() : void
    +getPassWord() : String
    +setPassWord() : void
  }
  class UserRoleListJson {
    +getUserName() : String
    +setUserName() : void
    +getRoleName() : String
    +setRoleName() : void
  }
  class Role <<Entity>> {
    -serialVersionUID : long
    -id : int
    -roleId : String
    -roleName : String
    +getId() : int
    +setId() : void
    +getRoleId() : String
    +setRoleId() : void
    +getRoleName() : String
    +setRoleName() : void
  }
}

package com.softdev.system.jpa.repository {
  interface UserRoleRepository {
  }
  interface RoleRepository {
  }
  interface UserRepository {
  }
}

package com.softdev.system.jpa.util {
  class ApiReturnUtil {
    -serialVersionUID : long
    +error() : ApiReturnObject
    +error() : ApiReturnObject
    +success() : ApiReturnObject
    +success() : ApiReturnObject
  }
  class BasePath {
    -contextPath : String
    -basePath : String
    -realPath : String
    +getBasePath() : String
    +getRealPath() : String
    +getMyRealPath() : String
  }
  class ApiReturnObject {
    -serialVersionUID : long
    +getErrorCode() : String
    +setErrorCode() : void
    +getErrorMessage() : Object
    +setErrorMessage() : void
    +getReturnObject() : Object
    +setReturnObject() : void
  }
}

package com.softdev.system.redis {
  class SpringCloudStudyRedisApplication {
    +main() : void
  }
}

package com.softdev.system.redis.config {
  class RedisConfig {
  }
  class ConfigurationFilter {
    +remoteIpFilter() : RemoteIpFilter
    +testFilterRegistration() : FilterRegistrationBean<MyFilter>
    +testFilterRegistration2() : FilterRegistrationBean<HttpPutFormContentFilter>
    +testFilterRegistration3() : FilterRegistrationBean<HiddenHttpMethodFilter>
    +destroy() : void
    +doFilter() : void
    +init() : void
  }
  class CorsFilter {
    +doFilter() : void
    +init() : void
    +destroy() : void
  }
  class FastjsonConverter {
    +customConverters() : HttpMessageConverters
  }
  class GlobalDefaultExceptionHandler {
    +defaultExceptionHandler() : ApiReturnObject
  }
}

package com.softdev.system.redis.controller {
  class RedisController <<Controller>> {
    +getItemById() : Item
    +getAllItem() : List<Item>
    +getAllItem2() : List<Item>
    +updateItem() : Item
    +updateItem() : Item
  }
}

package com.softdev.system.redis.entity {
  class Item {
    -serialVersionUID : long
    -itemId : int
    -itemName : String
    -itemIcon : String
    -itemDesc : String
    -itemStatus : String
    +getItemId() : int
    +setItemId() : void
    +getItemName() : String
    +setItemName() : void
    +getItemIcon() : String
    +setItemIcon() : void
    +getItemDesc() : String
    +setItemDesc() : void
  }
}

package com.softdev.system.redis.util {
  class ApiReturnUtil {
    -serialVersionUID : long
    +error() : ApiReturnObject
    +error() : ApiReturnObject
    +success() : ApiReturnObject
    +success() : ApiReturnObject
  }
  class BasePath {
    -contextPath : String
    -basePath : String
    -realPath : String
    +getBasePath() : String
    +getRealPath() : String
    +getMyRealPath() : String
  }
  class SerializeUtil {
    +serialize() : byte[]
    +unSerialize() : Object
  }
  class ApiReturnObject {
    -serialVersionUID : long
    +getErrorCode() : String
    +setErrorCode() : void
    +getErrorMessage() : Object
    +setErrorMessage() : void
    +getReturnObject() : Object
    +setReturnObject() : void
  }
}

package com.softdev.system.zuul {
  class ZuulApplication {
    +main() : void
  }
}

package com.softdev.system.zuul.config {
  class GateWayCorsConfig {
    -source : UrlBasedCorsConfigurationSource
    -corsConfiguration : CorsConfiguration
    +corsFilter() : CorsFilter
  }
  class WebSocketFilter {
    +filterType() : String
    +filterOrder() : int
    +shouldFilter() : boolean
    +run() : Object
  }
}

' --- Relatii ---
ConfigurationFilter --> BasePath
GlobalDefaultExceptionHandler --> ApiReturnObject
GlobalDefaultExceptionHandler --> ApiReturnUtil
PoiController --> ApiReturnObject
PoiController --> ApiReturnUtil
DemoController --> WebSocketServer
WebSecurityConfig --> JwtUserDetailsService
JwtRequestFilter --> JwtUserDetailsService
JwtAuthenticationController --> JwtTokenUtil
JwtAuthenticationController --> JwtRequest
JwtAuthenticationController --> JwtResponse
JwtAuthenticationController --> JwtUser
JwtAuthenticationController --> JwtUserDetailsService
JwtUserDetailsService --> User
JwtUserDetailsService --> JwtUser
JmsConfig --> Email
ConfigurationFilter --> BasePath
GlobalDefaultExceptionHandler --> ApiReturnObject
GlobalDefaultExceptionHandler --> ApiReturnUtil
Receiver --> Email
TestController --> Email
SpringCloudStudyDemoApplication --> NettyServer
ConfigurationFilter --> BasePath
GlobalDefaultExceptionHandler --> ApiReturnObject
GlobalDefaultExceptionHandler --> ApiReturnUtil
UserMapper --> User
UserController --> User
UserController --> UserMapper
UserController --> ApiReturnObject
UserController --> ApiReturnUtil
TaxiController --> TaxiFare
TaxiController --> TaxiRide
TaxiController --> TaxiFareCalculatorService
TaxiFareCalculatorService --> TaxiFare
TaxiFareCalculatorService --> TaxiRide
ArticleRepository --> Article
ArticleController --> Article
ArticleController --> ArticleRepository
ArticleController --> ApiReturnUtil
ConfigurationFilter --> BasePath
GlobalDefaultExceptionHandler --> ApiReturnObject
GlobalDefaultExceptionHandler --> ApiReturnUtil
DemoController --> ApiReturnObject
DemoController --> ApiReturnUtil
DemoController --> BasePath
WsSiteRepository --> WsSite
WsMessageRepository --> WsMessage
WebSocketServer --> WsMessage
WebSocketServer --> WsSite
WebSocketServer --> WsMessageRepository
WebSocketServer --> WsSiteRepository
WebSocketServer --> SpringUtils
DemoController --> WebSocketServer
DemoController --> WsMessage
DemoController --> WsSite
DemoController --> WsMessageRepository
DemoController --> WsSiteRepository
GateWayCorsConfig --> CorsFilter
DemoController --> Cert
DemoController --> CertType
GlobalDefaultExceptionHandler --> ApiReturnObject
GlobalDefaultExceptionHandler --> ApiReturnUtil
ChineseProverbServer --> ChineseProverbServerHandler
ChineseProverbClient --> ChineseProverClientHandler
ConfigurationFilter --> BasePath
GlobalDefaultExceptionHandler --> ApiReturnObject
GlobalDefaultExceptionHandler --> ApiReturnUtil
FeignController --> ApiReturnObject
FeignController --> ApiReturnUtil
FeignController --> BasePath
DemoRemoteClient --> ApiReturnObject
ConfigurationFilter --> BasePath
GlobalDefaultExceptionHandler --> ApiReturnObject
GlobalDefaultExceptionHandler --> ApiReturnUtil
RedisController --> Item
UserRoleRepository --> UserRole
RoleRepository --> Role
UserRepository --> User
UserRepository --> UserRoleList
ConfigurationFilter --> BasePath
GlobalDefaultExceptionHandler --> ApiReturnObject
GlobalDefaultExceptionHandler --> ApiReturnUtil
UserController --> Role
UserController --> User
UserController --> UserRole
UserController --> UserRoleList
UserController --> UserRoleListJson
UserController --> RoleRepository
UserController --> UserRepository
UserController --> UserRoleRepository
UserController --> ApiReturnObject
UserController --> ApiReturnUtil
GlobalDefaultExceptionHandler --> ApiReturnObject
GlobalDefaultExceptionHandler --> ApiReturnUtil
DemoController --> ApiReturnObject
DemoController --> ApiReturnUtil

@enduml