@startuml

package com.reljicd {
  class BlogDemoApplicationTests {
    +contextLoads() : void
  }
  class BlogDemoApplication {
    +main() : void
  }
}

package com.reljicd.config {
  class GlobalExceptionHandler {
    -logger : Logger
    -throwable : Throwable
    +exception() : ModelAndView
  }
  class SpringSecurityConfig {
    -accessDeniedHandler : AccessDeniedHandler
    -dataSource : DataSource
    -adminUsername : String
    -adminPassword : String
    -usersQuery : String
    -rolesQuery : String
    +configure() : void
    +configureGlobal() : void
    +passwordEncoder() : PasswordEncoder
  }
  class MyAccessDeniedHandler {
    -logger : Logger
    +handle() : void
  }
}

package com.reljicd.controller {
  class BlogController <<Controller>> {
    -userService : UserService
    -postService : PostService
    +blogForUsername() : String
  }
  class CommentController <<Controller>> {
    -postService : PostService
    -userService : UserService
    -commentService : CommentService
    +createNewPost() : String
    +commentPostWithId() : String
  }
  class RegistrationController <<Controller>> {
    -userService : UserService
    +registration() : String
    +createNewUser() : String
  }
  class PostController <<Controller>> {
    -postService : PostService
    -userService : UserService
    +newPost() : String
    +createNewPost() : String
    +editPostWithId() : String
    +getPostWithId() : String
    +deletePostWithId() : String
  }
  class BlogErrorController <<Controller>> {
    -PATH : String
    +error() : ModelAndView
    +error403() : ModelAndView
    +getErrorPath() : String
  }
  class HomeController <<Controller>> {
    -postService : PostService
    +home() : String
  }
  class LoginController <<Controller>> {
    +login() : String
  }
}

package com.reljicd.model {
  class Post <<Entity>> {
    -id : Long
    -title : String
    -body : String
    -createDate : Date
    -user : User
    -comments : Collection<Comment>
    +getId() : Long
    +setId() : void
    +getTitle() : String
    +setTitle() : void
    +getBody() : String
    +setBody() : void
    +getCreateDate() : Date
    +setCreateDate() : void
  }
  class User <<Entity>> {
    -id : Long
    -email : String
    -password : String
    -username : String
    -name : String
    -lastName : String
    -active : int
    -roles : Collection<Role>
    -posts : Collection<Post>
    +getId() : Long
    +setId() : void
    +getPassword() : String
    +setPassword() : void
    +getUsername() : String
    +setUsername() : void
    +getName() : String
    +setName() : void
  }
  class Comment <<Entity>> {
    -id : Long
    -body : String
    -createDate : Date
    -post : Post
    -user : User
    +getId() : Long
    +setId() : void
    +getBody() : String
    +setBody() : void
    +getCreateDate() : Date
    +setCreateDate() : void
    +getPost() : Post
    +setPost() : void
  }
  class Role <<Entity>> {
    -id : Long
    -role : String
    -users : Collection<User>
    +getId() : Long
    +setId() : void
    +getRole() : String
    +setRole() : void
    +getUsers() : Collection<User>
    +setUsers() : void
  }
}

package com.reljicd.repository {
  interface CommentRepository {
  }
  interface PostRepository {
  }
  interface RoleRepository {
  }
  interface UserRepository {
  }
}

package com.reljicd.service {
  interface UserService {
  }
  interface CommentService {
  }
  interface PostService {
  }
}

package com.reljicd.service.impl {
  class UserServiceImp <<Service>> {
    -userRepository : UserRepository
    -roleRepository : RoleRepository
    -passwordEncoder : PasswordEncoder
    -USER_ROLE : String
    +findByUsername() : Optional<User>
    +findByEmail() : Optional<User>
    +save() : User
  }
  class PostServiceImp <<Service>> {
    -postRepository : PostRepository
    +findForId() : Optional<Post>
    +save() : Post
    +findByUserOrderedByDatePageable() : Page<Post>
    +findAllOrderedByDatePageable() : Page<Post>
    +delete() : void
  }
  class CommentServiceImp <<Service>> {
    -commentRepository : CommentRepository
    +save() : Comment
  }
}

package com.reljicd.util {
  class Pager {
    -posts : Page<Post>
    +getPageIndex() : int
    +getPageSize() : int
    +hasNext() : boolean
    +hasPrevious() : boolean
    +getTotalPages() : int
    +getTotalElements() : long
    +getPosts() : Page<Post>
    +indexOutOfBounds() : boolean
  }
}

' --- Relatii ---
CommentRepository --> Comment
PostRepository --> Post
PostRepository --> User
RoleRepository --> Role
UserRepository --> User
Pager --> Post
BlogController --> Post
BlogController --> User
BlogController --> PostService
BlogController --> UserService
BlogController --> Pager
CommentController --> Comment
CommentController --> Post
CommentController --> User
CommentController --> CommentService
CommentController --> PostService
CommentController --> UserService
RegistrationController --> User
RegistrationController --> UserService
PostController --> Post
PostController --> User
PostController --> PostService
PostController --> UserService
HomeController --> Post
HomeController --> PostService
HomeController --> Pager
UserService --> User
CommentService --> Comment
PostService --> Post
PostService --> User
UserServiceImp ..|> UserService
UserServiceImp --> User
UserServiceImp --> RoleRepository
UserServiceImp --> UserRepository
UserServiceImp --> UserService
PostServiceImp ..|> PostService
PostServiceImp --> Post
PostServiceImp --> User
PostServiceImp --> PostRepository
PostServiceImp --> PostService
CommentServiceImp ..|> CommentService
CommentServiceImp --> Comment
CommentServiceImp --> CommentRepository
CommentServiceImp --> CommentService

@enduml