@startuml

package com.reljicd {
  class ShoppingCartApplicationTests {
    +contextLoads() : void
  }
  class ShoppingCartApplication {
    +main() : void
  }
}

package com.reljicd.config {
  class GlobalExceptionHandler {
    -logger : Logger
    -throwable : Throwable
    -model : Model
    +exception() : ModelAndView
  }
  class SpringSecurityConfig {
    -accessDeniedHandler : AccessDeniedHandler
    -dataSource : DataSource
    -adminUsername : String
    -adminPassword : String
    -usersQuery : String
    -rolesQuery : String
    +configure() : void
    +configureGlobal() : void
    +passwordEncoder() : PasswordEncoder
  }
  class MyAccessDeniedHandler {
    -logger : Logger
    +handle() : void
  }
}

package com.reljicd.controller {
  class CustomErrorController <<Controller>> {
    -PATH : String
    +error() : ModelAndView
    +error403() : ModelAndView
    +getErrorPath() : String
  }
  class ShoppingCartController <<Controller>> {
    -shoppingCartService : ShoppingCartService
    -productService : ProductService
    +shoppingCart() : ModelAndView
    +addProductToCart() : ModelAndView
    +removeProductFromCart() : ModelAndView
    +checkout() : ModelAndView
  }
  class RegistrationController <<Controller>> {
    -userService : UserService
    +registration() : ModelAndView
    +createNewUser() : ModelAndView
  }
  class HomeController <<Controller>> {
    -INITIAL_PAGE : int
    -productService : ProductService
    +home() : ModelAndView
  }
  class LoginController <<Controller>> {
    +login() : String
  }
}

package com.reljicd.exception {
  class NotEnoughProductsInStockException {
    -DEFAULT_MESSAGE : String
  }
}

package com.reljicd.model {
  class Product <<Entity>> {
    -id : Long
    -name : String
    -description : String
    -quantity : Integer
    -price : BigDecimal
    +getId() : Long
    +setId() : void
    +getName() : String
    +setName() : void
    +getDescription() : String
    +setDescription() : void
    +getQuantity() : Integer
    +setQuantity() : void
  }
  class User <<Entity>> {
    -id : Long
    -email : String
    -password : String
    -username : String
    -name : String
    -lastName : String
    -active : int
    -roles : Collection<Role>
    +getId() : Long
    +setId() : void
    +getPassword() : String
    +setPassword() : void
    +getUsername() : String
    +setUsername() : void
    +getName() : String
    +setName() : void
  }
  class Role <<Entity>> {
    -id : Long
    -role : String
    -users : Collection<User>
    +getId() : Long
    +setId() : void
    +getRole() : String
    +setRole() : void
    +getUsers() : Collection<User>
    +setUsers() : void
  }
}

package com.reljicd.repository {
  interface ProductRepository {
  }
  interface RoleRepository {
  }
  interface UserRepository {
  }
}

package com.reljicd.service {
  interface UserService {
  }
  interface ShoppingCartService {
  }
  interface ProductService {
  }
}

package com.reljicd.service.impl {
  class UserServiceImp <<Service>> {
    -userRepository : UserRepository
    -roleRepository : RoleRepository
    -passwordEncoder : PasswordEncoder
    -USER_ROLE : String
    +findByUsername() : Optional<User>
    +findByEmail() : Optional<User>
    +saveUser() : User
  }
  class ProductServiceImpl <<Service>> {
    -productRepository : ProductRepository
    +findAllProductsPageable() : Page<Product>
    +findById() : Optional<Product>
  }
  class ShoppingCartServiceImpl <<Service>> {
    -productRepository : ProductRepository
    +addProduct() : void
    +removeProduct() : void
    +checkout() : void
    +getTotal() : BigDecimal
  }
}

package com.reljicd.util {
  class Pager {
    -products : Page<Product>
    +getPageIndex() : int
    +getPageSize() : int
    +hasNext() : boolean
    +hasPrevious() : boolean
    +getTotalPages() : int
    +getTotalElements() : long
    +indexOutOfBounds() : boolean
  }
}

' --- Relatii ---
ProductRepository --> Product
RoleRepository --> Role
UserRepository --> User
Pager --> Product
ShoppingCartController --> NotEnoughProductsInStockException
ShoppingCartController --> ProductService
ShoppingCartController --> ShoppingCartService
RegistrationController --> User
RegistrationController --> UserService
HomeController --> Product
HomeController --> ProductService
HomeController --> Pager
UserService --> User
ShoppingCartService --> NotEnoughProductsInStockException
ShoppingCartService --> Product
ProductService --> Product
UserServiceImp ..|> UserService
UserServiceImp --> User
UserServiceImp --> RoleRepository
UserServiceImp --> UserRepository
UserServiceImp --> UserService
ProductServiceImpl ..|> ProductService
ProductServiceImpl --> Product
ProductServiceImpl --> ProductRepository
ProductServiceImpl --> ProductService
ShoppingCartServiceImpl ..|> ShoppingCartService
ShoppingCartServiceImpl --> NotEnoughProductsInStockException
ShoppingCartServiceImpl --> Product
ShoppingCartServiceImpl --> ProductRepository
ShoppingCartServiceImpl --> ShoppingCartService
NotEnoughProductsInStockException --> Product

@enduml