@startuml

  class MavenWrapperDownloader {
    -WRAPPER_VERSION : String
    -DEFAULT_DOWNLOAD_URL : String
    -MAVEN_WRAPPER_PROPERTIES_PATH : String
    -MAVEN_WRAPPER_JAR_PATH : String
    -PROPERTY_NAME_WRAPPER_URL : String
    +main() : void
    +getPasswordAuthentication() : PasswordAuthentication
  }

package com.tericcabrel.authorization {
  class AuthorizationApplicationTests {
    -MONGO_DB_CONTAINER : MongoDBContainer
  }
  class TestUtility {
    +createHeaders() : HttpHeaders
  }
  class BaseIT {
    -MONGO_DB_CONTAINER : MongoDBContainer
    -testUtility : TestUtility
  }
  class AuthorizationApplication {
    +main() : void
  }
}

package com.tericcabrel.authorization.boostrap {
  class DataSeeder {
    -roleService : RoleService
    -userService : UserService
    -permissionLoader : PermissionLoader
    +onApplicationEvent() : void
  }
  class MongoEnsureIndexes {
    -mongoTemplate : MongoTemplate
    +onApplicationEvent() : void
  }
}

package com.tericcabrel.authorization.configs {
  class WebSecurityConfig {
    -userServiceImpl : UserServiceImpl
    -jwtTokenUtil : JwtTokenUtil
    -unauthorizedHandler : AuthEntryPoint
    +authenticationManagerBean() : AuthenticationManager
    +globalUserDetails() : void
    +authenticationTokenFilterBean() : AuthenticationFilter
    +configure() : void
    +encoder() : BCryptPasswordEncoder
  }
  class ResourceWebConfig {
    -environment : Environment
    -registry : ResourceHandlerRegistry
    +addResourceHandlers() : void
  }
  class RedisConfiguration {
    +redisConnectionFactory() : LettuceConnectionFactory
    +redisProperties() : RedisProperties
  }
  class TemplateEngineConfig {
    -EMAIL_TEMPLATE_ENCODING : String
    -templateEngine : SpringTemplateEngine
    -templateResolver : ClassLoaderTemplateResolver
    +emailTemplateEngine() : TemplateEngine
    +webTemplateResolver() : ClassLoaderTemplateResolver
    +webTemplateEngine() : SpringTemplateEngine
    +viewResolver() : ViewResolver
    +addViewControllers() : void
  }
  class SwaggerProperties {
    -apiVersion : String
    -enabled : String
    -title : String
    -description : String
    -useDefaultResponseMessages : String
    -enableUrlTemplating : String
    -deepLinking : String
    -defaultModelsExpandDepth : String
    -defaultModelExpandDepth : String
    -displayOperationId : String
    +getApiVersion() : String
    +setApiVersion() : SwaggerProperties
    +getEnabled() : String
    +setEnabled() : SwaggerProperties
    +getTitle() : String
    +setTitle() : SwaggerProperties
    +getDescription() : String
    +setDescription() : SwaggerProperties
  }
  class SwaggerConfiguration {
    -methodsWithTryItOutButton : String[]
    -DEFAULT_PRODUCES_AND_CONSUMES : Set<String>
    +api() : Docket
    +tryItOutConfig() : UiConfiguration
  }
  class CORSFilter {
    +doFilter() : void
    +init() : void
    +destroy() : void
  }
  class AuthEntryPoint {
    +commence() : void
  }
  class AuthenticationFilter {
    -userDetailsService : UserDetailsService
    -jwtTokenUtil : JwtTokenUtil
    +doFilterInternal() : void
  }
}

package com.tericcabrel.authorization.constraints {
  interface Exists {
  }
  interface FieldMatch {
  }
  interface IsUnique {
  }
}

package com.tericcabrel.authorization.constraints.validators {
  class FieldMatchValidator {
    -firstFieldName : String
    -secondFieldName : String
    -constraintAnnotation : FieldMatch
    -value : Object
    -context : ConstraintValidatorContext
    -firstObj : Object
    -secondObj : Object
    -ignore : Exception
    +initialize() : void
    +isValid() : boolean
  }
  class IsUniqueValidator {
    -propertyName : String
    -repositoryName : String
    -action : UpdateAction
    -applicationContext : ApplicationContext
    -constraintAnnotation : IsUnique
    -value : Object
    -context : ConstraintValidatorContext
    -propertyObj : Object
    -objId : Object
    +initialize() : void
    +isValid() : boolean
  }
  class ExistsValidator {
    -propertyName : String
    -repositoryName : String
    -applicationContext : ApplicationContext
    -constraintAnnotation : Exists
    -value : Object
    -context : ConstraintValidatorContext
    -propertyObj : Object
    +initialize() : void
    +isValid() : boolean
  }
}

package com.tericcabrel.authorization.controllers {
  class RegisterUserIT {
    -ENDPOINT : String
    -restTemplate : TestRestTemplate
    -mailSender : JavaMailSender
    +testRegisterUserSuccess() : void
  }
  class RegisterUserTest {
    +testFailToRegisterUserCauseInvalidData() : void
  }
  class AdminController <<Controller>> {
    -roleService : RoleService
    -userService : UserService
    +create() : ResponseEntity<UserResponse>
    +delete() : ResponseEntity<Void>
  }
  class TokenController <<Controller>> {
    -logger : Log
    -jwtTokenUtil : JwtTokenUtil
    -refreshTokenRepository : RefreshTokenRepository
    -userService : UserService
    +refresh() : ResponseEntity<Object>
  }
  class AuthController <<Controller>> {
    -logger : Logger
    -userService : UserService
    -roleService : RoleService
    -authenticationManager : AuthenticationManager
    -jwtTokenUtil : JwtTokenUtil
    -refreshTokenRepository : RefreshTokenRepository
    -eventPublisher : ApplicationEventPublisher
    -userAccountService : UserAccountService
    -authentication : Authentication
    -token : String
    +register() : ResponseEntity<Object>
    +login() : ResponseEntity<Object>
    +confirmAccount() : ResponseEntity<Object>
  }
  class RoleController <<Controller>> {
    -roleService : RoleService
    -permissionService : PermissionService
    +create() : ResponseEntity<Role>
    +all() : ResponseEntity<RoleListResponse>
    +one() : ResponseEntity<RoleResponse>
    +update() : ResponseEntity<RoleResponse>
    +delete() : ResponseEntity<Void>
    +addPermissions() : ResponseEntity<RoleResponse>
    +removePermissions() : ResponseEntity<RoleResponse>
  }
  class ResetPasswordController <<Controller>> {
    -userService : UserService
    -eventPublisher : ApplicationEventPublisher
    -userAccountService : UserAccountService
  }
  class UserController <<Controller>> {
    -logger : Log
    -userService : UserService
    -permissionService : PermissionService
    -fileStorageServiceImpl : FileStorageServiceImpl
    +all() : ResponseEntity<UserListResponse>
    +currentUser() : ResponseEntity<UserResponse>
    +one() : ResponseEntity<UserResponse>
    +update() : ResponseEntity<UserResponse>
    +updatePassword() : ResponseEntity<UserResponse>
    +delete() : ResponseEntity<Void>
    +uploadPicture() : ResponseEntity<UserResponse>
    +assignPermissions() : ResponseEntity<UserResponse>
  }
  class PermissionController <<Controller>> {
    -permissionService : PermissionService
    +all() : ResponseEntity<PermissionListResponse>
    +one() : ResponseEntity<PermissionResponse>
  }
}

package com.tericcabrel.authorization.events {
  class OnRegistrationCompleteEvent {
    -user : User
    +getUser() : User
    +setUser() : OnRegistrationCompleteEvent
  }
  class OnResetPasswordEvent {
    -user : User
    +getUser() : User
    +setUser() : OnResetPasswordEvent
  }
}

package com.tericcabrel.authorization.exceptions {
  class ResourceNotFoundException {
    -serialVersionUID : long
  }
  class PasswordNotMatchException {
    -serialVersionUID : long
  }
  class GlobalExceptionHandler {
  }
  class FileNotFoundException {
    -serialVersionUID : long
  }
  class FileStorageException {
    -serialVersionUID : long
  }
}

package com.tericcabrel.authorization.listeners {
  class ModelUpdateListener {
    +onBeforeSave() : void
    +onBeforeConvert() : void
  }
  class RegistrationListener {
    -TEMPLATE_NAME : String
    -SPRING_LOGO_IMAGE : String
    -PNG_MIME : String
    -MAIL_SUBJECT : String
    -environment : Environment
    -userAccountService : UserAccountService
    -mailSender : JavaMailSender
    -htmlTemplateEngine : TemplateEngine
    -mimeMessage : MimeMessage
    -email : MimeMessageHelper
    +onApplicationEvent() : void
  }
  class ResetPasswordListener {
    -TEMPLATE_NAME : String
    -MAIL_SUBJECT : String
    -environment : Environment
    -userAccountService : UserAccountService
    -mailSender : JavaMailSender
    -htmlTemplateEngine : TemplateEngine
    -mimeMessage : MimeMessage
    -email : MimeMessageHelper
    -ctx : Context
    -htmlContent : String
    +onApplicationEvent() : void
  }
}

package com.tericcabrel.authorization.models.dtos {
  class UpdateUserPermissionDto {
    -permissions : String[]
  }
  class ValidateTokenDto {
    -token : String
  }
  class RefreshTokenDto {
    -token : String
  }
  class UpdatePasswordDto {
    -currentPassword : String
    -newPassword : String
  }
  class ResetPasswordDto {
    -token : String
    -password : String
    -confirmPassword : String
  }
  class LoginUserDto {
    -email : String
    -password : String
  }
  class CreateRoleDto {
    -name : String
    -description : String
    -isDefault : boolean
    +toRole() : Role
  }
  class CreateUserDto {
    -id : String
    -firstName : String
    -lastName : String
    -email : String
    -password : String
    -timezone : String
    -confirmPassword : String
    -gender : String
    -avatar : String
    -enabled : boolean
  }
  class ForgotPasswordDto {
    -email : String
  }
  class UpdateUserDto {
    -firstName : String
    -lastName : String
    -timezone : String
    -gender : String
    -avatar : String
    -enabled : boolean
    -confirmed : boolean
    -coordinates : Coordinates
    -roles : Set<Role>
  }
  class UpdateRolePermissionDto {
    -permissions : String[]
  }
  class UpdateRoleDto {
    -userId : String
    -roles : String[]
  }
  class PermissionLoadDto {
    -name : String
    -description : String
    -roleNames : String[]
    +toPermission() : Permission
  }
}

package com.tericcabrel.authorization.models.entities {
  class BaseModel {
    -id : String
    -createdAt : Date
    -updatedAt : Date
  }
  class RefreshToken {
    -id : String
    -value : String
  }
  class User {
    -firstName : String
    -lastName : String
    -gender : String
    -email : String
    -password : String
    -enabled : boolean
    -confirmed : boolean
    -avatar : String
    -timezone : String
    -coordinates : Coordinates
    +addPermission() : void
    +hasPermission() : boolean
    +removePermission() : void
    +allPermissions() : Set<Permission>
  }
  class Coordinates {
    -lat : float
    -lon : float
  }
  class Permission {
    -name : String
    -description : String
  }
  class Role {
    -name : String
    -description : String
    -isDefault : boolean
    -permissions : Set<Permission>
    +addPermission() : Role
    +hasPermission() : boolean
    +removePermission() : Role
  }
  class UserAccount {
    -user : User
    -token : String
    -expireAt : long
    +isExpired() : boolean
  }
}

package com.tericcabrel.authorization.models.enums {
  enum PermissionLoadMode {
  }
}

package com.tericcabrel.authorization.models.response {
  class InvalidDataResponse {
  }
  class UserListResponse {
    -data : List<User>
  }
  class UserResponse {
    -data : User
  }
  class RoleResponse {
    -data : Role
  }
  class RoleListResponse {
    -data : List<Role>
  }
  class SuccessResponse {
  }
  class PermissionListResponse {
    -data : List<Permission>
  }
  class BadRequestResponse {
  }
  class GenericResponse {
    -data : Object
  }
  class PermissionResponse {
    -data : Permission
  }
  class AuthTokenResponse {
    -accessToken : String
    -refreshToken : String
    -expiresIn : long
  }
}

package com.tericcabrel.authorization.repositories {
  interface UserAccountRepository <<Repository>> {
  }
  interface RefreshTokenRepository <<Repository>> {
  }
  interface RoleRepository <<Repository>> {
  }
  interface UserRepository <<Repository>> {
  }
  interface PermissionRepository <<Repository>> {
  }
}

package com.tericcabrel.authorization.services {
  class PermissionLoaderImpl <<Service>> {
    -logger : Log
    -loadMode : PermissionLoadMode
    -roleRepository : RoleRepository
    -permissionRepository : PermissionRepository
    +load() : void
  }
  class UserAccountServiceImpl <<Service>> {
    -userAccountRepository : UserAccountRepository
    +save() : UserAccount
    +findAll() : List<UserAccount>
    +delete() : void
    +findByToken() : UserAccount
    +findById() : UserAccount
  }
  class RoleServiceImpl <<Service>> {
    -roleRepository : RoleRepository
    +save() : Role
    +findAll() : List<Role>
    +delete() : void
    +findByName() : Role
    +findById() : Role
    +update() : Role
    +update() : Role
  }
  class PermissionServiceImpl <<Service>> {
    -permissionRepository : PermissionRepository
    +findAll() : List<Permission>
    +findByName() : Optional<Permission>
    +findById() : Optional<Permission>
  }
  class FileStorageServiceImpl <<Service>> {
    -fileStorageLocation : Path
    +storeFile() : String
    +loadFileAsResource() : Resource
    +deleteFile() : boolean
  }
  class UserServiceImpl <<Service>> {
    -userRepository : UserRepository
    -bCryptEncoder : BCryptPasswordEncoder
    +save() : User
    +findAll() : List<User>
    +delete() : void
    +findByEmail() : User
    +findById() : User
    +update() : User
    +update() : void
    +updatePassword() : User
  }
}

package com.tericcabrel.authorization.services.interfaces {
  interface UserService {
  }
  interface PermissionLoader {
  }
  interface RoleService {
  }
  interface UserAccountService {
  }
  interface PermissionService {
  }
}

package com.tericcabrel.authorization.utils {
  class JwtTokenUtil {
    -jwtSecretKey : String
    -claims : Claims
    -expiration : Date
    -username : String
    +getUsernameFromToken() : String
    +getExpirationDateFromToken() : Date
    +createTokenFromAuth() : String
    +createTokenFromUser() : String
    +validateToken() : Boolean
  }
  class Helpers {
    +generateRandomString() : String
    +getFileExtension() : String
    +capitalize() : String
  }
  class Constants {
    -TOKEN_LIFETIME_SECONDS : long
    -TOKEN_PREFIX : String
    -HEADER_STRING : String
    -AUTHORITIES_KEY : String
    -ROLE_USER : String
    -ROLE_ADMIN : String
    -ROLE_SUPER_ADMIN : String
    -JWT_ILLEGAL_ARGUMENT_MESSAGE : String
    -JWT_EXPIRED_MESSAGE : String
    -JWT_SIGNATURE_MESSAGE : String
  }
}

' --- Relatii ---
AuthorizationApplicationTests --> Role
AuthorizationApplicationTests --> RoleRepository
RegisterUserIT --|> BaseIT
RegisterUserIT --> BaseIT
RegisterUserIT --> CreateUserDto
RegisterUserIT --> Coordinates
RegisterUserIT --> User
RegisterUserIT --> InvalidDataResponse
RegisterUserTest --> GlobalExceptionHandler
RegisterUserTest --> RoleService
RegisterUserTest --> UserService
Exists --> ExistsValidator
FieldMatch --> FieldMatchValidator
IsUnique --> IsUniqueValidator
FieldMatchValidator --> FieldMatch
IsUniqueValidator --> IsUnique
IsUniqueValidator --> Helpers
ExistsValidator --> Exists
ExistsValidator --> Helpers
JwtTokenUtil --> User
UserAccountRepository --> UserAccount
RefreshTokenRepository --> RefreshToken
RoleRepository --> Role
UserRepository --> User
PermissionRepository --> Permission
UserListResponse --> User
UserResponse --> User
RoleResponse --> Role
RoleListResponse --> Role
PermissionListResponse --> Permission
PermissionResponse --> Permission
ResetPasswordDto --> FieldMatch
CreateRoleDto --> Role
CreateUserDto --> IsUnique
CreateUserDto --> FieldMatch
CreateUserDto --> Role
CreateUserDto --> Coordinates
ForgotPasswordDto --> Exists
UpdateUserDto --> Coordinates
UpdateUserDto --> Role
PermissionLoadDto --> Permission
User --|> BaseModel
Permission --|> BaseModel
Role --|> BaseModel
UserAccount --|> BaseModel
GlobalExceptionHandler --> BadRequestResponse
GlobalExceptionHandler --> InvalidDataResponse
GlobalExceptionHandler --> GenericResponse
GlobalExceptionHandler --> Helpers
WebSecurityConfig --> UserServiceImpl
WebSecurityConfig --> JwtTokenUtil
AuthenticationFilter --> JwtTokenUtil
DataSeeder --> ResourceNotFoundException
DataSeeder --> PermissionLoader
DataSeeder --> CreateRoleDto
DataSeeder --> CreateUserDto
DataSeeder --> RoleService
DataSeeder --> UserService
MongoEnsureIndexes --> Permission
MongoEnsureIndexes --> Role
MongoEnsureIndexes --> User
OnRegistrationCompleteEvent --> User
OnResetPasswordEvent --> User
AdminController --> ResourceNotFoundException
AdminController --> CreateUserDto
AdminController --> Role
AdminController --> User
AdminController --> BadRequestResponse
AdminController --> InvalidDataResponse
AdminController --> SuccessResponse
AdminController --> UserResponse
AdminController --> RoleService
AdminController --> UserService
TokenController --> ResourceNotFoundException
TokenController --> RefreshTokenDto
TokenController --> ValidateTokenDto
TokenController --> User
TokenController --> RefreshToken
TokenController --> RefreshTokenRepository
TokenController --> UserService
TokenController --> JwtTokenUtil
AuthController --> ResourceNotFoundException
AuthController --> Role
AuthController --> LoginUserDto
AuthController --> CreateUserDto
AuthController --> ValidateTokenDto
AuthController --> UserAccount
AuthController --> User
AuthController --> RefreshToken
AuthController --> RefreshTokenRepository
AuthController --> RoleService
AuthController --> UserService
AuthController --> UserAccountService
AuthController --> JwtTokenUtil
AuthController --> Helpers
AuthController --> OnRegistrationCompleteEvent
RoleController --> ResourceNotFoundException
RoleController --> CreateRoleDto
RoleController --> Role
RoleController --> RoleService
RoleController --> UpdateRolePermissionDto
RoleController --> Permission
RoleController --> PermissionService
ResetPasswordController --> ResourceNotFoundException
ResetPasswordController --> UserAccount
ResetPasswordController --> BadRequestResponse
ResetPasswordController --> SuccessResponse
ResetPasswordController --> UserAccountService
ResetPasswordController --> ForgotPasswordDto
ResetPasswordController --> ResetPasswordDto
ResetPasswordController --> InvalidDataResponse
ResetPasswordController --> User
ResetPasswordController --> UserService
ResetPasswordController --> OnResetPasswordEvent
UserController --> ResourceNotFoundException
UserController --> UpdateUserPermissionDto
UserController --> Permission
UserController --> PermissionService
UserController --> UpdatePasswordDto
UserController --> UpdateUserDto
UserController --> User
UserController --> PasswordNotMatchException
UserController --> FileStorageServiceImpl
UserController --> UserService
PermissionController --> ResourceNotFoundException
PermissionController --> Permission
PermissionController --> BadRequestResponse
PermissionController --> PermissionListResponse
PermissionController --> PermissionResponse
PermissionController --> RoleListResponse
PermissionController --> RoleResponse
PermissionController --> SuccessResponse
PermissionController --> PermissionService
ModelUpdateListener --> BaseModel
RegistrationListener --> User
RegistrationListener --> UserAccountService
RegistrationListener --> OnRegistrationCompleteEvent
ResetPasswordListener --> UserAccountService
ResetPasswordListener --> User
ResetPasswordListener --> OnResetPasswordEvent
PermissionLoaderImpl ..|> PermissionLoader
PermissionLoaderImpl --> PermissionLoadDto
PermissionLoaderImpl --> Permission
PermissionLoaderImpl --> Role
PermissionLoaderImpl --> PermissionLoadMode
PermissionLoaderImpl --> PermissionRepository
PermissionLoaderImpl --> RoleRepository
PermissionLoaderImpl --> PermissionLoader
UserAccountServiceImpl ..|> UserAccountService
UserAccountServiceImpl --> ResourceNotFoundException
UserAccountServiceImpl --> UserAccountService
UserAccountServiceImpl --> UserAccount
UserAccountServiceImpl --> User
UserAccountServiceImpl --> UserAccountRepository
RoleServiceImpl ..|> RoleService
RoleServiceImpl --> ResourceNotFoundException
RoleServiceImpl --> RoleService
RoleServiceImpl --> CreateRoleDto
RoleServiceImpl --> Role
RoleServiceImpl --> RoleRepository
PermissionServiceImpl ..|> PermissionService
PermissionServiceImpl --> Permission
PermissionServiceImpl --> PermissionRepository
PermissionServiceImpl --> PermissionService
FileStorageServiceImpl --> Helpers
FileStorageServiceImpl --> FileNotFoundException
FileStorageServiceImpl --> FileStorageException
UserServiceImpl ..|> UserService
UserServiceImpl --> ResourceNotFoundException
UserServiceImpl --> CreateUserDto
UserServiceImpl --> UpdatePasswordDto
UserServiceImpl --> UpdateUserDto
UserServiceImpl --> User
UserServiceImpl --> UserRepository
UserServiceImpl --> UserService
UserService --> ResourceNotFoundException
UserService --> UpdatePasswordDto
UserService --> UpdateUserDto
UserService --> CreateUserDto
UserService --> User
RoleService --> ResourceNotFoundException
RoleService --> CreateRoleDto
RoleService --> Role
UserAccountService --> ResourceNotFoundException
UserAccountService --> UserAccount
UserAccountService --> User
PermissionService --> Permission

@enduml