@startuml

package com.shawn {
  class Application {
    +main() : void
  }
}

package com.shawn.constant {
  class ErrorCode {
    -SERVER_INTERNAL_ERROR : int
    -PARAMETER_MISSING_ERROR : int
    -PARAMETER_ILLEGAL_ERROR : int
    -RESOURCE_NOT_FOUND_ERROR : int
  }
  class PageConstant {
    -PAGE : int
    -PER_PAGE : int
  }
  class ResourceNameConstant {
    -BOOK : String
  }
}

package com.shawn.model.dto {
  class PaginatedResult {
    -serialVersionUID : long
    -currentPage : int
    -totalPage : int
    -data : Object
  }
  class CustomUserDetails {
    -serialVersionUID : long
    -enabled : boolean
    -accountNonExpired : boolean
    -credentialsNonExpired : boolean
    -accountNonLocked : boolean
    -authorities : Set<GrantedAuthority>
  }
  class Error {
    -serialVersionUID : long
    -code : int
    -message : String
  }
}

package com.shawn.model.entity {
  class BookStoreWithBooks {
    -serialVersionUID : long
    -books : List<Book>
  }
  class BookStore {
    -serialVersionUID : long
    -id : long
    -name : String
    -address : String
  }
  class User {
    -serialVersionUID : long
    -id : Long
    -username : String
    -password : String
  }
  class Book {
    -serialVersionUID : long
    -id : Long
    -name : String
    -author : String
    -price : Double
    -topic : String
    -publishDate : Date
    -bookStoreId : Long
  }
  class BookWithBookStore {
    -serialVersionUID : long
    -bookStore : BookStore
  }
}

package com.shawn.monitor {
  class PerformanceMonitor {
    +monitorElapsedTime() : Object
  }
  class ServiceMonitor {
    +monitorException() : void
  }
}

package com.shawn.repository {
  interface BookRepository {
  }
  interface UserRepository {
  }
  interface BookStoreRepository {
  }
}

package com.shawn.repository.mybatis {
  interface BookStoreMapper {
  }
  interface UserMapper {
  }
  interface BookMapper {
  }
}

package com.shawn.security {
  class ResourceServerConfiguration {
    +configure() : void
  }
  class WebSecurityConfiguration {
    -userService : UserService
    +init() : void
  }
  class AuthorizationServerConfiguration {
    -tokenStore : TokenStore
    -authenticationManager : AuthenticationManager
    -userService : UserService
    +configure() : void
    +configure() : void
    +tokenStore() : TokenStore
    +tokenServices() : DefaultTokenServices
  }
}

package com.shawn.service {
  interface UserService {
  }
  interface BookStoreService {
  }
  interface BookService {
  }
}

package com.shawn.service.impl {
  class BookServiceImpl <<Service>> {
    -bookRepository : BookRepository
    +getBookById() : Optional<Book>
    +getBooksByAuthor() : List<Book>
    +getBooksByPage() : List<Book>
    +getAllBookNames() : List<String>
    +getBookWithBookStoreById() : Optional<BookWithBookStore>
    +getTotalPage() : Integer
    +saveBook() : boolean
    +modifyBookOnNameById() : boolean
  }
  class UserServiceImpl <<Service>> {
    -userRepository : UserRepository
    +loadUserByUsername() : UserDetails
    +getUserById() : Optional<User>
    +saveUser() : boolean
    +modifyUserOnPasswordById() : boolean
    +deleteUserById() : boolean
  }
  class BookStoreServiceImpl <<Service>> {
    -bookStoreRepository : BookStoreRepository
    +getBookStoreById() : Optional<BookStore>
    +getAllBookStoreNames() : List<String>
    +getBookStoreWithBooksById() : Optional<BookStoreWithBooks>
  }
}

package com.shawn.util {
  class PageUtil {
    +calculateOffset() : int
    +calculateOffset() : int
    +calculateTotalPage() : int
    +parsePage() : int
    +parsePerPage() : int
  }
}

package com.shawn.web.controller {
  class BookController <<Controller>> {
    -bookService : BookService
  }
}

package com.shawn.web.exception {
  class ResourceNotFoundException {
    -serialVersionUID : long
    -resourceName : String
    -id : Long
    +getMessage() : String
  }
  class ParameterIllegalException {
    -serialVersionUID : long
  }
  class ExceptionHandlerControllerAdvice {
  }
  class ServerInternalErrorException {
    -serialVersionUID : long
  }
}

' --- Relatii ---
BookRepository --> Book
BookRepository --> BookWithBookStore
UserRepository --> User
BookStoreRepository --> BookStore
BookStoreRepository --> BookStoreWithBooks
BookStoreMapper --|> BookStoreRepository
BookStoreMapper --> BookStoreRepository
UserMapper --|> UserRepository
UserMapper --> UserRepository
BookMapper --|> BookRepository
BookMapper --> Book
BookMapper --> BookRepository
ServiceMonitor --> ServerInternalErrorException
PageUtil --> ParameterIllegalException
WebSecurityConfiguration --> UserService
AuthorizationServerConfiguration --> UserService
BookController --> PageConstant
BookController --> ResourceNameConstant
BookController --> PaginatedResult
BookController --> Book
BookController --> BookService
BookController --> PageUtil
BookController --> ResourceNotFoundException
ExceptionHandlerControllerAdvice --> ErrorCode
ExceptionHandlerControllerAdvice --> Error
CustomUserDetails --|> User
CustomUserDetails --> User
BookStoreWithBooks --|> BookStore
BookWithBookStore --|> Book
UserService --> User
BookStoreService --> BookStore
BookStoreService --> BookStoreWithBooks
BookService --> Book
BookService --> BookWithBookStore
BookServiceImpl ..|> BookService
BookServiceImpl --> Book
BookServiceImpl --> BookWithBookStore
BookServiceImpl --> BookRepository
BookServiceImpl --> BookService
BookServiceImpl --> PageUtil
UserServiceImpl ..|> UserService
UserServiceImpl --> CustomUserDetails
UserServiceImpl --> User
UserServiceImpl --> UserRepository
UserServiceImpl --> UserService
BookStoreServiceImpl ..|> BookStoreService
BookStoreServiceImpl --> BookStore
BookStoreServiceImpl --> BookStoreWithBooks
BookStoreServiceImpl --> BookStoreRepository
BookStoreServiceImpl --> BookStoreService

@enduml