@startuml

package com.huan {
  class Application {
    +main() : void
  }
}

package com.huan.config {
  class DataSourceAspect {
    +declareJointPointExpression() : void
    +setDataSourceKey() : void
  }
  class AbstractApplication {
    -logger : Logger
    -staticEnv : Environment
    -env : ConfigurableEnvironment
    -env : Environment
    +abstractMain() : void
    +showAppInfo() : void
    +addDefaultProfile() : void
    +configure() : SpringApplicationBuilder
    +initApplication() : void
  }
  class MyBatisConfig {
    -environment : Environment
    -environment : Environment
    +setEnvironment() : void
    +test1DataSource() : DataSource
    +test2DataSource() : DataSource
    +dataSource() : DynamicDataSource
    +mapperScannerConfigurer() : MapperScannerConfigurer
    +sqlSessionFactory() : SqlSessionFactory
    +transactionManager() : DataSourceTransactionManager
  }
}

package com.huan.controller {
  class TestDataSourceController <<Controller>> {
    -commonService : CommonService
    +selectUser() : List<UserInfo>
    +userDetail() : List<UserDetail>
  }
  class WelcomeController <<Controller>> {
    +welcome() : Map
  }
}

package com.huan.mapper {
  interface UserDetailMapper {
  }
  interface UserInfoMapper {
  }
}

package com.huan.model {
  class UserDetail {
    -id : Long
    -name : String
    -qq : String
    +getId() : Long
    +setId() : void
    +getName() : String
    +setName() : void
    +getQq() : String
    +setQq() : void
  }
  class UserInfo {
    -id : String
    -username : String
    -netName : String
    -job : String
    -familyNativePlace : String
    -mobile : String
    -email : String
    +getId() : String
    +setId() : void
    +getUsername() : String
    +setUsername() : void
    +getNetName() : String
    +setNetName() : void
    +getJob() : String
    +setJob() : void
  }
}

package com.huan.service {
  interface CommonService {
  }
  interface Test1Service {
  }
  interface Test2Service {
  }
}

package com.huan.service.impl {
  class CommonServiceImpl <<Service>> {
    -test1Service : Test1Service
    -test2Service : Test2Service
    +selectUserInfo() : List<UserInfo>
    +selectUserDetail() : List<UserDetail>
  }
  class Test1ServiceImpl <<Service>> {
    -userInfoMapper : UserInfoMapper
    +selectUserInfo() : List<UserInfo>
  }
  class Test2ServiceImpl <<Service>> {
    -userDetailMapper : UserDetailMapper
    +selectUserDetail() : List<UserDetail>
  }
}

package com.huan.util {
  class DatabaseContextHolder {
    -contextHolder : ThreadLocal<DatabaseType>
    +getDatabaseType() : DatabaseType
    +setDatabaseType() : void
  }
  class DynamicDataSource {
    +determineCurrentLookupKey() : Object
  }
  enum DatabaseType {
  }
  class Constants {
    -DEBUG : boolean
    -DATA_ENCODE : String
    -JSON_VIEW_STATUS_SUCCESS : String
    -JSON_VIEW_STATUS_FAILED : String
    -JSON_VIEW_STATUS_ERROR : String
    -JSON_VIEW_STATUS_UNAUTHORIZED : String
    -SPRING_PROFILE_PRODUCTION : String
    -SPRING_PROFILE_DEVELOPMENT : String
    -SPRING_PROFILE_TEST : String
    -SPRING_PROFILE_FAST : String
  }
}

' --- Relatii ---
Application --|> AbstractApplication
Application --> AbstractApplication
DataSourceAspect --> Test1Service
DataSourceAspect --> Test1ServiceImpl
DataSourceAspect --> DatabaseContextHolder
DataSourceAspect --> DatabaseType
AbstractApplication --> Constants
MyBatisConfig --> DatabaseType
MyBatisConfig --> DynamicDataSource
UserDetailMapper --> UserDetail
UserInfoMapper --> UserInfo
TestDataSourceController --> UserDetail
TestDataSourceController --> UserInfo
TestDataSourceController --> CommonService
CommonService --> UserDetail
CommonService --> UserInfo
Test1Service --> UserInfo
Test2Service --> UserDetail
CommonServiceImpl ..|> CommonService
CommonServiceImpl --> UserDetail
CommonServiceImpl --> UserInfo
CommonServiceImpl --> CommonService
CommonServiceImpl --> Test1Service
CommonServiceImpl --> Test2Service
Test1ServiceImpl ..|> Test1Service
Test1ServiceImpl --> UserInfoMapper
Test1ServiceImpl --> UserInfo
Test1ServiceImpl --> Test1Service
Test2ServiceImpl ..|> Test2Service
Test2ServiceImpl --> UserDetailMapper
Test2ServiceImpl --> UserDetail
Test2ServiceImpl --> Test2Service

@enduml