@startuml

package hello {
  class ApplicationTest {
    -runner : Runner
    -rabbitTemplate : RabbitTemplate
    -receiver : Receiver
    +test() : void
  }
  class Application {
    -queueName : String
    -HOST : String
    -USERNAME : String
    -PASSWORD : String
    -PORT : int
    +connectionFactory() : ConnectionFactory
    +main() : void
  }
  class Receiver {
    -latch : CountDownLatch
    +receiveMessage() : void
    +getLatch() : CountDownLatch
  }
  class Runner {
    -rabbitTemplate : RabbitTemplate
    -receiver : Receiver
    -context : ConfigurableApplicationContext
    +run() : void
  }
}

' --- Relatii ---

@enduml