@startuml

package com.alibaba.boot.velocity {
  class VelocityConstantsTest {
    +testConstants() : void
  }
  interface VelocityConstants {
  }
  class VelocityLayoutProperties {
    -layoutEnabled : boolean
    -layoutUrl : String
    -layoutKey : String
    -screenContentKey : String
    +isLayoutEnabled() : boolean
    +setLayoutEnabled() : void
    +getLayoutUrl() : String
    +setLayoutUrl() : void
    +getLayoutKey() : String
    +setLayoutKey() : void
    +getScreenContentKey() : String
    +setScreenContentKey() : void
  }
}

package com.alibaba.boot.velocity.annotation {
  interface VelocityLayout {
  }
}

package com.alibaba.boot.velocity.autoconfigure {
  class VelocityLayoutAutoConfigurationDisabledProfileTest {
    -applicationContext : ApplicationContext
    +testAssert() : void
  }
  class VelocityLayoutAutoConfigurationTest {
    -velocityLayoutAutoConfiguration : VelocityLayoutAutoConfiguration
    -velocityLayoutProperties : VelocityLayoutProperties
    -embeddedVelocityLayoutViewResolver : EmbeddedVelocityLayoutViewResolver
    +testAssert() : void
    +testVelocityLayoutViewResolver() : void
  }
  class VelocityLayoutAutoConfiguration {
    -velocityLayoutProperties : VelocityLayoutProperties
    +velocityLayoutProperties() : VelocityLayoutProperties
    +embeddedVelocityLayoutViewResolver() : EmbeddedVelocityLayoutViewResolver
    +velocityLayoutWebMvcConfigurer() : VelocityLayoutWebMvcConfigurer
    +addInterceptors() : void
  }
  class VelocityToolsAutoConfiguration {
    +velocityToolsBeanDefinitionRegistryPostProcessor() : BeanDefinitionRegistryPostProcessor
    +embeddedVelocityViewResolverApplicationListener() : ApplicationListener<ContextRefreshedEvent>
  }
}

package com.alibaba.boot.velocity.autoconfigure.condition {
  class VelocityLayoutConditionTest {
    +testGetMatchOutcome() : void
  }
  class MockConditionContext {
    -registry : BeanDefinitionRegistry
    -beanFactory : ConfigurableListableBeanFactory
    -environment : Environment
    -resourceLoader : ResourceLoader
    -classLoader : ClassLoader
    +getRegistry() : BeanDefinitionRegistry
    +setRegistry() : void
    +getBeanFactory() : ConfigurableListableBeanFactory
    +setBeanFactory() : void
    +getEnvironment() : Environment
    +setEnvironment() : void
    +getResourceLoader() : ResourceLoader
    +setResourceLoader() : void
  }
  class VelocityToolsBasePackagesConditionTest {
    +testGetMatchOutcome() : void
  }
  class VelocityToolsBasePackagesCondition {
    +getMatchOutcome() : ConditionOutcome
  }
  class VelocityLayoutCondition {
    +getMatchOutcome() : ConditionOutcome
    +getMatchOutcome() : ConditionOutcome
  }
}

package com.alibaba.boot.velocity.beans.factory.support {
  class VelocityToolsBeanDefinitionRegistryPostProcessor {
    -logger : Log
    -velocityToolsRepository : VelocityToolsRepository
    -beanDefinitionRegistry : BeanDefinitionRegistry
    +postProcessBeanDefinitionRegistry() : void
    +postProcessBeanFactory() : void
    +getOrder() : int
    +onStartup() : void
    +postProcessAfterInitialization() : Object
  }
}

package com.alibaba.boot.velocity.bootstrap {
  class VelocitySampleBootstrap {
    +main() : void
  }
}

package com.alibaba.boot.velocity.context {
  class EmbeddedVelocityViewResolverApplicationListener {
    +onApplicationEvent() : void
  }
}

package com.alibaba.boot.velocity.controller {
  class IndexController <<Controller>> {
    +index() : String
    +tools() : String
  }
  class VelocityLayoutController <<Controller>> {
    -velocityLayoutProperties : VelocityLayoutProperties
    +layout() : String
    +layout2() : String
    +layout3() : String
  }
  class BaseController {
    +pageTitle() : String
    +linkLabel() : String
    +link() : String
  }
}

package com.alibaba.boot.velocity.tools {
  class VelocityToolsRepositoryTest {
    +testServletContext() : void
    +testGetAll() : void
  }
  class AnnotatedVelocityToolsScannerTest {
    -scanner : AnnotatedVelocityToolsScanner
    +testScan() : void
  }
  class EchoTool {
    -logger : Log
    -echo2Tool : Echo2Tool
    -applicationContext : ApplicationContext
    +echo() : void
    +setApplicationContext() : void
  }
  class StandardVelocityToolsScannerTest {
    -scanner : StandardVelocityToolsScanner
    +testScan() : void
    +setServletContext() : void
  }
  class ToolboxFactoryAdapter {
    +addToolInfo() : void
  }
  class StandardVelocityToolsScanner {
    -factoryConfigurationLoader : FactoryConfigurationLoader
    -servletContext : ServletContext
    -viewToolManager : ViewToolManager
    +resolveSources() : String[]
    +scan() : void
    +setServletContext() : void
  }
  class AnnotatedVelocityToolsScanner {
    -provider : ClassPathScanningCandidateComponentProvider
    -classLoader : ClassLoader
    +scan() : void
    +resolveSources() : String[]
    +setResourceLoader() : void
    +setEnvironment() : void
  }
  class FactoryConfigurationLoader {
    -logger : Log
    -servletContext : ServletContext
    +load() : FactoryConfiguration
    +load() : FactoryConfiguration
  }
  class VelocityToolsRepository <<Repository>> {
    -exposeBeans : boolean
    -propertyResolver : CompatibleRelaxedPropertyResolver
    -beanFactory : ConfigurableListableBeanFactory
    +init() : void
    +put() : boolean
    +setEnvironment() : void
    +postProcessBeanFactory() : void
  }
  class ViewToolManagerInitializer {
    -ORDER : int
    -CONTEXT_ATTRIBUTE_NAME : String
    +onStartup() : void
    +getViewToolManager() : ViewToolManager
    +getOrder() : int
  }
  class AbstractVelocityToolsScanner {
    -logger : Log
    -propertyResolver : CompatibleRelaxedPropertyResolver
    +resolveSources() : String[]
    +resolveRelaxedPropertyAsStringArray() : String[]
    +scan() : void
    +setEnvironment() : void
  }
  interface VelocityToolsScanner {
  }
  class VelocityTool {
    -toolInfo : ToolInfo
    -scope : String
    +getScope() : String
    +getKey() : String
    +getClassname() : String
    +getToolClass() : Class
    +hasConfigure() : boolean
    +isSkipSetters() : boolean
    +hasPermission() : boolean
    +create() : Object
  }
  class EchoTool {
    -logger : Log
    -echo2Tool : Echo2Tool
    -applicationContext : ApplicationContext
    +echo() : void
    +setApplicationContext() : void
  }
}

package com.alibaba.boot.velocity.tools2 {
  class Echo2Tool {
    -logger : Log
    +echo() : void
  }
  class Echo2Tool {
    -logger : Log
    +echo() : void
  }
}

package com.alibaba.boot.velocity.util {
  class PathUtilsTest {
    +testNormalize() : void
    +testRemoveHeadSlash() : void
  }
  class VelocimacroUtilsTest {
    +testAppendVelocimacroLibrary() : void
    +testToSingletonExtendedProperties() : void
  }
  class PathUtils {
    -SLASH : String
    -DOUBLE_SLASH : String
    +normalize() : String
    +removeHeadSlash() : String
  }
  class CompatibleRelaxedPropertyResolver {
    -delegate : PropertyResolver
    +containsProperty() : boolean
    +getProperty() : String
    +getProperty() : String
    +getRequiredProperty() : String
    +resolvePlaceholders() : String
    +resolveRequiredPlaceholders() : String
  }
  class VelocimacroUtils {
    +appendVelocimacroLibrary() : void
    +toSingletonExtendedProperties() : ExtendedProperties
  }
}

package com.alibaba.boot.velocity.web.servlet {
  class VelocityLayoutHandlerInterceptorTest {
  }
  class VelocityLayoutHandlerInterceptor {
    -logger : Log
    -layoutKey : String
    +postHandle() : void
  }
  class VelocityToolsHandlerInterceptor {
    +postHandleOnPageRenderContext() : void
  }
}

package com.alibaba.boot.velocity.web.servlet.view {
  class EmbeddedVelocityLayoutViewResolver {
    -toolboxConfigLocation : String
    +initApplicationContext() : void
    +setToolboxConfigLocation() : void
  }
  class EmbeddedVelocityToolboxView {
    +createVelocityContext() : Context
  }
  class EmbeddedVelocityLayoutToolboxView {
    +createVelocityContext() : Context
  }
}

package org.springframework.boot.autoconfigure.velocity {
  class VelocityProperties {
    -DEFAULT_RESOURCE_LOADER_PATH : String
    -DEFAULT_PREFIX : String
    -DEFAULT_SUFFIX : String
    -dateToolAttribute : String
    -numberToolAttribute : String
    -resourceLoaderPath : String
    -toolboxConfigLocation : String
    -preferFileSystemAccess : boolean
    +getDateToolAttribute() : String
    +setDateToolAttribute() : void
    +getNumberToolAttribute() : String
    +setNumberToolAttribute() : void
    +setProperties() : void
    +getResourceLoaderPath() : String
    +setResourceLoaderPath() : void
    +getToolboxConfigLocation() : String
  }
  class VelocityAutoConfiguration {
    -logger : Log
    -applicationContext : ApplicationContext
    -properties : VelocityProperties
    -properties : VelocityProperties
    +checkTemplateLocationExists() : void
    +applyProperties() : void
    +velocityConfiguration() : VelocityEngineFactoryBean
    +velocityConfigurer() : VelocityConfigurer
    +velocityEngine() : VelocityEngine
    +velocityViewResolver() : EmbeddedVelocityViewResolver
    +resourceUrlEncodingFilter() : ResourceUrlEncodingFilter
  }
  class VelocityTemplateAvailabilityProvider {
    +isTemplateAvailable() : boolean
  }
}

package org.springframework.boot.web.servlet.view.velocity {
  class EmbeddedVelocityToolboxView {
    -toolboxFile : String
    +createVelocityContext() : Context
    +invoke() : Object
  }
  class EmbeddedVelocityViewResolver {
    -toolboxConfigLocation : String
    +initApplicationContext() : void
    +setToolboxConfigLocation() : void
  }
}

' --- Relatii ---
EchoTool --> Echo2Tool
VelocityLayoutAutoConfigurationDisabledProfileTest --> VelocityLayoutProperties
VelocityLayoutAutoConfigurationDisabledProfileTest --> EmbeddedVelocityLayoutViewResolver
VelocityLayoutAutoConfigurationTest --> VelocityLayoutProperties
VelocityLayoutAutoConfigurationTest --> EmbeddedVelocityLayoutViewResolver
VelocityAutoConfiguration --> EmbeddedVelocityViewResolver
VelocityTemplateAvailabilityProvider --> CompatibleRelaxedPropertyResolver
VelocityConstants --> VelocityAutoConfiguration
VelocityConstants --> VelocityProperties
VelocityLayoutProperties --|> VelocityProperties
VelocityLayoutProperties --> VelocityProperties
StandardVelocityToolsScanner --|> AbstractVelocityToolsScanner
AnnotatedVelocityToolsScanner --|> AbstractVelocityToolsScanner
VelocityToolsRepository --> CompatibleRelaxedPropertyResolver
AbstractVelocityToolsScanner ..|> VelocityToolsScanner
AbstractVelocityToolsScanner --> CompatibleRelaxedPropertyResolver
EmbeddedVelocityViewResolverApplicationListener --> EmbeddedVelocityToolboxView
EmbeddedVelocityViewResolverApplicationListener --> EmbeddedVelocityViewResolver
VelocityLayoutHandlerInterceptor --> VelocityLayoutProperties
VelocityLayoutHandlerInterceptor --> VelocityLayout
EmbeddedVelocityLayoutViewResolver --> EmbeddedVelocityViewResolver
EmbeddedVelocityToolboxView --> VelocityToolsRepository
VelocityToolsBeanDefinitionRegistryPostProcessor --> VelocityTool
VelocityToolsBeanDefinitionRegistryPostProcessor --> VelocityToolsRepository
VelocityLayoutAutoConfiguration --> VelocityLayoutProperties
VelocityLayoutAutoConfiguration --> VelocityLayoutCondition
VelocityLayoutAutoConfiguration --> VelocityLayoutHandlerInterceptor
VelocityLayoutAutoConfiguration --> EmbeddedVelocityLayoutViewResolver
VelocityLayoutAutoConfiguration --> VelocityAutoConfiguration
VelocityToolsAutoConfiguration --> VelocityToolsBeanDefinitionRegistryPostProcessor
VelocityToolsAutoConfiguration --> EmbeddedVelocityViewResolverApplicationListener
VelocityToolsAutoConfiguration --> VelocityToolsRepository
VelocityToolsAutoConfiguration --> VelocityToolsScanner
EchoTool --> Echo2Tool
IndexController --|> BaseController
IndexController --> VelocityLayout
VelocityLayoutController --|> BaseController
VelocityLayoutController --> VelocityLayoutProperties
VelocityLayoutController --> VelocityLayout

@enduml