@startuml
package airhacks.alb.boundary; {
class LambdaAlbStack {
}

class LambdaAlbStackTest {
}

}

package airhacks.alb.control; {
class Alb {
}

class PublicVPC {
}

}

package airhacks.apigateway.boundary; {
class LambdaApiGatewayStack {
}

class LambdaApiGatewayStackTest {
}

}

package airhacks.apigateway.control; {
class APIGatewayIntegrations {
}

class IAMPolicy {
}

class PrivateVPC {
}

}

package airhacks; {
class CDKApp {
}

class ConventionalDefaults {
}

class InfrastructureBuilder {
}

class FunctionZip {
}

}

package airhacks.cloudfront.boundary; {
class CloudFrontFunctionURLStack {
}

}

package airhacks.functionurl.boundary; {
class FunctionURLStack {
}

class FunctionURLStackTest {
}

}

package airhacks.lambda.control; {
class QuarkusLambda {
}

class QuarkusLambdaTest {
}

}

package airhacks.lambda.greetings.boundary; {
class Greeter {
}

class GreetingResource {
}

class GreetingsResourceClient {
}

class GreetingsResourceIT {
}

}

package airhacks.lambda.time.boundary; {
class CurrentTimeResource {
}

}

LambdaAlbStack -- Alb
LambdaAlbStack -- PublicVPC
LambdaAlbStack -- QuarkusLambda
LambdaApiGatewayStack -- APIGatewayIntegrations
LambdaApiGatewayStack -- PrivateVPC
LambdaApiGatewayStack -- InfrastructureBuilder
LambdaApiGatewayStack -- QuarkusLambda
APIGatewayIntegrations -- IAMPolicy
APIGatewayIntegrations -- PrivateVPC
CDKApp -- InfrastructureBuilder
CloudFrontFunctionURLStack -- FunctionURLStack
CloudFrontFunctionURLStack -- InfrastructureBuilder
CloudFrontFunctionURLStack -- QuarkusLambda
FunctionURLStack -- InfrastructureBuilder
FunctionURLStack -- QuarkusLambda
InfrastructureBuilder -- ConventionalDefaults
InfrastructureBuilder -- FunctionZip
QuarkusLambda -- ConventionalDefaults
LambdaAlbStackTest -- LambdaAlbStack
LambdaAlbStackTest -- Alb
LambdaApiGatewayStackTest -- LambdaApiGatewayStack
LambdaApiGatewayStackTest -- InfrastructureBuilder
LambdaApiGatewayStackTest -- FunctionZip
FunctionURLStackTest -- FunctionURLStack
FunctionURLStackTest -- InfrastructureBuilder
FunctionURLStackTest -- FunctionZip
QuarkusLambdaTest -- QuarkusLambda
GreetingResource -- Greeter
GreetingsResourceIT -- GreetingsResourceClient
@enduml