@startuml
package java.util.*; {
class Main {
}

}

package java8; {
class Java8 {
}

class LambdaExample {
}

class StreamsExample {
}

}

package tasks.findElementClass; {
class ElementFinder {
}

class Main {
}

}

package tasks.findElementClass.StreamsChallenge; {
class ElementFinder {
}

}

package tasks.Week1Task; {
class TawfeekShalashLambdaExample {
}

class TawfeekShalashStreamsExample {
}

}

Main -- ElementFinder
TawfeekShalashLambdaExample -- LambdaExample
TawfeekShalashStreamsExample -- StreamsExample
@enduml