@startuml
package com.studioidan.httpagent; {
class ApplicationTest {
}

class ExampleUnitTest {
}

}

package studioidan.com.httpagent; {
class ApplicationTest {
}

class ExampleUnitTest {
}

}

@enduml