@startuml
package boot; {
class Application {
}

class SpringBootJupiterTests {
}

}

package demo; {
class BowlingGame {
}

class Calculator {
}

class Cat {
}

class Person {
}

class StringUtils {
}

class BowlingGameTest {
}

}

package extensions; {
class CaptureSystemOutput {
}

class CaptureSystemOutputExtension {
}

class SkipOnFailuresInEnclosingClass {
}

class SkipOnFailuresInEnclosingClassExtension {
}

}

package org.junit.jupiter.api.condition; {
class DisabledOnDayOfWeek {
}

class DisabledOnDayOfWeekCondition {
}

class EnabledOnDayOfWeek {
}

class EnabledOnDayOfWeekCondition {
}

class DisabledOnDayOfWeekTests {
}

class EnabledOnDayOfWeekTests {
}

}

package playground; {
class DynamicTests {
}

class FastTest {
}

class JUnit4CalculatorTests {
}

class JUnit4PersonTests {
}

class ParameterizedTests {
}

class RepeatedTests {
}

class TagsDisplayNamesDependencyInjectionAndConditionsTests {
}

}

package spring; {
class DisabledOnMac {
}

class EnabledOnMac {
}

class SpringBootJupiterTests {
}

class SpringJupiterTests {
}

class TestConfig {
}

}

package working; {
class CalculatorTests {
}

class DynamicTests {
}

class EnabledOn {
}

class JUnitJupiterCalculatorTests {
}

class JUnitJupiterPersonTests {
}

class LoggingExtension {
}

class OrderedTests {
}

class OuterTests {
}

class ParameterizedFibonacciTests {
}

class ParameterizedTests {
}

class RepeatedTests {
}

class SpringJupiterTests {
}

class SystemOutputTests {
}

class TagsDisplayNamesDependencyInjectionAndConditionsTests {
}

class TimingExtension {
}

}

Application -- Cat
CaptureSystemOutput -- CaptureSystemOutputExtension
SkipOnFailuresInEnclosingClass -- SkipOnFailuresInEnclosingClassExtension
DisabledOnDayOfWeek -- DisabledOnDayOfWeekCondition
DisabledOnDayOfWeek -- EnabledOnDayOfWeek
DisabledOnDayOfWeek -- EnabledOn
EnabledOnDayOfWeek -- EnabledOnDayOfWeekCondition
EnabledOnDayOfWeek -- EnabledOn
EnabledOnDayOfWeekCondition -- EnabledOn
SpringBootJupiterTests -- Cat
BowlingGameTest -- BowlingGame
DisabledOnDayOfWeekTests -- DisabledOnDayOfWeek
EnabledOnDayOfWeekTests -- EnabledOnDayOfWeek
EnabledOnDayOfWeekTests -- EnabledOn
JUnit4CalculatorTests -- Calculator
JUnit4CalculatorTests -- CalculatorTests
JUnit4PersonTests -- Person
ParameterizedTests -- StringUtils
TagsDisplayNamesDependencyInjectionAndConditionsTests -- FastTest
TagsDisplayNamesDependencyInjectionAndConditionsTests -- DisabledOnMac
TagsDisplayNamesDependencyInjectionAndConditionsTests -- EnabledOnMac
TagsDisplayNamesDependencyInjectionAndConditionsTests -- EnabledOn
EnabledOnMac -- EnabledOn
SpringJupiterTests -- Cat
SpringJupiterTests -- DisabledOnMac
SpringJupiterTests -- EnabledOnMac
SpringJupiterTests -- TestConfig
SpringJupiterTests -- EnabledOn
TestConfig -- Cat
CalculatorTests -- Calculator
JUnitJupiterCalculatorTests -- Calculator
JUnitJupiterCalculatorTests -- CalculatorTests
JUnitJupiterPersonTests -- Person
OuterTests -- SkipOnFailuresInEnclosingClass
OuterTests -- SkipOnFailuresInEnclosingClassExtension
ParameterizedFibonacciTests -- Calculator
ParameterizedFibonacciTests -- LoggingExtension
SystemOutputTests -- CaptureSystemOutput
@enduml