@startuml
package at.alwinschuster.HttpServer; {
class HttpServerModule {
}

class HttpServerReactPackage {
}

class Server {
}

}

HttpServerModule -- Server
HttpServerReactPackage -- HttpServerModule
HttpServerReactPackage -- Server
@enduml